### ISSUE TITLE
XCode 13. Module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5 compiler

### ISSUE THREAD

**Issue by elfstyle** [thebergamo/react-native-fbsdk-next#100]
## 🐛 Bug Report
I'm getting `Module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5 compiler` error when trying to run the app on a real device with `XCode 13`. Fine on a simulator. It was working fine with XCode `12.5.1` and the issue appeared after the upgrade.

## To Reproduce
Launch an app with react-native-fbsdk-next on a real device using `XCode 13`.

## Expected Behavior
There shouldn't be an error.

## Environment
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 74.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
![Screenshot 2021-09-27 at 14 46 18](https://user-images.githubusercontent.com/32192640/134902674-34dc3a8a-8b09-40f9-8b68-784d4d84e67d.png)

**Comment by elfstyle** [comment]
I was able to resolve this by deleting `~/Library/Developer/Xcode/DerivedData` folder. Hope it helps someone.

**Comment by mikehardy** [comment]
Not sure how everyone handles all these frustrating "stale cache" issues, but they happen to me frequently enough that I integrate a "deep-clean" package.json target that uses `npx react-native-clean-project` (in non-interactive mode using specific delete-or-do-not-delete settings I have chosen) as part of my release build process, so I know before I hit real devices via TestFlight that it's reproducibly good.

And then the first thing I do when I have an unexpected crash like this is to run that deep-clean target and retry. It gets rid of DerivedData as one of it's possible iOS cleanings
