### ISSUE TITLE
Firebase Facebook Login Keep Returning EUNSPECIFIED error (android)

### ISSUE THREAD

**Issue by vitojuliano** [thebergamo/react-native-fbsdk-next#106]
So, i have already follow the instructions from RN Firebase Facebook Social Auth to use the services and when i try to use 

> onFacebookButtonPress()
> .then(resp=> {
>     console.log(JSON.stringify(resp))
> })
> .catch(err => {
>     console.log(JSON.stringify(err))
> })

**I got this error message** 

> {
>   "nativeStackAndroid": [
>     {
>       "lineNumber": 221,
>       "file": "LoginManager.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.login.LoginManager"
>     },
>     {
>       "lineNumber": 181,
>       "file": "LoginManager.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.login.LoginManager$1"
>     },
>     {
>       "lineNumber": 81,
>       "file": "CallbackManagerImpl.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.internal.CallbackManagerImpl"
>     },
>     {
>       "lineNumber": 34,
>       "file": "FBActivityEventListener.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.reactnative.androidsdk.FBActivityEventListener"
>     },
>     {
>       "lineNumber": 305,
>       "file": "ReactContext.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.react.bridge.ReactContext"
>     },
>     {
>       "lineNumber": 762,
>       "file": "ReactInstanceManager.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.react.ReactInstanceManager"
>     },
>     {
>       "lineNumber": 90,
>       "file": "ReactDelegate.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.react.ReactDelegate"
>     },
>     {
>       "lineNumber": 112,
>       "file": "ReactActivityDelegate.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.react.ReactActivityDelegate"
>     },
>     {
>       "lineNumber": 68,
>       "file": "ReactActivity.java",
>       "methodName": "onActivityResult",
>       "class": "com.facebook.react.ReactActivity"
>     },
>     {
>       "lineNumber": 8550,
>       "file": "Activity.java",
>       "methodName": "dispatchActivityResult",
>       "class": "android.app.Activity"
>     },
>     {
>       "lineNumber": 5534,
>       "file": "ActivityThread.java",
>       "methodName": "deliverResults",
>       "class": "android.app.ActivityThread"
>     },
>     {
>       "lineNumber": 5582,
>       "file": "ActivityThread.java",
>       "methodName": "handleSendResult",
>       "class": "android.app.ActivityThread"
>     },
>     {
>       "lineNumber": 51,
>       "file": "ActivityResultItem.java",
>       "methodName": "execute",
>       "class": "android.app.servertransaction.ActivityResultItem"
>     },
>     {
>       "lineNumber": 135,
>       "file": "TransactionExecutor.java",
>       "methodName": "executeCallbacks",
>       "class": "android.app.servertransaction.TransactionExecutor"
>     },
>     {
>       "lineNumber": 95,
>       "file": "TransactionExecutor.java",
>       "methodName": "execute",
>       "class": "android.app.servertransaction.TransactionExecutor"
>     },
>     {
>       "lineNumber": 2317,
>       "file": "ActivityThread.java",
>       "methodName": "handleMessage",
>       "class": "android.app.ActivityThread$H"
>     },
>     {
>       "lineNumber": 106,
>       "file": "Handler.java",
>       "methodName": "dispatchMessage",
>       "class": "android.os.Handler"
>     },
>     {
>       "lineNumber": 246,
>       "file": "Looper.java",
>       "methodName": "loop",
>       "class": "android.os.Looper"
>     },
>     {
>       "lineNumber": 8595,
>       "file": "ActivityThread.java",
>       "methodName": "main",
>       "class": "android.app.ActivityThread"
>     },
>     {
>       "lineNumber": -2,
>       "file": "Method.java",
>       "methodName": "invoke",
>       "class": "java.lang.reflect.Method"
>     },
>     {
>       "lineNumber": 602,
>       "file": "RuntimeInit.java",
>       "methodName": "run",
>       "class": "com.android.internal.os.RuntimeInit$MethodAndArgsCaller"
>     },
>     {
>       "lineNumber": 1130,
>       "file": "ZygoteInit.java",
>       "methodName": "main",
>       "class": "com.android.internal.os.ZygoteInit"
>     }
>   ],
>   "userInfo": null,
>   "message": "SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: ",
>   "code": "EUNSPECIFIED",
>   "line": 5791,
>   "column": 45,
>   "sourceURL": "http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sabacustomerapp&modulesOnly=false&runModule=true"
> }

did you know why this happen? i think i have already follow the instruction in right way..

**Comment by mikehardy** [comment]
Sorry, I have no idea how to begin with this one - https://stackoverflow.com/help/minimal-reproducible-example

**Comment by efstathiosntonas** [comment]
@mikehardy getting the same error, Facebook has contacted us with a screenshot about the issue (user not being able to login/signup), we got an error modal in app and the error was: `SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]:`.

Tried to replicate the error on a Xiaomi Redmi 8 with Android 10 and I managed to login/sign up just fine. We're using `react-native-firebase` 12.8.0 and `react-native-fbsdk-next` 4.3.1

I really don't know for how long the issue exists, we never had a support ticket about "not being able to login/signup with facebook" and bugsnag has no reports too.

**Comment by mikehardy** [comment]
I believe there is a problem, at the same time, with no reproduction, no one can help even if they want to :shrug:

**Comment by efstathiosntonas** [comment]
I think it wont be easy to repro, Facebook spotted the issue while on my real device it won’t show up. Tomorrow I ll test on several devices/sdks on browserstack and If a device/sdk reproduces it I ll post a comment.

**Comment by efstathiosntonas** [comment]
I've changed:

```
    implementation 'com.facebook.android:facebook-android-sdk:7.1.0'
```

to:
```

dependencies {
    // ...implementations
    implementation "com.facebook.android:facebook-android-sdk:9.1.+"
```

And it seems it works fine. Will keep an eye on it though.

**Comment by vitojuliano** [comment]
I'm solved my problem with sign out my current facebook account on my android, becuase current account not registered yet on facebook developer account, so android returning error. When i try to login with the same account that i sign up on facebook developers, there is no error message. Just make sure, your facebook account is registered on facebook developer account to do debug. I think its done for this issue, i will close this issue. Thank you everyone, hopefully this issue help many developer outthere.

**Comment by chr4ss12** [comment]
+1 can see this error in production as well, frequently. @efstathiosntonas did you ever manage to make progress on that?

**Comment by efstathiosntonas** [comment]
@chr4ss12 this is what fixed it for me: https://github.com/facebook/facebook-android-sdk/issues/989#issuecomment-967099146
