### ISSUE TITLE
Not able to refetch valid token

### ISSUE THREAD

**Issue by MilanObradovic** [thebergamo/react-native-fbsdk-next#107]
This is not a bug, rather a question. We have received Facebook email, stating we have broken experience on our app. They provided us with use cases which we should test and find where the problem is.
One of those use cases is this:

![Screenshot 2021-09-30 at 12 38 18](https://user-images.githubusercontent.com/52998593/135440311-db68286d-3fa4-424e-b301-459881e88e41.png)

After user changes facebook password, access token is no longer valid. When trying to log with Facebook after password change logInWithPermissions throws error like this:

![Screenshot 2021-09-30 at 12 42 54](https://user-images.githubusercontent.com/52998593/135440960-61fd233c-1fca-48cd-8fa9-29d3b82e21b2.png)

**How am I supposed to fetch new token**? I cannot find suitable method to do this. I found a 'hack' where you would catch the error loginWithPermissions throws and then try again calling it with login behaviour set to 'web_only', but I doubt it would work in every case. Is there official way to do this, I couldn't find it.

I guess the use case is same when token expires.
Thanks!

**Comment by MilanObradovic** [comment]
Update here:
The problem seems to be present only on Android when there is Facebook application installed. If I use behaviour 'web_only' all the time, then it asks user to log in again to facebook account when token is invalid - as it should. Since iOS is using browser, it's working as expected as well.

**Comment by mikehardy** [comment]
I think you might be "first" here - I haven't seen this come up yet. If you have something that works for you, it might be a help to others if you added a note about it to the troubleshooting section (like https://github.com/thebergamo/react-native-fbsdk-next/commit/2614385e127455488f154bfef5a6f5d157080085) as well as to the loginWithPermissions section https://github.com/thebergamo/react-native-fbsdk-next#requesting-additional-permissions-with-login-manager

**Comment by MilanObradovic** [comment]
Thanks for the answer. I can make it work using 'web_only' behaviour, but I don't like that approach.
Does this lib handle token expirations and invalid tokens or is that something that sdks do by themselves?
When I get this error, if I go to Facebook app, it says 'Session expired' and it logs me out. After that, this lib works as it should.

**Comment by mikehardy** [comment]
Again with the "your first" theme, and my apologies - but I'm not sure? Inspection of the module / testing of the scenarios and documentation of the same would be a huge help as I'm just not sure myself.
