### ISSUE TITLE
Deprecating support for FB Login authentication on Android embedded browsers

### ISSUE THREAD

**Issue by efstathiosntonas** [thebergamo/react-native-fbsdk-next#110]
Not a bug, I’ve just wanted to raise attention to this: https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/

today is the last day to update the apps (they offer one last grace period until November 5th).

I believe README should be updated and notify users about this change, some users might use `LoginBehavior.web` for both platforms.

**Comment by mikehardy** [comment]
Hi there! Have you searched through the issues list at all? I believe this is in there.
#88
Please open a PR to the docs if you can think of something necessary there, we're happy to merge things

**Comment by efstathiosntonas** [comment]
Sorry @mikehardy , didn’t search for similar issues 🤦.

I ll open a PR tomorrow
