### ISSUE TITLE
Impossible to track events on iOS

### ISSUE THREAD

**Issue by Derewith** [thebergamo/react-native-fbsdk-next#114]
## 🐛 Bug Report
I'm trying to log events from my app, but the events are not shown correctly in the events manager dashboard of Facebook.
I'm using all the settings from the Setup / Installation, i'm using the same FB account on the test device ( iPhone XR, iOS 15 ) and the only events that i can see are "fb_mobile_login_method_start" and "fb_mobile_login_start".

## To Reproduce / Code Example
This is the javascript function that i'm calling for test.
After loading the main screen

```
Settings.initializeSDK();
await Settings.setAdvertiserTrackingEnabled(true);
```

By pressing one button

```
AppEventsLogger.logPurchase(Math.random(999), 'EUR', {
        [AppEventsLogger.AppEventParams.ContentID]: `order-${Math.random(
          9999,
        ).toString()}`,
      });
```

## Expected Behavior
The strange thing is that with the account of a colleague , the events are being tracked.

## Environment
```System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 20.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
This is not actionable without some sort of reproducible example, apologies https://stackoverflow.com/help/minimal-reproducible-example
We are about to release with a bump of underlying ios sdk from 9 to 11, maybe that helps
if not we must have an example that reproducibly fails for anyone to offer any help
