### ISSUE TITLE
App crashes on start app (only android)

### ISSUE THREAD

**Issue by edersonfaccin** [thebergamo/react-native-fbsdk-next#118]
I changed the react-native-fbsdk to react-native-fbsdk-next but in android crashes in open the app (simulator and real device), in IOS its work.
I loocked in closed issues but none solution worked for me.

Someone know how resolved this problem?

System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 5.77 GB / 24.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
Hi there! Please watch `adb logcat` from the Terminal while starting the app until it crashes, and capture the exception message / stack trace of the crash, without this information there is no help we can really offer.
