### ISSUE TITLE
Errors with SceneDelegate

### ISSUE THREAD

**Issue by Yonom** [thebergamo/react-native-fbsdk-next#12]
## 🐛 Bug Report

After setting up react-native-fbsdk-next, I get the error Module 'FacebookCore' not found in SceneDelegate.m.

![image](https://user-images.githubusercontent.com/1394504/113852024-60396a80-979c-11eb-9c95-e9d6c7030dd8.png)

## To Reproduce

- Start with a fresh react native 0.64 app
- Follow the setup instructions for react-native-fbssdk-next
- Add a new SceneDelegate.m file to my project as shown here: https://developers.facebook.com/docs/ios/getting-started/
- Run `yarn ios`

## Expected Behavior

The build should succeed.

## Example Repo

https://github.com/Yonom/react-native-fbsdk-next-bug-repo/commit/b3d51dc5da29869b796f3b77434b4b994b52616c#diff-7f1567ebab010f96652f686ce4d2d7dba0314511b6dd275914e1f767e2a470f3

## Environment

> info Fetching system and libraries information...
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 89.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /var/folders/4l/5q_1bbc93mb221kpmsz41jth0000gn/T/yarn--1617791043494-0.5877670075367989/node
    Yarn: 1.22.10 - /var/folders/4l/5q_1bbc93mb221kpmsz41jth0000gn/T/yarn--1617791043494-0.5877670075367989/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 24, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Comment by mikehardy** [comment]
"follow the steps" - do those include pod install? The Xcode project is not wired up until pod install has been executed

https://developers.facebook.com/docs/ios/use-cocoapods - is the page for cocoapods (which react-native uses for iOS)

Then when you opened it in Xcode are you sure you opened the .xcworkspace, instead of the .xcproject?

**Comment by mikehardy** [comment]
@thebergamo I made a "needs more info" label and applied it, I use a label like that in all the repos I collaborate on so when I have a time box available and I do an issue sweep I don't waste time clicking on something that's just waiting for someone else anyway - the seconds add up :-)

**Comment by thebergamo** [comment]
that's great! Thanks @mikehardy  I was thinking about it as well!

**Comment by Yonom** [comment]
@mikehardy 

> "follow the steps" - do those include pod install? 

Yep.

> Then when you opened it in Xcode are you sure you opened the .xcworkspace, instead of the .xcproject?

Yep.

---

I have created a repo with a minimum reproducible example:

https://github.com/Yonom/react-native-fbsdk-next-bug-repo/commit/b3d51dc5da29869b796f3b77434b4b994b52616c#diff-7f1567ebab010f96652f686ce4d2d7dba0314511b6dd275914e1f767e2a470f3

I hope this helps 😊

**Comment by iDuuck** [comment]
You don't need to force a SceneDelegate to be there at all. It is enough, if you are relying on the `AppDelegate` which is generated by react-native on bootstrapping.

--- 

Regarding the imports, this is working properly, when using the following `FBSDKCoreKit` as import.

---

Here is the diff (you are also not importing the linking manager class in the app delegate):

```diff
diff --git a/ios/fbsdkbugrepo/AppDelegate.m b/ios/fbsdkbugrepo/AppDelegate.m
index 6f43324..ddf73ec 100644
--- a/ios/fbsdkbugrepo/AppDelegate.m
+++ b/ios/fbsdkbugrepo/AppDelegate.m
@@ -3,6 +3,7 @@
 #import <React/RCTBridge.h>
 #import <React/RCTBundleURLProvider.h>
 #import <React/RCTRootView.h>
+#import <React/RCTLinkingManager.h>
 #import <FBSDKCoreKit/FBSDKCoreKit.h>
 
 #ifdef FB_SONARKIT_ENABLED
diff --git a/ios/fbsdkbugrepo/SceneDelegate.m b/ios/fbsdkbugrepo/SceneDelegate.m
index 083d63f..3a4d944 100644
--- a/ios/fbsdkbugrepo/SceneDelegate.m
+++ b/ios/fbsdkbugrepo/SceneDelegate.m
@@ -1,6 +1,6 @@
 #import <FBSDKCoreKit/FBSDKCoreKit.h>
 
-@import FacebookCore;
+@import FBSDKCoreKit;
 
 @interface SceneDelegate ()
 
```

**Comment by Yonom** [comment]
I see, so the SceneDelegate setup is only necessary if I already have a SceneDelegate for other purposes.

Thanks @iDuuck
