### ISSUE TITLE
Share to a FB page

### ISSUE THREAD

**Issue by kristijantomic** [thebergamo/react-native-fbsdk-next#121]
Is it possible to share to page that a FB profile admis? 
When share dialog opens it does not shows a dropdown where you can switch page,group,... 
Do we need to enable something, somewhere...any thoughts, anyone?

Thank you!

**Comment by mikehardy** [comment]
I would ask this on stackoverflow, clearyl not an active enough community for good answers, sorry. But if you learn something please report back for future people!
