### ISSUE TITLE
'isCancelled' is getting always true from 'loginWithPermissions' method in android devices

### ISSUE THREAD

**Issue by rakeshv1108** [thebergamo/react-native-fbsdk-next#122]
## 🐛 Bug Report
when trying to login with Facebook "User canceled the login process"  error always gets in android only.
------------ 'isCancelled' is getting always true from 'loginWithPermissions' method ---------------

## To Reproduce
1. Logout from Facebook
2. Try to login with Facebook into App

## Expected Behavior
Need to Login Successfully with Facebook in android.

## Code Example

// Attempt login with permissions
const result = await LoginManager.logInWithPermissions([
   'public_profile',
   'email',
]);
        
if (result.isCancelled) {
    contextData.setisGlobalLoading(false);
    console.log('User cancelled the login process');
    return;
}

## Environment
Android Devices (API Level above 30) (Android OS 11)

**Comment by bxvd** [comment]
This is what was causing that for me: https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/

**Comment by bxvd** [comment]
@mikehardy No the library is fine, it's an older app that was being updated and we needed to add the Custom Tabs intent.

**Comment by mikehardy** [comment]
@rakeshv1108 closing this in the absence of a reproduction then, likely cause is a need to forward port your app per https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews
