### ISSUE TITLE
app crash in pixel phone(android 12)

### ISSUE THREAD

**Issue by heekyu-pu** [thebergamo/react-native-fbsdk-next#124]
## 🐛 Bug Report
app crash after facebook login
only occurs in android 12, pixel phones(3, 4, 6)

error message:
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

stcktrace:
android.app.PendingIntent.checkFlags (PendingIntent.java:375)
android.app.PendingIntent.getBroadcast (PendingIntent.java:632)
com.facebook.AccessTokenManager.setTokenExpirationBroadcastAlarm (AccessTokenManager.java:164)
com.facebook.AccessTokenManager.setCurrentAccessToken (AccessTokenManager.java:130)
com.facebook.AccessTokenManager.setCurrentAccessToken (AccessTokenManager.java:110)
com.facebook.AccessToken.setCurrentAccessToken (AccessToken.java:245)
com.facebook.login.LoginManager.finishLogin (LoginManager.java:719)
com.facebook.login.LoginManager.onActivityResult (LoginManager.java:242)
com.facebook.login.LoginManager$1.onActivityResult (LoginManager.java:181)
com.facebook.internal.CallbackManagerImpl.onActivityResult (CallbackManagerImpl.java:81)
com.facebook.reactnative.androidsdk.FBActivityEventListener.onActivityResult (FBActivityEventListener.java:34)
com.facebook.react.bridge.ReactContext.onActivityResult (ReactContext.java:336)
com.facebook.react.ReactInstanceManager.onActivityResult (ReactInstanceManager.java:775)
com.facebook.react.ReactDelegate.onActivityResult (ReactDelegate.java:90)
com.facebook.react.ReactActivityDelegate.onActivityResult (ReactActivityDelegate.java:112)
com.facebook.react.ReactActivity.onActivityResult (ReactActivity.java:68)

## To Reproduce
* login with facebook

## Expected Behavior
app not crash

## Code Example
const result = await LoginManager.logInWithPermissions(['public_profile', 'email']);

## Environment
Pixel phones (3, 4, 6)
Android version 12
react-native: 0.65.1
react-native-fbsdk-next: 4.2.0

**Comment by mikehardy** [comment]
Please search issues lists prior to consuming limited maintainer time in open source repos
https://github.com/thebergamo/react-native-fbsdk-next/issues?q=is%3Aissue+is%3Aclosed+android+12

Please help forward port the library if this is a priority for you: #55
