### ISSUE TITLE
Change app name in LoginManager iOS dialog

### ISSUE THREAD

**Issue by jorgegvallejo** [thebergamo/react-native-fbsdk-next#134]
## 🐛 Bug Report

Not sure if this is a bug, but I'm not able to change the app name in the iOS dialog that pops up when using the LoginManager. I've changed it successfully elsewhere and I can see it works since my location permission dialog works fine. 

The popup dialog that says:

`AppName Wants to Use "facebook.com" to Sign In`

Where is this AppName set?

RN 0.66
RNFBSDKN 4.6.0

**Comment by mikehardy** [comment]
Please try again with current version from here, reproducing against old versions is an inefficient use of our very very limited volunteer time here, we can reopen if you still reproduce - on iOS in particular we changed the underlying ios sdk for a much more recent one (and we're about to take the final step - in the next release - to get current)

**Comment by jorgegvallejo** [comment]
I've updated to version 5.0.0 and I still have the same issue. I figured this dialog gets the app name from the plist `FacebookDisplayName` but I've already changed that without any effect.

**Comment by mikehardy** [comment]
Very strange! Sorry the new version did not work, definitely needs a look then. No promises from me, I will likely have no time to look but if it reproduces then it's a problem either in code or documentation (that is: maybe it's not possible for some reason?)

**Comment by mikehardy** [comment]
Just one more note before I turn my attention away for possibly quite a while: we will be releasing one last-for-a-while breaking change version v6 here shortly that has the final step up to the most current iOS SDK. It's a bump from their facebook-ios-sdk v11 release series to the current v12. There is some chance that fixes it as well, so please do re-test when that comes out. Maybe later today? Perhaps tomorrow?

**Comment by jorgegvallejo** [comment]
Thank you. I'm going to keep trying things to see if I can narrow down the issue. I'll definitely update once the new release is ready and try it again.

**Comment by jorgegvallejo** [comment]
Solved it by renaming everything on the iOS side of the project and updating the pods. In my case I re-named everything, except the bundle identifier, and it still works fine.

I guess this dialog goes by the target project name?

Either way I think we can close this issue. Thank you once again

**Comment by mikehardy** [comment]
Strange - you would think, if you changed that item in the plist, it would do what you think. But it wasn't until you changed project name in Xcode that it worked? Well, at least it's possible! Thanks for reporting back

**Comment by jaygould** [comment]
After a load of separate name changes in Xcode I finally narrowed it down to the actual value which needs changing. It's in:

Targets > [target] > Build Settings > Basic > Packaging > Product Name.

Be sure to clean the build folder once that value has been changed.
