### ISSUE TITLE
Unable to read the license file `LICENSE` for the spec `FBSDKCoreKit (9.3.0)`

### ISSUE THREAD

**Issue by sangolariel** [thebergamo/react-native-fbsdk-next#136]
## 🐛 Bug Report
  I just install react-native-fbsdk-next. and when I run "pod install" an error message showed up: "Unable to read the license file `LICENSE` for the spec `FBSDKCoreKit (9.3.0)`". I am using "react-native": "0.66.3".

## To Reproduce

  yarn add react-native-fbsdk-next
  cd ios & pod install

**Comment by mikehardy** [comment]
Please use current versions and see if you can reproduce, also may help to `npx react-native-clean-project`
As it is, this is not reproducible by me nor does it contain sufficient information to help https://stackoverflow.com/help/minimal-reproducible-example
