### ISSUE TITLE
Facebook Analytics is going away

### ISSUE THREAD

**Issue by Desintegrator** [thebergamo/react-native-fbsdk-next#14]
Facebook Analytics is going away:
https://www.facebook.com/business/help/966883707418907

It should affect on AppEventsLogger i suppose. Right?

Facebook says there is an alternative like "Events Manager"
Can we use it here?

**Comment by thebergamo** [comment]
I just read it in my mail hehe
Need to check how to include it, at least it's going away only by mid of this year

**Comment by iDuuck** [comment]
I think this issue can be closed easily. Let me state quickly:

## What is Facebook Analytics about?

Facebook Analytics has (in theory) nothing to do with the App Events other than showing the stats that were sent to Facebook's servers.

### Events Manager to the rescue

Events Manager is right in the same business dashboard that you are currently using for creating a new Facebook App or managing your Ads, etc.

## Am I experiencing a breaking change?

You are only experiencing a "**breaking change**", if you are currently relying on Facebook Analytics to run tests(e.g. measuring success-figures by checking analytics and see the conversion values or using the Funnel feature of Facebook Analytics). So the best thing would be to migrate your analytics to something like Firebase/GA (see below) or Flurry.

*However, you don't need to update anything in your code, everything should keep working as before. Only the Software from Facebook is being closed, not the Endpoints `AppEvents` is calling.*

## What can I do?

**Case 1:** You are not even using `AppEvents`? → Nothing to do.
**Case 2:** You are using `AppEvents` as "Analytics" like feature? → Migrate to Flurry or Firebase
**Case 3:** You are using `AppEvents` as Measuring Tool for Mobile App Ads **only**? → Nothing to do.

## Quick Links:
- [Events Manager](https://www.facebook.com/events_manager2/list)
- [Facebook Analytics](https://www.facebook.com/analytics/)
- [Flurry](https://www.flurry.com/)
- [Firebase / Google Analytics](https://firebase.google.com/)

**Comment by thebergamo** [comment]
I guess it would be the case to just remove the reference to this AppEvents and in docs somehow state this chances would be enough for now right?

**Comment by thebergamo** [comment]
It's merged now :)

**Comment by iDuuck** [comment]
I think this issue can be closed then?
