### ISSUE TITLE
Can't build iOS using react-native-fbsdk-next 

### ISSUE THREAD

**Issue by catarinaguerreiro** [thebergamo/react-native-fbsdk-next#141]
I am trying to upgrade from **react-native-fbsdk** to **react-native-fbsdk-next**. All the facebook integration was done and was working with **react-native-fbsdk**. 
When I updated to **react-native-fbsdk-next**:
    - In android I can build the app (but I am still getting error when trying to login with facebook). 
    - With iOS I even can't build the app, I'm getting an error identified in this code explanation: '**symbol(s) not found for architecture x86_64**'. I tried to create the Swift file but it didn't work. Can someone help me? 

## Environment
"react": "16.9.0",
"react-native": "0.61.5"
"react-native-fbsdk-next": "^4.6.0" (i also tried with the last version of the package)

**Comment by mikehardy** [comment]
You will have no luck with this unfortunately:

>  "react-native": "0.61.5"

As far as I know, you cannot even successfully build react-native < 0.63.4 with Xcode 12.5, much less Xcode 13.

There are workarounds of course, you did not specify the symbol that was not found so it is hard to say what workaround you would need but here is my strongest advice:

Update to react-native 0.66.3 - https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.66.3

Take special care with your .pbxproj to avoid flipper duplicate symbols https://stackoverflow.com/a/69565059/9910298

Without doing this now, if you struggle to stay on older react-native I can say you will encounter all of the pain I have worked to shield people from, do not do it! :sweat_smile: 

https://github.com/facebook/react-native/issues/31941
https://github.com/facebook/react-native/issues/31480

resulting in https://github.com/facebook/react-native/commit/ac4ddec542febda744de218dae3a3d34edc7da84#diff-adcf572f001c2b710d14f409c14763f1a50b08369b3034548f1602685d21f67fR219

I can say with 100% certainty this module works fine, I worked on it the last few days extensively including rebuilding the demo from scratch  https://github.com/thebergamo/react-native-fbsdk-next/pull/127/commits/4ceac39db0cca950489b8fa39c39e1bec27a05e9 with testing on ios and android and integrating it into a fresh work project

Cheers
