### ISSUE TITLE
React-native app crashes after adding settings to the info.plist

### ISSUE THREAD

**Issue by nikita-zot-1408** [thebergamo/react-native-fbsdk-next#146]
The issue is that once I add my Facebook App ID to the info.plist file my app completely crashes without any signifficant error. 

Did anyone encounter this issue and know how to solve it?

Xcode version:3.1
OS:MacOS Monteray Latest version
React-native:0.66.3

**Comment by mikehardy** [comment]
>  Did anyone encounter this issue and know how to solve it?

No

> The issue is that once I add my Facebook App ID to the info.plist file my app completely crashes without any signifficant error.

A report of a crash without a stack trace is not useful for troubleshooting, can you get the native stack trace and include it in your report?

You'll note we just did a lot of work on the example app - https://github.com/thebergamo/react-native-fbsdk-next/tree/master/RNFBSDKExample

It works fine, and always worked fine for me while working on it, so the burden of proof is on you to make a https://stackoverflow.com/help/minimal-reproducible-example as I can assert in a correctly integrated project (the example here, multiple work projects), it works without crashing
