### ISSUE TITLE
LoginBehavior problem on Android ?!

### ISSUE THREAD

**Issue by OooCleMooO** [thebergamo/react-native-fbsdk-next#147]
Hi everyone,

I'm working on a project which need react-native-fbsdk-next but seems to have a problem on Android side. Referring on this article (https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/), seems Facebook is changing the login way for Android support, and may be it's now an LoginBehavior issue with the library.

If anyone have more informations about that, I'm listening carefully.

Thanks for regarding.

**Comment by mikehardy** [comment]
Hi there!
Not sure what I'm regarding, what have you tried, and what *exact* problem are you actually having?
The example app works out of the box.

**Comment by OooCleMooO** [comment]
Thanks @mikehardy for your response. The Facebook Login works well on local environment but now the app is on the stores and the project's owner returns that some people encountered a Facebook login problem (not all Android users), even Facebook app isn't install on the device. Referring to article that I mentioned above, seems Facebook is changing his login system on Android, and this is concerning some Android web navigators.

**Comment by mikehardy** [comment]
None of that is actionable.
Imagine you were maintaining this repo. A user like yourself came and told you all if that.
Now what do you do?
I can't think of anything to actually do, sorry

**Comment by FaysalBsata** [comment]
> Hi everyone,
> 
> I'm working on a project which need react-native-fbsdk-next but seems to have a problem on Android side. Referring on this article (https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/), seems Facebook is changing the login way for Android support, and may be it's now an LoginBehavior issue with the library.
> 
> If anyone have more informations about that, I'm listening carefully.
> 
> Thanks for regarding.

I'm having the exact same problem, facebook has reached out to me that my android app login with facebook is not working. and i found no errors or faults in any of modules or build! An answer anyone?

**Comment by thebergamo** [comment]
In this case, if we could have a way to reproduce this behavior we could investigate it a bit better. As there is quite a big number of Android devices and as stated above, not all have issues.

**Comment by FaysalBsata** [comment]
> In this case, if we could have a way to reproduce this behavior we could investigate it a bit better. As there is quite a big number of Android devices and as stated above, not all have issues.

Hi, so the only device I found showing the problem is Motorola G9/G9 Plus
