### ISSUE TITLE
Could not GET 'https://dl.bintray.com/vdopiacorp/fsdk/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by Lazybon** [thebergamo/react-native-fbsdk-next#149]
Hello everyone! The day before yesterday when generating AAB, I ran into a problem, please tell me how to fix it.

<img width="1440" alt="Screenshot 2021-12-10 at 17 59 21" src="https://user-images.githubusercontent.com/47330059/145585435-d9588ad4-0605-48c0-9169-202421ba3016.png">

**Comment by mikehardy** [comment]
Hi there, this is a network failure on some external service completely out of our control. It has nothing to do with this module.
