### ISSUE TITLE
iOS Installation Instructions

### ISSUE THREAD

**Issue by pix2D** [thebergamo/react-native-fbsdk-next#150]
[Installation instruction 3.2](https://github.com/thebergamo/react-native-fbsdk-next#32-ios) links to https://developers.facebook.com/docs/ios/use-cocoapods however this is redirected to https://developers.facebook.com/docs/ios/getting-started and on that page step 3 contains Swift code instead of Objective-C. Step 4 is also just a build step, so I'm assuming the step numbers changed and/or perhaps other things also?

The docs should be updated to reflect the changes above otherwise one is stuck at this point.

**Comment by mikehardy** [comment]
Unfortunately, we're not in control of when external projects update their examples from Objective-C to Swift, but I understand the react-native ecosystem still relies on Objective-C (as we do here in the module) so that's unfortunate. But still out of our control.

If you could post a PR to the docs that leave the reference to their guide but provide the correct Objective-C that would be really hepful.

As for the numbering, if at some point during updates here the numbering became disordered, that would also be easy to fix with a PR

Just hit the pencil icon at the top right here - github web UI will walk you through it  https://github.com/thebergamo/react-native-fbsdk-next#readme

**Comment by pix2D** [comment]
I understand it's out of your control, but seeing as this library depends on the FB SDK without those instructions it is not usable (on iOS at least). I wish I could contribute to the docs but I do not know Obj-C. Hopefully someone who does can assist.

**Comment by mikehardy** [comment]
I did not know objective-c when I made my first objective-c contribution. For more react-native modules and "giving it a shot" first time contributors, I believe that is par for the course.

The second part of the installation instructions may easily be modified to handle just the single case and is what the third-party documentation hints at anyway. Something along the lines of this but with only one openURL handler would probably be fine. Stated differently, you can likely use this snippet but delete the others if you like, although keeping react-native linking in there is useful at minimum, and is why it's documented in the readme

```objective-c
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RNGoogleSignin application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

```

perhaps just updating the text to mention that the snippet we should in the readme is probably what you want, in lieue of step 3 (in swift now) from facebook

if you try it and it works, knowing it works is useful, then it's the basis for a PR

**Comment by datoon83** [comment]
I wonder whether it's better re-writing the iOS installation documents to be something like this.  I'm missing some knowledge with Facebook libraries and just going off their app setup:

This follows the app installation guide for iOS.

Edit the .plist:

`<key>CFBundleURLTypes</key>
<array>
  <dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fb#FACEBOOK_APP_ID#</string>
  </array>
  </dict>
</array>
<key>FacebookAppID</key>
<string>#FACEBOOK_APP_ID#</string>
<key>FacebookDisplayName</key>
<string>#FACEBOOK_DISPLAY_NAME#</string>`

The objective C code is as follows - for events:

`
#import <FBSDKCoreKit/FBSDKCoreKit.h>
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  return YES;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                         openURL:url
                                               sourceApplication:sourceApplication
                                                      annotation:annotation];
}
`

However, I'm not sure what the difference is between doing the following:
`[FBSDKAppEvents activateApp];` 

Or just doing this within the React Native:
`
     const isEnabled = (result: TrackingStatus): boolean =>
              result === 'authorized' || result === 'unavailable';

            await new Analytics().iosAppTracking(result);
            if (isEnabled(result)) {
              Settings.initializeSDK();
            }
            Settings.setAdvertiserTrackingEnabled(isEnabled(result));
`

**Comment by datoon83** [comment]
After a bit of further investigation, I don't think the following is required:
```
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}
```

As this is actually in the Facebook SDK itself, once you've set the AdvertisingTrackingIsEnabled flag. 

On iOS you need to do the following by the looks of things:

```
Settings.initializeSDK();
```

**Comment by cavalos0086** [comment]
Found this articlet: https://dev.to/dozgunyal/adding-facebook-sdk-to-a-react-native-app-for-ios-cno and it worked for me. Sharing it here in case it helps someone else.

**Comment by mikehardy** [comment]
You can make an open source contribution by helping all future users of this module! Update our documentation as needed:

> Just hit the pencil icon at the top right here - github web UI will walk you through it https://github.com/thebergamo/react-native-fbsdk-next#readme

**Comment by cavalos0086** [comment]
@mikehardy There you go: https://github.com/thebergamo/react-native-fbsdk-next/pull/216 
Thanks for the suggestion to add an open-source contribution 😄

**Comment by mikehardy** [comment]
@cavalos0086 --> :trophy:  - thank you!
