### ISSUE TITLE
Facebook Login iOS issue when Facebook app is also installed

### ISSUE THREAD

**Issue by djwesty** [thebergamo/react-native-fbsdk-next#151]
## 🐛 Bug Report
When using Facebook login when the Facebook app is installed (requires a real device), the facebook app returns to the webview and does not actually log the user in. This leads to the user being stuck in a loop of trying to log in. 

I see that there is another similar [open issue](https://github.com/thebergamo/react-native-fbsdk-next/issues/59) which has had some attention but was not resolved. I hope someone else may be able to re-create this with the information I am posting here in this new issue

## To Reproduce

https://user-images.githubusercontent.com/3537850/145878665-8a49582e-de14-49be-9ec1-2f3567d0788a.mp4

1. Clone the example code on a Mac
2. Replace the App ID, Client token and CFBundleURLSchemes in ios/RNFBSDKExample/Info.plist with your Facebook App ID
3. Install Facebook on your iOS device
4. Build and Run the example App on your iOS device via Xcode
5. Try to log in with a know user which would otherwise work on Android, or work on iOS when the Facebook app is not installed

For this test I created a new Facebook App in the Facebook developer console, and followed the relevant instructions for adding the Facebook login product to the app. 

## Expected Behavior
I would expect the Facebook app to return to the Example app after successfully authenticating 

## Code Example
I am using the Example App exactly as it is, aside from changes in Info.plist for the following keys

```
<key>FacebookAppID</key>
<string>MY_APP_ID</string>
<key>FacebookClientToken</key>
<string>MY_CLIENT_TOKEN</string>
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>fbMY_APP_ID</string>
    </array>
  </dict>
</array>
```

## Environment
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 1.74 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.1.4 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /Users/davidwestgate/.rvm/rubies/ruby-3.0.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by thebergamo** [comment]
@djwesty I believe would be best if you could post your bug report together with the other issue and make sure you're using latest code available.As from last comment from Mike, all SDKs are updated now.

**Comment by swelly-ian** [comment]
Still an issue with latest build.

**Comment by gabrielbezerra81** [comment]
I was having the same issue, you should update your AppDelegate.m to handle linking right. Facebook should be on top of RCTLinking Manager like the code below:

![image](https://user-images.githubusercontent.com/24686314/170546470-2d362b66-543a-4552-88b7-d34ced25f50d.png)

**Comment by shivam-kakkar27** [comment]
> I was having the same issue, you should update your AppDelegate.m to handle linking right. Facebook should be on top of RCTLinking Manager like the code below:
> 
> ![image](https://user-images.githubusercontent.com/24686314/170546470-2d362b66-543a-4552-88b7-d34ced25f50d.png)

This worked. Thanks

**Comment by michalis-ligopsychakis** [comment]
Hello everyone :)
I have the same issue but I am using SceneDelegate.

Is there any alternative of that works for SceneDelegate because right now the "openURL" method doesn't get called from my AppDelegate.

Thanks!

**Comment by michalis-ligopsychakis** [comment]
Ok I think I figure out a solution..
I added this method on my SceneDelegate:
```
- (void)scene:(UIScene *)scene openURLContexts:(NSSet<UIOpenURLContext *> *)URLContexts
{
  if ([URLContexts.allObjects count] > 0) {
    NSURL *url = URLContexts.allObjects.firstObject.URL;
    
    if ([url.absoluteString rangeOfString:@"facebook"].location != NSNotFound) {
      [[FBSDKApplicationDelegate sharedInstance]
      application: [UIApplication sharedApplication]
      openURL: url
      sourceApplication: nil
      annotation: nil];
    }
  }
}
```
