### ISSUE TITLE
Upgrade Facebook iOS SDK at least 12.2.0 or higher

### ISSUE THREAD

**Issue by ocarpinteyro** [thebergamo/react-native-fbsdk-next#152]
It looks that needs upgrading **Facebook iOS SDK** at least 12.2.0 to solve many issues like:

> Fixed: aem_conversion_configs should contain an explicit "fields" parameter (Issue #1933)

- Issue replicated in version 6.6.1: https://github.com/facebook/facebook-ios-sdk/issues/1933

Facebook iOS SDK Changelog: https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#1221

What do you think guys? 

Regards.

**Comment by mikehardy** [comment]
I think you should do it! 
Either just don't set anything at all, and you'll get it next time you build:
https://github.com/thebergamo/react-native-fbsdk-next/blob/f727b98c0fb1ade4c72aaea0d60aa9151c0e3bdb/android/build.gradle#L47 (note `12.+`)

Or set `ext.FACEBOOK_SDK_VERSION` explicitly in your `android/build.gradle` `ext` block if you like knowing you won't accidentally get 12.3 or similar

In other words: it's done :-), enjoy
