### ISSUE TITLE
AEM logging implementation for iOS

### ISSUE THREAD

**Issue by rnike** [thebergamo/react-native-fbsdk-next#153]
Hi, currently on my work we need the AEM Logging feature for iOS but it isn't in this sdk yet.

Offical document: [Aggregated Event Measurement(AEM)](https://developers.facebook.com/docs/app-events/guides/aggregated-event-measurement/)

Here's what I'm planning to do

1. export the `FBAEMReporter recordAndUpdateEvent:currency:value:parameters:` function to js (mentioned in the document at **Integration with Aggregated Events Measurement Kit -> Step 4. Add AEM Logging**)
2. documentation for AEM

**Comment by mikehardy** [comment]
Fantastic!
