### ISSUE TITLE
RN 0.66.2 | Android | Execution failed for task ':react-native-fbsdk-next:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by NourAliAbdou** [thebergamo/react-native-fbsdk-next#158]
Hi,

### installed successfully & configured properly but the build failed with the following error: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk-next:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-fbsdk-next:debugCompileCl
   > Failed to transform legacy-support-v4-1.0.0.jar (androidx.legacy:legacy-support-v4:tegory=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.us
      > Could not find legacy-support-v4-1.0.0.jar (androidx.legacy:legacy-support-v4:1.
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.
   > Failed to transform legacy-support-core-utils-1.0.0.jar (androidx.legacy:legacy-supr, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=releas
      > Could not find legacy-support-core-utils-1.0.0.jar (androidx.legacy:legacy-suppo
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-
   > Failed to transform cardview-1.0.0.jar (androidx.cardview:cardview:1.0.0) to match 
org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find cardview-1.0.0.jar (androidx.cardview:cardview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/cardview/cardview/1.0.0/car
```

### Solutions I tried: 🔢 
- I thought that it's a linking issue, so I did manually linking , SAME.
- I tried all possible codes in build.gradle; gives extra errors.
- I added to app/build.gradle:
   implementation 'androidx.legacy:legacy-support-v4:1.0.0'
   implementation 'androidx.cardview:cardview:1.0.0-rc02'
   implementation 'androidx.legacy:legacy-support-core-utils:1.0.0-rc02'
gives no effect.
- also added to build.gradle of the lib, no effect.
- tried to downgrade the lib version, SAME.
- it works properly with RN 0.63, but there is no chance to downgrade RN 🗡️!
- tried  classpath('com.android.tools.build:gradle:4.2.2')
- tried  classpath('com.android.tools.build:gradle:7.0.3')
- tried  distributionUrl=https\://services.gradle.org/distributions/gradle-7..2all.zip

### Environment
 "react": "17.0.2",
 "react-native": "0.66.2",
 "react-native-fbsdk-next": "^6.2.0",

 classpath('com.android.tools.build:gradle:4.1.2')
 distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip

--
**Any Clarification or explanation to what is happening!
Any possible solution?!
Thanks.**

**Comment by mikehardy** [comment]
I would not add those specific dependencies to build.gradle, I think that goes farther down the wrong path.

Usually this is either a local network failure where gradle cannot download something, or an incorrect set of repository definitions for gradle

Our example builds, and should build for you. Please try building the example here and if it works then you know you have some sort of project-specific issue, where the solution will be found in the difference between your project and the example project

Having it work with RN63 but not whatever you were on first is suspicious. You do not mention which versions you tried in between current and 63. Perhaps you still need jcenter() in your build. Examining the diffs here points at that https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.66.0

**Comment by NourAliAbdou** [comment]
the current RN is 0.66
I tried to build the example you mentioned on my computer, same weird error!

**Comment by mikehardy** [comment]
Yet it builds fine in CI https://github.com/thebergamo/react-native-fbsdk-next/actions/workflows/ci.yml

 something is wrong on your local network or computer somehow - you're trying everything I can think of. This must be frustrating

`npx react-native-clean-project` perhaps ? That is very thorough but is also a vague possible solution unfortunately

With no ability to reproduce the failure (it builds in all my environments and CI) I can't help further, apologies

**Comment by rnike** [comment]
We are also on react-native 0.66.2 but not facing this issue, I've noticed your version of `com.android.tools.build:gradle` is different from us, we are using `com.android.tools.build:gradle:4.2.2`

I've tried downgrading the version to `com.android.tools.build:gradle:4.1.2` to match your environment and it built failed, but the error message is different from yours.

Maybe you can try upgrade it to `4.2.2` and see if it works or not

**android/build.gradle**
```diff
dependencies {
-     classpath('com.android.tools.build:gradle:4.1.2')
+     classpath('com.android.tools.build:gradle:4.2.2')
```

**Comment by NourAliAbdou** [comment]
@rnike 
I've tried upgrading already!
no effect!

**Comment by NourAliAbdou** [comment]
to reproduce:
init new project -> installed the lib on fresh land!
same error 👎🏻

**Comment by mikehardy** [comment]
> Yet it builds fine in CI https://github.com/thebergamo/react-native-fbsdk-next/actions/workflows/ci.yml

This is not just any old reproduction, the great thing about the CI is that every version of every thing is specified and visible. That is, it is *completely reproducible*. I have no idea what is wrong in your build environment + project unfortunately. All I know is that there is a fully transparent working build to pattern off
