### ISSUE TITLE
SDK not sending events to facebook events_manager dashboard when AppEventsLogger.logPurchase() has been called

### ISSUE THREAD

**Issue by henryosim** [thebergamo/react-native-fbsdk-next#161]
- I have installed and initialised sdk then I put `                AppEventsLogger.logPurchase(15, 'USD', {param: 'value'});
` in the root of the app along with login code example
- user can login into facebook successfully but app events are not sent to facebook. Below is the component that has the facebook sdk
`import React, {FC} from 'react';
import {createStackNavigator} from '@react-navigation/stack';

import {WebviewParams} from 'components/WebView/FullPageWebView';
import {screenNames} from 'contentSquareScreenNames';
import {useContentSquareReporting} from 'hooks';
import {AppEventsLogger, Settings} from 'react-native-fbsdk-next';

import {Platform, View} from 'react-native';
import {
  AccessToken,
  AuthenticationToken,
  LoginButton,
} from 'react-native-fbsdk-next';

export type HomeStackParamList = {
  HomeWebView: WebviewParams;
};

const Stack = createStackNavigator<HomeStackParamList>();

const Home: FC = () => {
  useContentSquareReporting(screenNames.home);

  // Settings.setAppID('2767386567666666');
  Settings.initializeSDK();
  // Log a $15 purchase.
  AppEventsLogger.logPurchase(15, 'USD', {param: 'value'});

  // Log standard event. e.g. completed registration
  AppEventsLogger.logEvent(AppEventsLogger.AppEvents.CompletedRegistration, {
    [AppEventsLogger.AppEventParams.RegistrationMethod]: 'gigcat.mush@yahoo.com',
  });
  AppEventsLogger.logEvent('Share Session', 1, {id: 1});

  AppEventsLogger.logEvent('fb_mobile_complete_registration', {
    fb_registration_method: 'phone',
  });

  return (
    <View style={{marginTop: 100}}>
      <LoginButton
        onLoginFinished={(error, result) => {
          if (error) {
            console.log('login has error: ' + result.error);
          } else if (result.isCancelled) {
            console.log('login is cancelled.');
          } else {
            if (Platform.OS === 'ios') {
              AuthenticationToken.getAuthenticationTokenIOS().then(data => {
                console.log(data?.authenticationToken);
                // Log a $15 purchase.
                AppEventsLogger.logPurchase(15, 'USD', {param: 'value'});
              });
            } else {
              AccessToken.getCurrentAccessToken().then(data => {
                console.log(data?.accessToken.toString());
                // Log a $15 purchase.
                AppEventsLogger.logPurchase(15, 'USD', {param: 'value'});
              });
            }
          }
        }}
        onLogoutFinished={() => console.log('logout.')}
        loginTrackingIOS={'limited'}
        nonceIOS={'my_nonce'}
      />
    </View>
  );
};

export {Home};
`

**Comment by rnike** [comment]
How did you know that the app events are not sent to facebook

**Comment by rnike** [comment]
Besides, I can see some problems in your code, although I don't know what the `useContentSquareReporting` hook is doing,  you should wrap your function in a useEffect

```js
const [isLogin,setIsLogin] = useState(false);

//  this effect will fire only once per component's life cycle
useEffect(()=>{
  Settings.initializeSDK();
},[]);

// this effect will fire when isLogin changed
useEffect(()=>{
  // Log standard event. e.g. completed registration
  AppEventsLogger.logEvent(AppEventsLogger.AppEvents.CompletedRegistration, {
    [AppEventsLogger.AppEventParams.RegistrationMethod]: 'gigcat.mush@yahoo.com',
  });
  AppEventsLogger.logEvent('Share Session', 1, { id: 1 });

  AppEventsLogger.logEvent('fb_mobile_complete_registration', {
    fb_registration_method: 'phone',
  });
},[isLogin]);

// call logPurchase() where you needed
const logPurchase = useCallback(()=>{
  // Log a $15 purchase.
  AppEventsLogger.logPurchase(15, 'USD', { param: 'value' });
},[]);
```

**Comment by pratikgehlott** [comment]
Be extra cautions about how you send the custom parameters to Meta. :)
