### ISSUE TITLE
Android crash - Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by ahmadzraiq** [thebergamo/react-native-fbsdk-next#177]
Hello,
After upgrading the version from 4.6.0 to 6.2.0 I got this error on Android
**Method addObserver must be called on the main thread**

react native version is  0.63.4

Everything is good on IOS

![Screenshot_1641994463](https://user-images.githubusercontent.com/43582061/149150209-7c97f684-dd47-4edf-af17-51c33922a575.png)

**Comment by mikehardy** [comment]
@ahmadzraiq please include all of the details you would want if a colleague came to you with this.
Triage is hard and we need your help, versions, stack trace with line numbers from `adb logcat` etc etc
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ahmadzraiq** [comment]
@mikehardy Updated

**Comment by mikehardy** [comment]
Great, with that information I can tell you that our documentation needs an update but you will not be able to use that version of this package with react-native 0.63. You must update to react-native 0.64 or higher https://react-native-community.github.io/upgrade-helper/ - which is actually required if you want to do the build on Xcode 12.5+ which is transitively required in order to correctly support ios15+, so it should be quite high on the priority list regardless. react-native < 0.64 is not well supported (or really supported at all at this point) in the react-native ecosystem, I'd move forward ASAP

**Comment by ahmadzraiq** [comment]
@mikehardy  I've upgraded react-native to 0.64.2, but the error still there

**Comment by mikehardy** [comment]
:thinking: I was pretty sure that would do it. I wonder if you continue moving forward now (https://react-native-community.github.io/upgrade-helper/) if at some point it does go away? Thankfully those are pretty easy upgrades if I remember correctly.
Re-opening as that did not provide the expected fix...

**Comment by mikehardy** [comment]
Unfortunately I think we may now fall in this case: 
https://stackoverflow.com/help/minimal-reproducible-example

Our example in this repository runs correctly as far as I can tell, and it is actually built from scratch (https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh) so it serves as a really good demonstration of how to construct the project from scratch, and also demonstrates (as a minimal reproducible example) that it works.

Perhaps your error is coming from another module? You have not included your package.json or anything else so it's impossible to say. But it *appears* to me, based on refresh-example.sh working to generate a working project, that I cannot currently reproduce with the information provided

**Comment by ahmadzraiq** [comment]
@mikehardy  My main issue is "**Install registered on iOS**" doesn't want change even though I haven't changed anything and I didn't release any new version, I thought if I upgrade the sdk version from 4.0.0 into 6.2.0 it will work 
<img width="698" alt="Screen Shot 2022-01-12 at 6 10 15 PM" src="https://user-images.githubusercontent.com/43582061/149177630-6af4af55-0e60-458c-aeba-c5f554c6ea54.png">

Any advise?
