### ISSUE TITLE
getCurrentAccessToken() after app restart return null

### ISSUE THREAD

**Issue by mirkoricci94** [thebergamo/react-native-fbsdk-next#178]
After login FBAccesToken returns with no problem. If I refresh metro FBAccesToken exists, but if I kill the app and call getCurrentAccessToken() after app restart, it returns always null on IOS. Maybe there is an issue with persisting accessToken

**Comment by mikehardy** [comment]
Hi there! This lacks any sort of detail needed to help.

Imagine you are an extremely busy engineering manager. You have a direct report that comes to you with this. What do you do, drop everything to ... what exactly? Please do the prep work you would want done, it will help tremendously

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
