### ISSUE TITLE
Android issue - "For your account security, logging into Facebook from an embedded browser is disabled."

### ISSUE THREAD

**Issue by coolyoshi** [thebergamo/react-native-fbsdk-next#181]
I'm testing facebook login for android on my emulator, and getting the following error when clicking the login with facebook button: "For your account security, logging into Facebook from an embedded browser is disabled."

It seems to work fine for iOS though.

Am I doing something wrong or are there any workarounds?

**Comment by alvintankc** [comment]
It seems like facebook has deprecated logging in via embedded browser (webview) on Android.
https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews

**Comment by mikehardy** [comment]
Have you examined the example to see how we do it?
https://github.com/thebergamo/react-native-fbsdk-next/blob/master/RNFBSDKExample/App.js
I don't recall getting the error in my work projects nor in the example.

**Comment by coolyoshi** [comment]
Thanks all, at least so far it seems to only happen on emulator. Will report back if I find out it's not an emulator related issue.

**Comment by alvintankc** [comment]
It's happening to a few of my existing project apps on my android device as well. 
![Screenshot_20220124-150921](https://user-images.githubusercontent.com/85146944/151090483-29a45769-c015-4208-a294-a6d271828bb6.png)

**Comment by Akshh057** [comment]
Previously my project had this version `"react-native-fbsdk": "^1.0.0"` and after upgrading the version to `    "react-native-fbsdk": "^3.0.0",`, now it works perfectly

**Comment by mikehardy** [comment]
@Akshh057 wrong repo. we're "react-native-fbsdk-next" over here.

**Comment by Nezran** [comment]
Hi,

I am facing the same issue, it work on some device but this doesn't work on a Honor 20 Pro, android 10.

"react-native-fbsdk-next": "^11.0.1"

Even with forcing the loginBehaviorAndroid with the LoginButton component. 

Stuck since one week, does someone has the same issue ?

**Comment by andre-luiz1997** [comment]
I can confirm that today 19/07/2023, react-native-fbsdk-next is still not working with Facebook login. Is there any solution posted?

**Comment by hoangtrunnam** [comment]
Does anyone have any solution?
