### ISSUE TITLE
Bintry is down and I can't run the project. Alternatives?

### ISSUE THREAD

**Issue by osvald0** [thebergamo/react-native-fbsdk-next#183]
## 🐛 Bug Report

I can't run the project because bintry is down. [Check Status Here](https://status.bintray.com/)
I'm not sure if this is the problem but We need an alternative for the JCenter sunset.

## To Reproduce

Try to run any project where you use the package.

## Environment

react: 17.0.1 => 17.0.1 
react-native: 0.64.2 => 0.64.2 

![Screenshot from 2022-01-16 10-23-50](https://user-images.githubusercontent.com/20977158/149662066-1f3f50d7-269c-40a0-a281-e96eed4b098b.png)

**Comment by osvald0** [comment]
OK, I found the fix:

![Screenshot from 2022-01-16 10-51-52](https://user-images.githubusercontent.com/20977158/149662906-3a99b268-5690-4aa7-a375-857f2d52c110.png)

**Comment by mikehardy** [comment]
We don't use bintray as far as I know? If you have up to date versions of react-native and react-native-fbsdk-next bintray should not be in use and you should be fine. Not a problem with this module...
