### ISSUE TITLE
How to get an authorization code?

### ISSUE THREAD

**Issue by Seb33300** [thebergamo/react-native-fbsdk-next#186]
Is it possible to get an `authorization code` using this library?

This is the code returned by `https://www.facebook.com/v12.0/dialog/oauth`
See: https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/

It is required to implement this authentication process:

![image](https://user-images.githubusercontent.com/915273/150073459-ff9be18e-67de-49ca-bc68-690d53cb740b.png)

I found some other related issues to this, but unfortunately, no answer:
- https://github.com/thebergamo/react-native-fbsdk-next/issues/35
- https://github.com/facebookarchive/react-native-fbsdk/issues/746

Thank you

**Comment by mikehardy** [comment]
Hey @Seb33300 - I'm unsure, as this is the first time this use case has surfaced while I've helped maintain the repo. Have you dug in to the code to see what's available via native SDK APIs to see if there is anything existing there, or how to add it if not? Could be a documentation issue, or you may have to add the feature from native SDKs up through javascript. If it needs a PR please target the "beta" branch, as we are in the final quality-testing phase of a typescript rewrite, and the beta branch is where that work lives

**Comment by Seb33300** [comment]
No. I had to use the access token directly from the client.

**Comment by blobmold** [comment]
This just increases the amount of code required on server side if a web app using PKCE flow and you have this SDK converting `code` to `authenticationToken` client-side - you'll have to check for `code` or `authenticationToken`, if no `code`, then validate `authenticationToken` and retrieve the user from the server. I still think that exchanging `code` to `authenticationToken` client-side is unnecessary
