### ISSUE TITLE
Can't share image, ShareDialog not show on Android and IOS

### ISSUE THREAD

**Issue by vuonghvat** [thebergamo/react-native-fbsdk-next#187]
On IOS: 
[43180:367646] -canOpenURL: failed for URL: "fbapi:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
On Android:
Not show dialog.

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

But please also note: this repository moves forward through community effort. Stated differently, if you have a specific problem, like this, you will need to invest your time or your company's time in a fix for the problem, and propose the solution here

We can merge and release PRs but there is no group of people here with time to work on other people's problems
