### ISSUE TITLE
RN FbSdk setAdvertiserTrackingEnabled()  is not working, Unhandled promise rejection TypeError  is returned  on IOS Simulator

### ISSUE THREAD

**Issue by salihboshnak** [thebergamo/react-native-fbsdk-next#190]
## 🐛 Bug Report

setAdvertiserTrackingEnabled()  is not working, Unhandled promise rejection TypeError  is returned
## To Reproduce

- install react-native-fbsdk-next  via  "npm install react-native-fbsdk-next"
- change ios realated files according to documentation: info.plist, appDelegate.m
- cd ios
- pod install
- cd ..
- run "react-native run-ios"
- while running the app on simulator (iphone12), i get the error 
- Unhandled promise rejection TypeError, 
 
![Simulator Screen Shot - iPhone 12 - 2022-01-22 at 10 20 19](https://user-images.githubusercontent.com/7852720/150630810-3980b674-5847-4bec-b8f2-59fc3f7a4ff2.png)

## Code Example

this is my code 

import { useEffect, useState } from "react"
import { getTrackingStatus, requestTrackingPermission } from "react-native-tracking-transparency"
import { setAdvertiserTrackingEnabled } from "react-native-fbsdk-next"

const useGetTrackingStatus = () => {
    const [trackingStatus, setTrackingStatus] = useState(false)

    const setAdvertiserStatus = (status: boolean) => {
	                
        setAdvertiserTrackingEnabled(status)
        .then((result) => setTrackingStatus(status))
        .catch((err) => setTrackingStatus(false));    
    }

}

## Environment

IOS
running on iPhone12 simulator
react-native version is 0.64.1
**react-native-fbsdk-next  version is 6.14.15**

if any other details is needed please request

**Comment by mikehardy** [comment]
Hi there! Not enough information to reproduce - what version of this module, for example? Big difference between v6 and v7 for example

https://stackoverflow.com/help/how-to-ask

**Comment by salihboshnak** [comment]
hi @mikehardy 
thanks for your reply
i updated the bug description

thanks for helping

**Comment by salihboshnak** [comment]
the issue was resolved 

i am not sure if i am doing something not correct, or it is a real bug
but when i changed the code to 

import { useEffect, useState } from "react"
import { getTrackingStatus, requestTrackingPermission } from "react-native-tracking-transparency"
import {Platform, NativeModules} from 'react-native';

**const Settings = NativeModules.FBSettings;**

const useGetTrackingStatus = () => {
const [trackingStatus, setTrackingStatus] = useState(false)

const setAdvertiserStatus = (status: boolean) => {

    // note: TODO: need to add a condition of ios platform here
    **Settings.setAdvertiserTrackingEnabled(true)**
    .then((result) => setTrackingStatus(true))
    .catch((err) => setTrackingStatus(false));    
}

that is getting the FBSettings and call its method it worked

but i don't understand why 
is there something wrong with my import ? (in the original code i provided?)

**Comment by andrewdazs** [comment]
@salihboshnak in your bug report you're importing the method directly. I think you should import the `Settings` first to use the `setAdvertiserTrackingEnabled `. Like this:

```
import { Settings } from 'react-native-fbsdk-next'

Settings.setAdvertiserTrackingEnabled(status)

**Comment by salihboshnak** [comment]
@andrewdazs  thanks for passing by

but i think you are wrong 
since the function  setAdvertiserTrackingEnabled(status) implementation 
is calling Settings.setAdvertiserTrackingEnabled(status)  under IOS platform only 

this is a wrapper function in order to make the API  not related to a platform 
and to make easier for developers
