### ISSUE TITLE
There is an issue to retrieve profile info in Android

### ISSUE THREAD

**Issue by AhmedSharawyFCIS** [thebergamo/react-native-fbsdk-next#199]
`Profile.getCurrentProfile()` always returns null at the first time when calling it in Android after `LoginManager.logInWithPermissions(['public_profile','email'])`

**Comment by salao-na-mao** [comment]
Same, here!

**Comment by salao-na-mao** [comment]
@AhmedSharawyFCIS https://github.com/thebergamo/react-native-fbsdk-next/issues/73#issuecomment-1043025601

**Comment by mikehardy** [comment]
@salao-na-mao I repeat my comment from that issue:

> without a PR, it won't advance - but I'd be happy to collaborate. Could you make a PR? Please pay special attention to the documentation for it, to make sure people understand it is a Promise (asynchronous resolution) and could be a bit delayed.
> 
> I would also want to make sure that it timed out in some way - is there a chance this could hang and never resolve? That would not be acceptable - it would violate the caller's expectation of the API, so if there is not a timeout in the underlying call we would need to make it interruptible and set a timeout ourselves
