### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FBSDKCoreKit":

### ISSUE THREAD

**Issue by ceyanesb** [thebergamo/react-native-fbsdk-next#20]
Hi, I am having trouble using this library, I followed the instructions with the facebook guide that appears on the readMe and did all the steps.

Before this, I used the react-native-fbsdk library which is now deprecated due to facebook releasing a newer version (0.9) of the SDK. In the instructions [here](https://developers.facebook.com/docs/ios/use-cocoapods#step-2--specify-and-install-the-facebook-components) says that you can add the pod that you need in the podfile of ios but when I add them and then pod install I get this error:

````
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 9.0.1, ~> 9.0.1)

  In Podfile:
    FacebookShare was resolved to 0.1.1, which depends on
      FBSDKCoreKit (~> 4.14)

    react-native-fbsdk-next (from `../node_modules/react-native-fbsdk-next`) was resolved to 4.0.0, which depends on
      react-native-fbsdk-next/Core (= 4.0.0) was resolved to 4.0.0, which depends on
        FBSDKCoreKit (~> 9.0.1)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `react-native-fbsdk-next`.
   You should run `pod update FBSDKCoreKit` to apply changes you've made.
````

Also, with this library you need to modify the appDelegate.m [here](https://github.com/thebergamo/react-native-fbsdk-next#installation) but when I add that code it says I am missing an import, I know the import missing is FBSDKCoreKit or at least I think it is because the previous SDK used that one. To fix that you need to add the pod but when I add it the error above shows up.

**Comment by sanghavan** [comment]
@ceyanesb I think you may try on following cocoapods suggestion:
>  out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.

```pod install --repo-update``` may be help in your case.

**Comment by ceyanesb** [comment]
> @ceyanesb I think you may try on following cocoapods suggestion:
> 
> >  out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> 
> 
> 
> ```pod install --repo-update``` may be help in your case.

Hi! Actually that didn't work, the problem was that the documentation of FacebookSDK and the library have different naming in the pods, which is weird because this library work with the latest version of that SDK, so i don't know if it's a FBsdk documentation issue or anything else. Anyways I finally was able to update to the latest version

**Comment by thebergamo** [comment]
Seems to me that this issue can be closed then :)

Thanks @sanghavan for your help in solve this issue o/

**Comment by florinvasilevilsan** [comment]
> > @ceyanesb I think you may try on following cocoapods suggestion:
> > > out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> > 
> > 
> > `pod install --repo-update` may be help in your case.
> 
> Hi! Actually that didn't work, the problem was that the documentation of FacebookSDK and the library have different naming in the pods, which is weird because this library work with the latest version of that SDK, so i don't know if it's a FBsdk documentation issue or anything else. Anyways I finally was able to update to the latest version

So how did you fix this problem, if you wouldn't mind sharing?

**Comment by Nargle30** [comment]
Hi,
I'm having this issue too when I add  pod 'FacebookCore' to Podfile
Is there a way to fix it? Or may be there is an earlier version that we could all use?
Thanks

"react-native-fbsdk-next": "4.1.0",
"react-native": "0.63.4",

Podfile.lock
  - FBSDKCoreKit (9.0.1):
    - FBSDKCoreKit/Basics (= 9.0.1)
    - FBSDKCoreKit/Core (= 9.0.1)
  - FBSDKCoreKit/Basics (9.0.1)
  - FBSDKCoreKit/Core (9.0.1):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (9.0.1):
    - FBSDKLoginKit/Login (= 9.0.1)
  - FBSDKLoginKit/Login (9.0.1):
    - FBSDKCoreKit (~> 9.0.1)
  - FBSDKShareKit (9.0.1):
    - FBSDKShareKit/Share (= 9.0.1)
  - FBSDKShareKit/Share (9.0.1):
    - FBSDKCoreKit (~> 9.0.1)

**Comment by mikehardy** [comment]
If anything I'd go for a later version (9.2.0 is out https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md) which may be accessed via editing the podspec in this module to reference the new version then using patch-package to persist the change (that's how I'm doing it).

Pod version conflicts are out of scope for this package I think. Pod installation problems where suitable versions can't be found may be resolved by removing Podfile.lock and trying again, or looking at the graph pod spits out when there is a version collision, finding the package that needs the lower version, and making it compatible somehow with the new one.

If you truly need an older version of the FB iOS pods because you can't get the other packages to use the new version, then you don't want this repo, you want the old react-native-fbsdk repo I think
