### ISSUE TITLE
Android share link to Facebook throws  [Error: UnknownError]

### ISSUE THREAD

**Issue by kristijantomic** [thebergamo/react-native-fbsdk-next#200]
## 🐛 Bug Report
Share a link to a Facebook profile throws [Error: UnknownError], even though ShareDialog.canShow return true and content is successfully shared to Facebook. It seems that somehting throws in ShareDialog.show method. This happens only on Android devices, iOS seems to work fine. 

## Environment

"react": "17.0.2",
"react-native": "0.67.2",
"react-native-fbsdk-next": "^7.0.1",

**Comment by kristijantomic** [comment]
Hi @[mikehardy](https://github.com/mikehardy), really sorry for my rudeness and unclear definintion of the report issue 😢 . I tried to investigate where the error is thrown but i could no mange to find it. I  tried to put beak points in FBShareDialogModule and FBMessageDialogModule on show methods but it did not throw there. I'll try again on mondy. 

Thank you!

**Comment by kristijantomic** [comment]
Error message comes after Facebook share dialog is closed onError collback in th follwing class:
react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/ReactNativeFacebookSDKCallback.java

![Screenshot 2022-02-12 at 15 48 34](https://user-images.githubusercontent.com/1470994/153716023-bbb04a2d-70b0-4a56-be8a-f2bff67e1281.png)

**Comment by dishantwalia** [comment]
Error from logcat: 
E/com.facebook.GraphResponse: {HttpStatus: 400, errorCode: 190, subErrorCode: 460, errorType: OAuthException, errorMessage: Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.}

**Comment by mikehardy** [comment]
@dishantwalia I'm not sure what your desired action here is? If you propose a PR that is reasonable and exposes more information about errors like this - assuming that's the issue? - so that your code may handle them by re-authenticating the user, we can merge it

**Comment by omergilboa** [comment]
i'm using `react-native@0.68.5` and `react-native-fbsdk-next@6.2.0` and still getting `[Error: UnknownError]` when using `ShareDialog.show` so what was the solution here?
