### ISSUE TITLE
 Showing Recent Issues /Package.swift has no Package.swift manifest for version 0.10.3 in https://github.com/thebergamo/react-native-fbsdk-next

### ISSUE THREAD

**Issue by nwpnkmngm** [thebergamo/react-native-fbsdk-next#201]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/48342930/154028663-723844d9-0085-43c6-8a29-a7b36a5f6643.png">

**Comment by mikehardy** [comment]
An image and vague title is not an actionable issue report, sorry
There is no Package.swift in this repo
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
...and try the example project here, it should work. `refresh-example.sh` script here should also show a from-scratch integration from `npx react-native init`
