### ISSUE TITLE
[7.3.0] typings not found

### ISSUE THREAD

**Issue by efstathiosntonas** [thebergamo/react-native-fbsdk-next#206]
## 🐛 Bug Report

  After upgrading to 7.3.0 I get no typings found, tried installing @types/react-native-fbsdk-next to no avail so I guess there's something wrong in the typings export during build.

exact error is: `TS7016: Could not find a declaration file for module 'react-native-fbsdk-next'.`

## To Reproduce

just install 7.3.0. Prior opening issue I deleted `node_modules` and re-installed but it won't fix.

## Expected Behavior

  Typings should be available

## Environment

Typescript 4.5.4

**Comment by mikehardy** [comment]
Oh no! Performing triage now, there's only one feature in the release but it's a big one and it did alter package inclusion rules #205 - will pop out a 7.3.1 as soon as I figure out what happened + repair

**Comment by mikehardy** [comment]
Strange (to me) interaction between the `./tsconfig.json` file and the new `plugin/tsconfig.json` where the new plugin one sets an outdir of `src` and the main typescript transpile is picking that up and putting things one sub-directory down now, in in `src`

So, if I update `<my app dir>/node_modules/react-native-fbsdk-next/package.json` such that it's `types` entry is now 

```json
  "types": "lib/typescript/src/index.d.ts",
``` 

...in place of

```json
  "types": "lib/typescript/index.d.ts",
```

...then it works for me

@efstathiosntonas (or anyone else watching) if you confirm that also works for you I'll publish that change

**Comment by efstathiosntonas** [comment]
@mikehardy confirms it's working, thanks. 

ps. was about to say it doesn't work, had to restart the crappy Webstorm for the error to go away....

**Comment by mikehardy** [comment]
haha VSCode for the win! (I'm kidding, everyone should use the editor they want and I have to reload VSCode sometimes for type defs too)

Thanks so much for noting this, reporting it, and helping test. PR merging + release in a moment
