### ISSUE TITLE
Update to v13 of native SDKs [testers wanted! patch-package patch ready!]

### ISSUE THREAD

**Issue by mikehardy** [thebergamo/react-native-fbsdk-next#208]
facebook-android-sdk and facebook-ios-sdk just released v13 of their native SDKs

I'm happy maintaining this repo and do my best to merge PRs and fix little immediate issues but I do this in my free time

I do not have time to take on larger projects like forward porting to v13 right now

Anyone that needs v13 features or wants to see this library stay alive may consider either directly sponsoring me to get it done or should propose a PR themselves (which I will happily collaborate on!)

In the meanwhile, this issue will stay open for discussion among any interested parties, or status updates as they happen.

Please do not +1 or me too or ask for status though. Either contribute and move it forward, or quietly listen, to keep notification traffic down. It will be much appreciated. Thanks!

**Comment by likon416** [comment]
Hi @mikehardy 

Yeah without SDK 11+ you can't really send events on iOS due to tracking permissions. So basically SDK9 is making this plugin (same as expo-facebook) obsolete. 
Can you point me to what needs to be done to update to a new SDK? Maybe I can help somehow.

**Comment by mikehardy** [comment]
We're already on 12 here. Should be no issue. 13 was released last week, we should update over time but there should not be any functional problems with current versions used here

That said a PR to update would be great.

**Comment by likon416** [comment]
ahh, great, that solves everything :) thanks

**Comment by mikehardy** [comment]
Still doesn't solve that we need to move to v13 at some point ;-). But yes, you should not be blocked on anything. I'm going to hide these comments now as resolved to clean up the issue, no offense implied or intended, cheers !

**Comment by kalyaniDM** [comment]
It is showing critical error to update facebook sdk from 12 to 13 in ios.Could you please help in updating the repository with updated facebook sdk version 13.1.0 .

**Comment by mikehardy** [comment]
Could you please read my comment above and take appropriate action? I'll happily collaborate if you propose a PR.
This same comment applies to anyone else interested.

**Comment by ashuOxit** [comment]
Hi @mikehardy 
i am able to update SDK but I am not able to update Gaming share functionality 

I am sharing a patch file you can check it and if possible  try to update the gaming functionality 
[react-native-fbsdk-next+7.3.3.patch.txt](https://github.com/thebergamo/react-native-fbsdk-next/files/8378576/react-native-fbsdk-next%2B7.3.3.patch.txt)

**Comment by mikehardy** [comment]
Nice! That's a start - however with a PR it's difficult to work with just the patch. It appears pretty quick-n-dirty in that it looks like you've done the minimal to just get it to compile (you've commented out things that did not work?) without explanation of the reasons etc.

Most of the work of forward-porting is not the "getting it to compile" part, it's the actual PR, the careful consideration of how to adapt functionality, and the "BREAKING CHANGE" notes to help fellow developers adapt their use of the library.

None of that was specified before, so it's natural for no one to know that.

For anyone looking to collaborate on this though, that's the key stuff: 
- a real PR, even it's partial (just mark it WIP, someone else can build off it by pulling your fork + branch)
- comments on the PR or in the code with references to the SDK changes requiring adaptation
- testing!
- some release notes indicating what developers should do (if they can do anything) to adapt their usage

**Comment by isidoro98** [comment]
I've raised a PR with the update to v13. Any feedback would be great.

@mikehardy I've tried to follow the advise on your last message, but was a bit unsure about testing, since it doesn't seem to be changes that would impact it. But if you have any suggestions I'll happily implement them :).

**Comment by mikehardy** [comment]
First: awesome! Seriously, thank you. To your question: there are not many (any?) automated tests, so "testing" is unfortunately a matter of compiling it and running the example app to make sure that is still as good as it was, and if at all possible running your fork's branch containing the work in your work projects that use the functionality, via a git reference (and then `cd node_modules/react-native-fbsdk-next && yarn` to build the typescript - should work?)

I'll queue the PR for review but of course no one needs to wait on me except to just hit the merge+release button - *anyone* interested in this work can make it move faster by reviewing + testing in their projects as well. Success reports are very valuable (as are review comments or failure notes, really - any testing notes).

Thanks!

**Comment by mikehardy** [comment]
# #221 appears ready to merge so this is a call for testers. 

I would love to hear reports of how this goes when test-integrated in to your project.

Here is the patch-package formatted patch (unzip it in patches) to test it. 
[react-native-fbsdk-next+7.3.3.patch.zip](https://github.com/thebergamo/react-native-fbsdk-next/files/8452818/react-native-fbsdk-next%2B7.3.3.patch.zip)


Please report whether it was successful or not and what modules your app uses.

This will be the CHANGELOG entry, so you are aware of the breaking changes - they should be backwards compatible with your v12 use of the module at least, though it may affect your code:

----
BREAKING CHANGE: this version uses new major versions of the underlying SDKs and has breaking changes:

- iOS mininum target version moved to 11, alter this in your Podfile and in project.pbxproj as needed
- You must use Xcode 13 going forward. Xcode 12 is no longer supported
- Share dialog parameters changed, description and title were deprecated, they are removed now
- You must use configure a client token on Facebook console and in the app to use Graph API calls now
- GMS AD_ID Permission now added by the native SDK by default, use AndroidManifest tools:remove to remove if unwanted

**Comment by jorgegvallejo** [comment]
I tried the patch and for iOS I got a couple of errors on build, though I might be doing something wrong.

I applied the patch on a working project and the first error I got was:

`Module 'FBSDKGamingServicesKit' not found RCTFBSDKGameRequestDialog.h`

When I tried doing `pod install` I got:

`CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile... None of your spec sources contain a spec satisfying the dependency: FBSDKCoreKit (~> 13.1.0)`

I tried doing `pod repo update` without success. I dont know if this helps any, but those are my results.

**Comment by mikehardy** [comment]
@jorgegvallejo thanks a bunch for trying to test it! I don't think those are valid test results unfortunately
The 13.1.0 of FBSDKCoreKit certainly exists so you have some local issue you'll need to resolve: https://cocoapods.org/pods/FBSDKCoreKit

**Comment by jorgegvallejo** [comment]
> @jorgegvallejo thanks a bunch for trying to test it! I don't think those are valid test results unfortunately The 13.1.0 of FBSDKCoreKit certainly exists so you have some local issue you'll need to resolve: https://cocoapods.org/pods/FBSDKCoreKit

You're right, I updated cocoapods, applied the patch and its working fine for me now.

**Comment by mikehardy** [comment]
Got a couple test reports that show it appears to work, no one saying there are problems. I'm going to release it, if there are problems in wider usage please dig deeper than just saying "I have a problem" - really need PRs more than issues :pray: thanks

**Comment by mikehardy** [comment]
Just released in v8
