### ISSUE TITLE
Cannot run example app (crashes after infinite loop)

### ISSUE THREAD

**Issue by rahulsmehta** [thebergamo/react-native-fbsdk-next#21]
## 🐛 Bug Report

When running the example app on an iOS simulator (in `example/ios`), the example app fails to mount & the app crashes after entering an infinite loop with the error:
```
Invariant Violation: No callback found with cbID 2903 and callID 1451 for module <unknown>.
```

## To Reproduce

1. Install both the package & example app dependencies (`npm install && npx pod-install`)
2. Start the example app by running `npm example:ios`

## Expected Behavior

The example app builds & runs successfully

## Environment

```
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.87 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.10.0 - ~/git/sw/react-native-fbsdk-next/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 3.7.7 - /opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.63.3 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
I'm using the package in production now.
Not sure about the example though, I haven't tried it.

**Comment by Luehang** [comment]
That's good to know.  What `react-native` and `react-native-fbsdk-next` version are you using?  And what platform?

**Comment by mikehardy** [comment]
literally current stable every single thing as I type this - I maintain a pile of large repos so I keep everything up to date to catch the errors before my users do. Android and iOS

**Comment by thebergamo** [comment]
Example app is used for testing if I remember correctly. Either way feel free to update it if you would.
I'm also using it in production without any issues.

**Comment by KrisLau** [comment]
Just thought I'd add the error I got here in case anyone else looks at this in the future:
```
[Tue Jul 06 2021 08:58:32.853]  BUNDLE  example/index.js 

[Tue Jul 06 2021 08:59:21.814]  LOG      Running "RNFBSDKExample" with {"rootTag":1}
[Tue Jul 06 2021 08:59:21.815]  ERROR    Invariant Violation: View config getter callback for component `RCTFBLoginButton` must be a function (received `undefined`).

This error is located at:
    in RCTFBLoginButton (at FBLoginButton.js:112)
    in LoginButton (at App.js:55)
    in RCTView (at View.js:34)
    in View (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Tue Jul 06 2021 08:59:21.816]  ERROR    Invariant Violation: View config getter callback for component `RCTFBLoginButton` must be a function (received `undefined`).

This error is located at:
    in RCTFBLoginButton (at FBLoginButton.js:112)
    in LoginButton (at App.js:55)
    in RCTView (at View.js:34)
    in View (at App.js:54)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

**Comment by KrisLau** [comment]
Ok so I found out more things but still can't fully resolve the error. For some reason named imports from 'react-native' aren't recognized so changing all the `import {a, b} from 'react-native'` to 
```
import a from 'react-native'
import b from 'react-native'
```

For example:
```
import { requireNativeComponent, StyleSheet } from 'react-native';
```
turns into
```
import requireNativeComponent from 'react-native';
import StyleSheet from 'react-native';
```


This gets rid of a bunch of errors but leaves me with this error:
```
[Tue Jul 06 2021 09:41:54.464]  BUNDLE  example/index.js 

[Tue Jul 06 2021 09:42:01.667]  ERROR    TypeError: undefined is not a function (near '..._reactNative.default.create...')
[Tue Jul 06 2021 09:42:01.667]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Tue Jul 06 2021 09:42:01.686]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```
which I believe is coming from `render(): JSX.Element;` in `FBLoginButton.ts` but I can't seem to figure our what to do for that

**Comment by mikehardy** [comment]
@KrisLau if you have a chance I would love confirmation that the new example app actually works. Of course "it worked for me" when I was developing it but that's a lot less useful then independent confirmation. Cheers!

**Comment by KrisLau** [comment]
Sorry been having a hectic week, I'll try and test it out this weekend. Thanks!

**Comment by mikehardy** [comment]
No problem whatsoever, I'm happy you're even considering giving it a spin :-). Shouldn't feel guilt + time pressure on open source of course. Cheers

**Comment by KrisLau** [comment]
Ran the example yesterday and ran into a two errors that were pretty pretty easy to get around so I'll just drop them here for anyone that might run into the same ones. 

The first error: `com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.rnfbsdkexample signatures do not match the previously installed version; ignoring!` was just because I had installed the example before and that was clashing with the new example so I just uninstalled the old version off the emulator.

The other error I ran into was:
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (react-native-fbsdk-next-master\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:304:17)
    at new UnableToResolveError (react-native-fbsdk-next-master\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (react-native-fbsdk-next-master\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (react-native-fbsdk-next-master\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at react-native-fbsdk-next-master\node_modules\metro\src\lib\transformHelpers.js:271:42
    at Server.<anonymous> (react-native-fbsdk-next-master\node_modules\metro\src\Server.js:842:41)
    at Generator.next (<anonymous>)
```
only occurs when I run the app through IntelliJ instead of `yarn example:android`. I just had to run it using the command `yarn example:android`. The app now runs successfully. 

Thanks a bunch @mikehardy !

**Comment by mikehardy** [comment]
Thanks a bunch for verifying! With the example up to date and easy to update there's a much more solid basis to do future development

**Comment by KrisLau** [comment]
No problem, happy to help!
