### ISSUE TITLE
Trying to integrate the event manager.

### ISSUE THREAD

**Issue by development0264** [thebergamo/react-native-fbsdk-next#215]
Hello,
Thanks in advance.

I am trying to integrate Facebook event manager into my react-native app but I am not getting any event detected in it.
I have followed the steps from the official Facebook document only.

https://developers.facebook.com/docs/app-events/getting-started-app-events-android#7--add-app-events

After following the steps I integrated fbsdk-next library in react-native and from that library I am using.

**import { AppEventsLogger, AppEventParam } from "react-native-fbsdk-next";

AppEventsLogger.logEvent(AppEventsLogger.AppEvents.CompletedRegistration);
AppEventsLogger.logEvent('fb_mobile_complete_registration');**

I have tried both things but none of them are working for me.
Could you please guide how can I log the event?
Thanks

**Comment by jonathanpeterwu** [comment]
Hello I would recommend that you take a look at this closed issue and the suggested workaround here:

[Issue Solution](https://github.com/thebergamo/react-native-fbsdk-next/issues/24#issuecomment-881955651)
