### ISSUE TITLE
AEMReporterIOS auto log events

### ISSUE THREAD

**Issue by omer921** [thebergamo/react-native-fbsdk-next#220]
Currently setting up AEMReporterIOS. Was wondering if there was a way to automatically  log trial start and subscription events just like App Events API. (ex: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios)

Follow up: 
In order to use the Aggregated Event Measurement feature do I need to use AEMReporterIOS?
[This documentation](https://www.facebook.com/business/help/1267713610367185?id=1877298665783613) does not mention using the AEM logger.

**Comment by aarkalyk** [comment]
hey @omer921 did you manage to have AEM events autologged?

**Comment by omer921** [comment]
We never were able to, ended up switching to an MMP.
