### ISSUE TITLE
When to initialize the SDK? - iOS 

### ISSUE THREAD

**Issue by omer921** [thebergamo/react-native-fbsdk-next#225]
Should we initialize the SDK as soon as the app starts up or wait for the users to respond to the ATT message?

In the FB event manager I am seeing a "Send the Advertiser Tracking Enabled flag" error, even though my ATE opt in rate is 20%. Has anyone encountered this issue?

<img width="270" alt="Screen Shot 2022-04-10 at 12 27 09 PM" src="https://user-images.githubusercontent.com/10200905/162630165-0f0c509f-e8e3-4e65-9500-43e7e620e6d4.png">
<img width="1261" alt="Screen Shot 2022-04-10 at 12 27 05 PM" src="https://user-images.githubusercontent.com/10200905/162630168-68ed25c4-f94f-4c7a-bc02-6f574ef07ae5.png">

**Comment by mikehardy** [comment]
I'm not 100% sure as I don't do advertiser tracking. The upstream SDKs should have more information on when you can or should do what, and it likely varies based on your legal environment requirements and existing user relationship / permissions. Have you checked the upstream SDK (facebook-sdk-android / facebook-sdk-ios) documentation for this area?

**Comment by omer921** [comment]
@mikehardy Thank you for the quick reply. 

I have checked the FB iOS SDK docs and have not found much guidance as to when to initialize the SDK. In [this](https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled/) document they state on the bottom:

> After a user assents to advertiser tracking and you enable events, be sure to initialize the SDK before sending events.

I currently have two apps, with different flows of initializing the React Native FB SDK. 

App 1: Initialize FB SDK -> Request ATT permission -> Set advertising enable true or false
App 2: Request ATT permission -> Set advertising enable true or false -> Initialize FB SDK

Both are currently getting the error in the FB Event Manager.

**Comment by mikehardy** [comment]
The doc seems clear though...

**Comment by omer921** [comment]
I think so too but in the case of App 2 (follows the doc) it is still getting the same error as App 1. So I am not sure if the doc is current.

**Comment by mikehardy** [comment]
There may be a false assumption: built in to your statement is the assumption that is all you have to do! I think there may be other things to do, or other ways the user may disable tracking. There was some issue traffic related to ATT and the SDK working in the past, where I remember it was a combination of things to get it to work. I'd follow the doc for this part, and look in the issues / PRs for other possible things missing.

**Comment by omer921** [comment]
I see, thank you for the guidance!
