### ISSUE TITLE
Would there be any problem If I initialize the SDK every time the app turns to an "active" state?

### ISSUE THREAD

**Issue by ikotsov** [thebergamo/react-native-fbsdk-next#227]
## 🐛 Bug Report

Hello! Cheers to the great work of the community!

I wanted to ask a question concerning the use of the SDK.

I am using the [react-native-permissions][1] package in order to receive a consent from the user before initializing the Facebook SDK.

Since iOS 15 though, for the app tracking transparency modal to show up we have to request for permission, each time the app state status changes to "active". This is according [to the docs][2] of the package.

Would there be any problem if I do the initialization of the SDK each time the app state turns to "active"?

The code looks something like this:

```
useEffect(() => {
  const listener = AppState.addEventListener('change', (status) => {
    if (Platform.OS === 'ios' && status === 'active') {
          const userAllowsTracking = await requestTrackingPermission();
          if (!userAllowsTracking) return;

          const isTrackingEnabled = await Settings.setAdvertiserTrackingEnabled(true);
          if (!isTrackingEnabled) return;

          Settings.initializeSDK();
    }
  });

  return listener.remove;
}, []);


const requestTrackingPermission = async () => {
  const res = await request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);
  return res === RESULTS.GRANTED || res === RESULTS.UNAVAILABLE; // Android or iOS < 14.5 - when no ATT we just track
};
```
This means that in practice, if I open the app, the SDK will be initialized provided that I gave my consent to ATT modal, then I put it in a background state and then if I put it back in a foreground state, the initialization will run again.

Will this affect how the SDK works?

Thank you!

  [1]: https://github.com/zoontek/react-native-permissions
  [2]: https://github.com/zoontek/react-native-permissions#how-to-request-app-tracking-transparency-permission-on-ios

## To Reproduce

Provided that you have added the above code in `App.hs` file:
1. Open the app
2. The initialization will run
3. Put the app in a background state
4. Put the app back in a foreground state
5. The initialization will run again

## Expected Behavior

Running the initialization each time the app turns to "active" state should not affect the functionality of the SDK.

## Environment

```
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 45.18 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/opt/node@14/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-24 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
:thinking: I'm not aware of a problem with this but it's not something I've tested. I think you'll have to run the experiment + consult the upstream docs (github repos facebook-ios-sdk facebook-android-sdk) and see how it goes

**Comment by ikotsov** [comment]
@mikehardy Thank you for your comment.

I will check it out more thoroughly and if come up with anything I will post it here.

May I ask, what does the `Settings.initializeSDK();` exactly do under the hood?

Cheers 🙂

**Comment by mikehardy** [comment]
> May I ask, what does the Settings.initializeSDK(); exactly do under the hood?

I'm sorry - I won't have time to trace the code out here, but it's all open source so you can follow it through
