### ISSUE TITLE
Expo config plugin needs v13 update for client access token

### ISSUE THREAD

**Issue by mikehardy** [thebergamo/react-native-fbsdk-next#228]
Thanks for working on this @isidoro98 . I tested the build on expo managed app via the plugin from the repository. The  expo-dev-client build passed, on android it seems to work. On iOS, it crashes when I launch the app with this error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Starting with v13 of the SDK, a client token must be embedded in your client code before making Graph API calls.
Visit https://developers.facebook.com/apps/738908110438103/settings/advanced/ to find your client token for this app.
Add a key named FacebookClientToken to your Info.plist, and add your client token as its value.
Visit https://developers.facebook.com/docs/ios/getting-started#configure-your-project for more information.'
```

The facebook client token is not mandatory for iOS. We should add this to the documentation right? This was not required before and is also a breaking change for iOS.

In the expo plugin (plugin folder at the root of the repo) we could make the build throw an error if clientToken is not passed also (But I understand if you prefer to do this on another pull request)

I am adding the client token and give more feedback inchallah.

_Originally posted by @abumalick in https://github.com/thebergamo/react-native-fbsdk-next/issues/221#issuecomment-1094902670_

**Comment by bpouzet** [comment]
Hello,
To fix this issue, you can temporally add in your app.json (or app.config.js) under ios -> infoPlist -> 'FacebookClientToken' : 'xxxxxxxxxxxx'

```
...
ios: {
  infoPlist: {
    FacebookClientToken: 'xxxxxx' 
  }
},
...
```

**Comment by gitmarkuz** [comment]
> Hello, To fix this issue, you can temporally add in your app.json (or app.config.js) under ios -> infoPlist -> 'FacebookClientToken' : 'xxxxxxxxxxxx'
> 
> ```
> ...
> ios: {
>   infoPlist: {
>     FacebookClientToken: 'xxxxxx' 
>   }
> },
> ...
> ```

I did that but no luck it still crashes with the same error message as in MikeHardy's OP when starting the dev client. I spent the better part of a day trying to make it work and making a number of builds to no avail.

I even tried editing the react-native-fbsdk-next source code and logging the clientToken to make sure that the plugin was finding it.

It builds fine with eas build (development) but I can't run it.

I am running an Expo Managed app, with eas build(s) with the latest (8.0.5) of react-native-fbsdk-next.

Did anyone else get it to work in this situation?

**Comment by doctorrokter** [comment]
> > Hello, To fix this issue, you can temporally add in your app.json (or app.config.js) under ios -> infoPlist -> 'FacebookClientToken' : 'xxxxxxxxxxxx'
> > ```
> > ...
> > ios: {
> >   infoPlist: {
> >     FacebookClientToken: 'xxxxxx' 
> >   }
> > },
> > ...
> > ```
> 
> I did that but no luck it still crashes with the same error message as in MikeHardy's OP when starting the dev client. I spent the better part of a day trying to make it work and making a number of builds to no avail.
> 
> I even tried editing the react-native-fbsdk-next source code to make it require a clientToken before building, and logging the clientToken to make sure that the plugin was finding it.
> 
> It builds fine with eas build (development) but I can't run it.
> 
> I am running an Expo Managed app, with eas build(s) with the latest (8.0.5) of react-native-fbsdk-next.
> 
> Did anyone else get it to work in this situation?
> 
> I managed to get every other plugin to work, google ads, in app purchases etc. EAS build is amazing. But I just can't seem to get this to work.
> 
> Any help would be appreciated. It feels like I am missing something obvious since I don't seem to be able to find anyone else who still has this issue.

Hey! Did you solve the problem? Currently I'm using v11 of `react-native-fbsdk-next` lib and it simply crashes on iOS and Android. I'm using Expo + EAS, no problems with other native libs.

**Comment by jonasbetareader** [comment]
I'm also having trouble - using react-native-fbsdk-next 11.2.1 and the following plugin settings in app.config.js: 

```
plugins: [
      [
        'react-native-fbsdk-next',
        {
          appID: <myappid>,
          displayName: '<myname>'
          clientToken: '<mytoken>'
        }
      ],
```

Might the infoPlist collide with this in any way?
Here's an excerpt of my app.config.js setup:
```
...
infoPlist: {
        NSUserTrackingUsageDescription:
          'This identifier will be used to deliver personalized ads to you.',
        FacebookClientToken: '<mytoken>',
        SKAdNetworkItems: [
          {
            SKAdNetworkIdentifier: '<myidentifyer>'
          }
        ]
      },
      ...
    },
```
