### ISSUE TITLE
Cannot build android app with various versions

### ISSUE THREAD

**Issue by Looooong** [thebergamo/react-native-fbsdk-next#231]
## 🐛 Bug Report
I'm switching from `react-native-fbsdk@2.0.0` to `react-native-fbsdk-next@8.0.0`. However, I get the following errors while building android app. Lowering lib version doesn't help.

Version 7.3.3, 8.0.0:
```
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBGameRequestDialogModule.java:31: error: package com.facebook.gamingservices does not exist
import com.facebook.gamingservices.GameRequestDialog;
                                  ^
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBGameRequestDialogModule.java:42: error: package GameRequestDialog does not exist
    private class GameRequestDialogCallback extends ReactNativeFacebookSDKCallback<GameRequestDialog.Result> {
                                                                                                    ^
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBGameRequestDialogModule.java:49: error: package GameRequestDialog does not exist
        public void onSuccess(GameRequestDialog.Result result) {
                                               ^
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBGameRequestDialogModule.java:75: error: cannot find symbol
        promise.resolve(GameRequestDialog.canShow());
                        ^
  symbol:   variable GameRequestDialog
  location: class FBGameRequestDialogModule
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBGameRequestDialogModule.java:86: error: cannot find symbol
            GameRequestDialog gameRequestDialog = new GameRequestDialog(getCurrentActivity());
            ^
  symbol:   class GameRequestDialog
  location: class FBGameRequestDialogModule
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBGameRequestDialogModule.java:86: error: cannot find symbol
            GameRequestDialog gameRequestDialog = new GameRequestDialog(getCurrentActivity());
                                                      ^
  symbol:   class GameRequestDialog
  location: class FBGameRequestDialogModule
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBSettingsModule.java:39: error: cannot find symbol     
        FacebookSdk.setDataProcessingOptions(options, 0, 0);
                   ^
  symbol:   method setDataProcessingOptions(String[],int,int)
  location: class FacebookSdk
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBSettingsModule.java:50: error: cannot find symbol     
        FacebookSdk.setDataProcessingOptions(options, country, state);
                   ^
  symbol:   method setDataProcessingOptions(String[],int,int)
  location: class FacebookSdk
```

Version 4.3.0, 5.2.0, 6.2.0
```
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBSettingsModule.java:39: error: cannot find symbol     
        FacebookSdk.setDataProcessingOptions(options, 0, 0);
                   ^
  symbol:   method setDataProcessingOptions(String[],int,int)
  location: class FacebookSdk
C:\Projects\fitmode-mobile\node_modules\react-native-fbsdk-next\android\src\main\java\com\facebook\reactnative\androidsdk\FBSettingsModule.java:50: error: cannot find symbol     
        FacebookSdk.setDataProcessingOptions(options, country, state);
                   ^
  symbol:   method setDataProcessingOptions(String[],int,int)
  location: class FacebookSdk
```

## Environment

```
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 34.58 GB / 63.83 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE  
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64
      Android NDK: 24.0.8215888
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000        
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_312 - C:\Program Files\OpenJDK\openjdk-8u312-b07\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.3 => 0.64.3 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask
We'd need to see your build.gradle files

My guess is you have some outdated dependency in there since you are missing symbols that are definitely defined in the SDKs, and we bring them in for you (assuming you don't override them)

https://github.com/thebergamo/react-native-fbsdk-next/blob/caf9c0a5e3f3eaf267a1b817c73c83fc98b67d66/android/build.gradle#L47-L52

This will be a project-specific integration issue, it's not actionable by anyone else here - compare the example app integration - which is built by a script that shows you all the steps you need to take, and only those steps, and fix up your local project, you should be good then

https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

**Comment by Looooong** [comment]
I have already removed all the manual linking from `react-native-fbsdk` and rely on automatic linking from `react-native-fbsdk-next`. It doesn't work. Then I tried manual linking for `react-native-fbsdk-next` with:
```
dependencies {
  implementation "com.facebook.android:facebook-android-sdk:latest.release`
}
```
It still doesn't work.

Then I tried `gradle clean` as well as removing all the gradle caches. Still no luck.

**Comment by mikehardy** [comment]
Sorry to hear that! Our example definitely works though, and this definitely works in my projects, and there is literally an automated script that builds the example app from scratch and it works. I really don't know what more we can show you

**Comment by Looooong** [comment]
I understand. It's very hard to track down to what causes this behaviour. It feels like gradle is trying to use older version of FBSDK. I will figure something else out.

**Comment by mikehardy** [comment]
Agreed on that. Maybe just maybe `./gradlew :app:dependencies > dependencies.txt` then scanning through that to see who is fixing what version. Perhaps there is another dependency that is on an old version.

**Comment by awchang56** [comment]
I had this exact same issue. I'm on react-native v0.64.1 and using the latest react-native-fbsdk-next lib v8.0.2. when I ran the example app and looked at its dependency tree, I could see it pulling in Facebook-android-sdk v12+ but when running the gradlew command on my app it pinned it to v5 which didn't have the necessary dependencies. I fixed the issue by adding the following line to my `android/build.gradle` under `buildscript > ext`.

`facebookSdkVersion="13.+"`

I was able to successfully build android after doing so, although I'm not sure what was causing the package to automatically use the lower version of Facebook-android-sdk

**Comment by mikehardy** [comment]
This really should let you know who is pulling in what:

> ./gradlew :app:dependencies > dependencies.txt

(in combination with then looking at your node_modules/**/android/buld.gradle files to see who is pulling in what...)

Glad you got it working!

**Comment by Looooong** [comment]
Now that you mentioned `facebookSdkVersion`, I noticed there is a line `facebookSdkVersion = "5.15.3"` in my `gradle.build`. I didn't noticed it before, my bad.

Deleting that line should fix my problem.
