### ISSUE TITLE
Getting error when implementing fb login

### ISSUE THREAD

**Issue by SupriyaGo** [thebergamo/react-native-fbsdk-next#232]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/40319687/164676278-2065241a-e7a6-49aa-8634-d3ab1b2e535e.png">

How to solve ???

**Comment by mikehardy** [comment]
Probably by logging high-quality issues
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
