### ISSUE TITLE
IOS not call back to the app

### ISSUE THREAD

**Issue by ballza95** [thebergamo/react-native-fbsdk-next#233]
I'm login facebook by ios after click 'Continue' not call back to the app.

I'm use Expo dev-client.

My image.
![IMG_EF401DC08DB1-1](https://user-images.githubusercontent.com/32051406/165055328-f6b87c2b-651c-4af7-9d54-e5fc217db2ed.jpeg)

![IMG_1ED794CEE85B-1](https://user-images.githubusercontent.com/32051406/165055594-7876dd97-a026-45e3-a4fa-ff7982a8e767.jpeg)

My Code.

```
  useEffect(() => {
    Settings.initializeSDK()
    Settings.setAppID('**********')
  }, [])

const loginWithFacebook = async () => {
 try {
      const results = await LoginManager.logInWithPermissions(['public_profile', 'email'])

      if (results.isCancelled) {
        Alert.alert('Login failed', 'User cancelled the login process')
      }

      // Once signed in, get the users AccesToken
      if (Platform.OS === 'ios') {
        const res = await AuthenticationToken.getAuthenticationTokenIOS()
        console.log(res?.authenticationToken)
      } else {
        const resulta = await AccessToken.getCurrentAccessToken()
        console.log(resulta?.accessToken)
      }
      const data = await AccessToken.getCurrentAccessToken()

      if (!data) {
        Alert.alert('Login failed', 'Something went wrong obtaining access token')
      }

    } catch (error) {
      console.log(error.message)
    }
}
```

**Comment by mikehardy** [comment]
Probably some setup failure with regard to configuration in your client.
This is a low-quality issue though, not information to help.
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ballza95** [comment]
I solved the call back ios problem but I got a new problem after the call back.

Error : [auth/invalid-credential] The supplied auth credential is malformed or has expired.

My code.
`    const results = await LoginManager.logInWithPermissions(
        ['public_profile', 'email'],
        'limited',
      )

      const data = await AuthenticationToken.getAuthenticationTokenIOS()

      const facebookCredential = auth.FacebookAuthProvider.credential(data.authenticationToken)

      const signInFacebook = await auth().signInWithCredential(facebookCredential)`

**Comment by mikehardy** [comment]
Still nowhere near enough information to help. Really low quality issue. Not actionable based on provided information. With apologies, closing for inability to take any action.

**Comment by tragicmj** [comment]
@ballza95 how did you fix the issue of app callback??

**Comment by MaxJadav** [comment]
@BondPiyapan  How you fix malformed or has expired issue?
