### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by mbignotto** [thebergamo/react-native-fbsdk-next#235]
## 🐛 Bug Report

I'm facing this bug for days, I've tried to solve it but I couldn't find any solution.

Please give me some hope :(

![image](https://user-images.githubusercontent.com/61169748/165601937-a69fb51b-c48a-4394-9857-0b938da1eef8.png)

## Environment
 "react-native-fbsdk-next": "^8.0.0",
I'm on the latest version of the library and I've run yarn link several times

## To Reproduce

I couldn't even reproduce this crash that firebase crashlytics points out, but it's been happening with many users, all with the same log

**Comment by mikehardy** [comment]
Something about your dependencies is wrong in your build.gradle I think? Perhaps you are overriding our dependencies somehow?

They are defined here https://github.com/thebergamo/react-native-fbsdk-next/blob/caf9c0a5e3f3eaf267a1b817c73c83fc98b67d66/android/build.gradle#L47

basically, don't do that.

`./gradlew :app:dependencies` (and save the output somewhere, for inspection) will help you diagnose

This is fixed upstream in [facebook-android-sdk v11.3](https://github.com/facebook/facebook-android-sdk/issues/997#issuecomment-914691737) though, and that was [launched here in v5](https://github.com/thebergamo/react-native-fbsdk-next/releases/tag/v5.0.0)

So this is not a module problem, there is something causing an old dependency in your project.

**Comment by mbignotto** [comment]
Sorry for taking up your time, but could you help me? I don't know what else to do, I ran the suggested command, but on no line other than your lib, use facebook-android-sdk, in the print below I looked for it and it only has 4 places, and the four places are of this lib, help me :(

![image](https://user-images.githubusercontent.com/61169748/165750687-095f9f49-1e12-454f-84b7-193fb71eba8d.png)

**Comment by mikehardy** [comment]
Okay, so that indicates you are using the correct version
At that point then, I can only surmise that code you have inspected and determined to contain the fix is not the code actually running on client devices

**Comment by mbignotto** [comment]
The thing that intrigues me the most, is that it's really the code that is running in the current version of the users, is it to be sad?

**Comment by mikehardy** [comment]
I'm afraid so - I was doing triage on #236 just yesterday/today and tried it on an API31 emulator, it does seem to be working to me, and no one else is reporting this currently, though there were previous reports all resolved https://github.com/thebergamo/react-native-fbsdk-next/issues?q=is%3Aissue+FLAG_IMMUTABLE

Which gives me pretty high confidence in this module.
There's something else going on, but I'm not sure what unfortunately, thus can't help

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mbignotto** [comment]
ok, thanks for the help, I'll try to solve it and come back here if I can

**Comment by mbignotto** [comment]
Look at me here again haha, now my app is no longer building out of nowhere, do you know this error? I found it by log cat
![image](https://user-images.githubusercontent.com/61169748/166058321-d4877ba4-6eec-4f4c-b9c2-af75c04eb85b.png)

**Comment by mikehardy** [comment]
That line right below it seems pretty clear :eyes: - please read v8 changelog

**Comment by mbignotto** [comment]
hey, do you believe that the version I uploaded to the store and the one I was building all these days had the old sdk cache? now that the cache was lost, it started to crash and in this new version of the sdk it needs the token, now it worked, it even solved that login crash issue

**Comment by mikehardy** [comment]
If you are not using `npx react-native-clean-project` as part of your build process for the app stores, you are liable for all sorts of odd behavior...

**Comment by mikehardy** [comment]
I'm going to say, you really should look at the number of things cleaned by react-native-clean-project
And I will also say: not even close, no

**Comment by mbignotto** [comment]
ok thx for the help, i love you <3
