### ISSUE TITLE
Error with FacebookSdk Initialize

### ISSUE THREAD

**Issue by boreales** [thebergamo/react-native-fbsdk-next#236]
## 🐛 Bug Report

I keep having the error : The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first. 

## To Reproduce

Install the package 
Fill the AndroidManifest and strings.xml files with facebook-app-id as in the docs.
Run `npx react-native run-android` or launch the app through Android Studio on the emulator.

I also tried with a brand new app and another computer. I still have the same issue.

## Expected Behavior

The SDK should be auto-initialized at the launch of the app.

## Environment

```
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 1.93 GB / 15.92 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: 17.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
> I also tried with a brand new app and another computer. I still have the same issue.

Our example app is literally built by a script, fully automated

Check it out: https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

Run that, compare output to your project, you're missing a step somewhere, somehow. It's not a module problem though, and support questions are best on stackoverflow or similar until you can demonstrate a bug with steps to reproduce
https://stackoverflow.com/help/minimal-reproducible-example
https://stackoverflow.com/help/how-to-ask

**Comment by AlexandreLage** [comment]
Same here

**Comment by mikehardy** [comment]
Same answer :shrug: - put some effort in please

**Comment by mikehardy** [comment]
I'm not trying to be flippant either: I literally provide a fully automated scripted build to create an example, and last I checked (before last release), it worked. I really don't know what more I can do

**Comment by llanpham** [comment]
Before my project was working properly. But I saw this issue yesterday. I can't run the project right now.

**Comment by mikehardy** [comment]
Providing exactly as much information as you have provided, I run my project just fine. Who is right? Neither of us without a reproduction. Behold: https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh a reproduction

How's it go when you run it?

**Comment by arkkosoftMiKolbi** [comment]
Hi, I have the same problem. The project was working yesterday and today it doesn't work. 
My coworker has the same project and he can run it without problems.

![image](https://user-images.githubusercontent.com/62572265/165670319-9ef7686f-55a7-4c55-8c9d-df2e60075447.png)

**Comment by mikehardy** [comment]
I just followed the README in the example, it works

clone the repo
yarn example:install
yarn example:start
yarn example:android

No reproduction, no more comments from me. You will have to dig in on your projects and determine what happened, sorry

If anyone learns anything useful please make a PR to the docs, or if there really is a bug a PR to the module and/or the example to actually demonstrate it would be great.

Statements of "it doesn't work" lack substance and do not help unfortunately. Neither does visual evidence (screenshots) of same, as I can just post a screenshot of it working and it's equally pointless

**Comment by arkkosoftMiKolbi** [comment]
Thanks for your reply. 

I ran my project on iOS and it works. But when I ran my project on Android, it doesn't work.

Before reviewing the application and [Facebook documentation](https://developers.facebook.com/docs/android/getting-started/), we found the solution. 

The client token had to be added to string.xml:

`<string name="facebook_client_token">56789string>` 

Next add the meta-data in the application element, in the AndroidManifest.xml:

`<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`

After that, the application works again.

**Comment by ch3tan03** [comment]
> Before my project was working properly. But I saw this issue yesterday. I can't run the project right now.

same for me all of a sudden I'm getting this error.

**Comment by phuongwd** [comment]
We have to set the `facebook_client_token` to `/app/manifests/AndroidManifest.xml`

<img width="879" alt="Screen Shot 2022-04-28 at 16 00 05" src="https://user-images.githubusercontent.com/2460806/165717248-4cb14f23-5023-450d-8303-a8649e922af3.png">

**Comment by mikehardy** [comment]
Glad you found the solution!

Please pay very very careful attention to release notes on breaking change release notes, if you see a breaking change **expect your app to break unless you update it somehow**

https://github.com/thebergamo/react-native-fbsdk-next/releases
https://github.com/thebergamo/react-native-fbsdk-next/releases/tag/v8.0.0

> Client access token required: configure on Facebook console and in the app

**Comment by mikehardy** [comment]
One other thing I'll mention: if this happened without you knowing, you should examine your dependency management. Are you depending on this module with a `+` dependency, so it can just update any time, and break your builds without you knowing? That is a dangerous practice because you'll end up in situations like this. Depend on this module like `"react-native-fbsdk-next": "^8.0.0"` in your package.json so you are bound to the major version

We do our best not to issue breaking changes without release notes indicating the exact changes required, but you have to use semantic versioning appropriately for that to work for you

**Comment by keShraa** [comment]
Hey guys,
As mentioned below, you have to add the client token to the AndroidManifest:
`<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`

I had to create a token on the [Meta for Developers website](https://developers.facebook.com/apps/).

It is now working for me ! Thanks 🙏🏻 


> Thanks for your reply. 
> 
> I ran my project on iOS and it works. But when I ran my project on Android, it doesn't work.
> 
> Before reviewing the application and [Facebook documentation](https://developers.facebook.com/docs/android/getting-started/), we found the solution.
> 
> The client token had to be added to string.xml:
> 
> `<string name="facebook_client_token">56789string>` 
> 
> Next add the meta-data in the application element, in the AndroidManifest.xml:
> 
> `<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`
> 
> After that, the application works again.

**Comment by phuongwd** [comment]
> Glad you found the solution!
> 
> Please pay very very careful attention to release notes on breaking change release notes, if you see a breaking change **expect your app to break unless you update it somehow**
> 
> https://github.com/thebergamo/react-native-fbsdk-next/releases https://github.com/thebergamo/react-native-fbsdk-next/releases/tag/v8.0.0
> 
> > Client access token required: configure on Facebook console and in the app
> 
> Also from our example script:
> 
> https://github.com/thebergamo/react-native-fbsdk-next/blob/caf9c0a5e3f3eaf267a1b817c73c83fc98b67d66/refresh-example.sh#L88-L89

-----
@mikehardy thanks for detailed information.

We are still using the version `^4.6.0`. It was working to 27 Apr 2022.

```
// yarn.lock
react-native-fbsdk-next@^4.6.0:
  version "4.6.0"
  resolved "https://registry.yarnpkg.com/react-native-fbsdk-next/-/react-native-fbsdk-next-4.6.0.tgz#0e70aa6d64e99762e6b22b1344eebae3f7fbfcb5"
  integrity sha512-FPYLUFSWf7V4i084jKpSt8tc1DLkuBm38eYdq4RwpGcojxXIciQ8qQi9DRLNAxqNZHd0G/P6edSVEGsrjtvV7w==
```

**Comment by mikehardy** [comment]
That + in the dependencies there is what let the breaking change in the underlying SDK slip through i think 🤔

**Comment by smrgrg** [comment]
> Thanks for your reply. 
> 
> I ran my project on iOS and it works. But when I ran my project on Android, it doesn't work.
> 
> Before reviewing the application and [Facebook documentation](https://developers.facebook.com/docs/android/getting-started/), we found the solution.
> 
> The client token had to be added to string.xml:
> 
> `<string name="facebook_client_token">56789string>` 
> 
> Next add the meta-data in the application element, in the AndroidManifest.xml:
> 
> `<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`
> 
> After that, the application works again.

This worked for me. Thanks.

**Comment by mikehardy** [comment]
See: https://github.com/facebook/facebook-android-sdk/blob/main/CHANGELOG.md#1320

> The client token is now mandatory. SDK initialization will have a check on it and throw out an exception if the client token is not available.

**Comment by sspeng123** [comment]
> Thanks for your reply. 
> 
> I ran my project on iOS and it works. But when I ran my project on Android, it doesn't work.
> 
> Before reviewing the application and [Facebook documentation](https://developers.facebook.com/docs/android/getting-started/), we found the solution.
> 
> The client token had to be added to string.xml:
> 
> `<string name="facebook_client_token">56789string>` 
> 
> Next add the meta-data in the application element, in the AndroidManifest.xml:
> 
> `<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`
> 
> After that, the application works again.

fixed my issue. thanks

**Comment by dtthanh1** [comment]
Hey guys, I tried to integrate FB SDK with my app. Everything runs perfectly on emulator but when I push it on TestFlight my app crashed. Is anyone facing this issue like me?

**Comment by mikehardy** [comment]
Nope, if you ran the app on a device plugged in to your development machine and opened the log in Console.app you could post useful information to troubleshoot.

**Comment by dtthanh1** [comment]
Okay, it turns out the FBAudienceNetwork 6.10 is having a bug which made my app keep crashing. Downgraded to 6.9 and hope FB's team will release a new version to fix this bug soon. Thanks for your help tho

**Comment by mikehardy** [comment]
@dtthanh1 oh my! That's new information, had not heard of this yet. Do you have any links to upstream issues that people could subscribe to, or related release notes? Have you logged the issue upstream yourself or collaborated with upstream repo to characterize + fix the issue? Otherwise no one else may be aware of it

**Comment by dtthanh1** [comment]
After hours of debugging and researching on Google and I came up to this.
https://developers.facebook.com/support/bugs/659029835161893/

**Comment by shamilovtim** [comment]
This error persists for me. I confirmed that the `facebook_client_token` comes through gradle just fine. However the native SDK still throws the error. It's actually somewhat concerning that a native SDK dissatisfied with a token can crash your entire application like this. I would hope they're not performing any validation on the token and crashing apps with invalid tokens. That being said, I went into the admin panel and confirmed that the token is correct, appid is correct, and so on. Stumped as to what's causing this and have tried many different solutions. Going to downgrade this SDK to before the token was ever required and hope that fixes things.

**Comment by mikehardy** [comment]
It's possible they will start denying API requests without them or with the old SDK, so careful with that - you might be able to just configure it directly in the AndroidManifest if you want? I think that would work? I don't think they validate it on startup but I'm sure they'll validate it when you use the API, so if you put a random string in there your app will at least boot but it won't work for API calls to facebook.

I actually prefer an SDK that fails fast. Can you imagine if they made it a requirement but then you didn't find out until you tried a non-login API or something and just got an error? Much better as you update the SDK to just have it work or not on your first test IMHO

**Comment by shamilovtim** [comment]
> It's possible they will start denying API requests without them or with the old SDK, so careful with that - you might be able to just configure it directly in the AndroidManifest if you want? I think that would work? I don't think they validate it on startup but I'm sure they'll validate it when you use the API, so if you put a random string in there your app will at least boot but it won't work for API calls to facebook.
> 
> 
> 
> I actually prefer an SDK that fails fast. Can you imagine if they made it a requirement but then you didn't find out until you tried a non-login API or something and just got an error? Much better as you update the SDK to just have it work or not on your first test IMHO

Good point but maybe done at compile time is better? 

Anyways, are they doing any validation of the token or appid right now? Could that be causing this?

**Comment by shamilovtim** [comment]
same issue. I'm not even using their API at all. downgrading doesn't work either. I've tried just about everything. How do we convince them to stop throwing from their SDK and blocking our entire app at startup? this is crazy. <img width="1223" alt="Screen Shot 2022-08-26 at 1 44 56 AM" src="https://user-images.githubusercontent.com/3495974/186863769-0d0803cf-008d-4afa-b1c2-b5e4bebc678b.png">

**Comment by shamilovtim** [comment]
Welp I figured it out. One more build clean and it actually worked to put dummy values into AndroidManifest. What was happening was I had dynamic gradle values: `android:value="${foo}"`. From everything I know these have always worked but upon upgrade this plugin started throwing when encountering those. I have now moved my dynamic values into `manifestPlaceholders` and I'm referencing them using `@string`

**Comment by mikehardy** [comment]
manifestPlaceholders have always worked for me in the past, and I have not tried dynamic values as you indicate @shamilovtim - you may have found the critical reproduction, since I was not able to reproduce this.

Everyone else having this problem, does an AndroidManifest with variables seem like it's your case?

As for verification at compile time, not sure how you verify a configuration string at compile time when the config files can be so widely varied. And a crash right at startup is really just about the same, the delay is only marginally longer but the signal is just as absolute. Perhaps the error would be better ?

As for them verifying the ID, how did it go when you sent in a fake ID? I'm guessing the API calls failed. I've never tried to subvert their app auth token system by feeding it unexpected data so I can't say.

**Comment by mehraj43** [comment]
![image](https://user-images.githubusercontent.com/53511710/193205113-9328d8d4-22bb-467c-8685-545338b9f77b.png)

help me guyzz facing this issue when building

**Comment by mikehardy** [comment]
@mehraj43 - this is a poor question --> https://stackoverflow.com/help/how-to-ask -- also, what you displayed in a very difficult to read image (vs formatted text) is simply a warning. Not an error. You have not actually shown the error. This module currently has no compilation errors that I know of, your problem is elsewhere

**Comment by mehraj43** [comment]
> @mehraj43 - this is a poor question --> https://stackoverflow.com/help/how-to-ask -- also, what you displayed in a very difficult to read image (vs formatted text) is simply a warning. Not an error. You have not actually shown the error. This module currently has no compilation errors that I know of, your problem is elsewhere

Thanks but i was able to resolve the error sorry for not posting question in a proper format after reinstalling fbsdk issue got resolved

**Comment by kesylo** [comment]
Any fix for expo users?

**Comment by mikehardy** [comment]
@kesylo of course. You have to read documentation though: https://github.com/thebergamo/react-native-fbsdk-next#expo-installation (note the access token is one of the mandatory config elements for the config plugin....)

**Comment by kesylo** [comment]
@mikehardy thanks for your quick response. So I have already installed the package and the plugin. It worked fine before on both android and IOS. but now when I do a new build on android (without changing anything) it does not work. But IOS still work. the error is: SDK has not been initialized facebookSDK.sdkInitialize()

**Comment by mikehardy** [comment]
You have a project-specific problem and I won't be able to help, sorry. It's important to know that this is used by lots of Expo people though, so it's possible to work if you keep digging.

**Comment by kesylo** [comment]
@mikehardy I really do need help. I have everything configured as in the docs. I use the latest version of the package "react-native-fbsdk-next": "^11.0.1".
My config is on point
`[
      "react-native-fbsdk-next",
      {
	      scheme: facebookScheme,
	      appID: facebookAppID,
	      clientToken: facebookClientToken,
	      displayName: facebookAppDisplayName,
	      advertiserIDCollectionEnabled: true,
	      autoLogAppEventsEnabled: true,
	      isAutoInitEnabled: true,
	      iosUserTrackingPermission:
		      "This identifier will be used to deliver personalized ads to you."
      }
]`
I don't know what else to do. this happens only on android. I just tried another ios build and it works.  Any tips for me please ?

**Comment by kesylo** [comment]
For those EXPO guys out there who needs this. I fixed my issues by creating config plugins to add the values mentioned [https://github.com/thebergamo/react-native-fbsdk-next/issues/236#issuecomment-1111744717](url) to strings.xml and adndroiManifest.xml
here are my config plugins:

(with-android-add-metadata-in-application.js)
```
const { withAndroidManifest } = require("@expo/config-plugins");

function addMetadataInApplication(androidManifest, attributes) {
	const { manifest } = androidManifest;

	if (Array.isArray(manifest["application"])) {
		manifest["application"].forEach(item => {
			if (Array.isArray(item["meta-data"])) {
				attributes.forEach(el => {
					item["meta-data"].push({
						$: { "android:name": el.name, "android:value": el.value }
					});
				});
			}
		});
	}

	return { manifest };
}

module.exports = function withAndroidAddMetadataInApplication(config, attributes) {
	return withAndroidManifest(config, config => {
		config.modResults = addMetadataInApplication(config.modResults, attributes);
		return config;
	});
};
```

(with-android-strings-xml.js)
```
const { AndroidConfig, withStringsXml } = require("@expo/config-plugins");

const withAndroidSplashScreen = (expoConfig, customAttributes) =>
	withStringsXml(expoConfig, modConfig => {
		// format strings
		const stringsToUpdate = [];
		customAttributes.forEach(item => {
			let stringData = { name: item.name };
			// add any extra props
			if (item.extra) stringData = { ...stringData, ...item.extra };
			// push to list
			stringsToUpdate.push({
				_: item.value,
				$: stringData
			});
		});
		// override config
		modConfig.modResults = AndroidConfig.Strings.setStringItem(
			stringsToUpdate,
			modConfig.modResults
		);
		//console.log(modConfig.modResults.resources.string);
		return modConfig;
	});

module.exports = withAndroidSplashScreen;
```
then in your app.js or app.config.js use the plugin like this:
```
[
	"./plugins/with-android-strings-xml",
	[
		{ "name": "facebook_app_id", "value": "your-facebook-id"},
		{ "name": "facebook_client_token", "value": "your-facebook-client-token"}
	]
],
[
	"./plugins/with-android-add-metadata-in-application",
	[
		{
			"name": "com.facebook.sdk.ApplicationId",
			"value": "@string/facebook_app_id"
		},
		{
			"name": "com.facebook.sdk.ClientToken",
			"value": "@string/facebook_client_token"
		}
	]
]
```
@mikehardy this is a real issue. please if possible, apply the fix directly in the library plugin.
I made these myself as I was blocked. It works for me. I'm not the best programmer out there but this should be fine for now.
cheers.

**Comment by mikehardy** [comment]
@kesylo I won't be doing that, Expo support is provided by the community and the Expo plugin will be updated via PRs provided by the community. That said, I think this is unnecessary. I believe Expo already has built in config plugin features that allow you to add things to strings.xml and AndroidManifest.xml without any additional logic in this module's config plugin. I will repeat that there are lots of Expo folks using this module already, successfully, so I think you need to look in your project and your project's use of Expo. I think you'll find that there are ways to do what you need already, and if anything the item of work here would be a documentation update (for which a PR would be happily accepted)

**Comment by kesylo** [comment]
ok @mikehardy . please can you link me to expo plugins that add values to those files? I could find them that's why I created those. thanks

**Comment by mikehardy** [comment]
Turns out they are all just in the existing plugin here already. No idea what's going on with your project. https://github.com/thebergamo/react-native-fbsdk-next/blob/master/plugin/src/withFacebookAndroid.ts

It's the weekend here and I don't use Expo. My support here is done, I won't respond further, I'm unsubscribing from this issue.

**Comment by AliceRahul** [comment]
i resolved this by added on mainapplication.kt

import com.facebook.FacebookSdk
import com.facebook.appevents.AppEventsLogger

  override fun onCreate() {
    super.onCreate()

    FacebookSdk.setApplicationId("284906515572533")
    FacebookSdk.sdkInitialize(applicationContext)
    AppEventsLogger.activateApp(this)

    loadReactNative(this)
  }

**Comment by gtmbuddha2** [comment]
> We have to set the `facebook_client_token` to `/app/manifests/AndroidManifest.xml`
> 
> <img alt="Screen Shot 2022-04-28 at 16 00 05" width="879" src="https://user-images.githubusercontent.com/2460806/165717248-4cb14f23-5023-450d-8303-a8649e922af3.png">

This worked for me. set both app id, and client id
