### ISSUE TITLE
No Permission Request on SDK init and app rejected from App Store

### ISSUE THREAD

**Issue by likon416** [thebergamo/react-native-fbsdk-next#238]
Hello.

Our App is getting rejected from App Store reviews because of:
"We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are still unable to locate the App Tracking Transparency permission request when reviewed on iOS 15.4.1."

We are using v7.3.3 with expo and the request permissions dialog is not appearing on app start. 

we have configured the plugin like this:
"plugins": [
      [
        "react-native-fbsdk-next",
        {
          "appID": "appId",
          "clientToken": "appToken",
          "iosUserTrackingPermission": "Custom perm text",
          "displayName": "AppName",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": true,
          "isAutoInitEnabled": true
        }
      ]
    ]

We also tried option using Settings.initializeSDK(); in App.tsx in export default function App() {} so init SDK on start but also no luck.

What may be the problem? Why the permissions request is not appearing?

**Comment by mikehardy** [comment]
App Tracking Transparency is a fully separate set of features. You must satisfy the App Store requirements, but it is not handled by this module.

You might like https://github.com/zoontek/react-native-permissions/#how-to-request-app-tracking-transparency-permission-on-ios or however people do it in Expo (sorry, I don't use Expo so I don't know)

Stated differently: this module *uses* code that *requires* ATT be implemented. But ATT implements are separate things.

**Comment by likon416** [comment]
@mikehardy thanks for getting back to me so quickly.

Just wanted to ask in this case, why then you have in plugin config option: iosUserTrackingPermission where I can setup custom text?
It's this permission I'm talking about...

**Comment by mikehardy** [comment]
No idea, as mentioned i don't use expo, so i don't know how that config works ir what it means. All the source us available for inspection though, following it through will answer any why question you can think of i imagine?

**Comment by likon416** [comment]
this config is for this facebook plugin, who would know then? :) I will try what you wrote earlier, I just thought this Facebook plugins handles that permissions request. Thanks

**Comment by mikehardy** [comment]
> this config is for this facebook plugin, who would know then?

You would! Because it's an open source module, just read it: https://github.com/thebergamo/react-native-fbsdk-next/tree/master/plugin/src

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b :-)

**Comment by likon416** [comment]
@mikehardy so is it possible to use this plugin without using it for any advertisement and tracking and not set the NSUserTrackingUsageDescription value for iOS? Because looks like this plugin is setting this NSUserTrackingUsageDescription regardless, so then I must update App Store policy about tracking. 
But if I would like to use plugin only for example for FB login, then I don't want to have set this up.

**Comment by mikehardy** [comment]
How did it go when you used patch-package to edit that chunk out and try it? It's not this plugin, it's your plugin, # make it do what you need.

The only reason I'm here is because I maintain react-native-firebase and I want login to work. I don't use ads or tracking and don't set those personally. Works for me.

Hack on it and try things. Maybe make the Expo plugin set the key based on an app.json option and PR that
