### ISSUE TITLE
No enum constant com.facebook.share.widget.ShareDialog.Mode.NATİVE

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [thebergamo/react-native-fbsdk-next#239]
## 🐛 Bug Report
```ts
ShareDialog.setMode('native')
```

When the phone language is set to `Azerbaijani` or `Turkish` the above line causes following exception:
```bash
Fatal Exception: java.lang.IllegalArgumentException: NATİVE is not a constant in com.facebook.share.widget.ShareDialog$Mode
       at java.lang.Enum.valueOf(Enum.java:200)
       at com.facebook.share.widget.ShareDialog$Mode.valueOf(ShareDialog.java:73)
       at com.facebook.reactnative.androidsdk.FBShareDialogModule.setMode(FBShareDialogModule.java:99)
```

## To Reproduce
- Set the interface language to Azerbaijani or Turkish
- Call `ShareDialog.setMode('native')`

## Cause
The reason for this error is that in those languages `"native".toUpperCase()` call returns `NATİVE` not `NATIVE` (note that the dotted and dotless capital `i`).

https://github.com/thebergamo/react-native-fbsdk-next/blob/caf9c0a5e3f3eaf267a1b817c73c83fc98b67d66/android/src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java#L99

## Workaround
Pass dialog mode in capital letters
```ts
ShareDialog.setMode('NATIVE')
```

## Fix
Fix would be passing `Locale.ENGLISH` to uppercase function:
```patch
-mShareDialogMode = ShareDialog.Mode.valueOf(mode.toUpperCase());
+import java.util.Locale;
+mShareDialogMode = ShareDialog.Mode.valueOf(mode.toUpperCase(Locale.ENGLISH));
```

**Comment by mikehardy** [comment]
Great catch
This has caught me out many times! (the Turkish i glyph mixed with use of Android APIs toUpperCase. with no Locale) I think you may also set Locale.ROOT as a general solution, like I did in react-native-firebase one time when this bit me?

https://github.com/invertase/react-native-firebase/pull/5335/commits/bef04fc4e38dda3e30017f522c9dbe8f4035fdd3#diff-b4209ab36069bd49057515eb496ad53c8a29755c2e1264053cf1e8a12b4862e5

If you propose a PR with Locale.ROOT specified we can merge and release in minutes probably

**Comment by OrkhanAlikhanov** [comment]
@mikehardy Thank you for the quick response. Updating the PR 🙂
