### ISSUE TITLE
issues with event tracking integration for ios14.5+

### ISSUE THREAD

**Issue by YaroslavReact** [thebergamo/react-native-fbsdk-next#242]
## 🐛 Help with integration

Hello, I want to use your package for tracking Facebook event for IOS14.5 + 
I did everything according to the instructions but the events are not displayed  

I create a project on react-native , versions of my packages

      "react-native-fbsdk-next": "^8.0.0",
- FBSDKCoreKit (13.1.0):
    - FBAEMKit (= 13.1.0)
    - FBSDKCoreKit_Basics (= 13.1.0)
  - FBSDKCoreKit_Basics (13.1.0)
  - FBSDKGamingServicesKit (13.1.0):
    - FBSDKCoreKit (= 13.1.0)
    - FBSDKCoreKit_Basics (= 13.1.0)
    - FBSDKShareKit (= 13.1.0)
  - FBSDKLoginKit (13.1.0):
    - FBSDKCoreKit (= 13.1.0)
  - FBSDKShareKit (13.1.0):
    - FBSDKCoreKit (= 13.1.0)
    

## To Reproduce
taken from example

 #import <FBAEMKit/FBAEMKit.h>

// apply codes below to `application:openURL:options:` 
 // in `AppDelegate.m` or `SceneDelegate.m`
[FBAEMReporter configureWithNetworker:nil appID:{app-id}];
[FBAEMReporter enable];
[FBAEMReporter handleURL:url];

my AppDelegate.m

<img width="926" alt="Screenshot at May 03 11-08-59 AM" src="https://user-images.githubusercontent.com/76779524/166422289-a099fc04-af5b-4a1a-aa5d-b5aa68382448.png">

in what format should i set the app id ? putting @ at the beginning is the only option where xCode doesn't give me an error

## Expected Behavior

I understand that I have to parse permission from the user and send it to your package
<img width="690" alt="Screenshot at May 02 11-21-20 AM" src="https://user-images.githubusercontent.com/76779524/166422647-78125f72-9014-4503-a6ab-cf67205b28b7.png">

<img width="504" alt="Screenshot at May 02 11-26-24 AM" src="https://user-images.githubusercontent.com/76779524/166422657-52e66d4c-8fa8-41d6-baec-9ac1d62f8ed3.png">

it works and i can see device share on ios14.5+

in order to see events from ios14.5+, do I have to make additional settings for the necessary events in this section?
![photo_2022-05-02_11-36-24](https://user-images.githubusercontent.com/76779524/166422828-57a1a852-88d7-4b28-867d-fcfc5c994002.jpg)

this is how i track events
<img width="583" alt="Screenshot at May 02 11-18-59 AM" src="https://user-images.githubusercontent.com/76779524/166422908-2f2c1bb5-4091-43e3-b4a8-63da40c95f18.png">

**Comment by RRaideRR** [comment]
I have the same issue. I tried to fallback to version 7.3.3 but this problem still occurs there.

**Comment by YaroslavReact** [comment]
I found a problem, you need to separately configure events in facebook event manager and select the necessary events for SKAdNetwork and then select an event for ios 14.5 in the tab below
![photo_2022-05-02_11-36-24](https://user-images.githubusercontent.com/76779524/166446649-49cadaa9-09b2-4af0-9e29-852cb697f178.jpg)
