### ISSUE TITLE
Appcenter builds failing

### ISSUE THREAD

**Issue by caiorrsdeg** [thebergamo/react-native-fbsdk-next#244]
After upgrading the [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next) from `6.2.0` to `8.0.0` I'm getting build errors for ios in AppCenter using XCode 13.2.1 and 13.2. I am able to build the app locally with XCode 13.3, and I'm not sure how to fix that. I have read through some issues that are like mine, but could not get a working solution.
<br/>
<br/>
AppCenter output
`Failed to compile bundle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/FBSDKCoreKit_Basics7ybfyai_/FBSDKCoreKit_Basics.arm64.xar`
<br/>
<br/>
What I tried
1 - https://intercom.help/appcenter/en/articles/1338686-react-native-build-fails-with-fbsdkcorekit-fbsdkcorekit-h-file-not-found
<br/>
I created that directory and the script, inside the directory I put the extracted zip of https://github.com/facebook/facebook-ios-sdk, but that did not work
<br/>
2 - https://swiftobc.com/repo/facebook-facebook-ios-sdk-swift-official-sdk
<br/>
Tried to add that repo as as swift package, did not work either, getting error `/Package.swift has no Package.swift manifest for version 4.44.1`
<br/>
<br/>
Sorry if this is not the correct place to open this issue, if it's not, guide me where I can open it

**Comment by mikehardy** [comment]
Looks like this issue upstream? https://github.com/facebook/facebook-ios-sdk/issues/2062

**Comment by caiorrsdeg** [comment]
> Looks like this issue upstream? [facebook/facebook-ios-sdk#2062](https://github.com/facebook/facebook-ios-sdk/issues/2062)

Yep, looks like that is my issue. I will close the issue since it's not related to this package, thank you!

**Comment by mikehardy** [comment]
I've got a couple old machines as commented in that thread, where I cannot upgrade past Xcode 13.2 because 13.2 is only available on macOS 12 and the machines won't update past macOS 11.

That said if you are on AppCenter it appears their macOS12 images have the latest Xcode https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode

**Comment by caiorrsdeg** [comment]
> I've got a couple old machines as commented in that thread, where I cannot upgrade past Xcode 13.2 because 13.2 is only available on macOS 12 and the machines won't update past macOS 11.
> 
> That said if you are on AppCenter it appears their macOS12 images have the latest Xcode https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode

These are the ones AppCenter allows me to choose (11.2 ~ 13.2.1)

<img width="165" alt="Screen Shot 2022-05-04 at 10 54 07" src="https://user-images.githubusercontent.com/89278488/166696144-91c033e2-3ac5-49d8-b4a4-15f9d7504939.png">

**Comment by mikehardy** [comment]
Looks like the macos-11 runner to me https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode - why not macos-12 :thinking:

**Comment by mikehardy** [comment]
Releasing 8.0.2 here right now that brings in firebase-ios-sdk 13.2.0, indicated upstream as resolving this. Should work?

**Comment by caiorrsdeg** [comment]
@mikehardy can confirm it works now, thank you!
