### ISSUE TITLE
App tracking Transparency for IOS 14

### ISSUE THREAD

**Issue by deepaktringapps** [thebergamo/react-native-fbsdk-next#25]
In native code to disable tracking as below,
Settings.setAdvertiserTrackingEnabled(false)

Please let me know how to disable app tracking in react native with the IOS platform, To avoid prompting the run time permission for request tracking in IOS 14

**Comment by mikehardy** [comment]
You need to initialize the SDK after you have configured settings appropriately

You set it like this https://github.com/thebergamo/react-native-fbsdk-next/blob/de06551a8d40214f50a36d5aa78560556e37c2f2/src/FBSettings.js#L34

https://github.com/thebergamo/react-native-fbsdk-next/blob/master/README.md#platform-neutral-sdk-initialization

Did it not work when you tried it? It appears to be all set up to work correctly, I don't think there is an issue here.

We can reopen if you try it and it does not work.

**Comment by deepaktringapps** [comment]
Thank you :)

It works fine !!

**Comment by deepaktringapps** [comment]
Once I set tracking enable as false getting like Settings.setAdvertiserTrackingEnabled(false)

Then getting a response as a promise, Please let me know how to resolve this and extract the boolean

Result ::::::
Promise {_40: 0, _65: 0, _55: null, _72: null}
_40: 0
_55: false
_65: 1
_72: null
__proto__: Object

**Comment by mikehardy** [comment]
Using Promises is fundamental to javascript, this was the first search I thought of and I actually scanned the results, they appear good as a start to answer your question: https://duckduckgo.com/?t=ffab&q=how+to+use+promises+in+javascript&atb=v204-1&ia=web

**Comment by rukmanary** [comment]
Can it combine with `react-native-tracking-transparency` to get the status tracking? I'm using requestTrackingPermission function Promise. If status is authorized or unavailable then I initialize the SDK `Settings.initializeSDK()`

But I am afraid `setAdvertiserTrackingEnabled` is still required. So how to use it properly? is it like this?:

```
import { requestTrackingPermission } from 'react-native-tracking-transparency';
import { Settings } from 'react-native-fbsdk-next';

 requestTrackingPermission()
      .then(status => {
        const enableTracking =
          status === 'authorized' || status === 'unavailable';
        if (enableTracking) {
          Settings.setAdvertiserTrackingEnabled(true).then(() => {
               Settings.initializeSDK(); 
          });
        }
      })
      .catch(e => Alert.alert('Error', e?.toString?.() ?? e));
```

**Comment by mikehardy** [comment]
A couple notes on this, react-native-tracking-transparency is duplicating the ATT features in react-native-permissions, [without apparently having an explanation](https://github.com/mrousavy/react-native-tracking-transparency/issues/8#issuecomment-839571568), so I use [react-native-permissions](https://github.com/zoontek/react-native-permissions/) personally even though the react-native-tracking-transparency is an excellent developer (react-native-permissions maintainer is likewise excellent but the package is older and well-maintained, so it's an easy choice for me)

In the code you paste, I think you want to initialize the SDK in a finally - you always want it to be initialized right? - you just toggle whether tracking is okay based on ATT status
