### ISSUE TITLE
No cached version of com.facebook.android:facebook-android-sdk:13.2.0 available for offline mode.

### ISSUE THREAD

**Issue by Ritesh175862** [thebergamo/react-native-fbsdk-next#253]
## 🐛 Bug Report
<img width="974" alt="Screenshot 2022-05-16 at 1 41 07 PM" src="https://user-images.githubusercontent.com/51701629/168548412-c5c7baea-4461-419f-84ff-3038e5e86632.png">

## Environment

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 18.77 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30, 31
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
The error message contains exactly how you need to fix it.

"Disable gradle offline mode"

**Comment by Ritesh175862** [comment]
Hi Miike Hardy

i try many time with offline and online gradle but its giving me the same error
________________________________

**Comment by mikehardy** [comment]
You have something going on with your network, I need to be clear: this is not a problem in this module. There is nothing we can do to help you.

you can see the repository information easily with direct access: 
https://mvnrepository.com/artifact/com.facebook.android/facebook-android-sdk
https://mvnrepository.com/artifact/com.facebook.android/facebook-android-sdk/13.2.0
https://repo1.maven.org/maven2/com/facebook/android/facebook-android-sdk/13.2.0/

It's all there.

![image](https://user-images.githubusercontent.com/782704/169097275-9d6a0cbc-93b2-4bb7-80a7-cce00c1fc6af.png)
