### ISSUE TITLE
FBAEMKit Sign Problem on deploy

### ISSUE THREAD

**Issue by JonathanVeg** [thebergamo/react-native-fbsdk-next#259]
I just changed the react-native-fbsdk to the react-native-fbsdk-next and after some issues it's working properly, but when I try to deploy it to app store I'm getting some problems with signature, as showed bellow.

I'm compiling it to iOS 14.
RN is 0.61.5 
RNFB-next is ^8.0.5

The PODs from the lib are:
`FBAEMKit (13.2.0)`
`FBLazyVector (0.61.5)`
`FBReactNativeSpec (0.61.5)`
`FBSDKCoreKit (13.2.0)`
`FBSDKCoreKit_Basics (13.2.0)`
`FBSDKGamingServicesKit (13.2.0)`
`FBSDKLoginKit (13.2.0)`
`FBSDKShareKit (13.2.0)`

The error I'm getting is:

<img width="1213" alt="Captura de Tela 2022-05-18 às 15 38 38" src="https://user-images.githubusercontent.com/2810809/169328484-7a633554-d22b-4dd1-834e-d4a8beec7093.png">

**Comment by mikehardy** [comment]
From the previous thread I suggested a snippet to add to post install of Podfile that *may* be *close* to something that can work  https://github.com/thebergamo/react-native-fbsdk-next/issues/252#issuecomment-1131006998

But in general this may be something to chase down in https://github.com/facebook/facebook-ios-sdk repo, as it will be lower-level than our react-native wrapper here *or* it will be project specific, something odd in the project-specific signing - and I'm not sure which

I doubt we will be able to resolve it here though

**Comment by JonathanVeg** [comment]
Do not understand the error and why it was pointing to this lib, but I solved it by removing everything related to the business account (in keychain) and reinstalled everything from zero.

After this the problem stopped happening...
