### ISSUE TITLE
Question: Can I use Firebase Dynamic Links as Facebook Deferred App links?

### ISSUE THREAD

**Issue by Ggayane** [thebergamo/react-native-fbsdk-next#262]
I'm using firebase for my app dynamic links, but I also need to use facebook ads with deferred links. Facebook requires to have URL Scheme Suffix for iOS apps, for firebase I'm using my custom domain, which starts with https://... Is there a way to use web urls as deferred app links?

**Comment by Ggayane** [comment]
Thank you for your answer [mikehardy](https://github.com/mikehardy), I've searched in different forums trying to find something, with no luck so far...

**Comment by mikehardy** [comment]
I can't vouch for the facebook folks from the underlying SDKs but I know that the firebase folks actually use stackoverflow as one of their main (perhaps, the main?) support channel. If you create a question there with great details and tag it up correctly, I bet you get an answer - cannot guarantee, but I bet

**Comment by rishCodere** [comment]
Hi @Ggayane , did you get solution to your query? I also want to use firebase dynamic link within meta ads, so that we can resolve the deep link and get utm_source, utm_media, utm_campaign and campaign_code params from our dynamic link in our react native app and track where the user is coming from?

**Comment by rishCodere** [comment]
@Ggayane can you please tell me the name of the service you are using? And also, can you please suggest me some services which are free to use like firebase for the task.

**Comment by Ggayane** [comment]
Unfortunately I don't know any free services, I guess you have to do some research
