### ISSUE TITLE
Settings Aggregated Event Measurement in AppDelegate.m

### ISSUE THREAD

**Issue by DGonzo001** [thebergamo/react-native-fbsdk-next#264]
Hello, who tuned AEM? please share AppDelegate
I can't figure out how to add lines correctly to make it work

**Comment by AneeqaKhan** [comment]
Hello @mikehardy, In the documentation AEM settings code is like this.

#import <FBAEMKit/FBAEMKit.h>

// apply codes below to `application:openURL:options:` 
// in `AppDelegate.m` or `SceneDelegate.m`
[FBAEMReporter configureWithNetworker:nil appID:{app-id}];
[FBAEMReporter enable];
[FBAEMReporter handleURL:URL];

But I can't be able to figure out how to pass the 'app-id'. I have written it like this 
[FBAEMReporter configureWithNetworker:nil appID:@"267761358792975"];

It doesn't give me an error on Xcode after writing like this. But still not able to send AEM notifications.
Maybe I'm writing this wrong. Can you pls help?

**Comment by ekegus** [comment]
@vigzmv did this work for you? Also, do you have any advice on how best to test the implementation?

**Comment by camboYY** [comment]
it does not work

**Comment by devops35** [comment]
it does not work. @camboYY @ekegus Has anyone solved the problem?

**Comment by fluorescent23** [comment]
The following code worked for me.

`[FBAEMReporter configureWithNetworker:nil appID:@"APP-ID" reporter:nil];`
`[FBAEMReporter enable];`
`[FBAEMReporter handleURL:url];`

`[FBAEMReporter configureWithNetworker:nil appID:@"APP-ID" reporter:nil]` this line requires an extra parameter `reporter:nil`. Adding this worked for me.
