### ISSUE TITLE
how to enable advertiserID collection ?

### ISSUE THREAD

**Issue by khushbujilka22** [thebergamo/react-native-fbsdk-next#269]
As the requirements I was set the "FacebookAdvertiserIDCollectionEnabled" to false in info.plist, on obtain User consent needs to set "FacebookAdvertiserIDCollectionEnabled" true.
 
How can We set "FacebookAdvertiserIDCollectionEnabled" true ?

Does setAdvertiserTrackingEnabled(true), will also Enable the "advertiserIDCollection" ?

## Environment

xcode 13.3
"react-native": "0.65.1",
"react-native-fbsdk-next": "8.0.5",

**Comment by mikehardy** [comment]
Hi there!

Open source means you can look -

https://github.com/thebergamo/react-native-fbsdk-next/blob/2e4fc7aa91db8ebf4ceec45ee35b602dd706b57c/src/FBSettings.ts#L33

https://github.com/thebergamo/react-native-fbsdk-next/blob/2e4fc7aa91db8ebf4ceec45ee35b602dd706b57c/src/FBSettings.ts#L13

https://github.com/thebergamo/react-native-fbsdk-next/blob/2e4fc7aa91db8ebf4ceec45ee35b602dd706b57c/ios/RCTFBSDK/core/RCTFBSDKSettings.m#L32

https://github.com/facebook/facebook-ios-sdk/blob/1739821b7e35cb342d80692eadf92f45a9d88e9f/FBSDKCoreKit/FBSDKCoreKit/FBSDKSettings.m#L253-L259

https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled
