### ISSUE TITLE
Facebook dashboard is unable to having conversion with app.

### ISSUE THREAD

**Issue by khushbujilka22** [thebergamo/react-native-fbsdk-next#270]
Followed all the steps and has done updated SDK integration, also got test events on dashboard, but could not **Configure app events for iOS 14.5 and later ad optimisations**, didn't understand where is the issue ?

My app is in testFlight, does this will affect for setup ?

[https://imgur.com/VG8iMrY](url)
[https://imgur.com/51I9kPQ](url)

Environment
"react-native-fbsdk-next": "8.0.5"
 "react-native": "0.65.1"

**Comment by mahdieh-dev** [comment]
Same here, did you find any solution for it? @khushbujilka22
