### ISSUE TITLE
App LogEvent not work!

### ISSUE THREAD

**Issue by khanh21011999** [thebergamo/react-native-fbsdk-next#271]
I just try to get the LogEvent by example code but it not working:
I call it like inside a `TouchableOpacity`:
  ```
      <TouchableOpacity
        onPress={() => {
          AppEventsLogger.logPurchase(15, "USD", { param: "value" })
          AppEventsLogger.logEvent(AppEventsLogger.AppEvents.CompletedRegistration, {
            [AppEventsLogger.AppEventParams.RegistrationMethod]: "email",
          })
          console.log("run")
        }}
      >
        <Text>Log</Text>
      </TouchableOpacity>
```
But it not even log in the purchase:
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/37074707/174346009-66d9b162-9a61-47e2-ab6d-c5571082c90c.png">

I already setup everything correct, try to log in and log out and it log in app and it log that record:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/37074707/174346246-07c2ab23-62eb-44a8-acd9-51deebeedc6d.png">

In console.log, it log `run` already
So what possible can cause this?

**Comment by camboYY** [comment]
I have the same problem with manual events (LogEvent) and automatic events are not working

**Comment by merodiro** [comment]
My issue was that I needed to add `Settings.initializeSDK()`
