### ISSUE TITLE
NSUserTrackingUsageDescription included by default on Expo

### ISSUE THREAD

**Issue by BrodaNoel** [thebergamo/react-native-fbsdk-next#272]
## 🐛 Bug Report
`react-native-fbsdk-next` is including `NSUserTrackingUsageDescription` by default in `infoPlist`.

## To Reproduce
Just install this library as dependency in your Expo project, and you'll see `NSUserTrackingUsageDescription` added by default in your `infoPlist` file, after building with `eas build`.

## Expected Behavior
Not to be included by default (in the `infoPlist` file)

**Comment by mikehardy** [comment]
Hi there!

1) 

> Just install it, build it, and you'll see it.

This is insufficient. See it where? Be specific about exact file path etc where I may locate the file. Please always take in to account that maintainer time in open source repositories is one of the scarcest commodities on the planet. When you open an issue in an open source repo that you are using and obtaining value from, for free, please do everything you possibly can to make it easy on the maintainer to verify things

2) Why would you have this expectation:

> Not to be included by default

You're including a facebook library, right? Where their business model is based on advertising? Further, what's the impact on the consuming project? That is, does it matter in some tangible way, meaning you are unable to use the library in some context for some reason (be specific)? If so, how would you mitigate it with any changes here?

**Comment by BrodaNoel** [comment]
> This is insufficient. See it where?

<img width="677" alt="Screen Shot 2022-06-19 at 16 01 25" src="https://user-images.githubusercontent.com/1837969/174496489-7dccc5ee-4cbb-4fc2-b744-69d74cdb45e6.png">

 ^^^^^^^^^^ "by default in infoPlist."

----

And regarding your point 2, it could take me 30 minutes on making this thread viral on Reddit.
You are telling me that because I want to use this library for logging in users in my app, I have to track them and there is no way to avoid it?

----

> what's the impact on the consuming project?
Due to the library is tracking my users, I am forced to add a disclaimer in the App Store telling the users: "I'm tracking your life", and I saw a decrease of ~12% in the conversion rate.

<img width="408" alt="Screen Shot 2022-06-19 at 16 08 08" src="https://user-images.githubusercontent.com/1837969/174496704-3b11d4ed-4f7f-4326-82ab-ed1dbb88013f.png">

^^^ As you may already know, there is no way to publish an App on Apple Store without adding that disclaimer in the App Privacy.
How toes Apple Store knows when I am tracking the user? When "NSUserTrackingUsageDescription" is added on the infoPlist file.
Who is adding "NSUserTrackingUsageDescription" in the infoPlist? `react-native-fbsdk-next`.
Why? Not sure, because I am not showing Facebook Ads, only allowing users to login with Facebook.

**Comment by BrodaNoel** [comment]
Because I am using Expo, this may be related: https://github.com/thebergamo/react-native-fbsdk-next/blob/847feea88269ae000705c4f1e010b275c4ca8f12/plugin/src/config.ts#L46

Seems like adding a `false` value in the default plugin config, it may disable this behavior.
But, still, it may be really good to switch it to set the userTracking only when it's defined as `true`

**Comment by mikehardy** [comment]
The change between your first comment, and it's contents, which are threatening and unpleasant

>  it could take me 30 minutes on making this thread viral on Reddit.

And your second comment are illuminating

If you see a deficiency in this software that you would like to correct, please post a PR doing the same. We merge all reasonable things.

Try to refrain from threats aimed at the folks providing you free stuff though, that's not polite.

**Comment by BrodaNoel** [comment]
@mikehardy man, you are the one who is not communicating properly.
Next time, change this:

> You're including a facebook library, right? Where their business model is based on advertising?

With this:

> We are including it because it's part of Facebook business model.

There you'll sound really better, less ironic and less arrogant.
We all know which is the Facebook's business model (and I like it). I just reported an unexpected behavior. I don't want to change Facebook's business model.

If you think free time of people is important, now please consider that I'm reporting a bug/feedback in a long weekend (Fri, Sat, Sun, and Mon, this week, are holidays in my country. And it's even FATHER'S DAY today here). So... As you can see, I'm also pushing some effort for free here.

Anyways... Leaving those misscommunication issues behind, I would sumup with this:

It is understandable that Facebook needs to Track Users in order to get money, but, the fact of adding `NSUserTrackingUsageDescription` be set by default, even when the app does NOT shows any Ads, is a problem, because it kills the quality of the app that is using it.

I would agree on adding `NSUserTrackingUsageDescription` by default in case that it is a REQUIRED thing for the SDK to work, but, as far as I could see, it's not required. So, switching to `false` by default, may be a good approach.

If you consider `true` by default is the correct way, ok, I can close this issue. I don't have any strong opinion here, just a bringing over the table this idea.
I'll add the `false` value in `iosUserTrackingPermission` and that should be all to fix the problem in my end.

**Comment by BrodaNoel** [comment]
PS.: I just edited the main post adding a bit more of lights on the descriptions.

**Comment by mikehardy** [comment]
I don't use Expo
A user contributed the expo support (awesome!)
It may be that that support is deficient, that is, doesn't meet the needs of the vast majority of Expo users
I don't use Expo, so I wouldn't no. I don't reproduce this in a non-Expo situation
If you use Expo, and feel like it's deficient, post a PR :rocket:

**Comment by BrodaNoel** [comment]
Yeap, I'll talk about this in the Expo discord.

Do you know what is the default behavior on non-Expo project? Does this library adds by default the `NSUserTrackingUsageDescription` value in the `infoPlist` file?
It think it would be a good idea to mimic the default non-Expo behavior in the expo implementation.

In case we change this default behavior, it may even imply a new breaking semver (because it will be a breaking for Expo users)

**Comment by mikehardy** [comment]
The reason I could not reproduce is because in non-Expo case it does not do anything to Info.plist, I suppose whomever contributed expo support felt it matched the default case to include it, but I'm not sure that is really so. I think it should be optional personally, like the non-Expo case

Breaking changes are find - so long as they include in the changelog exactly who is affected, exactly what the affect is, and what to do if it affects them - easy to do with our semantic release here, I take care of that on merge

**Comment by foloinfo** [comment]
I think this option is better to be opt-in, since it is up to the developer and the project to choose whether to track the user or not.
In our case we just use this library to impletement facebook login and nothing more.

I didn't realize it sets `NSUserTrackingUsageDescription` string in the infoplist by default (maybe I didn't read README enough)
https://github.com/thebergamo/react-native-fbsdk-next/blob/847feea88269ae000705c4f1e010b275c4ca8f12/plugin/src/withFacebookIOS.ts#L218
and found out about this right before submitting the app for an app review, then Apple is raising alert to update the privacy survey to proceed.

If someone decided to track the user using expo, I think it's better to use [expo-tracking-transparency](https://docs.expo.dev/versions/latest/sdk/tracking-transparency/) and set the `userTrackingPermission` option to set `NSUserTrackingUsageDescription`, and manually prompting user right before the tracking starts.

Anyway, I though this options is better to be false by default, so I made a PR #285 . Plaese give any feedback if anybody think it's appropriate or not.

**Comment by mikehardy** [comment]
@foloinfo agreed, and I appreciate the PR. It's running through CI now I'll release it if it passes everything

**Comment by BrodaNoel** [comment]
Just remember this will be a breaking change, thus, breaking semver

**Comment by BrodaNoel** [comment]
And thanks for that PR man! I agree with that approach.

The library was just adding that string. It was not actually getting the value, so, it was not helping to the Facebooks business model.

If the dev actually uses the expo-transparency-tracking and shows the permission request in some place in the app, so there it will makes sense to enable this.

And... to be honest, I don't think this string will even be necessary here, because it's something that you already had set in the expo-tracking-transparency plugin

**Comment by mikehardy** [comment]
Yeah I suppose so - I was initially thinking it was not, but because people previously opted out would see the same behavior, but now I see how the default state would change.

There are more ways to do ATT and permissions than just expo, I can't know if they have used some other module that would require knowledge we don't have

**Comment by foloinfo** [comment]
I changed PR to be backward compatible (I think), since the type definition accepts `string | bool` same as before. It behaves same as before if you give false.

**Comment by BrodaNoel** [comment]
Won't be backward compatible because the default behavior now is to consider "false" the "set tracking string" stuff. (Double check it just in case).

But, still, I think the correct behavior here is to NOT be backward compatible and remove that string by default and only set it if the dev explicitly ask for it. (What you did in the PR)
