### ISSUE TITLE
How to Connect the App Delegate?

### ISSUE THREAD

**Issue by KrishnarajS-FSP** [thebergamo/react-native-fbsdk-next#276]
Hi, i'm trying to connect the app delegate following the [Step 3: Connect the App Delegate](https://developers.facebook.com/docs/ios/getting-started/?sdk=cocoapods)

I couldn't find the AppDelegate.swift file.

**Comment by squirrelhomie** [comment]
@KrishnarajS-FSP If you're using react-native, the AppDelegate file you need to change is `AppDelegate.m`

**Comment by mikehardy** [comment]
This code is in objective-c, not swift, so the pointer to AppDelegate.m is correct
You appear to have edited your comment but make sure you're on current releases when you ask for help (that is, right now v8.0.5 here, not v7.x.x) https://github.com/thebergamo/react-native-fbsdk-next/releases

**Comment by KrishnarajS-FSP** [comment]
Hi @mikehardy and @squirrelhomie 

I installed this library in the project and run it. after that App is crashed when I tried to open it.
