### ISSUE TITLE
Facebook Rate limit exceeding using login only 

### ISSUE THREAD

**Issue by MayheMatan** [thebergamo/react-native-fbsdk-next#277]
Hi There,
I'm trying to integrate login with facebook in my RN app but suffering from huge rate limits on the facebook apps dashboard
my app has something about 1.5m users.

happens on version:
"react-native-fbsdk-next": "^7.0.1",

It seems like the issue is coming from such an auto logging events mechanism but could be something else as well which i cannot tell.

i've tried to add those lines:
IOS: 
Info.plist:

	<key>FacebookAutoLogAppEventsEnabled</key>
	<false />

Android:

      <meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled"
                    android:value="false"/>

After adding the above lines, it seems that issue has been resolved on IOS but keep on going on the android platforms

The issue most likely not related to the way i implemented the login because **the login with facebook button is actually hidden right now**. but it seems like when users downloading/opening the app it causes huge rate limits on facebook side that causes facebook to block us immediately when deploying new versions 

Providing screenshoots from the fb dashboard:

![Screen Shot 2022-06-22 at 13 56 56](https://user-images.githubusercontent.com/46110691/175014529-97572f2b-6cbe-4ecb-989b-64c05cffe541.png)
![Screen Shot 2022-06-22 at 13 57 25](https://user-images.githubusercontent.com/46110691/175014535-87fef776-9120-407e-928b-924ed8498415.png)

Does anyone here suffering or have suffered from the same issue before?

**Comment by dmitrycoder** [comment]
the same issue. Please help.

**Comment by juanobrach** [comment]
Same issue!
