### ISSUE TITLE
when I tried to run the pod install in the  iOS folder I am facing the issues like below.

### ISSUE THREAD

**Issue by KrishnarajS-FSP** [thebergamo/react-native-fbsdk-next#279]
[!] CocoaPods could not find compatible versions for pod "react-native-fbsdk-next":
  In Podfile:
    react-native-fbsdk-next (from `../node_modules/react-native-fbsdk-next`)

Specs satisfying the `react-native-fbsdk-next (from `../node_modules/react-native-fbsdk-next`)` dependency were found, but they required a higher minimum deployment target.

**Comment by bextechnologies** [comment]
Hi @KrishnarajS-FSP iam facing same issue . please share how you solve this Thank you

**Comment by yurachumak** [comment]
@bextechnologies i'm facing the same issue. did you find a solution?

**Comment by rnz269** [comment]
minimum deployment target refers to the minimum OS version you're going to support for the pod project. 

I had the same problem, then realized I had in my ios/Podfile:
`platform :ios, '10.0'`

Updating this to 11.0, then rerunning pod install within the ios directory resolved the issue for me.

**Comment by yurachumak** [comment]
@rnz269 thank you! it works
