### ISSUE TITLE
App center build error :- Undefined symbols for architecture armv7 : FBSDKApplicationDelegate", 

### ISSUE THREAD

**Issue by Gauravbtl** [thebergamo/react-native-fbsdk-next#281]
With the latest version of the `react-native-fbsdk-next` that is `9.0.0`, local builds are successful with xCode and RN CLI. But when the same code is pushed to CI/CD on `App center ` it gives an error for `AppDelegate.m`

1. Add #import <FBSDKCoreKit/FBSDKCoreKit.h>
2. Inside didFinishLaunchingWithOptions, add the following:

` [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];`

## Error on App center 
`Undefined symbols for architecture armv7:
"_OBJC_CLASS_$_FBSDKApplicationDelegate", referenced from:
objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

## Code Example 

The code causing issues from `AppDelegate.m`

`#import <FBSDKCoreKit/FBSDKCoreKit.h>`
`#import <FBAEMKit/FBAEMKit.h>`

 `[[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];`
`[FBAEMReporter configureWithNetworker:nil appID:{app-id}];`
`[FBAEMReporter enable];`
`[FBAEMReporter handleURL:url];`

## Environment
`"react-native": "0.64.2",`
`"react-native-fbsdk-next": "^9.0.0",`
`xCode : 13.1`
`Deployment target : 12.1`

**Comment by mikehardy** [comment]
I don't use AppCenter and won't be able to offer help using that infrastructure, sorry.

This portion of your report is critical:

> local builds are successful with xCode and RN CLI.

We do development here with Xcode and RN CLI. RN CLI mainly.

If you can show a reproduction that fails with RN CLI I may be able to help, otherwise I suppose don't upgrade until you or someone else has figured out the issue with AppCenter.
