### ISSUE TITLE
[Latest Version, 9.0.0]CocoaPods could not find compatible version for pod "FBSDKLoginKit"

### ISSUE THREAD

**Issue by boodong-rn** [thebergamo/react-native-fbsdk-next#282]
## 🐛 Bug Report

<img width="859" alt="image" src="https://user-images.githubusercontent.com/95212382/176360714-46448f11-eced-485e-bfd2-701bf898713d.png">

I was using previous verison (v8.0.4) and trying to upgrade to latest version (v9.0.0).

## To Reproduce

1. `yarn add react-native-fbsdk-next`
2. `cd ios && pod install`

**Comment by mikehardy** [comment]
The error message is prescriptive and will fix it:

`pod repo update`

**Comment by boodong-rn** [comment]
`pod repo udpate` didn't fix my issue. So I had manually updated pods with command below and it's working.
`pod update FBSDKLoginKit FBSDKShareKit FBSDKGamingServicesKit FBSDKCoreKit`

**Comment by Ozaoujal** [comment]
I have the same issue, but in expo

**Comment by qualwebs** [comment]
> `pod repo udpate` didn't fix my issue. So I had manually updated pods with command below and it's working. `pod update FBSDKLoginKit FBSDKShareKit FBSDKGamingServicesKit FBSDKCoreKit`
> 
> Anyway thank you for replying!

You misspelled the command it's  pod repo update not pod repo udpate
