### ISSUE TITLE
Facebook pixel not showing app install in app promotion campaign

### ISSUE THREAD

**Issue by MuhammadZulkifle** [thebergamo/react-native-fbsdk-next#283]
We are using "react-native-fbsdk-next": "4.6.0" . Following the official instructions found at https://developers.facebook.com/docs/app-events/getting-started-app-events-android, we completed all the steps necessary to integrate the SDK. Additionally, our  application created Facebook at developer account that is connected to our business account displays app installs, active apps, and app launches; but, despite several link hits, our campaign does not display app instals from the previous 7 days.

**Comment by mikehardy** [comment]
We are on version 9 here. A version as old as 4.6.0 will receive no attention, going to close - please update to current and re-try. Note there are other issues related to app installs in the issue tracker here with lots of interesting info. After you are on current, if you still experience issues please read those and add commentary there so we don't have duplicates + keep conversation focused in relevant places. Thanks!
