### ISSUE TITLE
Error Building from "FacebookAppDelegate.swift" and "CompileSwiftSources"

### ISSUE THREAD

**Issue by dieg092** [thebergamo/react-native-fbsdk-next#284]
Hi, im tring to build my iOS App but it fails with next errors:

1. "CompileSwift normal x86_64 /Users/bigsur/take_and_goo/node_modules/react-native-fbsdk-next/ios/ExpoAdapterFBSDKNext/FacebookAppDelegate.swift"

2. "CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler"

### Steps to reproduce in cmd:
$ react-native run-ios

### Last Output lines:
![image](https://user-images.githubusercontent.com/11876652/176763163-e13886c1-21ad-4b5c-9a29-7b0a310c1257.png)

I tried to Build with play button on xcode and it fails too with next errors:
![image](https://user-images.githubusercontent.com/11876652/176772592-4c02a847-0f75-4219-b642-b9eafdad31d7.png)
![image](https://user-images.githubusercontent.com/11876652/176772762-dd573977-688d-4995-a46a-fea1c4dc60fe.png)

I tried: 
     - Clean build folder ($ rm -rf ~/Library/Developer/Xcode/DerivedData), 
     - Re-index  project on xcode, 
     - Update pods ($ pod install --repo-update)
     - Clean Build Project on /Project tab

### Podfile:
[Podfile.txt](https://github.com/thebergamo/react-native-fbsdk-next/files/9023246/Podfile.txt)

### Config:
"react-native": "0.64.3",
"expo": "^43.0.3",
"react-native-fbsdk-next": "^9.0.0",
"expo-modules-core": "~0.4.10"

xcode version: "12.5.1"
iOS Deployment Target 12.0
swift: "5.4.2"

**Comment by mikehardy** [comment]
Hi there! That's not an error. That's a notice that there was an error somewhere but is not itself an error.
https://stackoverflow.com/help/how-to-ask

- steps to reproduce
- useful error output
- what you tried already with explanations of why and why it did not work perhaps

Note that our example is actually generated automatically and it shows a working setup - https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh
