### ISSUE TITLE
ShareDialog.canShow returns true even if app is not installed

### ISSUE THREAD

**Issue by omergilboa** [thebergamo/react-native-fbsdk-next#286]
## 🐛 Bug Report

Using `ShareDialog.canShow` returns `true` even if facebook app is not installed on device.
## Expected Behavior

`ShareDialog.canShow` should return `false` if facebook app is not installed on device.
## Code Example

```
return await ShareDialog.canShow({contentType: 'link', contentUrl});
```
## Environment

v: `react-native-fbsdk-next@6.2.0`

**Comment by omergilboa** [comment]
please can someone take a look at this?

**Comment by mikehardy** [comment]
Sorry, this does not appear to be a use case of any of the maintainers. If this is an important use case for your business, you'll have to dedicate resources to dig in and diagnose + fix
