### ISSUE TITLE
IOS app crashing while launching  

### ISSUE THREAD

**Issue by Joshig99** [thebergamo/react-native-fbsdk-next#287]
Hi i added fbsdk swift package by following this doc https://developers.facebook.com/docs/ios/getting-started, after adding this package app crashing while launching, but its working if run the project through xcode but not working through command line
also not getting any error logs 

## Environment

System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 28.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
    react-native-fbsdk-next: "^9.0.0",

**Comment by BrianIto** [comment]
Exact same problem here with the same hardware, no missing Client Token.

**Comment by mikehardy** [comment]
ios crash reports should always be accompanied by the crash trace - if you can reproduce this please launch app from Xcode, reproduce, then paste a crash trace, otherwise all I can say is I don't have any crashes so this has no reproduction or root cause analysis I'm aware of
