### ISSUE TITLE
FBSDK does not allow to sign in with a different account after logging out

### ISSUE THREAD

**Issue by rdsedmundo** [thebergamo/react-native-fbsdk-next#29]
This is a transfer of this original issue in the now archived repository: https://github.com/facebookarchive/react-native-fbsdk/issues/712

## 🐛 Bug Report
There's no way to change the account you have signed in, even if you successfully log out of the application.

I also tried to clear the Safari cache in the Settings, and it still presents me with a "You previously logged in to [APP] with Facebook".

## To Reproduce
1. Login in with a Facebook account A.
2. Successfully log out of facebook account B. Logout of Safari browser, clear Safari cache on Settings.
3. Try to login in with a Facebook account B. You're unable because the webview somehow still remembers the Facebook account A.

## Expected Behavior
There should be a way to clear the webview cookies/cache.

This is likely a problem on the iOS Facebook SDK to be honest, but I wonder if there's anything we can do in our side to clear it manually, at least in development.

## Workaround (development)

1. In the iOS simulator, go to Device -> Erase all content and settings
2. Rebuild the app `react-native run-ios`.

## Environment
```
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 24.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1
    Yarn: 1.19.1
    npm: 6.14.12
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by rdsedmundo** [comment]
Thanks for doing that, I had seen this comment but didn't occur to move it over.

I also edited the issue including a workaround for development-only while using the iOS simulator.

**Comment by thebergamo** [comment]
I will leave it closed for now, as there is no tangible action on our side. 
If someone comes with any news about this getting fixed by Facebook or Apple we can reopened :)

Thanks for including the workaround o/

**Comment by kolboch** [comment]
Possible this might be the way to be able to change account: 
https://github.com/facebook/facebook-ios-sdk/issues/2000
Raised the issue on ios-sdk as this is the case, basically since iOS 13+ it's possible to request running `ASWebAuthenticationSession` with `prefersEphemeralWebBrowserSession` set to true, but the api would have to expose that or give some interface to request that.

**Comment by mikehardy** [comment]
Interesting @kolboch I wonder if you patched facebook-ios-sdk locally if it would work? Historically I have been able to patch things like that via a cocoapods post-install hook that either directly edited source files in place via sed or by calling the system `patch` binary on a file and applying a patch similar to how patch-package works. A PR to that repo would be better than an issue in other words - and may stand a good chance of being merged, then maybe we could make progress here

**Comment by kolboch** [comment]
Hi @mikehardy , thanks for your comment, didn't know it's possible as I recently switched to ios but would try to make it. There seem to be some contributing guide in facebook-ios-sdk, I hope it would go well :)

**Comment by KrisLau** [comment]
Not sure about iOS but I managed to clear the cache on my Android phone through Chrome which seems to allow me to log in with a different account.

**Comment by mikehardy** [comment]
> Same for me. Any updates?

It's open source, the updates you see are the updates you've got: https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

@Reykjavik151 if this is an important use case for you / your app / your company, pursue it with whatever resources you can, and post your updates here

**Comment by lukkimo** [comment]
I have the same issue in android too😩
