### ISSUE TITLE
Uncaught Error `new NativeEventEmitter()` requires a non-null argument

### ISSUE THREAD

**Issue by tunnaduong** [thebergamo/react-native-fbsdk-next#291]
## 🐛 Bug Report

The error on the title showed whenever I'm import react-native-fbsdk-next.

## To Reproduce

Create new Expo app, install react-native-fbsdk-next, no using expo run:ios or prebuild

## Expected Behavior

I expected it will show up a login screen with my app name and icon

## Code Example

```javascript
import auth from "@react-native-firebase/auth";
import { LoginManager, AccessToken } from "react-native-fbsdk-next";

async function onFacebookButtonPress() {
  // Attempt login with permissions
  const result = await LoginManager.logInWithPermissions([
    "public_profile",
    "email",
  ]);

  if (result.isCancelled) {
    throw "User cancelled the login process";
  }

  // Once signed in, get the users AccesToken
  const data = await AccessToken.getCurrentAccessToken();

  if (!data) {
    throw "Something went wrong obtaining access token";
  }

  // Create a Firebase credential with the AccessToken
  const facebookCredential = auth.FacebookAuthProvider.credential(
    data.accessToken
  );

  // Sign-in the user with the credential
  return auth().signInWithCredential(facebookCredential);
}

export default onFacebookButtonPress;
```

**Comment by pfinazzo** [comment]
any updates on this? this is happening for me as well!

**Comment by mikehardy** [comment]
@pfinazzo welcome! As an open source project, you're the developer also, not just the user. If you see no updates, there are no updates. Do you propose anything that could fix it?

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

**Comment by kastriotkastrati** [comment]
This could happen if you're trying to run this on expo-go. Build a dev client and try it then.

**Comment by kastriotkastrati** [comment]
This could happen if you're trying to run this on expo-go, which should not work here. Build a dev client and try it then.

**Comment by jakequade** [comment]
> As an open source project, you're the developer also, not just the user

Somebody woke up on the passive-aggressive side of the bed.

**Comment by mikehardy** [comment]
Nuh uh uh. I'm aggressive aggressive.

**Comment by mikehardy** [comment]
Stated differently to be clear: happy to help things merge but it's open source - you need the thing? You'll probably need to do the thing. And we'll all move forward
