### ISSUE TITLE
Update FB-SDK to modern v14.1.0

### ISSUE THREAD

**Issue by boovius** [thebergamo/react-native-fbsdk-next#294]
Is it possible to bring in the update for the latest SDK version 14.1.0 here?

**Comment by mikehardy** [comment]
Sure! Just post a PR that bumps the versions and I can help merge and release it. Locally you can use patch-package to test any changes. The lines are seen here https://github.com/thebergamo/react-native-fbsdk-next/blob/master/react-native-fbsdk-next.podspec and https://github.com/thebergamo/react-native-fbsdk-next/blob/63f9c6f6d61d99134c648809346d6fc4fe645387/android/build.gradle#L47 (but android seems to use 14+ so should already have it)

**Comment by boovius** [comment]
@mikehardy here's a PR! Thanks for your response and help here! https://github.com/thebergamo/react-native-fbsdk-next/pull/297

**Comment by usamaabutt** [comment]
Hi @mikehardy @boovius guys thanks for having this conversation I am also wishing to have the latest SDK 14.1.0, kindly approve and merge the PR @mikehardy 
Thanks!

**Comment by mikehardy** [comment]
Just got another time slice where I had a chance to check the PR, looks/looked great and is working through CI now. You can use patch-package in the interim of course (in case CI doesn't finish before I have to close my laptop and run off somewhere without releasing it...) but hopefully it releases shortly
