### ISSUE TITLE
[DOCS] How to use it with Expo 45?

### ISSUE THREAD

**Issue by robertoosantos** [thebergamo/react-native-fbsdk-next#296]
## 🐛 Bug Report

The documentation does not make it clear about how to use it with [Expo](https://expo.dev/).

I've tried just installing it as I've done with many other dependencies and it doesn't work.

In production I'm using [expo-facebook](https://docs.expo.dev/versions/v45.0.0/sdk/facebook/) but it's deprecated and recommended to use react-native-fbsdk-next but there's no explanation about how to do it too.

May someone help me?

## To Reproduce

1. Create an [Expo 45 project](https://docs.expo.dev/get-started/create-a-new-app/)

2. Install react-native-fbsdk-next  `expo install react-native-fbsdk-next`

3. Replace the App component with the README example

And then, got the error: **Invariant Violation: requireNativeComponent: "RCTFBLoginButton" was not found in the UIManager.**

## Expected Behavior

The Facebook Login button at least shows up

## Code Example

Also on Snack: https://snack.expo.dev/@robertoosan/-react-native-fbsdk-next---expo44

```javascript
import React from 'react'
import { LoginButton, AccessToken } from 'react-native-fbsdk-next';

function FacebookLogin(props) {

    return (
        <LoginButton
            onLoginFinished={
                (error, result) => {
                    if (error) {
                        console.log("login has error: " + result.error);
                    } else if (result.isCancelled) {
                        console.log("login is cancelled.");
                    } else {
                        AccessToken.getCurrentAccessToken().then(
                            (data) => {
                                console.log(data.accessToken.toString())
                            }
                        )
                    }
                }
            }
            onLogoutFinished={() => console.log("logout.")} />
    )
}

export default FacebookLogin
```

## Environment
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.20.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.17 - /usr/bin/npm
    npmPackages:
      expo: ^45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: managed

**Comment by baochungit** [comment]
The docs is not very clear. As far as I checked, Expo now supports it in Dev Client mode. So it's easy to config without the "Adding custom native code" guide part.

Just add & config this block in app.json (or app.config.js) is enough:
{
  "expo": {
    "plugins": [
      [
        "react-native-fbsdk-next",
        {
          "appID": "48127127xxxxxxxx",
          "clientToken": "c5078631e4065b60d7544a95xxxxxxxx",
          "displayName": "Your FB App Name",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": false,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "This identifier will be used to deliver personalized ads to you."
        }
      ]
    ]
  }
}

After that, build your development app with EAS Build and try it

**Comment by robertoosantos** [comment]
Amazing! I've just released a new version of the app in bare workflow with the native code configuration.

I'll try this on the next version.

But out of curiosity, how did you figure out how to do those configurations? It may be useful in the future.

**Comment by baochungit** [comment]
I'm using this package for my project and faced the same issue as you did. After checked the docs and tried the part "Adding custom native code" I figured out it was an unnecessary step since Expo covers the rest for us (linking, adding strings to AndroidManifest.xml,...). I'm sure you could use this package with Expo managed SDK 45. (not checked yet for iOS)
