### ISSUE TITLE
[Android] The library doesn't work with latest version of Facebook App 

### ISSUE THREAD

**Issue by williamtran29** [thebergamo/react-native-fbsdk-next#301]
I tried 3 versions 9.0.0, 10.0.0, 10.1.0 and return same bug 

## 🐛 Bug Report

When we login with 
`LoginManager.logInWithPermissions(['public_profile'])`
it alway return isCancelled : true
and we can't login

I also tried with `LoginButton` too, and it has same issue

**Comment by mikehardy** [comment]
Hmmm :thinking: no one else has reported this, which makes me curious

I do this in my app:

> stores/UserStore.ts:      const result = await LoginManager.logInWithPermissions(['public_profile', 'email']);

I just tested it on an android phone with fully up to date apps (including facebook) and it works, so I cannot reproduce

If you can post an MVCE (https://stackoverflow.com/help/mcve) or someone else reproduces this, we can reopen, but I don't see it at the moment based on the info you provide

**Comment by khudratov** [comment]
I got this error too:
1. Opened my app and press to button 
2. Click on the button and the facebook application will open

Boom. 
![2022-08-24 11 21 54](https://user-images.githubusercontent.com/58653980/186345814-148f71ba-d936-4651-ac52-2972fe39189f.jpg)

there is my code : 
`const getDataForAndroid: () => Promise<responseType> = async () => {
  const result = await LoginManager.logInWithPermissions([
    'public_profile',
    'email',
  ])

  if (result.isCancelled) {
    return { message: 'Request cancelled' }
  }

  const accessData = await AccessToken.getCurrentAccessToken()

  return new Promise((resolve, reject) => {
    if (!accessData?.accessToken) {
      return reject({ message: 'Empty FB accessToken' })
    }

    const infoRequest = new GraphRequest(
      '/me',
      {
        accessToken: accessData.accessToken,
        parameters: {
          fields: {
            string: 'email,name,id',
          },
        },
      },
      (error, result) => {
        if (error) {
          console.error({ message: 'fetch FB error', error })
          return reject(error)
        }

        const { id, name, email } = result || {}

        if (
          typeof id === 'string' &&
          typeof name === 'string' &&
          typeof email === 'string'
        ) {
          return resolve({ id, name, email, token: accessData.accessToken })
        }

        return reject({ message: 'Invalid data' })
      },
    )
    new GraphRequestManager().addRequest(infoRequest).start()
  })
}`

**Comment by khudratov** [comment]
I got this error too:
1. Opened my app and press to button 
2. Click on the button and the facebook application will open

Boom. 
![2022-08-24 11 21 54](https://user-images.githubusercontent.com/58653980/186345814-148f71ba-d936-4651-ac52-2972fe39189f.jpg)

there is my code : 

![photo_2022-08-24 11 33 18](https://user-images.githubusercontent.com/58653980/186347387-07634a03-5ddb-49f6-ae86-47d28918dc26.jpeg)

in IOS works correctly 

If i remove facebook application it works in android too

**Comment by mikehardy** [comment]
facebook application is what version?

I'm on 380.0.0.29.109 still works for me

**Comment by hugoh59** [comment]
I have a similar issue I think with a hidden transparent modal on android I just created an issue.

**Comment by hugoh59** [comment]
@williamtran29 did you figure it out ?
