### ISSUE TITLE
App is not active

### ISSUE THREAD

**Issue by m7amad-7asan** [thebergamo/react-native-fbsdk-next#303]
Signing in is working on android very well.
on ios it works on the simulator, but when i use a real iphone i'm getting "app is not active: this app is not accessible right now and the app developer is aware of the issue. you will be able to log in when the app is reactivated"

**Comment by m7amad-7asan** [comment]
Solved, The problem was that i still on the development mode, When i switch to my app to live mode it works

**Comment by chaosLegacy** [comment]
Hey @m7amad-7asan I'm facing the same issue with both ios simulator and real device, currently I can't switch to live mode since I don't have yet a written privacy policy nor a valid website, but it will come in the future, as for now I only want to test the app under development mode, is it possible?
<img width="346" alt="Screenshot 2022-09-07 at 11 38 36" src="https://user-images.githubusercontent.com/11313734/188846127-3a813984-6faf-4380-9010-f3cd6dd78108.png">

**Comment by andrespaggy** [comment]
Hi @chaosLegacy.

Yes, actually you can test the app under development mode using an account created in one of the following ways:
1. You can add an existing facebook user as a Tester under the tab `App Roles > Roles`, from the left sidebar.
2. You can create a test account under the tab `App Roles > Test Users`, from the left sidebar.

**Please note**: if you don't create an account this way you'll get that _App not active_ screen.

Hope this could help.

**Comment by Punith-goud** [comment]
> Solved, The problem was that i still on the development mode, When i switch to my app to live mode it works

hey can please tell me how to switch the app to live mode?  did you i need to publish my app?

**Comment by hdjvieira** [comment]
I was in a similar situation, although my app has been published and functioning for 3 years, early 2025 got a bunch of violations and the Annual Data Use Checkup blocking my app.

After resolving all of them got another violation saying:

> Platform Term 7.a - App is not loading or has broken functionality
> Platform affected: Android
> During [a review](https://developers.facebook.com/docs/resp-plat-initiatives/terms) of your app, we found that parts of your app were broken.
...
> Reasons for this violation
> fb login leading to error page stating (this app isnt available)
...

Sure enough upon testing got the same page as @chaosLegacy posted.
After losing a few hours scouring the internet and my code, finally discovered the issue: my FB APP ID was changed!

Don't have a clue how it's even possible for that to happen, but it has.
After setting the correct facebook_app_id and fb_login_protocol_scheme with the new APP ID on my code everything worked as expected again.

So for anyone getting that page, double check the FB APP ids on your code match the ones on the dashboard.
