### ISSUE TITLE
Crash on IOS FBSDKGameRequestDialog react-native 0.69 

### ISSUE THREAD

**Issue by kingkongqn4444** [thebergamo/react-native-fbsdk-next#308]
## 🐛 Bug Report
  I'm facing bug native module when used react-native-fbsdk-next with react native version 0.69, I install the library and Pos bug when building application success, app crash, and bug report 

When I remove it from the project it runs normally, Please help me thank you very much

Thread 1: "-[FBSDKGameRequestDialog initWithContent:delegate:]: unrecognized selector sent to instance 0x600002a7d290"
## To Reproduce
  1. Install the library and follow docs integrate native code for ios
  2. build application and crash

## Environment
 react-native-fbsdk-next version 10.1.0
System:
    OS: macOS 11.6.8
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.48 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/admin/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /Users/admin/Library/Java/JavaVirtualMachines/openjdk-18/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:

**Comment by kingkongqn4444** [comment]
I create a new project and reinstalled the library.. it work perfectly, I will investigate many thanks

**Comment by mikehardy** [comment]
When I see this:

> Thread 1: "-[FBSDKGameRequestDialog initWithContent:delegate:]: unrecognized selector sent to instance 0x600002a7d290"

"unrecognized selector" - that usually means "the javascript code and the native code are not in line", `npx react-native-clean-project` may clear things up
