### ISSUE TITLE
access token change every time page load

### ISSUE THREAD

**Issue by ArjunKarki** [thebergamo/react-native-fbsdk-next#311]
access token change every time page load and my signup token and login token never the same .I was giving token to serve with 
AccessToken.getCurrentAccessToken().

**Comment by mikehardy** [comment]
This issue report represents a failure to include any information useful to troubleshoot.

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

If you were asked this question by a subordinate, I feel confident in asserting you would not be able to help, and neither can we. With apologies, closing.
