### ISSUE TITLE
Subscribe Event is not showing in the events manager of my App. [ANDROID]

### ISSUE THREAD

**Issue by AnthonyHaykal** [thebergamo/react-native-fbsdk-next#312]
## 🐛 Bug Report

Subscribe Event is not showing in the events manager of my App. (All other automatic events are showing) [ANDROID]

## To Reproduce

1- Try to purchase from google
2- Check Test events and/or events inside the Event Manager of your app
3- Android Subscribe events are not triggering

## Expected Behavior

- All automatic events should trigger, especially the Subscribe Event
- As you can see from the screenshots, other automatic events are already triggering, our only problem is the "Subscribe" event which is really important for us.

## Environment
 "react-native-fbsdk-next": "^10.1.0",
  "react-native": "0.66.1",

<img width="1235" alt="151313064-1857ff79-d079-45be-8986-9259b907fe49" src="https://user-images.githubusercontent.com/19162832/191018965-5232313e-61d1-41c3-b993-fceb2d0c7aca.png">

<img width="1203" alt="151313058-c961400c-7430-44b3-bae8-3d653a945cd8" src="https://user-images.githubusercontent.com/19162832/191018981-41a67784-6fad-4f5e-b042-7648a064c7ee.png">

**Comment by devops35** [comment]
@AnthonyHaykal I have the same problem. How did you solve it?
