### ISSUE TITLE
Doubt about UserTracking

### ISSUE THREAD

**Issue by Namoku** [thebergamo/react-native-fbsdk-next#314]
Hello! In my app I was using expo-facebook to have Facebook Login in my both platforms but expo-facebook stop working in android 12, so I'm gonna update to this but I got a doubt about UserTracking Policy, is there a way to keep it disabled because I only need the login in iOS or do I need to have it enabled and update the privacy policy in the appstore

**Comment by mikehardy** [comment]
Sounds like this from the README? https://github.com/thebergamo/react-native-fbsdk-next#limited-login-ios

**Comment by Namoku** [comment]
Oh god, sorry! Ty a lot for replying!
