### ISSUE TITLE
Build failed when add FBSDKApplicationDelegate

### ISSUE THREAD

**Issue by sandirr** [thebergamo/react-native-fbsdk-next#316]
Version
<img width="258" alt="image" src="https://user-images.githubusercontent.com/50796200/193399792-7a5d575c-3253-43c8-959a-aabd74774a1b.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/50796200/193399931-7699dc4c-63fa-4c20-a569-88f16a3a0bea.png">

Info.plist
![image](https://user-images.githubusercontent.com/50796200/193400090-3ca18f26-2eb4-4ac1-8abb-5e600df09c5f.png)

## If I add these (line 72 and 111-118) build process will failed. If I removed/commented it, build will success
<img width="748" alt="image" src="https://user-images.githubusercontent.com/50796200/193399833-9adf5e80-ce0c-441e-a68e-59e2517958fe.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/50796200/193400290-8ce54e4b-2343-4778-8dba-7f3b7a838389.png">

## Error logs
<img width="722" alt="image" src="https://user-images.githubusercontent.com/50796200/193399774-f110aa9a-2995-4673-bba7-caff20853b67.png">

## Is there anyone can help? please!

**Comment by mikehardy** [comment]
Please post text not images, github is really a text-based environment so we can snip and refer to things and so it works well for people that are on the mobile client.

Looks like you are missing an import though. Step 1 here https://github.com/thebergamo/react-native-fbsdk-next#32-ios

**Comment by sandirr** [comment]
Ups sorry @mikehardy 

step 1 is to add
```
#import <FBSDKCoreKit/FBSDKCoreKit.h>
```
in appDelegate.m right?


I've done that tho (2nd image)

**Comment by mikehardy** [comment]
I wonder if it is related to this: #317 - which is another way of saying that I didn't realize it but it appears that facebook-ios-sdk v15 may have changed the way things work, or there is an impact in their swift conversion that alters symbol availability 🤔
