### ISSUE TITLE
Native crash on Android with Expo 46.0.13 due to FBProfileModule.java:50 attempt to get length of null array

### ISSUE THREAD

**Issue by evelant** [thebergamo/react-native-fbsdk-next#318]
The following code added in https://github.com/thebergamo/react-native-fbsdk-next/commit/63f9c6f6d61d99134c648809346d6fc4fe645387 causes a hard crash on Android 30s after the first call to `getCurrentProfile`. The exception is

```
java.lang.NullPointerException: Attempt to get length of null array
        at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:164)
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:31)
        at com.facebook.reactnative.androidsdk.FBProfileModule$1.run(FBProfileModule.java:50)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
```

https://github.com/thebergamo/react-native-fbsdk-next/blob/f0dae02948ea129be80f5a860ee6dd28b6caae99/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java#L42-L66

I'm not quite sure _why_ this is happening. I don't have enough experience with native android to know but it seems like maybe some sort of threading issue so the argument is null instead of an array containing null? `fromJavaArgs` expects an array and it looks like it should be called with an array containing a single `null` but instead it seems to be called with just `null`.

Roliing back to `9.0.0` fixes the issue. 

Not sure how to debug this one further due to lack of experience with native android.

**Comment by mikehardy** [comment]
Interesting - our native code is usually pretty simple but this specific chunk is a bit "fancy" because of the need to work around a possibly hanging promise (that's why there is a 30 second wait + cancel - otherwise it's possible the Promise would never resolve, which is a big no no)

Anyway, your hunch seems pretty good, you can reach right into the node_modules and fiddle with the Java to try testing your hunch perhaps? Does Expo allow that?

I don't use this method personally so I don't have a reproduction nor the motivation to throw volunteer time at a use case not used in my projects (being honest), so any way you can get Expo to use a modified version where you test the theory of an Array with null would be the quickest way to move this forward. I would happily merge + release any reasonable PR

**Comment by evelant** [comment]
Not stale, I just haven’t gotten around to looking into a real fix

**Comment by lancyrosy** [comment]
same things happens in my side and there is no any useful solution online

**Comment by evelant** [comment]
@lancyrosy For now I've made a patch to revert to the previous behavior before this bug was introduced in https://github.com/thebergamo/react-native-fbsdk-next/commit/63f9c6f6d61d99134c648809346d6fc4fe645387

You can apply this patch with `patch-package` or use the built in patch support in `pnpm` (I highly recommend `pnpm`, it fixes a lot of the problems with js package management)

react-native-fbsdk-next@11.0.1.patch
```patch
diff --git a/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java b/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
index 71ceda57f40f4031b791ca847471d64b79990f37..04bd6587b5dcdf2a9ef82948376a72f5da4f8100 100644
--- a/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
+++ b/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
@@ -33,36 +33,14 @@ public class FBProfileModule extends ReactContextBaseJavaModule {
   }
 
     /**
-     * Get the current logged profile.
-     * @param callback Use callback to pass the current logged profile back to JS.
-     */
+    * Get the current logged profile.
+    * @param callback Use callback to pass the current logged profile back to JS.
+    */
     @ReactMethod
-    public void getCurrentProfile(final Callback callback) {
-      // Return the profile object as a ReactMap.
-      if (Profile.getCurrentProfile() == null) {
-        final Timer timer = new Timer();
-        synchronized (timer) {
-          timer.schedule(
-            new TimerTask() {
-              @Override
-              public void run() {
-                timer.cancel();
-                callback.invoke(null);
-              }
-            },
-            30000
-          );
-          mProfileTracker = new ProfileTracker() {
-            @Override
-            protected void onCurrentProfileChanged(Profile oldProfile, Profile currentProfile) {
-              timer.cancel();
-              mProfileTracker.stopTracking();
-              callback.invoke(Utility.profileToReactMap(currentProfile));
-            }
-          };
-        }
-      } else {
-        callback.invoke(Utility.profileToReactMap(Profile.getCurrentProfile()));
-      }
+    public void getCurrentProfile(Callback callback) {
+        //Return the profile object as a ReactMap.
+        callback.invoke(Profile.getCurrentProfile() == null
+                ? null
+                : Utility.profileToReactMap(Profile.getCurrentProfile()));
   }
 }
diff --git a/ios/ExpoAdapterFBSDKNext.podspec b/ios/ExpoAdapterFBSDKNext.podspec
index c518a9754bc481aabe2b951f814b376034838e69..c3a2619958460d77240ea64df80f69a2f7335b86 100644
--- a/ios/ExpoAdapterFBSDKNext.podspec
+++ b/ios/ExpoAdapterFBSDKNext.podspec
@@ -10,7 +10,7 @@ Pod::Spec.new do |s|
   s.license        = package['license']
   s.author         = package['author']
   s.homepage       = package['homepage']
-  s.platform       = :ios, '12.0'
+  s.platform       = :ios, '13.0'
   s.swift_version  = '5.4'
   s.source         = { :git => 'https://github.com/thebergamo/react-native-fbsdk-next.git', :tag => "v#{package['version']}" }
   s.static_framework = true
```

**Comment by mikehardy** [comment]
> I would happily merge + release any reasonable PR

**Comment by evelant** [comment]
@mikehardy I'd love to make one but I've been really swamped and haven't had time to fully investigate a solution that I'd be comfortable releasing given my limited java/kotlin/android experience.  For now reverting the behavior works for me but I'm assuming others probably rely upon the newer behavior.

**Comment by mikehardy** [comment]
> I'd love to make one but I've been really swamped

As are we all. Then it will sit until someone with enough at stake is motivated to contribute

**Comment by OscarBC** [comment]
I wasn't able to get the profile through this package, however with the access_token you can query the open graph fb api and you can retrieve the profile information + email (on android) it works.

```
AccessToken.getCurrentAccessToken().then(
          async (data) => {
            const token = data?.accessToken;
            const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
            const { id, first_name, last_name, email } = await response.json();
          }
        );

```

**Comment by lancyrosy** [comment]
> I wasn't able to get the profile through this package, however with the access_token you can query the open graph fb api and you can retrieve the profile information + email (on android) it works.
> 
> ```
> AccessToken.getCurrentAccessToken().then(
>           async (data) => {
>             const token = data?.accessToken;
>             const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
>             const { id, first_name, last_name, email } = await response.json();
>           }
>         );
> ```

Cool It works for getting user's name. Is there any way to get user avatar link using accesstoken?

**Comment by OscarBC** [comment]
> > I wasn't able to get the profile through this package, however with the access_token you can query the open graph fb api and you can retrieve the profile information + email (on android) it works.
> > ```
> > AccessToken.getCurrentAccessToken().then(
> >           async (data) => {
> >             const token = data?.accessToken;
> >             const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
> >             const { id, first_name, last_name, email } = await response.json();
> >           }
> >         );
> > ```
> 
> Cool It works for getting user's name. Is there any way to get user avatar link using accesstoken?

https://developers.facebook.com/docs/graph-api/reference/user/ 

I guess it's "picture"

**Comment by SMKH-PRO** [comment]
I am facing this issue in 11.2.1

**Comment by smitroshin** [comment]
> I wasn't able to get the profile through this package, however with the access_token you can query the open graph fb api and you can retrieve the profile information + email (on android) it works.
> 
> ```
> AccessToken.getCurrentAccessToken().then(
>           async (data) => {
>             const token = data?.accessToken;
>             const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
>             const { id, first_name, last_name, email } = await response.json();
>           }
>         );
> ```

It also works using [GraphAPI](Settings.initializeSDK();) from this library.

```ts
new GraphRequestManager()
  .addRequest(
    new GraphRequest("/me", undefined, (error, result) => {
      if (error) {
        console.log("Error fetching data: ", error)
      } else {
        console.log("Success fetching data: ", result)
      }
    }),
  )
  .start()
```

But you need to be sure you have SDK initialized before using this API.
For me, worked adding lines below in the main App.tsx file.

```ts
import { Settings } from "react-native-fbsdk-next"

Settings.initializeSDK()
```
