### ISSUE TITLE
firebase crashlytics report:  FBSDKSKAdNetworkReporter (After version of ATT)

### ISSUE THREAD

**Issue by cnhsttyle** [thebergamo/react-native-fbsdk-next#32]
After version of react-native-tracking-transparency (ATT) applied
Firebase Crashlytics reports crashes, such as attached images.
(FBSDKSKAdNetworkReporter.m line 92 / Fatal Exception: NSInvalidArgumentException)

<img width="802" alt="firebase_crash" src="https://user-images.githubusercontent.com/15974698/117618498-fd772c80-b1a8-11eb-8949-4e998f635b68.png">

I am currently using react-native-fbsdk-next. (FB SDK >= 9)
What should I do to fix the problem?
Thank you.

**Comment by thebergamo** [comment]
Hi thanks for opening this issue, but to be honest only based in this image is quite hard to guess the issue/solution.

Would you be able to provide a minimum project that reproduces this error?

**Comment by cnhsttyle** [comment]
> Hi thanks for opening this issue, but to be honest only based in this image is quite hard to guess the issue/solution.
> 
> Would you be able to provide a minimum project that reproduces this error?

Sorry.
The version currently reporting crash was react-native-fbsdk 3.0.0.
Maybe the problem is because it is not the latest version?

<img width="830" alt="firebase" src="https://user-images.githubusercontent.com/15974698/117752034-0faca580-b251-11eb-8a34-fb6215db1ac1.png">

<img width="804" alt="adNetwork_52_90" src="https://user-images.githubusercontent.com/15974698/117752047-1509f000-b251-11eb-9072-7b89a459d257.png">


<img width="1148" alt="appEvents_1173" src="https://user-images.githubusercontent.com/15974698/117752063-19cea400-b251-11eb-85a4-4c0f45912b43.png">


<img width="646" alt="appEvents_450" src="https://user-images.githubusercontent.com/15974698/117752064-1a673a80-b251-11eb-9c77-e14867e2b111.png">

**Comment by cnhsttyle** [comment]
Yes, thank you.
I will try again after updating to the latest version.
