### ISSUE TITLE
App Crash when open and give error below

### ISSUE THREAD

**Issue by kushalshrestha2053** [thebergamo/react-native-fbsdk-next#328]
dyld[74666]: Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit
  Referenced from: <5D1C46D6-7782-3715-B701-F0E94ABDD9A8> /Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/ozzyTicketBooking
  Reason: tried: '/Users/mac/Library/Developer/Xcode/DerivedData/ozzyTicketBooking-bcpgbbhshajsgwccdulwhdtyceea/Build/Products/Debug-iphonesimulator/FBAEMKit.framework/FBAEMKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2)
Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit
  Referenced from: <5D1C46D6-7782-3715-B701-F0E94ABDD9A8> /Users/mac/Library/Developer/CoreSimulator/Devices/2BFB1004-1867-484E-9C7D-09BD0ADC6167/data/Containers/Bundle/Application/9E2F1E54-C800-4DCC-84DE-DA05F6E70D11/ozzyTicketBooking.app/ozzyTicketBooking
  Reason: tried: '/Users/mac/Library/Developer/Xcode/DerivedData/ozzyTicketBooking-bcpgbbhshajsgwccdulwhdtyceea/Build/Products/Debug-iphonesimulator/FBAEMKit.framework/FBAEMKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/
dyld config: DYLD_SHARED_CACHE_DIR=/Users/mac/Library/Developer/CoreSimulator/Caches/dyld/21G83/com.apple.CoreSimulator.SimRuntime.iOS-16-0.20A360 DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/ozzyTicketBooking-bcpgbbhshajsgwccdulwhdtyceea/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/ozzyTicketBooking-bcpgbbhshajsgwccdulwhdtyceea/Build/Products/Debug-iphonesimulator DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib
(lldb)

**Comment by kr396** [comment]
same issue

**Comment by mikehardy** [comment]
That is an unreadable wall of unformatted text, wow!

https://github.com/thebergamo/react-native-fbsdk-next/issues?q=is%3Aissue+dyld+

duplicate #324 - upstream issue

I'll reopen that one though
