### ISSUE TITLE
Expo plugin breaks auto-verification of Android deep linking

### ISSUE THREAD

**Issue by Wituz** [thebergamo/react-native-fbsdk-next#329]
## 🐛 Bug Report
   When the expo plugin injects a data tag into the auto-verify Intent in AndroidManifest.xml, it no longer verifies the given domain and it is disabled by default when the app is installed. 

  These lines are responsible (plugin/withFacebookAndroid.ts):
  ```typescript
  if (scheme && !hasScheme(scheme, androidManifest)) {
      androidManifest = appendScheme(scheme, androidManifest);
  }
  ``` 
  
  If I remove them, my deep linking verifies the domain once again.
  I therefore right now run with my own fork: https://github.com/Wituz/react-native-fbsdk-next
  
  Not sure what these lines are meant to do, or what that data tag does, but for my usage (just app events) it seems to work just fine without it. Maybe someone can comment on what injecting that data tag is supposed to do. 

## To Reproduce
Set up deep linking in `app.json` for Android
```json
"intentFilters": [
  {
    "action": "VIEW",
    "autoVerify": true,
    "data": [
      {
        "scheme": "https",
        "host": "your-domain.com",
        "pathPrefix": "/"
      }
    ],
    "category": [
      "BROWSABLE",
      "DEFAULT"
    ]
  }
],
```

Correctly put a `assetlinks.json` on `your-domain.com/.well-known/assetlinks.json`.

Apply the react-native-fbsdk-next plugin in `app.json`

```json
[
  "react-native-fbsdk-next",
  {
    "appID": "...",
    "clientToken": "...",
    "displayName": "...",
    "advertiserIDCollectionEnabled": true,
    "autoLogAppEventsEnabled": true,
    "isAutoInitEnabled": true,
    "iosUserTrackingPermission": "..."
  }
],
```

Build and install an APK, filter logcat output for domain verification - there is none. 
But if I remove the line generating the data tag, it works. 

## Expected Behavior
The domain is supposed to be verified on app install

## Workaround
  These lines are responsible (plugin/withFacebookAndroid.ts):
  ```typescript
  if (scheme && !hasScheme(scheme, androidManifest)) {
      androidManifest = appendScheme(scheme, androidManifest);
  }
  ``` 
  
  If I remove them, my deep linking verifies the domain once again.
  I therefore right now run with my own fork: https://github.com/Wituz/react-native-fbsdk-next

## What do
I know Expo support in this project is community-driven in this project, so I'm down to attempt to fix this in the main repo. 
I'm just not sure what those lines I remove do for the project, and how to make a proper pull request for it. 
But none the less here is a workaround for those in trouble. 

## Environment
```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 95.89 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    expo: 46.0.16
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6
```

**Comment by mikehardy** [comment]
Hmm :thinking: - my goto for that would be to check git blame on the file and contact the previous author:

https://github.com/thebergamo/react-native-fbsdk-next/blame/master/plugin/src/withFacebookAndroid.ts#L209-L225

Looks to be from @giautm - perhaps they know why those lines are important or why they would cause this problem for you?

> I know Expo support in this project is community-driven in this project, so I'm down to attempt to fix this in the main repo.

This is sincerely appreciated :heart: - I do my best here but can only really support what I run. Always happy to try to get fixes in if anyone posts them up. Hopefully we can get something working here

**Comment by nakedgun** [comment]
Principally related to this bug: https://github.com/expo/expo/issues/19745 . 

That Facebook entry does not belong in the auto verification section of `AndroidManifest.xml`. There's a _workaround_ plugin in that case which I've modified to handle this bug too. It will remove any non 'http' or 'https' entries in the intent filters which are set to `autoVerify=true`. That means the erroneous Facebook entry added by this plugin is removed.

1. Add it to `plugins/withAndroidVerifiedLinksWorkaround.js`
2. In your expo plugins, add ` "./plugins/withAndroidVerifiedLinksWorkaround"` **above** `react-native-fbsdk-next` (expo seems to run plugins in reverse order - so for this to remove the Facebook entry, it must be run after).

<details closed>
<summary>withAndroidVerifiedLinksWorkaround.js</summary>
<br>

```
const {
  createRunOncePlugin,
  withAndroidManifest,
} = require('@expo/config-plugins');

/**
 * @typedef {import('@expo/config-plugins').ConfigPlugin} ConfigPlugin
 * @typedef {import('@expo/config-plugins').AndroidManifest} AndroidManifest
 */

/**
 * Remove any non 'http' or 'https' entries in the intent filters which are set to `autoVerify=true`.
 *
 * This stops some plugins like the expo-dev-client and react-native-fbsdk-next adding their own custom schemes which break auto verification.
 *
 * See: https://github.com/expo/expo/issues/19745 and https://github.com/thebergamo/react-native-fbsdk-next/issues/329
 *
 * Important: Expo seems to run plugins in the reverse order that they are listed in your config. So place this plugin
 * at the top of your plugin config so it runs last.
 *
 * @type {ConfigPlugin}
 */
const withAndroidVerifiedLinksWorkaround = (config) =>
  withAndroidManifest(config, (config) => {
    config.modResults = removeInvalidIntentFiltersFromIntentFilters(
      config.modResults
    );
    return config;
  });

/**
 * Iterate over all `autoVerify=true` intent filters and only keep ones which begin
 * with 'http' or 'https'.
 *
 * @param {AndroidManifest} androidManifest
 */
function removeInvalidIntentFiltersFromIntentFilters(androidManifest) {
  for (const application of androidManifest.manifest.application || []) {
    for (const activity of application.activity || []) {
      if (activityHasSingleTaskLaunchMode(activity)) {
        for (const intentFilter of activity['intent-filter'] || []) {
          if (
            intentFilterHasAutoVerification(intentFilter) &&
            intentFilter?.data
          ) {
            intentFilter.data = intentFilterRemoveSchemeFromData(
              intentFilter,
              (scheme) =>
                !scheme?.startsWith('https') || !scheme?.startsWith('http')
            );
          }
        }
        break;
      }
    }
  }

  return androidManifest;
}

/**
 * Determine if the activity should contain the intent filters to clean.
 *
 */
function activityHasSingleTaskLaunchMode(activity) {
  return activity?.$?.['android:launchMode'] === 'singleTask';
}

/**
 * Determine if the intent filter has `autoVerify=true`.
 */
function intentFilterHasAutoVerification(intentFilter) {
  return intentFilter?.$?.['android:autoVerify'] === 'true';
}

/**
 * Remove schemes from the intent filter that matches the function.
 */
function intentFilterRemoveSchemeFromData(intentFilter, schemeMatcher) {
  return intentFilter?.data?.filter(
    (entry) => !schemeMatcher(entry?.$['android:scheme'] || '')
  );
}

module.exports = createRunOncePlugin(
  withAndroidVerifiedLinksWorkaround,
  'withAndroidVerifiedLinksWorkaround',
  '1.0.0'
);
```
</details>

**Comment by mikehardy** [comment]
So, is there a PR needed for the plugin in this repo? Happy to merge + release a PR if one is proposed

**Comment by giautm** [comment]
Hey, sorry for the delay. I missed the notification until now.

Look like the issue come from the up-stream SDK. So, we have to use the workaround until Expo fixed their plugin. I also saw another PR merged in a few days ago. Can we verify the issue again with SDKv47?

**Comment by nakedgun** [comment]
@mikehardy @giautm There is this expo [pull request](https://github.com/expo/expo/pull/18963) but it only refers to removing the `exp+` scheme from Android autoVerification intents. So as far as I can tell it wouldn't fix this bug or any other plugin which uses the same approach of updating the manifest.

**Comment by giautm** [comment]
```js
if (scheme && !hasScheme(scheme, androidManifest)) {
    androidManifest = appendScheme(scheme, androidManifest);
}
```

Those lines were intended for support of Facebook login SDK. Step 5 of the document here: https://developers.facebook.com/docs/facebook-login/android/

**Comment by ttrebicki** [comment]
@giautm I Think these lines of code should not append the scheme to the autoVerify list, FB login works in my app if I remove the scheme from there. I think it should just be appended to the one that includes custom app schemes, or just another intent filter, without the autoVerify set to "true".

**Comment by clevadani** [comment]
This is still happening on my app despite adding the plugin.

**Comment by enpi** [comment]
Same here, any update on this issue?

**Comment by pedropedruzzi** [comment]
I believe we no longer need to set this up in the RN/expo layer. Quoting from [FB login doc](https://developers.facebook.com/docs/facebook-login/android/):
>If you use version 5.15 or later of the Facebook SDK for Android, you don't need to to add an activity or intent filter for Chrome Custom Tabs. This functionality is included in the SDK.

I confirm the CustomTabActivity activity and intent filter are added to my manifest (although they no longer use the scheme with "fb" followed by the appId). I think we should just get rid of this appendScheme stuff to fix the issue. It doesn't make sense to add the fb scheme to existing intent filters of existing activities anyway.

BTW, for a cleaner workaround, just add the data bellow to android.intentFilters array on your [expo app config](https://docs.expo.dev/versions/latest/config/app/#intentfilters). This package won't touch intent filters in this case.

```
{
    "action": "VIEW",
    "category": ["BROWSABLE", "DEFAULT"],
    "data": { "scheme": "fb<YOUR_APP_ID_GOES_HERE>" }
}
```

**Comment by MateuszRostkowski** [comment]
Hi, I have manage to solve this issue removing the fb scheme from auto verify intend, [using this solution](https://github.com/expo/expo/issues/19745).

I've added this plugin:

<details>
  <summary>plugins/withAndroidVerifiedLinksWorkaround.js</summary>
  
```js
const { createRunOncePlugin, withAndroidManifest } = require('@expo/config-plugins');

/**
 * @typedef {import('@expo/config-plugins').ConfigPlugin} ConfigPlugin
 * @typedef {import('@expo/config-plugins').AndroidManifest} AndroidManifest
 */

/**
 * Remove the custom Expo dev client scheme from intent filters, which are set to `autoVerify=true`.
 * The custom scheme `<data android:scheme="exp+<slug>"/>` seems to block verification for these intent filters.
 * This plugin makes sure there is no scheme in the autoVerify intent filters, that starts with `exp+`.
 * 
 * @type {ConfigPlugin}
 */
const withAndroidVerfiedLinksWorkaround = (config) => (
  withAndroidManifest(config, (config) => {
    config.modResults = removeExpoSchemaFromVerifiedIntentFilters(config.modResults);
    return config;
  })
);

/**
 * Iterate over all `autoVerify=true` intent filters, and pull out schemes starting with `exp+`.
 * 
 * @param {AndroidManifest} androidManifest
 */
function removeExpoSchemaFromVerifiedIntentFilters(androidManifest) {
  // see: https://github.com/expo/expo-cli/blob/f1624c75b52cc1c4f99354ec4021494e0eff74aa/packages/config-plugins/src/android/Scheme.ts#L164-L179
  for (const application of androidManifest.manifest.application || []) {
    for (const activity of application.activity || []) {
      if (activityHasSingleTaskLaunchMode(activity)) {
        for (const intentFilter of activity['intent-filter'] || []) {
          if (intentFilterHasAutoVerification(intentFilter) && intentFilter?.data) {
            intentFilter.data = intentFilterRemoveSchemeFromData(intentFilter, (scheme) => scheme?.startsWith('fb'));
          }
        }
        break;
      }
    }
  }

  return androidManifest;
}

/**
 * Determine if the activity should contain the intent filters to clean.
 * 
 * @see https://github.com/expo/expo-cli/blob/f1624c75b52cc1c4f99354ec4021494e0eff74aa/packages/config-plugins/src/android/Scheme.ts#L166
 */
function activityHasSingleTaskLaunchMode(activity) {
  return activity?.$?.['android:launchMode'] === 'singleTask';
}

/**
 * Determine if the intent filter has `autoVerify=true`.
 */
function intentFilterHasAutoVerification(intentFilter) {
  return intentFilter?.$?.['android:autoVerify'] === 'true';
}

/**
 * Remove schemes from the intent filter that matches the function.
 */
function intentFilterRemoveSchemeFromData(intentFilter, schemeMatcher) {
  return intentFilter?.data?.filter(entry => !schemeMatcher(entry?.$['android:scheme'] || ''));
}

module.exports = createRunOncePlugin(withAndroidVerfiedLinksWorkaround, 'withAndroidVerfiedLinksWorkaround', '1.0.0');
```
</details>


And  then I've updated app.json / app.config.ts (it's important to first add the plugin above and then this package plugin), like this:
```json
{
  "expo": {
    ...
    "plugins": [
      ...
      "./plugins/withAndroidVerifiedLinksWorkaround", // THIS SHOULD BE FIRST
      [
        "react-native-fbsdk-next",
        {
          "appID": "xxx",
          "clientToken": "xxx",
          "displayName": "NAME",
          "scheme": "fbXXXXX",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": true,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "Permission text"
        }
      ]
    ]
  }
}
```

@mikehardy 
I don't know what do you think but maybe it's good to modify the plugin of this package and additional plugin will not be needed. (Maybe I will find some free time to do this)

**Comment by islamashraful** [comment]
This issue is still relevant with the expo 50. Spent really long time to find out which config/package was causing the issue. 

The workaround provided by @MateuszRostkowski works. Thanks
