### ISSUE TITLE
[iOS] "FBAEMKit does not contain bitcode" error on Expo EAS Build

### ISSUE THREAD

**Issue by vonkanehoffen** [thebergamo/react-native-fbsdk-next#331]
## 🐛 Bug Report

I have a managed Expo project on SDK 46. With `"react-native-fbsdk-next": "^11.0.0"`. When I run

```
eas build --profile production --platform ios
```
 I get this error:
```
[RUN_FASTLANE]
❌  ld: '/Users/___/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBAEMKit/FBAEMKit.framework/FBAEMKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/___/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBAEMKit/FBAEMKit.framework/FBAEMKit' for architecture arm64
```

If I downgrade the package to `10.1.0` everything is fine.
Also if I build with `"developmentClient": true, "distribution": "internal"` everything's fine too (on `11.0.0`).

The only special config I have that I guess could make a difference is the custom plugin from https://github.com/thebergamo/react-native-fbsdk-next/issues/323#issuecomment-1274647385 that solves an android build issue. ...but I can't really see it influencing this right?

I also see this when running `expo doctor`
```
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
```
and I notice 4.1.5 is a dependency of `react-native-fbsdk-next` .... could that be the problem? I tried
```
"resolutions": {
  "@expo/config-plugins": "5.0.1"
},
```
which cleared the `expo doctor` warning, but still didn't solve the main issue.

Has anyone else seen this or got any ideas? I've got no clue what I'm doing with `FBAEMKit` and all that side of things 😅 

## Environment

```
npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.6.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.0 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      eas-cli: 2.4.1
      expo-cli: 6.0.6
    Expo Workflow: managed
```

**Comment by mikehardy** [comment]
bitcode is dead, as a technology need, is no longer supported by Apple/Xcode, and should be disabled everywhere 

https://stackoverflow.com/questions/72543728/xcode-14-deprecates-bitcode-but-why

So the solution is to figure out how to disable bitcode globally in Expo however you do that with Expo

If it were vanilla react-native I'd throw a disable chunk in the Podfile (and in fact have this in my Podfile as a postinstall):

https://github.com/invertase/react-native-firebase/issues/6397#issuecomment-1187680556

I believe this is a project-specific build issue at that point then (because, bitcode is not going to come back / the upstream libraries will not be rebuilt with bitcode...) so I'm going to close this as not actionable / nothing more can be done

**Comment by appsgenie** [comment]
@vonkanehoffen where you able to get it to work on Expo? I am running into the same issue with EAS and not sure how to change that ENABLE_BITCODE setting..

**Comment by vonkanehoffen** [comment]
Ah thanks so much for the tip @mikehardy ! 🤩 I found out, thanks to this issue: https://github.com/expo/expo-cli/issues/4253 you can disable bitcode in Expo/EAS managed builds with
```
"expo": {
  "ios": {
    "bitcode": "Debug"
  }
}
```
in `app.json` @appsgenie . I have a working build now on my `--local` and cloud EAS :-) 

(after writing this issue I found only my local EAS builds were passing with the downgraded version but cloud ones were failing with `CocoaPods could not find compatible versions for pod "FBSDKCoreKit":` ) 

All sorted now hopefully...presuming the app store doesn't have a problem

**Comment by mikehardy** [comment]
If anyone wants to hit the "edit" button at the top of whatever documentation explains how to install and includes Expo instructions to add this note, you will be doing your fellow Expo developers a favor, and decreasing issue traffic load here which does me a huge favor...

**Comment by appsgenie** [comment]
yes sorry for the traffic. I posted about this to the Expo's Discord channel but from what I've seen they want information related to setting up an external package with Expo to be there in that specific package's repo. So I assume we can gather our finding and put them here if you don't mind. Willing to contribute with what has worked for me so far. I am also about to submit this to Apple and if that passes, we know it worked for iOS. As for Android, it's still TBD on my site, unless @vonkanehoffen you are able to get it to build and into the Play Store with the latest v11.

**Comment by nickmacavoy** [comment]
Just leaving my experience of solving this.

Using Expo `46.0.16` and react-native-fbsdk-next `11.0.1`, I've been struggling to get past building iOS locally (`eas build --profile development --platform ios --local`) and with Expo servers (`eas build --profile development --platform ios`), with and without the `app.config.js` ios bitcode setting. What's finally worked for me is the below. I wish I could explain how it works but now it's working i'll move on.

Thanks for all your work @mikehardy 🤙

```
"expo": {
  "ios": {
    "bitcode": "No"
  }
}
```

**Comment by appsgenie** [comment]
@nickmacavoy is 'No' a valid value for bitcode? 
with SDK 46 I was able to build fine with bitcode=Debug, but now on SDK 47 not sure as I am getting this error but I think it's a different package..
