### ISSUE TITLE
Event id parameter?

### ISSUE THREAD

**Issue by lifwanian** [thebergamo/react-native-fbsdk-next#332]
I'd like to send the `event_id` parameter via `logEvent()` but I can't find any documentation on what the parameter should be, i.e. `eventID`, `_eventId`, `event_id`. I've seen each of these mentioned, wondering if one of these can be used.

Looking at the link below, it seems like the correct one is `eventID`, but wondering if anyone could confirm, since the format is different.

https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/server-event#event-id

**Comment by mikehardy** [comment]
I would ask upstream in facebook-android-sdk or facebook-ios-sdk if possible - I don't know off the top of my head and I'm not aware of others answering things regularly here

**Comment by lifwanian** [comment]
Thanks, was able to figure it out using "Test Events". The parameter to use is `_eventID `

<img width="343" alt="Screen Shot 2022-10-19 at 2 23 46 PM" src="https://user-images.githubusercontent.com/3913873/196773768-25f8b096-f15b-4c2c-9429-8509db1d3d29.png">

**Comment by Mykyta-Chernenko** [comment]
> Thanks, was able to figure it out using "Test Events". The parameter to use is `_eventID `
> 
> <img alt="Screen Shot 2022-10-19 at 2 23 46 PM" width="343" src="https://user-images.githubusercontent.com/3913873/196773768-25f8b096-f15b-4c2c-9429-8509db1d3d29.png">

I used _eventID as well, but it doesn't seem to show in the Event ID column in the Test Events, so do not think it matches the events with the Convertions API in this case, while for the web it works with eventID

what did you end up with if you remember? thanks!

**Comment by sagarpaliwal-12** [comment]
Hey! @Mykyta-Chernenko 
Were you able to identify which parameter is directly linked to the Event ID column? I’ve already tried multiple variations -_eventId, _eventID, custom_event_id, eventId, eventID, and others. Additionally, I attempted sending event_id, but it didn’t even show up under the parameters.
