### ISSUE TITLE
null is not an object (evaluating `'Settings.initializeSDK'`)

### ISSUE THREAD

**Issue by sankparatkar** [thebergamo/react-native-fbsdk-next#333]
I am trying to integrate facebook sdk into my react native app with a goal of optimizing app installs through the fb ads.

I followed all the steps mentioned here

https://www.npmjs.com/package/react-native-fbsdk-next
https://developers.facebook.com/quickstarts/487102509986353/?platform=android

But while trying to initialise sdk via `Settings.initializeSDK() `( as mentioned in the usage section) getting the following error. null is not an object (evaluating `'Settings.initializeSDK'`) in the native android build.

What is going wrong? Also, do we need to use Settings.initializeSDK() for fb to track app installs?

## To Reproduce
```
import { Settings } from 'react-native-fbsdk-next';

 Settings.initializeSDK();
```

## Environment
Expo Bare Workflow
React version : "0.64.3"
Android Build

**Comment by mikehardy** [comment]
Hi there!

Not sure why you would base on react-native 0.64, that's too old to support really. Probably not directly related to this problem, but I would upgrade.

If you *ever* see an error "null is not an object" when evaluating something that is likely a native module, you probably have not installed things correctly or built them, such that the native object is not present + available in the native app.

I suggest you create a new clean / throwaway app following the instructions to see that it works.

We do that in this script here and it works: https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

So this will likely be project-specific and no further action is possible in this repo
