### ISSUE TITLE
Facebook login from embedded browser error 

### ISSUE THREAD

**Issue by ibrahim-musa** [thebergamo/react-native-fbsdk-next#334]
## 🐛 Bug Report
I'm planning to integrate my app using Facebook login. But on some Android phone, when `LoginManager.logInWithPermissions` function is called, it often opening a Facebook Login page while the device is actually already had Facebook app installed and already in a logged in state. Even after I trying to log in using by email and password, it still won't let the user to log in. It show **_For your account security, logging into Facebook from an embedded browser is disabled_**.
(**_see attached video below_**)

I already set the LoginBehaviour to `LoginManager.setLoginBehavior('NATIVE_WITH_FALLBACK')` and the device already had native Facebook app installed and the Facebook app is also already in logged in state.

## To Reproduce
Here's the code I use to login to Facebook
```
LoginManager.setLoginBehavior('NATIVE_WITH_FALLBACK');
LoginManager.logInWithPermissions(["ads_management", "pages_manage_ads", "leads_retrieval", "pages_manage_metadata", "pages_read_engagement"]);
```

## Expected Behaviour
It should open a Facebook app with the current logged in state.

## Environment
React Native version : `0.65.2`
react-native-fbsdk-next version: `10.1.0`
Android device used: `Samsung Galaxy Note 20 Ultra`
Android version: `12`
Facebook app installed version: `389.0.0.42.111`

https://user-images.githubusercontent.com/47311555/197615710-db018481-cf4c-4351-956c-8f2c0b2d81b0.mp4

**Comment by mikehardy** [comment]
Upstream: https://github.com/facebook/facebook-android-sdk/issues?q=is%3Aissue++for+your+account+security+logging+into+facebook+from+an+embedded+browser+is+disabled

**Comment by ibrahim-musa** [comment]
@mikehardy Hi Mike, thank you for the response. This issue is happened only to some device sometimes. Do you had any idea why it failed to login while I already had the Facebook app installed (and logged it) and I don't set the `LoginBehaviour` to using webview?

From the video that user sent to me (attached above) it's also look like it open a Facebook app instead of Chrome custom tab (it didn't show X button on top left) or a webview (it didn't show as a dialog). Why the app still think it logged in an embedded browser?

**Comment by mikehardy** [comment]
I'm sorry, I don't know. This might be something to approach the facebook-android-sdk team with, bearing in mind that they are a *native* SDK, not a react-native SDK, so you should be familiar with the way the module here uses the SDK API calls

https://github.com/thebergamo/react-native-fbsdk-next/blob/3ec1bd3d4512f1cf4aceb23c59724f4d1d17d4c5/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java#L139-L163

**Comment by ibrahim-musa** [comment]
@mikehardy okay, I'll try asking on the `facebook-android-sdk` github page. Thank you Mike. Really appreciate your help and quick responses. 🙏🏼

**Comment by bradjones1** [comment]
@ibrahim-musa Did you ever get to the bottom of this behavior?

> From the video that user sent to me (attached above) it's also look like it open a Facebook app instead of Chrome custom tab (it didn't show X button on top left) or a webview (it didn't show as a dialog). Why the app still think it logged in an embedded browser?

I am able to recreate this myself; the Facebook native app is handling auth, however it is still complaining about the webview. Doesn't seem, then, like something that this SDK can do much about. [This comment](https://github.com/facebook/facebook-android-sdk/issues/1012#issuecomment-952832235) seems to imply that the issue is with Firefox (my default mobile browser) but AFAICT Firefox isn't being used by the Firefox app to handle the login.

Curious if you ever were able to figure this one out.

**Comment by skizzo** [comment]
May I ask why this issue is closed? I can't get Facebook Login to work on Android no matter what.. Thanks for any hints
