### ISSUE TITLE
FBAEMKit.framework/FBAEMKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

### ISSUE THREAD

**Issue by radekzz** [thebergamo/react-native-fbsdk-next#338]
**Actual result**
While archiving, build fail on this error:
`FBAEMKit.framework/FBAEMKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.`

**Expected result**
Been able to make an archive. Keep settings `ENABLE_BITCODE = YES`

**Comment by AndrewKirkovski** [comment]
Just got same issue

**Comment by mikehardy** [comment]
please search first: https://github.com/thebergamo/react-native-fbsdk-next/issues?q=is%3Aissue+bitcode

**Comment by radekzz** [comment]
Sorry @mikehardy but I didn't find any mention of bitcode issue here.

**Comment by mikehardy** [comment]
https://github.com/thebergamo/react-native-fbsdk-next/issues?q=is%3Aissue+bitcode

Shows

https://github.com/thebergamo/react-native-fbsdk-next/issues/331

https://github.com/thebergamo/react-native-fbsdk-next/issues/331#issuecomment-1284360816

https://github.com/invertase/react-native-firebase/issues/6397#issuecomment-1187680556

**Comment by radekzz** [comment]
Thank you, that explains everything.

**Comment by ThushalIntervest** [comment]
```
/BuildProductsPath/ReleaseDev-iphoneos/BVLinearGradient/libBVLinearGradient.a(BVLinearGradientManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file /Developer/Xcode/DerivedData/Wapp-bbautvtezqgnpccvinrtnmgvcejs/Build/Intermediates.noindex/ArchiveIntermediates/BuildProductsPath/ReleaseDev-iphoneos/BVLinearGradient/libBVLinearGradient.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have also gotten this error. Can someone please tell me how to fix this error?

**Comment by radekzz** [comment]
> ```
> /BuildProductsPath/ReleaseDev-iphoneos/BVLinearGradient/libBVLinearGradient.a(BVLinearGradientManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file /Developer/Xcode/DerivedData/Wapp-bbautvtezqgnpccvinrtnmgvcejs/Build/Intermediates.noindex/ArchiveIntermediates/BuildProductsPath/ReleaseDev-iphoneos/BVLinearGradient/libBVLinearGradient.a' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> I have also gotten this error. Can someone please tell me how to fix this error?

You have to disable bitcode in your xcode

**Comment by AndrewKirkovski** [comment]
I'll just add details to this ticket, so nobody need to follow 2 links to understand if disabling bitcode is safe:

Bitcode is deprecated by Apple. It used to be needed to cross-architecture builds, now we only need arm 64 build, so we can safely disable bitcode

See detailed explanation here https://stackoverflow.com/questions/72543728/xcode-14-deprecates-bitcode-but-why

**Comment by ramyareye** [comment]
in our case local was fine, bitrise had error so we changed xcode version from 13 to 14 and it worked!
