### ISSUE TITLE
Expo stuck on splashscreen after installing react-native-fbsdk-next

### ISSUE THREAD

**Issue by ls30378** [thebergamo/react-native-fbsdk-next#342]
## 🐛 Bug Report

After I installed react-native-fbsdk-next I did npx expo prebuild, I followed the steps to add app id and other stuff on android strings manifest, and on app.json for expo plugin, after that I builded with eas-cli, and now my app is stuck on splash screen, no error but just doesn't work anymore.

## To Reproduce

app.json
```
"plugins": [
      [
        "react-native-fbsdk-next",
        {
          "appID": " MY APP ID",
          "clientToken": " MY CLIENT TOKEN",
          "displayName": "RN SDK Demo",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": false,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "This identifier will be used to deliver personalized ads to you."
        }
      ]
    ]
```
also modified strings.xml and AndroidManifest.xml following official meta guide
## Expected Behavior

I didn't implement anything in js files, so I expected the app to continue working as it was before. 
## Code Example

Didn't implement anything in js files so no need for expo snack.

## Environment

```
System:
    OS: Linux 6.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.41 GB / 7.57 GB
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.9.0/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by AnimusAudax** [comment]
i had same error with expo-facebook, now trying to replace it with fbsdk next, but not sure about how to set parameters, are You sure about variable names in JSON?

**Comment by ls30378** [comment]
> i had same error with expo-facebook, now trying to replace it with fbsdk next, but not sure about how to set parameters, are You sure about variable names in JSON?

I refered to this:
https://www.npmjs.com/package/react-native-fbsdk-next
Go to Expo Install section and you can find instructions about properties of plugin in app.json

**Comment by AnimusAudax** [comment]
@ls30378 thank You, i was reading there, but it seems, that this page was way too long and I didn't tried search there.

now I am with this error instead:
Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference

Any luck on Your side?

**Comment by ls30378** [comment]
> @ls30378 thank You, i was reading there, but it seems, that this page was way too long and I didn't tried search there.
> 
> now I am with this error instead: Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference
> 
> Any luck on Your side?

No I'm stuck on splash screen :( Dont forget to prebuild and build the project after each time you modify app.json maybe that's the fix for your problem

**Comment by yousefamar** [comment]
@AnimusAudax I had your same `NullPointerException` — make sure to completely remove `expo-facebook` and related plugin config if you're migrating. That sorted it for me.

**Comment by ls30378** [comment]
> @AnimusAudax I had your same `NullPointerException` — make sure to completely remove `expo-facebook` and related plugin config if you're migrating. That sorted it for me.

did you experience any splash stuck in expo?

**Comment by yousefamar** [comment]
> did you experience any splash stuck in expo?

No, in my case it just crashed outright during the splash screen instead of being stuck. It might be that we had two separate issues.

For these kinds of issues, my immediate instinct is that it's a problem with a dependency that uses native non-expo code, but relies on a different version of an upstream dependency shared with other modules you have installed. In this case it was `expo-facebook`'s dependencies clashing, but what usually gets me out of this pickle is to try and upgrade everything (using [ncu](https://www.npmjs.com/package/npm-check-updates)) then downgrading anything that `expo doctor` says is too new. Also removing any dependencies you're no longer using.

When there are packages that haven't kept up with Expo SDK updates (e.g. say they're a year old with no updates) I try disabling them and see if the crash goes away. If it does, then I try to replace them with a different package that's better maintained.

Then to save yourself future pain, try to regularly keep everything up to date. Hope that helps!

**Comment by BrianIto** [comment]
I'm facing exactly the same issue in my Android Version after an Expo Doctor "downgrading" on some modules. 

What I really think it's happening is that my implementation on ```build.gradle``` is not working, but I don't know which version to use or something like that.

I was facing many problems before that, but it wasn't even compiling. This will be surely my last project on React Native, I'm migrating to full native after a life of problems with React Native. I know this is pretty personal and has nothing to do with the issue but I found this space to share my misery. haha

**Comment by samvoults** [comment]
I have the same error "Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference" if I only add :

import { Settings } from "react-native-fbsdk-next";

Settings.initializeSDK();

in my project. Also, I didn't have "expo-facebook" before in my project.

Any help pls?

**Comment by doctorrokter** [comment]
> @ls30378 thank You, i was reading there, but it seems, that this page was way too long and I didn't tried search there.
> 
> now I am with this error instead: Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference
> 
> Any luck on Your side?

Hello from 2023. I have the same problem. Did you solve it?

**Comment by jeonghoonkim** [comment]
> > @ls30378 thank You, i was reading there, but it seems, that this page was way too long and I didn't tried search there.
> > now I am with this error instead: Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference
> > Any luck on Your side?
> 
> Hello from 2023. I have the same problem. Did you solve it?

Did you put `<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>` in not `<activity>` level but `<application>`?

**Comment by doctorrokter** [comment]
> > > @ls30378 thank You, i was reading there, but it seems, that this page was way too long and I didn't tried search there.
> > > now I am with this error instead: Attempt to invoke virtual method 'void com.facebook.AccessTokenTracker.stopTracking()' on a null object reference
> > > Any luck on Your side?
> > 
> > 
> > Hello from 2023. I have the same problem. Did you solve it?
> 
> Did you put `<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>` in not `<activity>` level but `<application>`?

Yeah, I solved the problem. The issue was in absence of fb client token. I didn't want to hardcode it in code or app.json file, so, it comes from env var. And fb client token was empty because it was incorrectly injected to app during build time.

Anyways, thanks for help!
