### ISSUE TITLE
'ExpoModulesCore' has a minimum deployment target of iOS 13.0

### ISSUE THREAD

**Issue by rgbutov** [thebergamo/react-native-fbsdk-next#346]
expo project:
<img width="1694" alt="Screenshot 2022-11-08 at 8 07 28 PM" src="https://user-images.githubusercontent.com/7040394/200736245-bf503de2-3805-4034-b133-0686570d308d.png">

**Comment by mikehardy** [comment]
This issue is nearly content free https://stackoverflow.com/help/how-to-ask
I can only really decipher what you mean + want because of this #344 also existing
But that PR has issues, as described.
