### ISSUE TITLE
Unable to login with Facebook while on Testflight mode

### ISSUE THREAD

**Issue by edouardaihua** [thebergamo/react-native-fbsdk-next#347]
Hi guys,

First of all, thanks for the good job of working on this very useful library.

I've setup everything following your documentation but i can't make the Facebook login works while using TestFlight mode. Here is the error I got: "Feature Unavailable: Facebook Login is currently unavailable for this app, since we are updating additional details for this app. Please try again later."

I am sending the token returned to my website API that works properly when tested manually.

Is there anything i miss here ? Can you confirm this library is supposed to work in Testflight mode ?

Thanks

**Comment by mikehardy** [comment]
Works fine on TestFlight.

**Comment by Craques** [comment]
Is this maybe because the account is in development mode, have you taken  the facebook account live?

**Comment by mikehardy** [comment]
Some of my backends are in development mode, some are live. They all work in TestFlight.

**Comment by edouardaihua** [comment]
Facebook account is live but as the app has never been published yet . We are missing some info on Facebook side such as "Iphone Store ID" for Apple and we can't verify ownership for Android as "app-ads.txt" can't be validated before the app is published to Play Store. I assumed that we can't have Facebook login works for everyone until we got this.

**Comment by Punith-goud** [comment]
Hi @edouardaihua  did you fixed this?? I'm also facing the same in IOS, i have completed data checkup, and made app live in facebook console, but when i try to sign in im getting this error
