### ISSUE TITLE
Email Information is not being retrieved

### ISSUE THREAD

**Issue by Aayush19** [thebergamo/react-native-fbsdk-next#349]
In some cases, while trying to log in with facebook in android, Email is not getting retrieved. It returns email as null, but in some cases it returns the email.

On what grounds it decides to return email in response.
is there any resolution for this?

**Comment by mikehardy** [comment]
Hi there! Sorry, I have no idea - we're a pretty thin wrapper on facebook-android-sdk - you might search their issues list: https://github.com/facebook/facebook-android-sdk

**Comment by OscarBC** [comment]
Hi All! 
Unfortunately I wasn't able to get this working in Android, even with the patch mentioned [here](https://github.com/thebergamo/react-native-fbsdk-next/issues/318#issuecomment-1307506613).

However I made a workaround like this:

1) Get the current access token
2) Directly calling the opengraph api endpoint

It looks like this:


`AccessToken.getCurrentAccessToken().then(
          async (data) => {
            const token = data?.accessToken;
            const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
            const { id, first_name, last_name, email } = await response.json();
          }
        );
`

**Comment by silencie** [comment]
> 

This works fine on iOS standalone app but on Android it only works on dev mode. Did you make it work on Android standalone app ?

**Comment by silencie** [comment]
> Hi All!
> 
> Unfortunately I wasn't able to get this working in Android, even with the patch mentioned [here](https://github.com/thebergamo/react-native-fbsdk-next/issues/318#issuecomment-1307506613) (I'm using Expo).
> 
> However I made a workaround like this:
> 
> 1. Get the current access token
> 2. Directly calling the opengraph api endpoint
> 
> It looks like this:
> 
> ```
> AccessToken.getCurrentAccessToken().then(
>           async (data) => {
>             const token = data?.accessToken;
>             const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
>             const { id, first_name, last_name, email } = await response.json();
>           }
>         );
> ```

This works fine on iOS standalone app but on Android it only works on dev mode. Did you make it work on Android standalone app ?

**Comment by OscarBC** [comment]
> This works fine on iOS standalone app but on Android it only works on dev mode. Did you make it work on Android standalone app ?

I didn't had an issue

**Comment by putuoka** [comment]
> 

I try this and working but why this repo not adopt the solution to Java and bridge it to react native?

**Comment by putuoka** [comment]
> Hi All!
> 
> Unfortunately I wasn't able to get this working in Android, even with the patch mentioned [here](https://github.com/thebergamo/react-native-fbsdk-next/issues/318#issuecomment-1307506613) (I'm using Expo).
> 
> However I made a workaround like this:
> 
> 1. Get the current access token
> 2. Directly calling the opengraph api endpoint
> 
> It looks like this:
> 
> ```
> AccessToken.getCurrentAccessToken().then(
>           async (data) => {
>             const token = data?.accessToken;
>             const response = await fetch(`https://graph.facebook.com/me?fields=id,first_name,last_name,email&access_token=${token}`);
>             const { id, first_name, last_name, email } = await response.json();
>           }
>         );
> ```


I try this and working but why this repo not adopt the solution to Java and bridge it to react native?

**Comment by Ozaoujal** [comment]
> const { id, first_name, last_name, email } = await response.json();

This solution works for me, thank you
