### ISSUE TITLE
Can we get Authorization Code i.e response_type = code as per facebook doc? 

### ISSUE THREAD

**Issue by askynet** [thebergamo/react-native-fbsdk-next#35]
Hi,
Can we configure `response_type=code` to get authorization code?

**Comment by mikehardy** [comment]
Everyone should re-try with v6 of this library to see if it affects things, it has the up to date native libraries.
I'm going to close this as I'm not sure there is anything this module specifically can do other than stay up to date with native lib versions, but please feel free to continue sharing information on how best to use the available APIs / configurations

If this is a gap in this modules support for the underlying SDK capabilities please feel free to post a PR, we will happily merge it
