### ISSUE TITLE
Trouble building after installing react-native-fbsdk-next in managed Expo workflow

### ISSUE THREAD

**Issue by aaron-barbieriaghib** [thebergamo/react-native-fbsdk-next#353]
Hey, 

I was curious if anyone has seen this build error before (`CocoaPods could not find compatible versions for pod "ExpoAdapterFBSDKNext"`)? I looked through the Troubleshooting section in the docs, but I'm running with a managed Expo workflow, so a lot of the fixes don't apply. Happy to provide more details on request, just wasn't quite sure where to start.

```
[INSTALL_PODS] /private/var/folders/vr/0_c1zf616_v1lp8wcbhj7nmc0000gn/T/eas-build-local-nodejs/2d693dfe-232f-405b-bb32-4a8cb7fd611a/build/node_modules/react-native-fbsdk-next/react-native-fbsdk-next.podspec:4: warning: already initialized constant Pod::FBSDKVersion
[INSTALL_PODS] /private/var/folders/vr/0_c1zf616_v1lp8wcbhj7nmc0000gn/T/eas-build-local-nodejs/2d693dfe-232f-405b-bb32-4a8cb7fd611a/build/node_modules/react-native-fbsdk-next/react-native-fbsdk-next.podspec:4: warning: previous definition of FBSDKVersion was here
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "ExpoAdapterFBSDKNext":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     ExpoAdapterFBSDKNext (from `../../node_modules/react-native-fbsdk-next/ios`)
[INSTALL_PODS] 
[INSTALL_PODS] Specs satisfying the `ExpoAdapterFBSDKNext (from `../../node_modules/react-native-fbsdk-next/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by mikehardy** [comment]
> but they required a higher minimum deployment target

https://search.brave.com/search?q=but+they+required+a+higher+minimum+deployment+target+expo&source=desktop

So can you edit your Podfile and bump the target to match the new higher requirement that all the other Expo people asserted quite decisively needed to change in #346 / #352?

Or use Expo47 ?

**Comment by aaron-barbieriaghib** [comment]
Super appreciate the quick response @mikehardy! That did it :)

**Comment by mikehardy** [comment]
excellent, good luck on your project
