### ISSUE TITLE
initializeSDK() causes Invariant Violation

### ISSUE THREAD

**Issue by aaron-barbieriaghib** [thebergamo/react-native-fbsdk-next#354]
Hey all,

Calling `Settings.initializeSDK()` triggers an Invariant Violation in Expo go, but production + simulator builds seem fine. I have `appID`, `clientToken`, `displayName`, and `scheme` in my `app.json`, so I _think_ my config should be fine. I'm trying to track app installs – nothing fancy, so I assumed making `autoLogAppEventsEnabled` and `advertiserIDCollectionEnabled` true and manually initializing the sdk (since ios removed the autoInit option) would be sufficient. Commenting out the  `initializeSDK()` call fixes the Invariant violation. Installs don't seem to be tracked, so I'm wondering if this error is silently triggering in production.

## The actual error
```
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
```

## Things I've tried

1. deleting node modules, clearing yarn, metro, and expo caches
2. Upgrading/downgrading modules so `expo doctor` doesn't complain
3. moving the `initializeSDK` deeper in the app (I was pretty desperate by this point)

## Environment
"expo": "^47.0.0",
"react": "18.1.0",
"react-native": "0.70.5",
"react-native-fbsdk-next": "^11.1.0",

**Comment by mikehardy** [comment]
Expo Go does not contain most non-Expo native modules. That's a known limitation of Expo Go, explained clearly in it's documentation.

**Comment by aaron-barbieriaghib** [comment]
ah ok. i didn't realize it would cause app crash. I even stuck the call behind a `__DEV__` check but i guess that's not sufficient. Thanks anyway

**Comment by mikehardy** [comment]
read docs --> https://docs.expo.dev/bare/using-expo-client/#runtime-detection
