### ISSUE TITLE
Unable to track App Installs - Missing or Invalid Field in Promoted Objects

### ISSUE THREAD

**Issue by jessiealbarian** [thebergamo/react-native-fbsdk-next#355]
## 🐛 Bug Report
After adding react-native-fbsdk-next to our app, we are not seeing any activity or connection to Facebook. In the Facebook Ads Manager, when creating an Ad Set I'm getting the following delivery error:

**Missing or Invalid Field in Promoted Objects: For optimization goal APP_INSTALLS, application_id needs to be valid. Please set it in the Promoted Objects**

I've followed the README for adding the react-native-fbsdk-next, and read through the Troubleshooting. Currently we are only setting up for iOS.

## To Reproduce
N/A

## Expected Behavior
We should be able to publish an Ad to track App Installs without an error

## Code Example

In App.js
```
import {Settings} from 'react-native-fbsdk-next';

export default function App() {
  useEffect(() => {
    Settings.setAdvertiserTrackingEnabled(true);
  }, []);
  return <StackNav />;
}
```

## Environment
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.91 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by vknez** [comment]
Hi @jessiealbarian, we have a similar issue. How did you fix it?

**Comment by jenipharachel** [comment]
Does app installs needs to be enabled for iOS as well (https://github.com/thebergamo/react-native-fbsdk-next#enabling-auto-app-installs-in-expo)?

@jessiemichelleblack Curious how you fixed your issue? Would be grateful if you shared what you did.

**Comment by Meet-JS** [comment]
Any update from anyone? @jenipharachel @vknez @jessiemblack

**Comment by jenipharachel** [comment]
@Meet-JS I did a bunch of stuff regarding it. I reached out to the support at Facebook Apps. Enabled Advertiser Tracking for iOS through react-native-fbsdk-next library and also acquired permission from user to obtain app tracking data. I eventually was able to view the app install but I moved to another project later. So, I'm not exactly sure. But try this https://stackoverflow.com/a/71890253
