### ISSUE TITLE
Question: Can we use this package to show ads in our app by using meta audience network ?

### ISSUE THREAD

**Issue by prateekuttreja2020** [thebergamo/react-native-fbsdk-next#356]

**Comment by prateekuttreja2020** [comment]
Hi, it is just a question... Can we use this package to show ads in our app by using meta audience network ?

**Comment by amanzrx4** [comment]
@prateekuttreja2020 Actually i got it, i used https://github.com/callstack/react-native-fbads for interstitial ads, it worked fine. Follow the docs.
