### ISSUE TITLE
Facebook app deeplink opens but no result

### ISSUE THREAD

**Issue by pidogc** [thebergamo/react-native-fbsdk-next#363]
i use browser mode ,open fb app share, but no result

![image](https://user-images.githubusercontent.com/42857270/206648518-f9773429-e31c-48e2-8cf7-5bc95fc06ca1.png)

ios system 15.2 
ipone se
"react-native-fbsdk-next": "10.1.0 "

<img width="736" alt="image" src="https://user-images.githubusercontent.com/42857270/206648863-c7b0400e-7d26-471a-95a7-1180bcfbe28a.png">
Can you guide me why there is no callback when using the app to share? thanks

**Comment by leturluer** [comment]
I've got the same problem using:
"react-native-fbsdk-next": "^11.1.0",
"react-native": "0.63.5"

Was working as expected when I was using "react-native-fbsdk": "^3.0.0"
Any help or guidance would be appreciated, thanks.

**Comment by pidogc** [comment]
Hello, have you found a solution? Although the lower version is ok, it still has problems on some ios versions 

"react-native-fbsdk-next": "4.0.3"
ios: 16
@leturluer

**Comment by leturluer** [comment]
Still nothing, is this repo still maintained ?

**Comment by mikehardy** [comment]
Lightly, but I don't have a lot of time for things I don't personally use, and I don't personally use deeplinks, I use firebase for that

Open Source in general means: work on the things you are interested in. Sounds like you're interested? Is there a PR you propose?
