### ISSUE TITLE
An error message "sorry, something went wrong" appears when I try to login  Facebook app through my react native application

### ISSUE THREAD

**Issue by Hari-krish-v** [thebergamo/react-native-fbsdk-next#366]
![unnamed (1)](https://user-images.githubusercontent.com/91190155/207804691-409452ff-f967-4fa6-bffd-dfd67bd50f0d.png)
As you can see in the screenshot above, I got the warning message when I added "user_friends" to loginButton.setPermissions("email", "public_profile", "user_friends"), but when I tried logging into Facebook, I received a message saying, "Sorry, something went wrong." Is this a permission disable issue or not?
It has been over a year since I submitted the app and there were no issues. However, it is one month before the issue begins.
React native package used is : react-native-fbsdk-next
![unnamed (2)](https://user-images.githubusercontent.com/91190155/207804725-d11b334f-41fa-4e00-a9f6-097a1073cda2.png)

**Comment by mikehardy** [comment]
You are in the part of the login process that is controlled by the native SDK and facebook, it is not related to this plugin.

**Comment by JapjyotSuri** [comment]
Did you find any solution for the above???

**Comment by anurenj4u** [comment]
any solution Iam facing the same issue
