### ISSUE TITLE
Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by ahmadalghalban** [thebergamo/react-native-fbsdk-next#367]
## 🐛 Bug Report
Execution failed for task ':app:processDebugManifest'.

Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
[com.facebook.android:facebook-common:15.2.0] /Users/shopyardshopyard/.gradle/caches/transforms-2/files-2.1/fa2ba5b6a25f3ccc8bff867bf8f50ded/AndroidManifest.xml:18:9-55 Error:
        Missing 'package' key attribute on element package at [com.facebook.android:facebook-common:15.2.0] AndroidManifest.xml:18:9-55
[com.facebook.android:facebook-common:15.2.0] /Users/shopyardshopyard/.gradle/caches/transforms-2/files-2.1/fa2ba5b6a25f3ccc8bff867bf8f50ded/AndroidManifest.xml Error:
        Validation failed, exiting
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/shopyardshopyard/Documents/GitHub/luliz-main/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
## To Reproduce
Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
[com.facebook.android:facebook-common:15.2.0] /Users/shopyardshopyard/.gradle/caches/transforms-2/files-2.1/fa2ba5b6a25f3ccc8bff867bf8f50ded/AndroidManifest.xml:18:9-55 Error:
        Missing 'package' key attribute on element package at [com.facebook.android:facebook-common:15.2.0] AndroidManifest.xml:18:9-55
[com.facebook.android:facebook-common:15.2.0] /Users/shopyardshopyard/.gradle/caches/transforms-2/files-2.1/fa2ba5b6a25f3ccc8bff867bf8f50ded/AndroidManifest.xml Error:
        Validation failed, exiting
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/shopyardshopyard/Documents/GitHub/luliz-main/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

## Expected Behavior
Bug don't work in android

## Code Example
No code error when run app

**Comment by mikehardy** [comment]
Versions of things in use? That is: https://stackoverflow.com/help/how-to-ask

No one else has reported this, so I suspect there is something out of date in your local environment. Are your versions all up to date with current stale releases, and you are using JDK11 etc?

**Comment by connorbode** [comment]
For anyone else finding this issue, I was able to resolve by bumping my gradle version in `android/build.gradle` to `3.5.4`:

```
buildscript {
  .. 
  dependencies {
    ..
    classpath("com.android.tools.build:gradle:3.5.4")
  }
}
```
