### ISSUE TITLE
[IOS] ShareDialog return empty object if user share successfully and also if user not install FB app.

### ISSUE THREAD

**Issue by hoanghuy0604** [thebergamo/react-native-fbsdk-next#369]
## 🐛 Bug Report

ShareDialog return empty object if user share successfully and also if user not install FB app. 

## To Reproduce

- yarn add react-native-fbsdk-next
- cd ios && pod install

- <img width="692" alt="Screenshot 2022-12-28 at 12 29 59 PM" src="https://user-images.githubusercontent.com/24283972/209762644-c219560e-7f31-4c4f-9e57-2743553ecf32.png">

## Expected Behavior

Need something to distinct between share successfully and if App is not installed
## Code Example

ShareDialog.canShow(state.shareLinkContent).then(canShow => {

        if (canShow) {
          return ShareDialog.show(state.shareLinkContent)
        }
      })
      .then(async (result: any) => {
        if (result.isCancelled) {
         Alert.alert('Cancelled')
        } else {
          Alert.alert('Shared')
        }
      })
      .catch(error => {
        console.log('Error: ', error)
      })

## Environment

 "react-native-fbsdk-next": "^11.1.0",
"react-native": "0.69.3",

**Comment by leturluer** [comment]
I've got the same problem using:
"react-native-fbsdk-next": "^11.1.0",
"react-native": "0.63.5"

Was working as expected when I was using "react-native-fbsdk": "^3.0.0"
Any help or guidance would be appreciated, thanks.

**Comment by leturluer** [comment]
Does something have a fix for this ?
