### ISSUE TITLE
Could not do pod install after doing npm I react-native-fbsdk-next

### ISSUE THREAD

**Issue by nikita-zot-1408** [thebergamo/react-native-fbsdk-next#37]
I did npm I react-native-fbsdk-next and after I tried to do cd ios && pod install 

But I got cocoa pods error somewhy.

I am using MacBook Pro M1, BigSur 11.1

**Comment by mikehardy** [comment]
No details, there is nothing to go on to help. Please try to reproduce with the sample app.

**Comment by mtzluisalfredo** [comment]
@nikita-zot-1408 Did you find any solution?

**Comment by mikehardy** [comment]
@mtzluisalfredo you may like https://github.com/mikehardy/react-native-fbsdk-next/blob/new-example/refresh-example.sh

goes from `npx react-native init` to a working project. There's no problem with the module, near as I can tell
