### ISSUE TITLE
Error: While trying to resolve module `react-native-fbads` from file 

### ISSUE THREAD

**Issue by chungtvdev** [thebergamo/react-native-fbsdk-next#373]
I can not show the fbads . PLease help me
Metro show Error:
 Error: While trying to resolve module `react-native-fbads` from file `D:\Reactnative\Test20230105\App.js`, the package `D:\Reactnative\Test20230105\node_modules\react-native-fbads\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`D:\Reactnative\Test20230105\node_modules\react-native-fbads\dist\lib\index.js`. Indeed, none of these files exist:
![FBs](https://user-images.githubusercontent.com/90433366/210840446-a6047fed-e08c-4cca-834f-229a30db0148.jpg)

**Comment by RodolfoGS** [comment]
Wrong project, this is `react-native-fbsdk-next` and your issue is with `react-native-fbads`
Report here: https://github.com/callstack/react-native-fbads

**Comment by faazlerabbi** [comment]
I am also facing same issues.
