### ISSUE TITLE
Manually handle login and logout

### ISSUE THREAD

**Issue by domjesus** [thebergamo/react-native-fbsdk-next#378]
Hello everyone, I'm using this package to handle login on my app and I'd  like to handle login and logout on Facebook without using the LoginButton native component. Is this possible?

My login button looks like this: 

`<LoginButton
            permissions={['email']}
            onLoginFinished={(error, result) => {
              if (error) {
                console.log('login has error: ' + result.error);
              } else if (result.isCancelled) {
                console.log('login is cancelled.');
              } else {
                AccessToken.getCurrentAccessToken().then(data => {
                  console.log(data.accessToken.toString());
                });
                getFacebookUserInfo();
              }
            }}
            onLogoutFinished={() => {
              console.log('logout.');
            }}
/>`

Because the initial request don't have the email I need to re-fetch with GraphRequest to recover email. 
 The code to recover user info is: 

`const getFacebookUserInfo = () => {
    const responseInfoCallback = (error, result) => {
      if (error) {
        console.log('Error fetching data: ' + error.toString());
      } else {
        console.log('Success fetching data: ', result);
        setUser({email: result.email, name: result.name}); //SET THE EMAIL AND NAME USER 
      }    
    };

    const param = {
      fields: {
        string: 'name,email',
      },
    };
    // Create a graph request asking for user information with a callback to handle the response.
    const infoRequest = new GraphRequest(
      '/me',
      {
        httpMethod: 'GET',
        version: 'v2.5',
        parameters: param,
      },
      responseInfoCallback,
    );
    // Start the graph request.
    new GraphRequestManager().addRequest(infoRequest).start();
    // console.log('Res is :', res);
  };`

Thanks.

**Comment by DoctorJohn** [comment]
You can use `LoginManager` instead of the `LoginButton`. There is a [section with example code](https://github.com/thebergamo/react-native-fbsdk-next#requesting-additional-permissions-with-login-manager) in this repositories readme file.

**Comment by sandeep-aample** [comment]
> You can use `LoginManager` instead of the `LoginButton`. There is a [section with example code](https://github.com/thebergamo/react-native-fbsdk-next#requesting-additional-permissions-with-login-manager) in this repositories readme file.

This section shows only login example. 
* Where can I find an example for logout? 
* What are the other features/option of LoginManager?  
* Where can I find the detailed documentation with all API references?
