### ISSUE TITLE
Facebook Login error: Logging into this app is not available at this time

### ISSUE THREAD

**Issue by EduGomes18** [thebergamo/react-native-fbsdk-next#38]
## 🐛 Bug Report
Hello everyone, i was trying to implement sample Facebook login flux following this github docs, and i get this error, if someone know how to deal with it, i was trying with expo managed and expo-facebook, and was getting the same error, maybe i lost in some app config from facebook, please i need D:, my app is 99% based in facebook sdk

Basicaly i follow the docs importing the LoginButton, configured appId following facebook android steps, and everytime i fall into this:

![WhatsApp Image 2021-05-23 at 19 50 25](https://user-images.githubusercontent.com/61379704/119279505-8f981f80-bc02-11eb-9a6e-e50dff6083b2.jpeg)

I cant reproduce with expo-snack, but basicaly is the normal use, using login button

https://snack.expo.io/@edusnown/logging-into-this-app-facebook-error

## Environment

System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.25 GB / 15.42 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.14.0 - ~/www/imobiteste/node_modules/.bin/npm
    Watchman: 20210516.170703.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
  Languages:
    Java: 11.0.11 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
This module will not work with expo
If you were also having this problem with their modules, you must have a project config problem of some sort.
You should ask on stackoverflow - if it's not going to result in a change to the module (and it is not, the module is working fine) there is not a lot we can do for you unfortunately

**Comment by EduGomes18** [comment]
i eject from expo to use this module D:, but i will ask in stackoverflow, thank you for the reply

**Comment by mikehardy** [comment]
Sure sure - but you mentioned above you tried the others and had the same result which gave you the hunch the facebook config isn't right. I'd follow that
