### ISSUE TITLE
logEvent not working with multiple parameters

### ISSUE THREAD

**Issue by GonzaloAszyn** [thebergamo/react-native-fbsdk-next#383]
## 🐛 Bug Report

  I am implementing some events in my code, and when I send more that one parameter in the event, the event is not registered in Facebook Event Manager. 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/88556506/214375946-06704bfb-4994-480a-86ea-7ba8f03c7017.png">

## To Reproduce

Use the logEvent function with more that one parameter

## Expected Behavior

Event registers in Facebook Event Manager

**Comment by reinel-zinli** [comment]
@GonzaloAszyn could you solve it ? same issue here
