### ISSUE TITLE
Facebook login not working in android if facebook app is installed

### ISSUE THREAD

**Issue by Deepali-Rai** [thebergamo/react-native-fbsdk-next#384]

**Comment by BUGLittlePrince** [comment]
I had the same problem

**Comment by sazan10** [comment]
👍

**Comment by tonvlad88** [comment]
same problem...

**Comment by Deepali-Rai** [comment]
It was key hash issue
As command in document for debug and release key hash is wrong
Actual Command is
Debug hash key ~ keytool -exportcert -alias androiddebugkey -keystore <your_project>/android/app/debug.keystore | openssl sha1 -binary | openssl base64
Release hash key ~ keytool -exportcert -alias my-key-alias -keystore android/app/my-upload-key.keystore | openssl sha1 -binary | openssl base64

**Comment by hugoh59** [comment]
Is there any way to know if the key is valid or not ?
