### ISSUE TITLE
Invalid Scopes: public_profile, email, openid

### ISSUE THREAD

**Issue by uboltabaev** [thebergamo/react-native-fbsdk-next#388]
I get an error while trying to login Facebook:

Invalid Scopes: public_profile, email, openid.

I checked Facebook documentation and there is no openid permission.

My code is:

`const result = await LoginManager.logInWithPermissions(['public_profile', 'email'])`

Not sure how openid is added there.

**Comment by FadiAboMsalam** [comment]
same issue happend here as well

**Comment by mikehardy** [comment]
hasn't happened to me

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by FadiAboMsalam** [comment]
@uboltabaev @mikehardy I figured out my issue and hope it helps other.
Basically it was issue in the configuration inside developer.facebook.com  after add a product **Facebook login for Business** the issue still happend
i entered the **settings** of Facebook login for Business and **switched to Facebook Login** and issue was solved afterwards

**Comment by bawantha** [comment]
Same

**Comment by bawantha** [comment]
> @uboltabaev @mikehardy I figured out my issue and hope it helps other. Basically it was issue in the configuration inside developer.facebook.com after add a product **Facebook login for Business** the issue still happend i entered the **settings** of Facebook login for Business and **switched to Facebook Login** and issue was solved afterwards

Thanks

**Comment by robozb** [comment]
> > @uboltabaev @mikehardy I figured out my issue and hope it helps other. Basically it was issue in the configuration inside developer.facebook.com after add a product **Facebook login for Business** the issue still happend i entered the **settings** of Facebook login for Business and **switched to Facebook Login** and issue was solved afterwards
> 
> Thanks

How could you do that? I see there just the FB login for business, nothing else. Thx

**Comment by robozb** [comment]
![DE4E47EE-455B-4531-B502-A29646EDE515](https://user-images.githubusercontent.com/8656998/228130150-04365028-c3b6-45e6-bba1-20ac27e771f8.png)

but it is still not working

**Comment by LeXuanKhanh** [comment]
> ![DE4E47EE-455B-4531-B502-A29646EDE515](https://user-images.githubusercontent.com/8656998/228130150-04365028-c3b6-45e6-bba1-20ac27e771f8.png)
> 
> but it is still not working

https://stackoverflow.com/a/76354777/11974635

You have to to edit the Use Cases permissons the facebook developer settings to get more data
![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/27200149/6f22d0d5-1797-4df3-8a1d-a7c4ee30f0b0)

**Comment by kamal614** [comment]
Thanks @LeXuanKhanh that was helpful

**Comment by zip99** [comment]
I solved my problem by not using the Facebook account associated with the developer account on FB on my iPhone.

**Comment by madsongr** [comment]
> I get an error while trying to login Facebook:
> 
> Invalid Scopes: public_profile, email, openid.
> 
> I checked Facebook documentation and there is no openid permission.
> 
> My code is:
> 
> `const result = await LoginManager.logInWithPermissions(['public_profile', 'email'])`
> 
> Not sure how openid is added there.

I had the same issue. I knew that when I created the app in developers.facebook.com, `email` and `public_profile` were automatically added to my login environment but when I went back there to check it out again, `email` wasn't added yet. It was only listed along with `public_profile`.

So, select your app in developers.facebook.com and under "Use cases" => "Authentication and account creation", click to enter edit/personalize and under "Permissions", add `email` to get ready for testing.

PS: my dashboard is not in english so maybe titles I mentioned here are a little bit different.

**Comment by MatkoMilic** [comment]
Under use cases there is email option that you must turn on, then this error goes away, I use firebase and expo

**Comment by Namr547** [comment]
> > I get an error while trying to login Facebook:
> > Invalid Scopes: public_profile, email, openid.
> > I checked Facebook documentation and there is no openid permission.
> > My code is:
> > `const result = await LoginManager.logInWithPermissions(['public_profile', 'email'])`
> > Not sure how openid is added there.
> 
> I had the same issue. I knew that when I created the app in developers.facebook.com, `email` and `public_profile` were automatically added to my login environment but when I went back there to check it out again, `email` wasn't added yet. It was only listed along with `public_profile`.
> 
> So, select your app in developers.facebook.com and under "Use cases" => "Authentication and account creation", click to enter edit/personalize and under "Permissions", add `email` to get ready for testing.
> 
> PS: my dashboard is not in english so maybe titles I mentioned here are a little bit different.

Thank You Man, this worked for me
