### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FBSDKCoreKit" (part#2)

### ISSUE THREAD

**Issue by supagu** [thebergamo/react-native-fbsdk-next#39]
I'm having this issue: https://github.com/thebergamo/react-native-fbsdk-next/issues/20
@mikehardy has provided a possible solution how ever he has not given me enough details to work out how to get things working, so I'm starting a new thread as that one is locked.

I have tried updating the react-native-fbsdk-next.podspec to: https://pastebin.com/8BDx9r84

but I am still getting the following errors: https://pastebin.com/X8yZbpCh

I also tried changing the version on the Podfile.lock to 9.2.0.

Can any one provide more information on how to resolve this issue?

**Comment by mikehardy** [comment]
Managing your dependencies is not the responsibility of this module.
You have this module which is depending one version.
If you delete `Podfile.lock` and run `pod install` and continue to get the message, you have some other module depending on some other version, and the error message tells you exactly what, it's some thing that requires "FacebookLogin" 

You must fix that in your own project.
