### ISSUE TITLE
Error building RNFBSDKExample on ios - issue with #import <FBSDKCoreKit/FBSDKCoreKit-swift.h> 

### ISSUE THREAD

**Issue by sharived** [thebergamo/react-native-fbsdk-next#393]
## 🐛 Bug Report
Error building RNFBSDKExample on ios.  Got the error FBSDKApplicationDelegate not found.  By replacing 
#import <FBSDKCoreKit/FBSDKCoreKit-swift.h> with
#import <FBSDKCoreKit/FBSDKCoreKit.h> 
in ios/RNFBSDKExample/AppDelegate.mm it built and ran

## To Reproduce
Build the example app for ios as per instructions, however I used Xcode to figure out what the problem was

## Expected Behavior
It should have built.
## Code Example
replace
#import <FBSDKCoreKit/FBSDKCoreKit-swift.h> 
with
#import <FBSDKCoreKit/FBSDKCoreKit.h> 
in ios/RNFBSDKExample/AppDelegate.mm

## Environment
info Fetching system and libraries information...
System:
    OS: macOS 13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 32.29 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /var/folders/92/x0_tgnpn6vzdq5tr3lfqf4j40000gt/T/yarn--1677175610834-0.8988226430218316/node
    Yarn: 1.22.19 - /var/folders/92/x0_tgnpn6vzdq5tr3lfqf4j40000gt/T/yarn--1677175610834-0.8988226430218316/yarn
    npm: 8.12.1 - ~/react-native-fbsdk-next/node_modules/.bin/npm
    Watchman: 2023.02.20.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 33.0.0, 34.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikeislearning** [comment]
YES. I'm having the exact same issue. Everything was working fine when my versions where:
```
"react-native": "0.70.6",
"react-native-fbsdk-next": "^8.0.5",
```

However, once I updated react native to latest, I was forced to update my Facebook module too, so now I have:
```
"react-native": "0.71.3",
"react-native-fbsdk-next": "^11.1.0",
```
And I get the error that @sharived is getting

I also tried using v10 where I'd import an objective-c file instead of a swift file, and got the same error.

**Comment by sharived** [comment]
@mikeislearning did you try changing the include
#import <FBSDKCoreKit/FBSDKCoreKit.h>

**Comment by mikeislearning** [comment]
@sharived 

So I'm able to get it to build now with the swift file, due to one key change. I now import:

```
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
```

With Swift capitalized, then it builds without any errors.
However, it still seems to fail actually loading the app due to Firebase not loading correctly
