### ISSUE TITLE
get this error when i want to build: Execution failed for task ':react-native-fbsdk-next:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by peyman-hakemi** [thebergamo/react-native-fbsdk-next#397]
## 🐛 Bug Report
I followed the install steps and when I want to run my project, I'm getting this error.

Execution failed for task ':react-native-fbsdk-next:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-fbsdk-next:debugCompileClasspath'.
   > Failed to transform legacy-support-core-utils-1.0.0.jar (androidx.legacy:legacy-support-core-utils:1.0.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find legacy-support-core-utils-1.0.0.jar (androidx.legacy:legacy-support-core-utils:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.jar
   > Failed to transform cardview-1.0.0.jar (androidx.cardview:cardview:1.0.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find cardview-1.0.0.jar (androidx.cardview:cardview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/cardview/cardview/1.0.0/cardview-1.0.0.jar

## Environment
 "react-native-fbsdk-next": "^11.1.0",
   "react-native": "0.68.1",

**Comment by mikehardy** [comment]
I don't see those in our dependency list for android

https://github.com/thebergamo/react-native-fbsdk-next/blob/0da60ca622a6c2242da8ad9a6188de7e43e6a713/android/build.gradle#L49-L53

Suggest running `./gradlew :app:dependencies > dependencies.txt` then analyzing dependencies.txt to see what module is pulling those in and opening an issue with them

**Comment by peyman-hakemi** [comment]
Can you help me out with this? I didn't quite get how I can determine these dependencies are belong to which libraries.

[dependencies.txt](https://github.com/thebergamo/react-native-fbsdk-next/files/10895063/dependencies.txt)

I created a new react native project with version 0.68.1 and I tried installing this library, but it gave me the same error and I didn't install any other libraries, but funny thing is when I created a react native project with latest version and installed this library everything was ok.
I can't upgrade my project to latest react native version for some reasons. What can I do?

**Comment by mikehardy** [comment]
@peyman-hakemi 

> @mikehardy Can you help me out with this

No I cannot, I don't have any available free time, sorry.
