### ISSUE TITLE
Cannot login in android([Error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: ])

### ISSUE THREAD

**Issue by lee-corey** [thebergamo/react-native-fbsdk-next#398]
## 🐛 Bug Report

```
import { LoginManager, AccessToken, Settings } from 'react-native-fbsdk-next';
Settings.initializeSDK();

const { logInWithPermissions } = LoginManager;
export default async function () {
  try {
    LoginManager.logOut();

    console.log('facebookAuth before call');
    LoginManager.setLoginBehavior('NATIVE_ONLY');
    const res = await logInWithPermissions(['public_profile', 'email']);
}
```

Here is my code and I'm getting `[Error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: ]` in the console catch and `com.facebook.login.LoginManager: You're calling logging in Facebook with an activity supports androidx activity result APIs. Please follow our document to upgrade to new APIs to avoid overriding onActivityResult().` in Logcat

## To Reproduce

Just click facebook button which trigger above function and in UI nothing shows

## Expected Behavior

It should login with facebook

## Environment

```
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 177.23 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-29 | ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Also react-native-fbsdk-next: 11.1.0
```

**Comment by lee-corey** [comment]
Update: 
https://github.com/thebergamo/react-native-fbsdk-next/issues/396#issuecomment-1455632943
After I saw this, I added the 'user_friends' permission in the logInWithPermissions then it's opening the facebook login page but it shows another error in the screen.
`App not active: This app is not accessible right now and the app developer is aware of the issue. You will be able to log in when the app is reactivated` 
Note that I'm testing in the staging

**Comment by mikehardy** [comment]
That's a lot of errors, and no one else seems to be reporting login issues. No idea what is actually actionable here, as a repository maintainer. Does not appear anything is actionable except on your part, in your project.

**Comment by lee-corey** [comment]
Thank you for your reply. Could you give me some advice to what should I check or which part could be wrong?

**Comment by mikehardy** [comment]
No
