### ISSUE TITLE
Not working deferred app link

### ISSUE THREAD

**Issue by seongjoojin** [thebergamo/react-native-fbsdk-next#4]
Hello.

https://github.com/facebook/react-native-fbsdk/pull/813#issuecomment-764700820

The same problem occurs as the above issue.
Is there any solution?

**Comment by thebergamo** [comment]
Hi @seongjoojin i don't think we'be any solution yet for it.
Would you be able to provide working example that we could replicate the issue?
It would be even better if you could implement some failing test in the project itself :)

**Comment by rnike** [comment]
@seongjoojin We've encountered the facebook deeplink issue several months ago, we've also contacted the [facebook developer support](https://developers.facebook.com/support/bugs/1408755882662815/) but it seems to be no luck

**Comment by thebergamo** [comment]
It seems to be some issue with fb itself.
Issue will be closed, if you believe it should be re-opened let me know :)
