### ISSUE TITLE
Send the Advertising tracking enable true 

### ISSUE THREAD

**Issue by abdulahad96** [thebergamo/react-native-fbsdk-next#405]
## 🐛 Bug Report

Hi There,
I am getting warning error from Facebook continuously that I am not passing flag of advertising tracking enable, 

## ▲ Send the Advertiser Tracking Enabled flag.
The Advertiser Tracking Enabled flag indicates whether we should use event data for ads in line with your own legal obligations, platform terms and commitments that you've made to your users. If the flag is sent and set to false or no, we'll treat that event as opted out from tracking. We'll rely solely upon your parameter setting to determine whether you want us to treat an event as opted out from tracking. If we don't receive any value for this parameter, we'll treat that event as opted out. If your parameter is set inaccurately, you may see a decrease in the number of reported conversions and some of your ads may be paused or stop delivering to iOS 14.5 or later devices. We created this task to help you reduce the negative impacts of Apple's iOS 14 changes. Visit the Resource Centre to learn more. See Instructions react native 

even I am following complete guidance and set ads tracking enable to true 

## Code in App Delegate.m
[[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
                           
# Code in react native app start
      const isAte = await Settings.getAdvertiserTrackingEnabled()
      if(!isAte){
        await Settings.setAdvertiserTrackingEnabled(true)  
      }
## Environment
 "react-native-fbsdk-next": "^11.0.0",
  "react-native": "^0.67.1",

**Comment by mikehardy** [comment]
PRs happily accepted!

**Comment by abdulahad96** [comment]
Hi @mikehardy ,
thank for replying me, I didn't find any PR related to this issue can you please give me PR Reference.
thank

**Comment by mikehardy** [comment]
What I meant was: If you need this feature, develop the feature, and post a PR with the feature developed. I can merge it and release it. This feature is not relevant to me and I will not spend time on it personally
