### ISSUE TITLE
Aggregated Event Measurement is not verify

### ISSUE THREAD

**Issue by devops35** [thebergamo/react-native-fbsdk-next#407]
I tried almost every method but I couldn't verify Aggregated Event Measurement. Auto verify is not working because Facebook sdk is 15.0.0. So I am trying manual verify method in events manager. Facebook is sending me a notification and trying to verify. But I couldn't make it. I init the sdk in appdelegate, I init it in react native. I sent AEMReporterIOS.logAEMEvent as soon as it opens in React native. I also tried the methods mentioned in Issues. It never did. I am writing the final version of my code below. please someone help.

`#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import <Firebase.h>
#import "RNNotifications.h"
#import <FBAEMKit/FBAEMKit.h>
#import <FBSDKCoreKit/FBSDKCoreKit-swift.h>

#import <React/RCTAppSetupUtils.h>
#import <React/RCTLinkingManager.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  //RCTAppSetupPrepareApp(application, true);

  //[FBSDKApplicationDelegate.sharedInstance initializeSDK];
  
  
  
  [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  [RNNotifications startMonitorNotifications];
  
  [[FBSDKApplicationDelegate sharedInstance] application:application
                       didFinishLaunchingWithOptions:launchOptions];

  return YES;
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler {
  [RNNotifications didReceiveBackgroundNotification:userInfo withCompletionHandler:completionHandler];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  #if DEBUG
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
  #else
    return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}

- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
 // NSLog(@"NSLog messageff");
 // printf("printf 11 messageff\n");
  
  //[FBAEMReporter configureWithNetworker:nil appID:@"my-app-id" reporter:nil];
  //[FBAEMReporter enable];
  //[FBAEMReporter handleURL:url];
  
  //NSDictionary* infoDict = [[NSBundle mainBundle] infoDictionary];
  //  NSString* fbappid = [infoDict objectForKey:@"FacebookAppID"];
  
  [FBAEMReporter configureWithNetworker:nil appID:@"my-app-id" reporter:nil];
  [FBAEMReporter setConversionFilteringEnabled:YES];
  [FBAEMReporter enable];
  [FBAEMReporter handleURL:url];

  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }
  
  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

@end
`

**Comment by Pankil01** [comment]
@devops35  Are you able to resolve the issue?

**Comment by devops35** [comment]
@Pankil01 I couldn't solve it. I tried every way but it doesn't verify. No one is answering here. Are you having the same problem?

**Comment by Pankil01** [comment]
@devops35 Yes, suffering with same the issue and also tried to find a way to contact FB support, but NO LUCK.

**Comment by jenipharachel** [comment]
@devops35 @Pankil01  Please check the below links

https://github.com/thebergamo/react-native-fbsdk-next/issues/288#issuecomment-1209756854
https://github.com/thebergamo/react-native-fbsdk-next/issues/264#issuecomment-1160618187

**Comment by fluorescent23** [comment]
Any solutions @devops35 ? I too am not able to verify deep links from the facebook events manager.

**Comment by wzs** [comment]
I have a similar problem, from my notes it seems that it's an issue with the verification tool itself:

> Manual verification tool basically sends a _verification notification_ to the **Facebook mobile app**, which when tapped on device - opens the appropriate deep link (I receive it as `fb123456789://authorize?target_url=http%3A%2F%2Fitunes.apple.com%2Fapp%2Fid654321`), that should be retrieved and validated by the FB SDK implemented in the app.
> 
> App is configured to handle that - it opens at tap on this deeplink, and passes it to [`FBAEMKit/AEMReporter.handle`](https://github.com/facebook/facebook-ios-sdk/blob/814863c8d877f0fc7981237bebdf452d8e290f30/FBAEMKit/FBAEMKit/AEMReporter.swift#L221)  method from SDK. Looking deep into implementation of that method, it's obvious that we can't get verified with beforementioned deeplinks, as it's in a format totally different from what SDK expects (it should be something like `fbfb123456789://authorize?target_url=http%3A%2F%2Fitunes.apple.com%2Fapp%2Fid654321&al_applink_data=%7B%0Atest_deeplink%3A1%2C%0Acampaign_ids%3A%20%22foo%22%2C%0Aacs_token%3A%22bar%22%0A%7D`)
