### ISSUE TITLE
Can't run react-native run-android

### ISSUE THREAD

**Issue by markoDragusic** [thebergamo/react-native-fbsdk-next#41]
## 🐛 Bug Report

I changed from react-native-fbsdk to react-native-fbsdk-next, following steps on comment section here https://github.com/thebergamo/react-native-fbsdk-next/pull/1#issuecomment-796918413.  It works fine on iOS. On Android, when trying to build react-native app with "react-native run-android", i got the following error:

> /node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java:16: error: constructor ReactContextBaseJavaModule in class ReactContextBaseJavaModule cannot be applied to given types;
public class FBProfileModule extends ReactContextBaseJavaModule {
       ^
  required: ReactApplicationContext
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/myuser/Project/project-mobile/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:å
Execution failed for task ':react-native-fbsdk-next:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/myuser/Project/project-mobile/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java:16: error: constructor ReactContextBaseJavaModule in class ReactContextBaseJavaModule cannot be applied to given types;
public class FBProfileModule extends ReactContextBaseJavaModule {
       ^
  required: ReactApplicationContext
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/myuser/Project/project-mobile/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk-next:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/myuser/Project/project-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/myuser/Project/project-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/myuser/Project/project-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Is it possibly related to this: https://github.com/facebook/react-native/issues/21917 ?

## To Reproduce

Update from react-native-fbsdk on Android project, to react-native-fbsdk-next. Run "react-native run-android" in terminal.
## Expected Behavior

To build Android project successfully and debug on a device.
## Environment

System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 177.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/local/opt/openjdk@8/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by tmjordan** [comment]
Hi @markoDragusic i have exactly the same problem.
Have you find a solution?

**Comment by tmjordan** [comment]
Duplicated #30

**Comment by markoDragusic** [comment]
Yes I'm afraid I've duplicated it. Sorry, folks. 

@tmjordan I tried to change node modules like described in #30, but I only got new errors then.

**Comment by tmjordan** [comment]
@markoDragusic the solution is to use react-native version 0.63 at least or apply a local patch

**Comment by tmjordan** [comment]
for the patch, modify the code by applying the recommendations mentioned in #30

**Comment by markoDragusic** [comment]
@tmjordan Thank you so much! I was just thinking of trying to go with react-native update.

**Comment by tmjordan** [comment]
[react-native-fbsdk-next+4.2.0.patch.txt](https://github.com/thebergamo/react-native-fbsdk-next/files/6539942/react-native-fbsdk-next%2B4.2.0.patch.txt)

Here is my patch, just remove the .txt extension, and then apply patch-package

**Comment by markoDragusic** [comment]
Thanks, will take a look!

**Comment by markoDragusic** [comment]
Well my "new errors problem" was just that I had app  already installed on my phone, so some signatures collided somehow. I can confirm that #30 works, and will have to check this patching thing which is new to me. I guess I'll have to create a patch myself for my team, but thanks anyway @tmjordan, you were of great help!

**Comment by uasghar-smile** [comment]
same error!

**Comment by mikehardy** [comment]
@uasghar-smile this bug has been closed for nearly a year. Highly doubt you've got the same error.
