### ISSUE TITLE
App Id not found . add a string value with your app id for the key FacebookAppID to the info.plist or call Setting.shared.appid 

### ISSUE THREAD

**Issue by Madhav131** [thebergamo/react-native-fbsdk-next#411]
I have install this library, and run to ios simulator get some error

--> device name : iphone 12 pro
--> ios version: ios 16.2

get error for App Id not found . add a string value with your app id for the key FacebookAppID to the info.plist or call Setting.shared.appid. how to slove it. please help 

*  Attach to screenshot for get error
![Simulator Screen Shot - iPhone 12 Pro - 2023-04-10 at 17 29 35](https://user-images.githubusercontent.com/89082726/230899123-16e7b54a-443a-4506-87b6-ae8256c9e3cc.png)

**Comment by mikehardy** [comment]
With apologies, the issues list here is not a help desk, that's stackoverflow.

This is a project-specific configuration error and not a bug in the module, it will not result in a change to the module so it is not an issue here
