### ISSUE TITLE
[iOS] Application Rate limit exceeding

### ISSUE THREAD

**Issue by dmitrycoder** [thebergamo/react-native-fbsdk-next#412]
## 🐛 Bug Report
Hello. 
I have bug with Rate Limiting. 
Most of the time I see rate limit exceeding but I don't understand why. 
I use only react-native-fbsdk-next(sdk) for my ios application. I don't use any FB API's at all. 
DAU is max 2500 users a day. 

What is the endpoint gr:get:Application? 
Why does it use so often?

<img width="1000" alt="Rate Limiting Details - Meta for Developers" src="https://user-images.githubusercontent.com/24842537/230958164-9a3f3f91-8039-407b-ae0e-bb701f12dc50.png">

## To Reproduce
I see how "call count usage rate" increased every time when I start my app. 

## Expected Behavior
Limit use is not exceeding

## Code Example
 I install the sdk according the docs.
 
 I checked it on 11.1.0, 11.2.0 and 11.2.1 versions
 
 There are only two place where I use the sdk. 
 to init in AppDelegate.mm and track event in analytics.js
 That's it!
 
 AppDelegate.mm
 `
   - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
      {
        self.moduleName = @"app";
        self.initialProps = @{};
      
        [[FBSDKApplicationDelegate sharedInstance] application:application
                                 didFinishLaunchingWithOptions:launchOptions];
        
        [super application:application didFinishLaunchingWithOptions:launchOptions];
        
        center.delegate = self;
      
        return YES;
      }
      
   - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
      if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
        return YES;
      }
    
      if ([RCTLinkingManager application:app openURL:url options:options]) {
        return YES;
      }
    
      return NO;
    }
 `
 
analytics.js
`
  import { AppEventsLogger } from 'react-native-fbsdk-next';

  export const trackEvent = (event) => AppEventsLogger.logEvent(event);
`
-->

## Environment

Please Help!

**Comment by mikehardy** [comment]
Unfortunately I don't think we can be much help here. This is a pretty thin wrapper over the underlying facebook-ios-sdk and facebook-android-sdk

You might post directly on those repos or try on stackoverflow, or inspect your project even more closely

This module just wraps the APIs and translates the javascript calls you make into the corresponding native ones, and as such you are in control of the rate you call things and the underlying SDKs make the calls to the cloud services. So nothing about this question will result in a change to the module and as such is not really an issue here

**Comment by dmitrycoder** [comment]
Okay, thanks anyway

**Comment by aharodnikau** [comment]
@dc-full-dev did you find resolving for this issue?

**Comment by dc-full-dev** [comment]
> [@dc-full-dev](https://github.com/dc-full-dev) did you find resolving for this issue?

No, it still exists and SDK has been updated to the latest version.

**Comment by Rauzon** [comment]
@dc-full-dev , did you find a reason or maybe you have some thought regarding it? faced with same issue
