### ISSUE TITLE
FBSDKCoreKit version problem

### ISSUE THREAD

**Issue by ebykdrms** [thebergamo/react-native-fbsdk-next#415]
I want to add Facebook Login button to my project.

developer.facebook.com wants an upgrade:
![fbsdk version problem](https://user-images.githubusercontent.com/9490742/232214850-0f53e137-589a-48e8-9d73-62dbfca7fccb.jpg)
I can not change API version becouse information says: "*Deprecated API versions will not show in the dropdown*".

if i run `cd ios && pod outdated`, the output is: 
```terminal
The following pod updates are available:
- FBSDKCoreKit 15.0.0 -> 15.0.0 (latest version 16.0.1)
- FBSDKCoreKit_Basics 15.0.0 -> 15.0.0 (latest version 16.0.1)
- FBSDKGamingServicesKit 15.0.0 -> 15.0.0 (latest version 16.0.1)
- FBSDKLoginKit 15.0.0 -> 15.0.0 (latest version 16.0.1)
- FBSDKShareKit 15.0.0 -> 15.0.0 (latest version 16.0.1)
```
**I can not update to latest version 16 because react-native-fbsdk-next depends version 15.**

I added this lines to my PodFile (because Facebook suggest it):
```terminal
pod 'FBSDKCoreKit', '~> 16.0.0'
pod 'FBSDKShareKit', '~> 16.0.0'
```
(My PodFile has this line: `platform :ios, '12.4'`)

and i run `pod update` command but i get this error:
```terminal
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    FBSDKCoreKit (~> 16.0.0)

    FBSDKShareKit (~> 16.0.0) was resolved to 16.0.0, which depends on
      FBSDKCoreKit (= 16.0.0)

    react-native-fbsdk-next (from `../node_modules/react-native-fbsdk-next`) was resolved to 11.2.1, which depends on
      react-native-fbsdk-next/Core (= 11.2.1) was resolved to 11.2.1, which depends on
        FBSDKCoreKit (~> 15.0.0)

Specs satisfying the `FBSDKShareKit (~> 16.0.0), FBSDKShareKit (~> 15.0.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by jenipharachel** [comment]
@ebykdrms You need to wait until a new version release of this library supporting the latest native sdk versions is released.

**Comment by kesha-antonov** [comment]
Here's PR https://github.com/thebergamo/react-native-fbsdk-next/pull/408
