### ISSUE TITLE
Xcode framework Invalid bundle structure. 

### ISSUE THREAD

**Issue by JakubKasprzyk17** [thebergamo/react-native-fbsdk-next#423]
## 🐛 Bug Report

Xcode give me error when I'm distributing iOS app

Asset validation failed
Invalid bundle structure. The “Mobile.app/Frameworks/FBSDKGamingServicesKit.framework/FBSDKGamingServicesKit” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: 3f86da88-ad6d-4377-af62-a51ce0b5bfb5)

Asset validation failed
Invalid bundle structure. The “Mobile.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: 2579c81a-7cc8-45fe-8e38-32056086c005)

Asset validation failed
Invalid bundle structure. The “Mobile.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: 2bf5cb41-63f8-4852-96e2-e22bb378d230)

Asset validation failed
Invalid bundle structure. The “Mobile.app/Frameworks/FBAEMKit.framework/FBAEMKit” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: e0c82525-d907-429c-aea2-342071de43c5)

Asset validation failed
Invalid bundle structure. The “Mobile.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: 8b59d47d-af0a-45f2-a965-cd3375f8a2cb)

Asset validation failed
Invalid bundle structure. The “Mobile.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: b3a75652-1b96-4c09-ab73-699827ebe93b)

## To Reproduce
 implement react-native-fbsdk-next
 add Facebook-sdk-ios packages from Xcode 

## Expected Behavior

I can archive iOS app but I can't push app to app store connect.

## Code Example
Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'App' do
  use_unimodules!
  config = use_native_modules!

  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'FacebookSDK'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'  

  use_react_native!(:path => config["reactNativePath"])
## Environment

**Comment by Rossella-Mascia-Neosyn** [comment]
We have the same problem:
![3](https://github.com/thebergamo/react-native-fbsdk-next/assets/79088170/7f224997-e77e-4cd5-b30f-f993d2cd668a)
![2](https://github.com/thebergamo/react-native-fbsdk-next/assets/79088170/ef25f998-7b45-450d-8ef6-e5a82928556b)
![1](https://github.com/thebergamo/react-native-fbsdk-next/assets/79088170/108d178a-06b7-424c-88cb-4da1cd469263)

### Environment
     System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 179.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/neosynmac/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.0 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by claudioPrisco** [comment]
Thanks @Rossella-Mascia-Neosyn, your solution solved my problem!
