### ISSUE TITLE
Cannot login via facebook using firebase - Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired. [ Invalid access_token, error code 43 ]

### ISSUE THREAD

**Issue by proactivebit** [thebergamo/react-native-fbsdk-next#424]
## 🐛 Bug Report

Hi Recently I started getting error "Invalid access_token, error code 43" when I want to login to the app using facebook option and firebase integration. Before that everything works. I haven't change anything. Right now facebook developer team turn off my application from production because of this. I checked configuration and it seems be ok. 
When I do investigation I see that I get access token from facebook but when I send it to the firebase I get in response error 43. I also checked my other app and it looks that the problem is also visible there. Maybe it's some global problem?

logs:
LOG  {"accessToken": "myaccesstoken", "accessTokenSource": "CHROME_CUSTOM_TAB", "applicationID": "myapplicationid", "dataAccessExpirationTime": 1692302693000, "declinedPermissions": [], "expirationTime": 1689683970908, "expiredPermissions": [], "lastRefreshTime": 1684526692908, "permissions": ["openid", "public_profile", "email"], "userID": "myuserid"}
 LOG  [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired. [ Invalid access_token, error code 43 ]]

## To Reproduce

Use login via Facebook option with firebase integration in react native app.

## Expected Behavior

User should be able to login to the app using his facebook credentials

## Code Example

![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/9938300/704659d6-760e-41e7-bce9-e682143d7b85)

## Environment

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 78.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    Yarn: 1.22.10 - ~/Projects/puzzleTimer/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
"react-native-fbsdk-next": "11.2.0"
"@react-native-firebase/auth": "11.3.3",

**Comment by aleantoniolli** [comment]
Same problem here

**Comment by mladen4** [comment]
I have similar problem, maybe is related:
https://stackoverflow.com/questions/76339655/ios-react-native-fbsdk-next-token-is-generated-as-expired-error-bad-credentia

**Comment by Sauvetonbio** [comment]
Same problem here... And my business account had been verified !

**Comment by mladen4** [comment]
Any news?

**Comment by MaxJadav** [comment]
Getting the same issue. Is there any solution?

**Comment by badams2527** [comment]
I'm having the same issue. I think it may be related to facebook loading "limited.facebook.com" when doing the login instead of the normal URL. This was working for us in prod, then suddenly broke.

**Comment by mahendrapratap4022** [comment]
> [@MaxJadav](https://github.com/MaxJadav) If you're still having this issue, this comment pointed me in the right direction: [#520 (comment)](https://github.com/thebergamo/react-native-fbsdk-next/issues/520#issuecomment-2067687075)
> 
> For us, we were using `react-native-firebase` with this library, and we had to adjust the code to allow authentication on the limited login (https://rnfirebase.io/auth/social-auth#facebook-limited-login-ios-only). Haven't tried Android yet but iOS is working.

Thanks, this worked for me.

**Comment by AshishAlagiyac-lab** [comment]
`&platform=ios&dev=tr…ect&shallow=true:63 Facebook login error: NativeFirebaseError: [auth/invalid-credential] The supplied auth credential is malformed or has expired.
    at ?anon_0_ (&platform=ios&dev=tr…&shallow=true:60:79)
    at next (native)
?anon_0_	@	&platform=ios&dev=tr…ect&shallow=true:63
`

I'm also facing same errors. on android and iOS both.

**Comment by ajjankit5** [comment]
This issue also happened to me when I did not allow the app tracking permission. However, after allowing tracking, the issue was resolved.

Two options to fix the issue:

Option 1:
Remove the app and install it again. When the app asks for tracking and analytics permission, select Allow.

Option 2:
Go to the app settings and make sure the Allow Tracking toggle is turned ON.
