### ISSUE TITLE
[Bug]: Login by account list

### ISSUE THREAD

**Issue by tabydabi** [thebergamo/react-native-fbsdk-next#425]
## 🐛 Bug Report
try to login by account list(check video) -> and we going to facebook page

## To Reproduce
try to login by account list(check video)

## Code 
        LoginManager.logInWithPermissions([
            'email',
            'public_profile',
            'user_friends',
            'pages_show_list',
            'instagram_basic',
          ]).then(
            (result) => {
              if (!result.isCancelled) {
                setAccessTokenLoading(true);

                AccessToken.getCurrentAccessToken().then((data) => {
                  setAccessTokenLoading(false);
                  console.log('data', data);

                  if (data?.accessToken) {
                    connectSocialAccount({
                      variables: {
                        socialAccessToken: data.accessToken,
                        platform: PLATFORMS[platform].toUpperCase(),
                        reconnect: false,
                        socialRefreshToken: '',
                      },
                    });
                  }

                  LoginManager.logOut();
                });
              }
            },

https://github.com/thebergamo/react-native-fbsdk-next/assets/69752848/9974a4a1-b817-4af0-ba61-4833b949cfc6

**Comment by kdenz** [comment]
@tabydabi Hi wondering if you've had a solution?

**Comment by mateo2181** [comment]
I think this can helps: https://medium.com/@thejessieryan/react-native-graph-api-the-curious-case-of-instagram-business-insights-e2a43b3ab777
