### ISSUE TITLE
Xcode 12.4 Build getting failed 

### ISSUE THREAD

**Issue by aamir-ans** [thebergamo/react-native-fbsdk-next#43]
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FBSDKShareKit in libFBSDKShareKit.a(Enums+Extensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FBSDKShareKit)
  "__swift_FORCE_LOAD_$_swiftCoreMIDI", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_FBSDKShareKit in libFBSDKShareKit.a(Enums+Extensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMIDI_$_FBSDKShareKit)
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit in libFBSDKCoreKit.a(AccessToken.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit in libFBSDKCoreKit.a(Permission.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit in libFBSDKCoreKit.a(Settings.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKLoginKit in libFBSDKLoginKit.a(FBLoginButton.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKLoginKit in libFBSDKLoginKit.a(LoginManager.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKShareKit in libFBSDKShareKit.a(Enums+Extensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKLoginKit, __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKShareKit , __swift_FORCE_LOAD_$_swiftWebKit_$_FBSDKCoreKit )
ld: symbol(s) not found for architecture x86_64

react-native => 0.62.1
Xcode Version 12.4 

I have tried this [https://github.com/facebookarchive/react-native-fbsdk/issues/794] solution but nothing works

**Comment by mikehardy** [comment]
Have you tried using Xcode 12.5 + react-native 0.63.3 ?

**Comment by aamir-ans** [comment]
@mikehardy No I didn't, currently I don't have any plan to upgrade react native version. Is there anyway to handle this using react native version 0.62 and Xcode 12.4 ?

**Comment by mikehardy** [comment]
No idea, I only use react-native versions that still compile with current stable versions of Xcode (12.5), sorry

**Comment by jamesxabregas** [comment]
Just came across this same issue. Added an empty swift file in my project and it fixed the issue [as described here.](https://github.com/facebookarchive/react-native-fbsdk/issues/794#issuecomment-695217977)

**Comment by claudiozam** [comment]
@jamesxabregas thanks for your help! It is working!!

I'm using XCode 12.5 + RN 0.63.4

**Comment by mikehardy** [comment]
I think it's possible to say this module does not have a compile issue at this point, so no need to keep it open. I just built it myself in my project and it's fine as far as I can tell at least, along with success reports above. Cheers

**Comment by jamesxabregas** [comment]
> I think it's possible to say this module does not have a compile issue at this point, so no need to keep it open. I just built it myself in my project and it's fine as far as I can tell at least, along with success reports above. Cheers

Perhaps this cavet should be added to the readme?

**Comment by mikehardy** [comment]
@jamesxabregas - that is a great idea, I happened to have the bridging header from long ago so it did not bite me but it is a pretty esoteric error. Hit the edit button on the README and if it looks reasonable at all I'll happily :+1:  it to save future devs from pulling hair out

**Comment by jamesxabregas** [comment]
> @jamesxabregas - that is a great idea, I happened to have the bridging header from long ago so it did not bite me but it is a pretty esoteric error. Hit the edit button on the README and if it looks reasonable at all I'll happily 👍 it to save future devs from pulling hair out

Looks there was already a refrence to it in the Torubleshooting section but it only mentioned the solution and not the problem, so it was hard to understand. Pushed through the changes to the readme to make it clearer.
