### ISSUE TITLE
How to use with AppDelegate derived from EXAppDelegateWrapper

### ISSUE THREAD

**Issue by westofpluto** [thebergamo/react-native-fbsdk-next#432]
The instructions for configuring the AppDelegate in iOS assume that AppDelegate is a standard NSObject so no superclass method has to be called. But my (Expo ejected) app uses Expo v 46 where AppDelegate derives from EXAppDelegateWrapper. So in my AppDelegate code created by Expo, the didFinishLaunchingWithOptions code makea a call to [super application:application didFinishLaunchingWithOptions:launchOptions];
Similarly the openURL method has a superclass call:

if ([super application:application openURL:url options:options]) 
{
  return YES;
}

So how do I modify AppDelegate in this case?

**Comment by mikehardy** [comment]
Sorry, Expo support is community driven - you'll need to either read up on how to do it and post a PR to the docs or ask in the Expo support channels for guidance (then ideally post a PR to the docs here)
