### ISSUE TITLE
Error: Invalid Signature

### ISSUE THREAD

**Issue by tdvuanh** [thebergamo/react-native-fbsdk-next#433]
## 🐛 Bug Report

  Our application use react-native-fbsdk-next to implement user login by facebook, we requires user's email and profile. We go this bug rarely in production Error: Invalid Signature

## To Reproduce

  This bug is rarely happen, so we cannot reproduce, but lucky, our sentry show where is the bug happen, the code here
`export const getFacebookToken = async () => {
  return new Promise((resolve, reject) => {
    LoginManager.logInWithPermissions(['email', 'public_profile']).then(result => {`

## Expected Behavior

  No more Errore: Invalid Signature

## Version
react-native-fbsdk-next v9.0.0

## Environment
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 90.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac

**Comment by mladen4** [comment]
Maybe it's related to this.
https://github.com/thebergamo/react-native-fbsdk-next/issues/424
and this
https://stackoverflow.com/questions/76339655/ios-react-native-fbsdk-next-token-is-generated-as-expired-error-bad-credentia

**Comment by VanThanh258** [comment]
same problem

**Comment by mikehardy** [comment]
@adorum your comment provides no information that would be useful to actually fix the problem, unfortunately
