### ISSUE TITLE
new NativeEventEmitter() requires a non-null argument on a expo monorepo setup

### ISSUE THREAD

**Issue by alonzuman** [thebergamo/react-native-fbsdk-next#435]
## UPDATE
reinstalled & rebuilt (eas build) multiple times and its now working, I think the issue was that my initial install was `yarn add react-native-fbsdk-next` and only then `yarn remove...` && `expo install ...` which caused issues in the install

## 🐛 Bug Report
Installing the lib in a monorepo setup breaks 
<img width="347" alt="image" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/57261095/5625d8d1-22f9-4a58-9acc-89e269592354">

Update:
Its because of the `NativeModules.FBAccessToken` which is `null`, then passed to the `new NativeEventEmitter(AccessToken)` which throws an error

It must have something to do with my setup of my repo, but still can't put my finger on it, any ideas? 🥲

## To Reproduce
1. Pretty much follow [this setup guide](https://docs.expo.dev/guides/monorepos/) for a monorepo provided by expo
2. Follow the `react-native-fbsdk-next` expo setup guide
3. Get the error

## Expected Behavior
To not throw the error

## Code Example
Will be added

## Environment
Will be added

**Comment by gbyesiltas** [comment]
@alonzuman hello! I'm having the same issue, do you remember how you managed to fix this?

**Comment by MariuzM** [comment]
Hm i have the same issue but i usually delete everything like node modules, native folders and rebuild with yarn install later
