### ISSUE TITLE
Undefined symbol: _FBLinkable_* & _OBJC_CLASS_*

### ISSUE THREAD

**Issue by Bilal-Abdeen** [thebergamo/react-native-fbsdk-next#437]
## 🐛 Bug Report

Whenever I build my project (for iOS), I get the errors below! It works fine for Android. This started after I upgraded all libraries I am using, including react-native. 

I was using `0.71.8` and react-native-fbsdk-next version `7.2.0`. 

Now, I am using react-native `0.72.1` and react-native-fbsdk-next version `11.2.1`. 
- I added an empty file called `File.swift` to my project folder. 
- On Xcode, the iOS deployment target is set to `13.0`
- On Xcode, the minimum deployment is set to iOS `12.0`
```
Undefined symbol: _FBLinkable_NSBundle_InfoDictionaryProviding
Undefined symbol: _FBLinkable_NSData_FileDataExtracting
Undefined symbol: _FBLinkable_NSFileManager_FileManaging
Undefined symbol: _FBLinkable_NSNotificationCenter_NotificationDelivering
Undefined symbol: _FBLinkable_NSNotificationCenter_NotificationPosting
Undefined symbol: _FBLinkable_NSProcessInfo_MacCatalystDetermining
Undefined symbol: _FBLinkable_NSProcessInfo_OperatingSystemVersionComparing
Undefined symbol: _FBLinkable_NSURLSessionTask_NetworkTask
Undefined symbol: _FBLinkable_NSURLSession_URLSessionProviding
Undefined symbol: _FBLinkable_NSUserDefaults_DataPersisting
Undefined symbol: _OBJC_CLASS_$_FBSDKApplicationDelegate
Undefined symbol: _OBJC_CLASS_$_FIRApp
Undefined symbol: _OBJC_CLASS_$_GMSServices
Undefined symbol: _OBJC_CLASS_$_Orientation
Undefined symbol: _OBJC_CLASS_$_RCTAppDelegate
Undefined symbol: _OBJC_CLASS_$_RCTLinkingManager
Undefined symbol: _OBJC_CLASS_$_RNFBAppCheckModule
Undefined symbol: _OBJC_CLASS_$_RNFBDynamicLinksAppDelegateInterceptor
Undefined symbol: _OBJC_METACLASS_$_RCTAppDelegate
```
## AppDelegate.mm
```mm
#import "RNFBMessagingModule.h"
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <Firebase.h>
#import "RNFBAppCheckModule.h"
#import <GoogleMaps/GoogleMaps.h>

#import <React/RCTLinkingManager.h>
#import <RNFBDynamicLinksAppDelegateInterceptor.h>  

// react-native-fbsdk-next installation
// #import <FBSDKCoreKit/FBSDKCoreKit.h> // 2 errors: Use of undeclared identifier 'FBSDKApplicationDelegate'
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h> // many errors: Undefined symbol .....
// #import <FBAEMKit/FBAEMKit.h>

#import "Orientation.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [GMSServices provideAPIKey:@"xxxxx"]; 
  [RNFBDynamicLinksAppDelegateInterceptor sharedInstance]; 

  self.moduleName = @"casualjob";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  [RNFBAppCheckModule sharedInstance]; 
  [FIRApp configure];

  // react-native-fbsdk-next installation
  [[FBSDKApplicationDelegate sharedInstance] application:application
    didFinishLaunchingWithOptions:launchOptions];

  return [super application:application didFinishLaunchingWithOptions:launchOptions]; 
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// react-native-fbsdk-next installation
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  // [FBAEMReporter configureWithNetworker:nil appID:@"xxxxx" reporter:nil]; 
  // [FBAEMReporter enable];
  // [FBAEMReporter handleURL:url];

  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}
@end
```

## Podfile
```javascript
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.0'
# platform :ios, min_ios_version_supported

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'casualjob' do
  rn_maps_path = '../node_modules/react-native-maps'      
  pod 'react-native-google-maps', :path => rn_maps_path   

  config = use_native_modules!

  #   Note - Hermes:A fix was put in place in react-native release 0.69.1 that makes it work with and without Hermes. To use it with Hermes make sure you have set static linkage with use_frameworks! :linkage => :static.
  #   https://rnfirebase.io/#altering-cocoapods-to-use-frameworks
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  # use_frameworks!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $FirebaseSDKVersion = '10.7.0' 

  target 'casualjobTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      if (target.name.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ENABLE_BITCODE"] = "NO"
      end
    end

    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
    end

    # react-native-fbsdk-next installation 
    # Mixing Swift and Objective-C in a react-native project may be problematic.
    # Workaround:  https://github.com/facebookarchive/react-native-fbsdk/issues/755#issuecomment-787488994
    installer.aggregate_targets.first.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']
      end
    end

  end
end
```
## Environment

```
Binaries:
  Node:
    version: 18.15.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.03.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/macbilal/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.7.6
    path: /Users/macbilal/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by Bilal-Abdeen** [comment]
I followed the instructions on the Facebook SDK official page. Then, I removed what I did, and followed the instructions for this library. It seems that this was NOT enough to undo what I have done when I followed the instructions on the Facebook SDK official page.

I created the project from scratch; the problem was fixed.

**Comment by XeeshanAnsari** [comment]
I am having the same error

Undefined symbol: _FBLinkable_NSProcessInfo_MacCatalystDetermining
Undefined symbol: _FBLinkable_NSProcessInfo_OperatingSystemVersionComparing
Undefined symbol: _FBLinkable_UIPasteboard_FBSDKPasteboard

**Comment by EmilianoCervantesOfferUp** [comment]
Having the same issue with a fresh project:

1. react-native: 0.72.4
2. react-native-fbsdk-next: ^12.1.0

Followed the official fb guide and the npm lib docs.

```
Undefined symbols for architecture x86_64:
  "_FBLinkable_NSProcessInfo_MacCatalystDetermining", referenced from:
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKSendButtonManager.o)
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKMessageDialog.o)
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKAuthenticationToken.o)
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKAppLink.o)
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKGameRequestDialog.o)
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKSettings.o)
      _FBLink_NSProcessInfo_MacCatalystDetermining in libreact-native-fbsdk-next.a(RCTFBSDKGraphRequestManager.o)
      ...
  "_FBLinkable_NSProcessInfo_OperatingSystemVersionComparing", referenced from:
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKSendButtonManager.o)
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKMessageDialog.o)
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKAuthenticationToken.o)
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKAppLink.o)
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKGameRequestDialog.o)
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKSettings.o)
      _FBLink_NSProcessInfo_OperatingSystemVersionComparing in libreact-native-fbsdk-next.a(RCTFBSDKGraphRequestManager.o)
      ...
  "_FBLinkable_UIPasteboard_FBSDKPasteboard", referenced from:
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKSendButtonManager.o)
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKMessageDialog.o)
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKAuthenticationToken.o)
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKAppLink.o)
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKGameRequestDialog.o)
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKSettings.o)
      _FBLink_UIPasteboard_FBSDKPasteboard in libreact-native-fbsdk-next.a(RCTFBSDKGraphRequestManager.o)
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by pedroohcs** [comment]
Having the same issue

**Comment by nurmanbe7ov** [comment]
> I am having the same error
> 
> Undefined symbol: _FBLinkable_NSProcessInfo_MacCatalystDetermining Undefined symbol: _FBLinkable_NSProcessInfo_OperatingSystemVersionComparing Undefined symbol: _FBLinkable_UIPasteboard_FBSDKPasteboard

I'm having the same errors right now during build. did you get it resolved?

**Comment by BelenDeAmorrortu** [comment]
> ```objc++
> #import <FBSDKCoreKit/FBSDKCoreKit.h>
> ```

Same issue here. Did anyone find a solution?

**Comment by BelenDeAmorrortu** [comment]
> I am having the same error
> 
> Undefined symbol: _FBLinkable_NSProcessInfo_MacCatalystDetermining Undefined symbol: _FBLinkable_NSProcessInfo_OperatingSystemVersionComparing Undefined symbol: _FBLinkable_UIPasteboard_FBSDKPasteboard

Same issue here. Did anyone find a solution?

**Comment by etch01** [comment]
> ## 🐛 Bug Report
> Whenever I build my project (for iOS), I get the errors below! It works fine for Android. This started after I upgraded all libraries I am using, including react-native.
> 
> I was using `0.71.8` and react-native-fbsdk-next version `7.2.0`.
> 
> Now, I am using react-native `0.72.1` and react-native-fbsdk-next version `11.2.1`.
> 
> * I added an empty file called `File.swift` to my project folder.
> * On Xcode, the iOS deployment target is set to `13.0`
> * On Xcode, the minimum deployment is set to iOS `12.0`
> 
> ```
> Undefined symbol: _FBLinkable_NSBundle_InfoDictionaryProviding
> Undefined symbol: _FBLinkable_NSData_FileDataExtracting
> Undefined symbol: _FBLinkable_NSFileManager_FileManaging
> Undefined symbol: _FBLinkable_NSNotificationCenter_NotificationDelivering
> Undefined symbol: _FBLinkable_NSNotificationCenter_NotificationPosting
> Undefined symbol: _FBLinkable_NSProcessInfo_MacCatalystDetermining
> Undefined symbol: _FBLinkable_NSProcessInfo_OperatingSystemVersionComparing
> Undefined symbol: _FBLinkable_NSURLSessionTask_NetworkTask
> Undefined symbol: _FBLinkable_NSURLSession_URLSessionProviding
> Undefined symbol: _FBLinkable_NSUserDefaults_DataPersisting
> Undefined symbol: _OBJC_CLASS_$_FBSDKApplicationDelegate
> Undefined symbol: _OBJC_CLASS_$_FIRApp
> Undefined symbol: _OBJC_CLASS_$_GMSServices
> Undefined symbol: _OBJC_CLASS_$_Orientation
> Undefined symbol: _OBJC_CLASS_$_RCTAppDelegate
> Undefined symbol: _OBJC_CLASS_$_RCTLinkingManager
> Undefined symbol: _OBJC_CLASS_$_RNFBAppCheckModule
> Undefined symbol: _OBJC_CLASS_$_RNFBDynamicLinksAppDelegateInterceptor
> Undefined symbol: _OBJC_METACLASS_$_RCTAppDelegate
> ```
> 
> ## To Reproduce
> ## AppDelegate.mm
> ```objc++
> #import "RNFBMessagingModule.h"
> #import "AppDelegate.h"
> #import <React/RCTBundleURLProvider.h>
> #import <Firebase.h>
> #import "RNFBAppCheckModule.h"
> #import <GoogleMaps/GoogleMaps.h>
> 
> #import <React/RCTLinkingManager.h>
> #import <RNFBDynamicLinksAppDelegateInterceptor.h>  
> 
> // react-native-fbsdk-next installation
> // #import <FBSDKCoreKit/FBSDKCoreKit.h> // 2 errors: Use of undeclared identifier 'FBSDKApplicationDelegate'
> #import <FBSDKCoreKit/FBSDKCoreKit-Swift.h> // many errors: Undefined symbol .....
> // #import <FBAEMKit/FBAEMKit.h>
> 
> #import "Orientation.h"
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   [GMSServices provideAPIKey:@"xxxxx"]; 
>   [RNFBDynamicLinksAppDelegateInterceptor sharedInstance]; 
> 
>   self.moduleName = @"casualjob";
>   // You can add your custom initial props in the dictionary below.
>   // They will be passed down to the ViewController used by React Native.
>   self.initialProps = @{};
> 
>   [RNFBAppCheckModule sharedInstance]; 
>   [FIRApp configure];
> 
>   // react-native-fbsdk-next installation
>   [[FBSDKApplicationDelegate sharedInstance] application:application
>     didFinishLaunchingWithOptions:launchOptions];
> 
>   return [super application:application didFinishLaunchingWithOptions:launchOptions]; 
> }
> 
> - (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
> {
> #if DEBUG
>   return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
> #else
>   return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
> #endif
> }
> 
> // react-native-fbsdk-next installation
> - (BOOL)application:(UIApplication *)app
>             openURL:(NSURL *)url
>             options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
> {
>   // [FBAEMReporter configureWithNetworker:nil appID:@"xxxxx" reporter:nil]; 
>   // [FBAEMReporter enable];
>   // [FBAEMReporter handleURL:url];
> 
>   if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
>     return YES;
>   }
> 
>   if ([RCTLinkingManager application:app openURL:url options:options]) {
>     return YES;
>   }
> 
>   return NO;
> }
> 
> - (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
>  restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
> {
>  return [RCTLinkingManager application:application
>                   continueUserActivity:userActivity
>                     restorationHandler:restorationHandler];
> }
> 
> - (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
>   return [Orientation getOrientation];
> }
> @end
> ```
> 
> ## Podfile
> ```js
> # Resolve react_native_pods.rb with node to allow for hoisting
> require Pod::Executable.execute_command('node', ['-p',
>   'require.resolve(
>     "react-native/scripts/react_native_pods.rb",
>     {paths: [process.argv[1]]},
>   )', __dir__]).strip
> 
> platform :ios, '13.0'
> # platform :ios, min_ios_version_supported
> 
> prepare_react_native_project!
> 
> # If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
> # because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
> #
> # To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
> # ```js
> # module.exports = {
> #   dependencies: {
> #     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
> # ```
> flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
> 
> linkage = ENV['USE_FRAMEWORKS']
> if linkage != nil
>   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
>   use_frameworks! :linkage => linkage.to_sym
> end
> 
> target 'casualjob' do
>   rn_maps_path = '../node_modules/react-native-maps'      
>   pod 'react-native-google-maps', :path => rn_maps_path   
> 
>   config = use_native_modules!
> 
>   #   Note - Hermes:A fix was put in place in react-native release 0.69.1 that makes it work with and without Hermes. To use it with Hermes make sure you have set static linkage with use_frameworks! :linkage => :static.
>   #   https://rnfirebase.io/#altering-cocoapods-to-use-frameworks
>   use_frameworks! :linkage => :static
>   $RNFirebaseAsStaticFramework = true
>   # use_frameworks!
> 
>   # Flags change depending on the env values.
>   flags = get_default_flags()
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     # Hermes is now enabled by default. Disable by setting this flag to false.
>     :hermes_enabled => flags[:hermes_enabled],
>     :fabric_enabled => flags[:fabric_enabled],
>     # Enables Flipper.
>     #
>     # Note that if you have use_frameworks! enabled, Flipper will not work and
>     # you should disable the next line.
>     # :flipper_configuration => flipper_config,
> 
>     # An absolute path to your application root.
>     :app_path => "#{Pod::Config.instance.installation_root}/.."
>   )
> 
>   $FirebaseSDKVersion = '10.7.0' 
> 
>   target 'casualjobTests' do
>     inherit! :complete
>     # Pods for testing
>   end
> 
>   post_install do |installer|
>     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
>     react_native_post_install(
>       installer,
>       config[:reactNativePath],
>       :mac_catalyst_enabled => false
>     )
> 
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
> 
>     installer.pods_project.targets.each do |target|
>       if (target.name.eql?('FBReactNativeSpec'))
>         target.build_phases.each do |build_phase|
>           if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
>             target.build_phases.move(build_phase, 0)
>           end
>         end
>       end
>     end
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings["ENABLE_BITCODE"] = "NO"
>       end
>     end
> 
>     installer.pods_project.targets.each do |target|
>       if target.name == 'react-native-google-maps'
>         target.build_configurations.each do |config|
>           config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
>         end
>       end
>     end
> 
>     # react-native-fbsdk-next installation 
>     # Mixing Swift and Objective-C in a react-native project may be problematic.
>     # Workaround:  https://github.com/facebookarchive/react-native-fbsdk/issues/755#issuecomment-787488994
>     installer.aggregate_targets.first.user_project.native_targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']
>       end
>     end
> 
>   end
> end
> ```
> 
> ## Expected Behavior
> ## Code Example
> ## Environment
> ```
> Binaries:
>   Node:
>     version: 18.15.0
>     path: /usr/local/bin/node
>   Yarn:
>     version: 1.22.19
>     path: /usr/local/bin/yarn
>   npm:
>     version: 9.5.0
>     path: /usr/local/bin/npm
>   Watchman:
>     version: 2023.03.27.00
>     path: /usr/local/bin/watchman
> Managers:
>   CocoaPods:
>     version: 1.12.0
>     path: /Users/macbilal/.rbenv/shims/pod
> SDKs:
>   iOS SDK:
>     Platforms:
>       - DriverKit 22.2
>       - iOS 16.2
>       - macOS 13.1
>       - tvOS 16.1
>       - watchOS 9.1
>   Android SDK: Not Found
> IDEs:
>   Android Studio: Not Found
>   Xcode:
>     version: 14.2/14C18
>     path: /usr/bin/xcodebuild
> Languages:
>   Java: Not Found
>   Ruby:
>     version: 2.7.6
>     path: /Users/macbilal/.rbenv/shims/ruby
> npmPackages:
>   "@react-native-community/cli": Not Found
>   react:
>     installed: 18.2.0
>     wanted: 18.2.0
>   react-native:
>     installed: 0.72.1
>     wanted: 0.72.1
>   react-native-macos: Not Found
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: true
>   newArchEnabled: false
> iOS:
>   hermesEnabled: true
>   newArchEnabled: false
> ```

add to your pod file:
```
installer.aggregate_targets.first.user_project.native_targets.each do |target|
   target.build_configurations.each do |config|
     config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']
   end
 end
```

or add a new file named File.Swift in the main project folder and answer "yes" when Xcode asks you if you want to "Create Bridging Header"
