### ISSUE TITLE
FBSDK is blocked at version 9.0.1 and can't be updated to 9.3.0

### ISSUE THREAD

**Issue by bcomeau** [thebergamo/react-native-fbsdk-next#44]
## 🐛 Bug Report
It looks like the FBSDK is blocked to **9.0.x** by the CocoaPods optimistic operator since commit [6b67a79](https://github.com/thebergamo/react-native-fbsdk-next/commit/6b67a79733042183030641d55ea1bc9a9f90a076#diff-f4c4b7d6d9cdd78a219cf71d0e6419ccd036dc5705d62b5f299e6cbbe2c2354b) in `react-native-fbsdk-next.podspec`

## To Reproduce
Run `pod update` and look a the FBSDK version in the `Podfile.lock` (9.0.1)

## Expected Behavior
Running `pod update` should update the FBSDK to the latest version (currently 9.3.0)

**Comment by mikehardy** [comment]
So, a PR to change the podspect to `'~> 9'` would work?
How does it work when you make that change locally?

**Comment by bcomeau** [comment]
It does in fact work. I'm currently testing that there is no other impact.

**Comment by bcomeau** [comment]
It won't be that simple.
The build fails.


```
❌  .../node_modules/react-native-fbsdk-next/ios/RCTFBSDK/core/RCTFBSDKAppEvents.m:101:53: no known class method for selector 'advertiserID'

NSString *advertiserID = [FBSDKAppEventsUtility advertiserID];
```

**Comment by mikehardy** [comment]
This may be why we pin it ;-)
