### ISSUE TITLE
Tracking Events is NOT Working on iOS

### ISSUE THREAD

**Issue by Bilal-Abdeen** [thebergamo/react-native-fbsdk-next#442]
## 🐛 Bug Report

Tracking of (1) application installations, (2) application activations, and (3) events are NOT working on iOS. It is working fine on Android. 

Note: it says on the Facebook Events Manager: `Your app is out of date. To run your app on iOS 14, update to the latest Facebook SDK for iOS.` Then, it suggests adding the following. When I tried adding the following, I got the error message `Specs satisfying the FBSDKCoreKit (~> 8.0.0), FBSDKCoreKit (= 15.0.0, ~> 15.0.0) dependency were found, but they required a higher minimum deployment target.`. I think the suggestion to update the app is misleading! 
```
pod 'FBSDKCoreKit', '~> 8.0.0'
pod 'FBSDKLoginKit', '~> 8.0.0'
pod 'FBSDKShareKit', '~> 8.0.0'
```

## To Reproduce

**Configuration:**
1. Apple store > App Privacy > Usage Data > Product Interaction > "Developer’s Advertising or Marketing" > Next > Next > Next > "Tracking" > user data is tracked
2. `Info.plist` > add `NSUserTrackingUsageDescription` + other FB-properties
3. to initialise the SDK, I added `[FBSDKApplicationDelegate.sharedInstance initializeSDK];` to `AppDelegate.mm`
4. Enable ATT (App Tracking Transparency) using `requestTrackingPermission()` (from `react-native-tracking-transparency`)
5. Just in case the initialisation in AppDelegate.mm (above) did NOT work, I called `Settings.initializeSDK()` after getting ATT (App Tracking Transparency) permission
6. After enabling ATT, I call `setAdvertiserTrackingEnabled(true)`

**Device Considerations:** 
7. iPhone > Settings > Privacy > Tracking > Make sure it is enabled it for Facebook app & my app 
8. Facebook app is running in the background on the device and logged in to an account
9. Testing is done on a real device (NOT a simulator)

**Testing Steps**
1. Visit the Facebook Events Manager Page: `https://business.facebook.com/events_manager2/list/dataset/xxxxx/test_events?business_id=xxxxxx&nav_source=task_center`
2. Install the app on an iPhone. I tried iPhone XR having `iOS: 15.3.1`. Then, I updated iOS to `16.5.1`. This did NOT help. 
3. Trigger some event: `AppEventsLogger.logEvent("testing_event");`

## Expected Behavior

Events should be displayed on Facebook Events Manager `https://business.facebook.com/events_manager2/list/dataset/xxxxx/test_events?business_id=xxxxxx&nav_source=task_center`

## AppDelegate.mm
```mm
#import "RNFBMessagingModule.h"

#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <Firebase.h>
#import "RNFBAppCheckModule.h"
#import <GoogleMaps/GoogleMaps.h>
#import <React/RCTLinkingManager.h>
#import <RNFBDynamicLinksAppDelegateInterceptor.h>  
#import "Orientation.h"

#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h> 
#import <FBAEMKit/FBAEMKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [GMSServices provideAPIKey:@"xxxxxxxx"]; 
  [RNFBDynamicLinksAppDelegateInterceptor sharedInstance]; 

  self.moduleName = @"xxxx";
  self.initialProps = @{};

  [RNFBAppCheckModule sharedInstance]; 
  [FIRApp configure];

  [[FBSDKApplicationDelegate sharedInstance] application:application
    didFinishLaunchingWithOptions:launchOptions];

  // I am expecting this would enable tracking very early, and consequently, app installations and activations would be tracked. 
  [FBSDKApplicationDelegate.sharedInstance initializeSDK];

  return [super application:application didFinishLaunchingWithOptions:launchOptions]; 
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [FBAEMReporter configureWithNetworker:nil appID:@"xxxxxx" reporter:nil]; 
  [FBAEMReporter enable];
  [FBAEMReporter handleURL:url];

  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}

@end
```

## Info.plist
```xml
....
<key>NSUserTrackingUsageDescription</key>
<string>To help us optimise our Ads, this app needs to track some of your app-related activity while using the app.</string>
...
```

## Code Example

```javascript 
const trackingStatus = await requestTrackingPermission(); 
if (trackingStatus === "authorized" || trackingStatus === "unavailable") {
	Settings.initializeSDK();
	await Settings.setAdvertiserTrackingEnabled(true); 
	AppEventsLogger.logEvent("testing_event");
}
```
## Environment

react-native-fbsdk-next version: `11.2.1`
```
Binaries:
  Node:
    version: 18.15.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.03.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/macbilal/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.7.6
    path: /Users/macbilal/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by JCaraballo113** [comment]
I can confirm this since our Facebook Ad Campaign app install attribution is 100% not working unfortunately. We have no way of measuring which campaign ads are triggering app installs which is a big sad

**Comment by pkayfire** [comment]
@JCaraballo113 do you have any pointers on how to implement server side tracking? We're running into the same issue on iOS with AEM installs not tracking properly.

**Comment by JCaraballo113** [comment]
@pkayfire my project for the next week. Will report back and probably do a tutorial on it when I'm done because so far it's COMPLEX

**Comment by FeidaMeng** [comment]
@Bilal-Abdeen did you try step two of the [guide](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios). I did, but still doesn't work

**Comment by duongdinh98** [comment]
Still not work with latest v12.0.0 release

**Comment by felipecro28** [comment]
still not working .. any solutions ?

**Comment by 1jmj** [comment]
Really need a solution for this... I'm not a swift/native programmer so cannot suggest, but happy to test anyone else's solution

**Comment by dmitriiivashko** [comment]
Having the same issue here

**Comment by mikehardy** [comment]
Please reactions instead of +1s
It's open source, please post PRs or post comments that advance the issue with new information showing how to reliably reproduce the problem and under exactly what conditions
Please make sure that indeed you *are* on the latest versions following all the latest guides upstream and that if doing so requires you update minimum targets etc you do that

I do not personally use tracking events and I'm not aware of anyone else that volunteers even a minute of their time in this repo, so I will not be able to help much unfortunately (besides merging reasonable PRs...) and I don't believe anyone else will either

So if this is to be solved, some interested party here will have to do it...

**Comment by dmitriiivashko** [comment]
I have investigated the problem, and I can no longer reproduce the issue on the latest version.
Some of my clients complained that their events aren't being tracked, but all of them had the invalid token in their facebook configs.

A friendly reminder: a few SDK versions back, facebook introduced app tokens. To correctly configure facebook, you now not only need the app id, but also the app token from the facebook dev portal. Providing an invalid token doesn't crash the app, but the events are no longer being tracked.

I bet some of you have issues related to tokens.

**Comment by davidg327** [comment]
Thanks to the previous message you can see and review and with the new version that there is, there is a variable called setClienteToken, if you put the secret token there, it starts serving me like this and started taking the events.

This is how I have the code in the app.tsx, I know that having the client ID may not be necessary but I put it in by default

`useEffect(() => {
    Settings.initializeSDK()
    Settings.setAppID('')
    Settings.setClientToken('')
}, [])`

I hope it works for you

**Comment by built-by-as** [comment]
> Please reactions instead of +1s It's open source, please post PRs or post comments that advance the issue with new information showing how to reliably reproduce the problem and under exactly what conditions Please make sure that indeed you _are_ on the latest versions following all the latest guides upstream and that if doing so requires you update minimum targets etc you do that
> 
> I do not personally use tracking events and I'm not aware of anyone else that volunteers even a minute of their time in this repo, so I will not be able to help much unfortunately (besides merging reasonable PRs...) and I don't believe anyone else will either
> 
> So if this is to be solved, some interested party here will have to do it...

I can try looking, any high level ideas on how to repro and diagnose?

**Comment by Kouznetsov** [comment]
@Bilal-Abdeen Did you end up finding a solution? 

On my end, it looks like the events are properly sent, the Facebook Dashboard does report installs when building on a device, but even though the fbsdk's podspec downloads the correct pods, Facebook still yells at me, telling my version is out of date. Maybe it thinks so because there's something that we're configuring in an old fashioned way, which Facebook interprets as the usage of a deprecated library?

**Comment by Bilal-Abdeen** [comment]
@Kouznetsov I have decided not to enable events tracking at all on iOS! I think users would NOT like to be asked to accept tracking before even trying to use the app! NOT having detailed tracking data is better than turning customers away before even starting to use the app!

**Comment by Kouznetsov** [comment]
Fair enough.

FYI, after a few days, Facebook ended up letting me create an iOS 14.5+ ads campaign. So I guess everything was actually fine, we just have to wait for them to notice that.
