### ISSUE TITLE
Doesnt seem to work that well in Typescript

### ISSUE THREAD

**Issue by superm123** [thebergamo/react-native-fbsdk-next#443]
## 🐛 Bug Report

When using plugin in Typescript enviornment it creates these errors:
`export 'default' (imported as 'Settings') was not found in 'react-native-fbsdk-next' (possible exports: AEMReporterIOS, AccessToken, AccessTokenMap, AppEvent, AppEventParam, AppEventsFlushBehavior, AppEventsLogger, AppLink, AuthenticationToken, AuthenticationTokenMap, DefaultAudience, Event, GameRequestDialog, GameRequestDialogResult, GraphRequest, GraphRequestCallback, GraphRequestConfig, GraphRequestManager, GraphRequestParameters, LoginBehavior, LoginBehaviorAndroid, LoginBehaviorIOS, LoginButton, LoginManager, LoginResult, LoginTracking, MessageDialog, MessageDialogResult, Params, ProductAvailability, ProductCondition, Profile, ProfileMap, RNFBSDKCallback, SendButton, Settings, ShareButton, ShareContent, ShareContentCommonParameters, ShareDialog, ShareDialogMode, ShareDialogModeAndroid, ShareDialogModeIOS, ShareDialogResult, ShareLinkContent, SharePhotoContent, ShareVideoContent, TooltipBehaviorIOS, UserData)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/FBLoginButton.js 88:25-47
export 'requireNativeComponent' (imported as 'requireNativeComponent') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, DeviceInfo, Dimensions, DrawerLayoutAndroid, Easing, FlatList, I18nManager, Image, ImageBackground, InputAccessoryView, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, PermissionsAndroid, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Settings, Share, StatusBar, StyleSheet, Switch, Systrace, TVEventHandler, Text, TextInput, ToastAndroid, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, VirtualizedList, YellowBox, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/FBSendButton.js 53:24-46
export 'requireNativeComponent' (imported as 'requireNativeComponent') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, DeviceInfo, Dimensions, DrawerLayoutAndroid, Easing, FlatList, I18nManager, Image, ImageBackground, InputAccessoryView, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, PermissionsAndroid, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Settings, Share, StatusBar, StyleSheet, Switch, Systrace, TVEventHandler, Text, TextInput, ToastAndroid, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, VirtualizedList, YellowBox, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/FBShareButton.js 53:25-47
export 'requireNativeComponent' (imported as 'requireNativeComponent') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, DeviceInfo, Dimensions, DrawerLayoutAndroid, Easing, FlatList, I18nManager, Image, ImageBackground, InputAccessoryView, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, PermissionsAndroid, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Settings, Share, StatusBar, StyleSheet, Switch, Systrace, TVEventHandler, Text, TextInput, ToastAndroid, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, VirtualizedList, YellowBox, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 22:0-73
export 'AccessTokenMap' (reexported as 'AccessTokenMap') was not found in './FBAccessToken' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 23:0-97
export 'AuthenticationTokenMap' (reexported as 'AuthenticationTokenMap') was not found in './FBAuthenticationToken' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'AppEventsFlushBehavior' (reexported as 'AppEventsFlushBehavior') was not found in './FBAppEventsLogger' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'ProductAvailability' (reexported as 'ProductAvailability') was not found in './FBAppEventsLogger' (possible exports: default)      

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'ProductCondition' (reexported as 'ProductCondition') was not found in './FBAppEventsLogger' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'Params' (reexported as 'Params') was not found in './FBAppEventsLogger' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'UserData' (reexported as 'UserData') was not found in './FBAppEventsLogger' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'AppEvent' (reexported as 'AppEvent') was not found in './FBAppEventsLogger' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 24:0-171
export 'AppEventParam' (reexported as 'AppEventParam') was not found in './FBAppEventsLogger' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 26:0-94
export 'GameRequestDialogResult' (reexported as 'GameRequestDialogResult') was not found in './FBGameRequestDialog' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 27:0-125
export 'GraphRequestCallback' (reexported as 'GraphRequestCallback') was not found in './FBGraphRequest' (possible exports: default)       

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 27:0-125
export 'GraphRequestConfig' (reexported as 'GraphRequestConfig') was not found in './FBGraphRequest' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 27:0-125
export 'GraphRequestParameters' (reexported as 'GraphRequestParameters') was not found in './FBGraphRequest' (possible exports: default)   

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 29:0-159
export 'DefaultAudience' (reexported as 'DefaultAudience') was not found in './FBLoginManager' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 29:0-159
export 'LoginBehavior' (reexported as 'LoginBehavior') was not found in './FBLoginManager' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 29:0-159
export 'LoginBehaviorAndroid' (reexported as 'LoginBehaviorAndroid') was not found in './FBLoginManager' (possible exports: default)       

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 29:0-159
export 'LoginBehaviorIOS' (reexported as 'LoginBehaviorIOS') was not found in './FBLoginManager' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 29:0-159
export 'LoginResult' (reexported as 'LoginResult') was not found in './FBLoginManager' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 29:0-159
export 'LoginTracking' (reexported as 'LoginTracking') was not found in './FBLoginManager' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 30:0-82
export 'MessageDialogResult' (reexported as 'MessageDialogResult') was not found in './FBMessageDialog' (possible exports: default)        

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 31:0-61
export 'ProfileMap' (reexported as 'ProfileMap') was not found in './FBProfile' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 33:0-137
export 'ShareDialogMode' (reexported as 'ShareDialogMode') was not found in './FBShareDialog' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 33:0-137
export 'ShareDialogModeAndroid' (reexported as 'ShareDialogModeAndroid') was not found in './FBShareDialog' (possible exports: default)    

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 33:0-137
export 'ShareDialogModeIOS' (reexported as 'ShareDialogModeIOS') was not found in './FBShareDialog' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 33:0-137
export 'ShareDialogResult' (reexported as 'ShareDialogResult') was not found in './FBShareDialog' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 34:0-84
export 'Event' (reexported as 'Event') was not found in './FBLoginButton' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 34:0-84
export 'TooltipBehaviorIOS' (reexported as 'TooltipBehaviorIOS') was not found in './FBLoginButton' (possible exports: default)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 39:0-85
export 'ShareContent' (reexported as 'ShareContent') was not found in './models/FBShareContent' (module has no exports)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 39:0-85
export 'ShareContentCommonParameters' (reexported as 'ShareContentCommonParameters') was not found in './models/FBShareContent' (module has no exports)

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 40:0-63
export 'ShareLinkContent' (reexported as 'ShareLinkContent') was not found in './models/FBShareLinkContent' (module has no exports)        

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 41:0-65
export 'SharePhotoContent' (reexported as 'SharePhotoContent') was not found in './models/FBSharePhotoContent' (module has no exports)     

ERROR in ./node_modules/react-native-fbsdk-next/lib/module/index.js 42:0-65
export 'ShareVideoContent' (reexported as 'ShareVideoContent') was not found in './models/FBShareVideoContent' (module has no exports) `
## To Reproduce

Create new react app on Typescript.
in App.tsx:

`import {Settings}  from 'react-native-fbsdk-next';
Settings.setAdvertiserTrackingEnabled(true);
`
## Expected Behavior

Code should work in typescript as well or a workaround need to be provided
## Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 2.09 GB / 15.69 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-222.4459.24.2221.10121639
    Visual Studio: 17.6.33723.286 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: ^7.0.1 => 7.0.4
    react: 18 => 18.2.0
    react-native: ^0.72.3 => 0.72.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
Not sure what's going on, but I didn't have this problem / do not have this problem ?
Can you reproduce it in the example app ?

**Comment by superm123** [comment]
Steps yo reproduce
Import package in any package that is based on typescript
