### ISSUE TITLE
Login on Android gets stuck with error message 'ERR_TOO_MANY_REDIRECTS'

### ISSUE THREAD

**Issue by t-tornado** [thebergamo/react-native-fbsdk-next#444]
Issue:
I am unable to complete the login on android using the Button or LoginManager. it gets stuck on the Web page and shows 'ERR_TOO_MANY_REDIRECTS'. 

System:

`    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 65.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /var/folders/p7/5hr1nq4s0jx2b9bxph6fz0_h0000gn/T/yarn--1691464971619-0.3818947441367595/node
    Yarn: 1.22.19 - /var/folders/p7/5hr1nq4s0jx2b9bxph6fz0_h0000gn/T/yarn--1691464971619-0.3818947441367595/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
     react-native-fbsdk-next: 11.1.0
`

Component
` <LoginButton
            onLoginFinished={(error, result: any) => {
              if (error) {
                console.log('login has error: ' + result.error);
              } else if (result.isCancelled) {
                console.log('login is cancelled.');
              } else {
                AccessToken.getCurrentAccessToken().then((data: any) => {
                  console.log(data.accessToken.toString());
                });
              }
            }}
            onLogoutFinished={() => console.log('logout.')}
          />`

ScreenShot

![Screenshot_1691464896](https://github.com/thebergamo/react-native-fbsdk-next/assets/60879439/e94f68ec-1413-40b1-ad1c-0cc94fa7732a)

PS: I have completed all the required steps in the Facebook Android integration page

**Comment by kesha-antonov** [comment]
Hi
Did you find a solution?
