### ISSUE TITLE
unable to build app 11.3.0 -> 12.1.0

### ISSUE THREAD

**Issue by ethanneff** [thebergamo/react-native-fbsdk-next#448]
the following error shows even after following the guide https://github.com/thebergamo/react-native-fbsdk-next/releases/tag/v12.0.0

```ts
❌  /Users/user/Library/Developer/Xcode/DerivedData/core-bjnxatkygohicofepkatfwbrgkks/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBSDKCoreKit/FBSDKCoreKit.framework/Headers/FBSDKCoreKit-swift.h:1127:146: cannot find protocol declaration for 'SFSafariViewControllerDelegate'

@interface _BridgeAPI : NSObject <FBSDKBridgeAPIRequestOpening, FBSDKApplicationObserving, FBSDKURLOpener, FBSDKContainerViewControllerDelegate, SFSafariViewControllerDelegate>
            ^



❌  /Users/user/Library/Developer/Xcode/DerivedData/core-bjnxatkygohicofepkatfwbrgkks/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBSDKCoreKit/FBSDKCoreKit.framework/Headers/FBSDKCoreKit-swift.h:1142:56: cannot find protocol declaration for 'ASWebAuthenticationPresentationContextProviding'

@interface _BridgeAPI (SWIFT_EXTENSION(FBSDKCoreKit)) <ASWebAuthenticationPresentationContextProviding>
                                                                                                                                                 ^



❌  /Users/user/Library/Developer/Xcode/DerivedData/core-bjnxatkygohicofepkatfwbrgkks/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FBSDKCoreKit/FBSDKCoreKit.framework/Headers/FBSDKCoreKit-swift.h:1143:4: expected a type

- (ASPresentationAnchor _Nonnull)presentationAnchorForWebAuthenticationSession:(ASWebAuthenticationSession * _Nonnull)session SWIFT_WARN_UNUSED_RESULT;
```

**Comment by DarkShtir** [comment]
Same issue

**Comment by DarkShtir** [comment]
Renaming AppDelegate.mm to AppDelegate.m fixed this issue

But i found this issue https://github.com/facebook/facebook-ios-sdk/issues/2183

**Comment by jreybaylen** [comment]
> Same issue
> 
> "react-native": "0.71.13", "react-native-fbsdk-next": "^12.1.0",
> 
> used AppDelegate.mm
> 
> Added this imports
> 
> ```
> #import <FBSDKCoreKit/FBSDKCoreKit-swift.h>
> #import <FBAEMKit/FBAEMKit-Swift.h>
> #import <AuthenticationServices/AuthenticationServices.h>
> #import <SafariServices/SafariServices.h>
> ```
> 
> in other project which use Appdelegate.m all alright

Please check this answer https://github.com/facebook/facebook-ios-sdk/issues/2183#issuecomment-1693569643

**Comment by sergeymild** [comment]
the same issue
<img width="1105" alt="Screenshot 2023-11-02 at 11 08 46 AM" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/3685209/6ec345e5-ec5a-4a0d-9024-210203b46afb">

**Comment by usmanabid94** [comment]
is there any update on this i am also facing the same issue on latest version of     "react-native-fbsdk-next": "^13.0.0",
@ethanneff @sergeymild @jreybaylen @DarkShtir @reidab

**Comment by wercks** [comment]
Change the order of imports 

**FROM**

```
#import <AuthenticationServices/AuthenticationServices.h>
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
#import <SafariServices/SafariServices.h>
```

**TO**

```
#import <AuthenticationServices/AuthenticationServices.h>
#import <SafariServices/SafariServices.h>
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
```
