### ISSUE TITLE
Does this lib use Open Graph?

### ISSUE THREAD

**Issue by rafaelsevla** [thebergamo/react-native-fbsdk-next#449]
I got an email about Open Graph saying the version I'm using is deprecated, but I didn't find anything in the code other than this lib
I wanted to know if this lib makes use of the Open Graph/Graph API

**Comment by PouyaLitkouhi** [comment]
Hi,
This library actually contains Graph API, there is a method to set the version `setGraphAPIVersion` 
But I also have the same question, I got a similar message, but since we are not using it, do we need to do something about it or not?
here are the methods I'm using in my app:

```js
Settings.setDataProcessingOptions
Settings.setAdvertiserTrackingEnabled
LoginManager, 
AccessToken
```

**Comment by rafaelsevla** [comment]
do you know which version of Open Graph is used by default?

**Comment by rafaelsevla** [comment]
On facebook developers i found where we are using Open Graph version!

Now my doubt is: up to which Open Graph version does the react-native-fbsdk-next lib support?

if I change Open Graph on facebook developers to version 12 or 13 will my application break?

![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/38443896/786871f4-d346-4a08-a6e7-03d482981f24)

**Comment by livnunes** [comment]
> On facebook developers i found where we are using Open Graph version!
> 
> Now my doubt is: up to which Open Graph version does the react-native-fbsdk-next lib support?
> 
> if I change Open Graph on facebook developers to version 12 or 13 will my application break?
> 
> ![image](https://user-images.githubusercontent.com/38443896/263011490-786871f4-d346-4a08-a6e7-03d482981f24.png)

I took a look at their API Upgrade Tool and there it says I don't need to make any changes, still a bit worried if I can just set the version in those drop downs to the most updated version without having any issues.

**Comment by PouyaLitkouhi** [comment]
I used `Settings.setGraphAPIVersion('v17.0')` but not sure if that helps or not, I checked the login and authentication flows and everything is working as before.
any updates? do we even need to touch anything inside the code? or it's something we need to change only via the Facebook dashboard?

**Comment by joan-saum** [comment]
Hi!
Any update on this? The version 14 of Graph API will be deprecated soon and I'm not sure if we have to change something about it.
