### ISSUE TITLE
Graph API v11.0

### ISSUE THREAD

**Issue by joaolvcas** [thebergamo/react-native-fbsdk-next#451]
I recently received this message from **Facebook**:

"Your application, "My App Name", is currently accessing Graph API v11.0 which will reach the end of its 2 year lifespan on September 14, 2023. To ensure a smooth transition please migrate all calls to Graph API v12 .0 or higher. Use the [API Upgrade Tool ](https://developers.facebook.com/tools/api_versioning/658541761668650/) to find out exactly how this change will impact your app.

Note: If you don't see any impacted calls in the API Update Tool, your app/code may not be affected by this update.

Please visit our [changelog](https://developers.facebook.com/docs/apps/changelog/)to see the complete list of changes across all versions of the Graph API."

Im using the last version from this SDK and others SDK are higher then 11.0:

![Screen Shot 2023-08-24 at 09 27 40](https://github.com/thebergamo/react-native-fbsdk-next/assets/110208228/ea9ebbe5-d339-4668-8c19-e73193d78cc0)

 "react-native-fbsdk-next": "^11.2.1",
 "react-native": "0.71.7",

**Comment by rafaelsevla** [comment]
I got the same error!
I am researching which version about open graph is using

**Comment by gattigaga** [comment]
Could you try something like this to call Graph API with certain version you need...

<img width="472" alt="Screen Shot 2023-08-29 at 14 30 40" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/23469511/34d86ebb-d6b5-4c55-b50c-68b97e5828ff">

**Comment by Kowshika-aspire** [comment]
> It looks like work, testing right now!

Hey @joaolvcas. Does the above code resolves the Graph API issue ?

**Comment by joaolvcas** [comment]
Exactly, I'm not sure yet. I am testing, for now sounds like work. When I got more information, I send you more feedback.
