### ISSUE TITLE
iOS Events Manager

### ISSUE THREAD

**Issue by bilal-prog** [thebergamo/react-native-fbsdk-next#459]
## 🐛 Bug Report
react-native-fbsdk-next events on ios works on my ios 16.6.1, and it doesn't work on another ios 16.6.1 even the APP_TRACKING_TRANSPARENCY permission is granted

## Code Example

Podfile

permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  
 AppDelegate.mm
 
 #import <FBSDKCoreKit/FBSDKCoreKit-swift.h>
#import <FBAEMKit/FBAEMKit.h>
#import <React/RCTLinkingManager.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>

[FBSDKApplicationDelegate.sharedInstance initializeSDK];

- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{

  [FBAEMReporter configureWithNetworker:nil appID:@"123456789" reporter:nil]; // Replace {app-id} with your Facebook App id
  [FBAEMReporter enable];
  [FBAEMReporter handleURL:url];

  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

App.js

initFbSdk = async () => {
    // fbsdk settings
    Settings.initializeSDK();

    const requestResult = await request(
      PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY,
    );
    // Enable the Advertising tracking flag for IOS 14 devices
    //Settings.setAdvertiserTrackingEnabled(requestResult === RESULTS.GRANTED);

    Settings.setAdvertiserTrackingEnabled(true);

  };

## Environment
 "react-native": "0.69.4",
  "react-native-fbsdk-next": "^11.1.0",

**Comment by mikehardy** [comment]
PRs happily accepted

**Comment by priyankagupta23pg** [comment]
Writing this code
AppEventsLogger.logEvent(AppEventsLogger.AppEvents.ViewedContent, {
"event_name": isIOS?"ios Login screen":"android Login screen",
"event_time": new Date().getMilliseconds(),  });

unable to see parameters on Event manager console..Please clarify where I can see these parameter values
