### ISSUE TITLE
 Could not resolve com.facebook.android:facebook-android-sdk:16.+

### ISSUE THREAD

**Issue by sergeymild** [thebergamo/react-native-fbsdk-next#462]
## 🐛 Bug Report
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:16.+.
     Required by:
         project :app > project :react-native-fbsdk-next
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > Read timed out

**Comment by mikehardy** [comment]
PRs happily accepted

**Comment by naquilini** [comment]
Since a couple of days I'm getting a similar error using version 12.2.0, I was not getting this error before on the same version:

```
Could not resolve all task dependencies for configuration ':app:googlePlayDebugRuntimeClasspath'. >
Could not resolve com.facebook.android:facebook-android-sdk:16.+. 
Required by: project :app > project :react-native-fbsdk-next > Failed to list versions for com.facebook.android:facebook-android-sdk. > 
Unable to load Maven meta-data from https://s3.amazonaws.com/android-listener/mvn-repo/com/facebook/android/facebook-android-sdk/maven-metadata.xml. > 
Could not GET 'https://s3.amazonaws.com/android-listener/mvn-repo/com/facebook/android/facebook-android-sdk/maven-metadata.xml'. Received status code 403 from server
```

https://s3.amazonaws.com/android-listener/mvn-repo/com/facebook/android/facebook-android-sdk/maven-metadata.xml indeed return 403.

Related to: https://github.com/facebook/facebook-android-sdk/issues/1345
