### ISSUE TITLE
mismatch in swift version for expo SDK 49

### ISSUE THREAD

**Issue by Eldar-Jumagaliyev-vas** [thebergamo/react-native-fbsdk-next#465]
<img width="542" alt="Снимок экрана 2023-10-17 в 13 44 32" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/113993585/314623ea-b2d6-4115-a043-10f55bbd6f6d">
<img width="985" alt="Снимок экрана 2023-10-18 в 13 06 33" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/113993585/5d8815b9-f607-4c43-a398-825238d605d6">

## 🐛 Bug Report

failing build through XCode 

## To Reproduce

Build through Xcode

## Expected Behavior

Working build on simulator without errors

## Code Example

```
export async function initFacebookSdk (): Promise<void> {
    await Settings.initializeSDK()
    const { granted } = await requestTrackingPermissionsAsync()
    if (granted) {
        await Settings.setAdvertiserTrackingEnabled(true)
    }
}
```

## Environment

    "react-native": "0.72.5",
    "react": "18.2.0",
    "react-native-fbsdk-next": "12.1.0",
    "expo": "49.0.13",

**Comment by mikehardy** [comment]
Perhaps the facebook-ios-sdk has released a new version and we could adopt it here?
PRs happily accepted

**Comment by Eldar-Jumagaliyev-vas** [comment]
will reopen this issue from my personal account
