### ISSUE TITLE
FB login is not working

### ISSUE THREAD

**Issue by rhuber-rbi** [thebergamo/react-native-fbsdk-next#472]
I'm getting this with 11.2.1 version on ANDROID app 

<img width="714" alt="Captura de pantalla 2023-11-10 a la(s) 16 21 21" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/93785870/44a530c8-5464-4e6d-90c7-5a440cd276bc">

**Comment by mikehardy** [comment]
Lacks a lot of information that could be used to help, like, how you reproduce this... https://stackoverflow.com/help/minimal-reproducible-example

**Comment by rhuber-rbi** [comment]
no time to create an mre, just started to throw this today, It was working last week, no problem I'll investigate this
