### ISSUE TITLE
Limited login doesn't return authentication token

### ISSUE THREAD

**Issue by marcin-piela-800** [thebergamo/react-native-fbsdk-next#475]
Any idea why limited login doesn't return an AuthenticationToken? When I select the Facebook account in the modal window, it redirects me to the app with isCancelled: true every time. It works with non-limited login (I can get AccessToken), but my API requires an authentication token, so limited login is necessary. My Facebook app is live, and I noticed that I can get an AuthenticationToken when the user is assigned to the Facebook app as a test user only

**Comment by mikehardy** [comment]
Sorry to say this isn't a use case for me as the only person normally around this repo as maintainer so I have no idea

Not mentioning that to be unhelpful, but to emphasize that if no one else from the community responds here you'll need to prepare to dig in on wider documentation searches + possibly instrumenting the code here for your app with logs that show more clearly what is going on and hopefully why

I can merge any reasonable PRs though
