### ISSUE TITLE
Is this the correct library for Facebook campaign to promote the app?

### ISSUE THREAD

**Issue by pierroo** [thebergamo/react-native-fbsdk-next#477]
I want to do some ad campaigns on Facebook to promote my app.
  Is this the correct library to use for this very straight forward purpose? (no need for the login / share etc other features)
  
  I basically just want to connect my app to the App ID created on facebook developer and link it with my campaign.

Does the above still require all the steps from the installation? (there are quite a few, with many modifying core files etc)

**Comment by cwkeam** [comment]
Same! Especially considering that react-native-facebook sdk is no longer officially maintained by Meta.

**Comment by pierroo** [comment]
Perhaps @mikehardy has the answer?
I hope it won't be intrusive to tag you here, but I constantly see you contributing to almost every react native libraries so maybe you know for that as well... :)

**Comment by mikehardy** [comment]
I don't know, sorry, my apps are not advertising based so I've never explored any of those use cases

Actionable thing to do: try it and see. Report back. Alternatively ask on stackoverflow
