### ISSUE TITLE
How to change  add appdelegate.mm 

### ISSUE THREAD

**Issue by NadeemKhanFh** [thebergamo/react-native-fbsdk-next#479]
## To Reproduce
this is my current appdelegate
bool didFinish=[super application:application didFinishLaunchingWithOptions:launchOptions];
  //[super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  return didFinish;

how to [[FBSDKApplicationDelegate sharedInstance] application:application
                       didFinishLaunchingWithOptions:launchOptions];

**Comment by mikehardy** [comment]
https://github.com/thebergamo/react-native-fbsdk-next/blob/329c67f116912befb9d4bff6edb27d2a2673543d/refresh-example.sh#L80-L81

https://github.com/thebergamo/react-native-fbsdk-next/blob/master/RNFBSDKExample/ios/RNFBSDKExample/AppDelegate.mm

Your question is incomplete thus all I can provide are working examples.

https://stackoverflow.com/help/how-to-ask
