### ISSUE TITLE
App crash when any event is emitted

### ISSUE THREAD

**Issue by carlosq-ordering** [thebergamo/react-native-fbsdk-next#48]
## 🐛 Bug Report
I have an implementation, but app crash when I try to do anything. Please check it out the video

## To Reproduce

https://d.pr/v/Wp17SH

**Comment by mikehardy** [comment]
Hi there! Sorry, I will not watch a video
I can help if you can post a stack trace from either Xcode console or `adb logcat` from a minimum reproducible example you can share here https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mikehardy** [comment]
Everyone should re-try with v6 of this library to see if it affects things, it has the up to date native libraries.
I'm going to close this as I'm not sure there is anything this module specifically can do other than stay up to date with native lib versions, but please feel free to continue sharing information on how best to use the available APIs / configurations
