### ISSUE TITLE
com.google.android.gms.permission.AD_ID Error on Play Store

### ISSUE THREAD

**Issue by ReMuSoMeGA93** [thebergamo/react-native-fbsdk-next#483]
## 🐛 Bug Report
Google Play Store gives me this error:
```
Your advertising ID declaration in Play Console says that your app uses advertising ID. A manifest file in one of your active artifacts doesn't include the com.google.android.gms.permission.AD_ID permission.

If you don't include this permission in your manifest file, your advertising identifier will be zeroed out. This may break your advertising and analytics use cases, and cause loss of revenue. [Learn more](https://support.google.com/googleplay/android-developer/answer/6048248)

You can remove these errors by updating your advertising ID declaration
```

I have advertising declared for analytics.
There is nothing I can do to get rid of this error.

## To Reproduce
Simply install RN FBSDK-Next to any android Project using Expo, build a production build and submit to play store.

## Expected Behavior
I expected it not to give me that error.

## Code Example
Here is what I've tried to debug it.
I've tire adding these permissions explicitly to expo.android.permissions in the app.json file
```
      "permissions": [
        "com.google.android.gms.permission.AD_ID",
        "android.adservices.adid"
      ]
```

## Environment
React Native Expo

```
    "expo": "~49.0.15",
    "react": "18.2.0",
    "react-native": "0.72.6",
```

These are my android build settings
```
[
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 34,
            "targetSdkVersion": 33,
            "minSdkVersion": 24
          }
        }
      ]
```

**Comment by socheatleang** [comment]
Hi @ReMuSoMeGA93 . is there any solutions to deal with this ?

**Comment by ReMuSoMeGA93** [comment]
> Hi @ReMuSoMeGA93 . is there any solutions to deal with this ?

I ended up installing an MMP. I used Branch.io specifically.
