### ISSUE TITLE
Need FBSDK update for events manager

### ISSUE THREAD

**Issue by AhmadSoftwareAlliance** [thebergamo/react-native-fbsdk-next#484]
<img width="528" alt="Screenshot 2024-01-17 at 11 42 09 AM" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/145774095/0d69f1ad-a1a0-4a15-a9d8-6ed93ddc2a7e">

how can I update?

I have install react-native-fbsdk-next latest version     but I got this alert

**Comment by ReMuSoMeGA93** [comment]
Did you try installing FBSDK v11.3.0? I've read that that has helped for some people. Unfortunately this project does not seem to be actively maintained, which is both a good and bad thing.

**Comment by AhmadSoftwareAlliance** [comment]
I have try but when i downgrade fbsdk some other error show .And not change
status on metedeveloper .And i have use fb Events ,Ads,And Networking for
marketing.
what fbsdk v11.3.0 have Events ?
and on what points where fb change the status ?

**Comment by priyankagupta23pg** [comment]
I am facing same alert on Event manager console while using latest sdk of this library

**Comment by mikehardy** [comment]
I maintain the library @ReMuSoMeGA93 - reasonably actively. There's just not a lot to do about this problem.
I believe it is a false alarm.
See #476 
Follow upstream issue https://github.com/facebook/facebook-android-sdk/issues/1191

I believe this is duplicate and there is not anything to actually do, so I will close this. Github leaves a handy "reopen" button if that's wrong, no worries.

**Comment by AhmadSoftwareAlliance** [comment]
I have done with  FBSDK v11.3.0

**Comment by TowhidKashem** [comment]
> I have done with FBSDK v11.3.0

Did downgrading to v11.3.0 remove the error from meta developer for you? And does everything else work correctly like sending events?
