### ISSUE TITLE
React Native Facebook Login Error: 'There is an error in logging you into this application'

### ISSUE THREAD

**Issue by riya-coddle** [thebergamo/react-native-fbsdk-next#488]
I'm encountering an issue with Facebook login in my React Native project. I've implemented Facebook login using react-native-fbsdk-next v^12.1.0, and while it works perfectly through the web app, I'm facing an error when the Facebook app is installed on the device.

The error message I'm receiving is: "Login Error: There is an error in logging you into this application. Please try again later."

Has anyone else encountered this issue? If so, could you please share any insights or solutions you've found? Any help or guidance would be greatly appreciated.

**Comment by MiteshIts** [comment]
Same

**Comment by risbellycarvajal** [comment]
I'm facing the same issue in our app, there are specific users from android that are unable to log in from the Facebook app (the need to uninstall the app and log in from the device browser)

Any progress or recommendation for this issue?

**Comment by janeirojoaopedro** [comment]
Hi. I'm also facing the same issue. In my case, users need to click several times to open the view to login, and sometimes it doesn't even work. Also this looks like only happen on android devices. In android emulators all works good, with or without facebook app installed. On iPhone, both emulators and devices work. Any idea ?

**Comment by janeirojoaopedro** [comment]
Hi again. Definitely @short-dsb and @MiteshIts solutions worked for me:

1. keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64
2. keytool -exportcert -alias `YOUR_RELEASE_KEY_ALIAS` -keystore `YOUR_RELEASE_KEY_PATH` | openssl sha1 -binary | openssl base64

I was writing the wrong value on `YOUR_RELEASE_KEY_PATH`, and even with the wrong values this generate a key, so be carefull when you do that. To be sure what the `YOUR_RELEASE_KEY_ALIAS` and `YOUR_RELEASE_KEY_PATH` are, you can go to build > generate signed bundle or APK > App bundle or APK > and then you can copy the key store path. The key store password, I suggest to write it to be sure what it is, if it is wrong the build will fail. Hope I can help you.
