### ISSUE TITLE
Did not redirect back after login from facebook app IOS

### ISSUE THREAD

**Issue by Jheysoon** [thebergamo/react-native-fbsdk-next#496]
## 🐛 Bug Report
Did not redirect after login from facebook app

## To Reproduce
1. Logout of safari and facebook app
2. Login in app -> this will redirect open a safari window and tells to open the facebook app
3. Click Open when "Open in Facebook" dialog appears (see Image 1)
4. Choose account to open
5. It will be stuck in facebook app, and will not redirect to app to complete the login process (see Image 2 with Test user from facebook dashboard)

### Image 1
![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/8098903/98fb9218-880d-4103-8473-f724f98f6f85)

### Image 2
![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/8098903/25df6505-2bd0-4d9b-ba8e-82be19533c8b)

## Expected Behavior
After logging in facebook app, it should redirect to the app and complete the login process

## Code Example
In AppDelegate.mm

#import <AuthenticationServices/AuthenticationServices.h>
#import <SafariServices/SafariServices.h>
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>

// other imports here

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options 
{
  
  if ([[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options]) {
    return YES;
  }
  
  if ([RCTLinkingManager application:application openURL:url options:options]) {
    return YES;
  }
  
  if ([RNGoogleSignin application:application openURL:url options:options]) {
    return YES;
  }
  
  return NO;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // other code here

  [[FBSDKApplicationDelegate sharedInstance] application:application
                         didFinishLaunchingWithOptions:launchOptions];
  
  [RNBootSplash initWithStoryboard:@"LaunchScreen" rootView:rootView];

  return YES;
}

## Environment
System:
    OS: macOS 13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.82 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.10.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11090377
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^10.1.3 => 10.1.3
    react: 18.1.0 => 18.1.0
    react-native: 0.70.15 => 0.70.15
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Elyknhoj** [comment]
Facing that same issue.

**Comment by markstreich** [comment]
Same issue, react-native-fbsdk-next 12.1.2

Our facebook signups dropped ~half instantly after release

**Comment by swrobel** [comment]
Did anyone find a solution to this, or a way to prevent the Facebook app from launching on iOS?

**Comment by Zeeshan404** [comment]
Anyone find a solution ?
