### ISSUE TITLE
[Expo] How to initialize SDK only on specific build?

### ISSUE THREAD

**Issue by otani-mnbf** [thebergamo/react-native-fbsdk-next#497]
## Needs help
using Expo, I can install the SDK without any problem by following [the README](https://github.com/thebergamo/react-native-fbsdk-next?tab=readme-ov-file#expo-installation), and I'm trying to initialize the SDK only on production env so it collects only real-world data.

so what I did is
- setting `isAutoInitEnabled` false in app.json(to disable the auto initialization on Android)
- call initialize method in App.jsx (using dynamic import so I can still use ExpoGo).

package.json
```json
    "react-native-fbsdk-next": "^12.1.3",
```

app.json
```json
    "plugins": [
      ...
      [
        "react-native-fbsdk-next",
        {
          "appID": "14124113217378",
          "clientToken": "fb7dddxxxe4eac1120535xxx",
          "displayName": "demo-app",
          "scheme": "fb14124113217378",
          "advertiserIDCollectionEnabled": true,
          "autoLogAppEventsEnabled": true,
          "isAutoInitEnabled": false
        }
      ]
    ]
```

App.jsx
```jsx
...
import { isDev, isExpoGo } from '@config/env';

export default function App() {
  const getFacebookSDK = useCallback(async () => {
    return (await import('react-native-fbsdk-next')).Settings;
  }, []);

  useEffect(() => {
    const initSDK = async () => {
      if (!isDev && !isExpoGo) {
        const fbSDK = await getFacebookSDK();
        fbSDK.initializeSDK();
      }
    };

    initSDK();
  }, [getFacebookSDK]);

  return (
    <MainApp />
   )
```

, which doesn't seem working on Android although it does on iOS for some reason...
`not working`  I mean, on Meta Console I can't see any numbers of sdk_initialization on Android and AppInstalls count doesn't seem correct cuz it doesn't match the one on GooglePlayConsole.

so if anyone knows anything about it or how to achieve it, Please let me know here🙏
Thank you!

**Comment by pecabum** [comment]
Hello, if we use react native project without expo, is there a way to disable auto init ?
