### ISSUE TITLE
Idea: Splitting up the project into specific parts

### ISSUE THREAD

**Issue by iDuuck** [thebergamo/react-native-fbsdk-next#5]
*Disclaimer: I removed the template, since this is an idea and not a bug report.*

---

I currently only need some parts of the SDK, hence I moved to the native SDK's using only the automatic tracking.

My supposed solution would be to have one base package, and then splitting up all the rest.
What do you think about this?

**Comment by thebergamo** [comment]
@iDuuck I believe it's a wonderful idea!
Also in my project specifically I only need fb-login, but needs to carry the whole lib.

There is some idea for migration to TS and having this split would be very nice :)

I would like also to have a better way to automate test cases to give us more confidence while releasing.

**Comment by thebergamo** [comment]
Closing his issue in favor of #16
