### ISSUE TITLE
Build error:  Showing Recent Messages Error [ERR_REQUIRE_ESM]: require() of ES Module...

### ISSUE THREAD

**Issue by beqramo** [thebergamo/react-native-fbsdk-next#503]
## 🐛 Bug Report

Hi,
After upgrading package to v12.1.4 from v12.1.2 I'm facing build issue on ios on archiving and sometimes on dev build.
downgrading it to v12.1.2 helps the problem.

I'm using node 18.17 version so theoretically, it should not have any problems.

<img width="1468" alt="Screenshot 2024-03-13 at 10 56 08 PM" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/40486471/816e7f5c-42a7-4992-a455-899f5926243e">

## To Reproduce

Install  latest package and try to archive, Most probably you need to face same issue.

## Expected Behavior

It should be able to build without any problem

## Environment

```
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 187.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.21 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.14 => 0.71.14 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
Not related to this package
newer versions of wrap-ansi aren't compatible and you need to pin them
I learned this from a basic search and looking at the related stackoverflow
https://stackoverflow.com/questions/77406363/error-err-require-esm-require-of-es-module-node-modules-wrap-ansi-index-js

**Comment by beqramo** [comment]
Sorry for this, I forgot to close it :)
