### ISSUE TITLE
Will this lib be updated to meet Apple's new third party sdk privacy manifest requirement?

### ISSUE THREAD

**Issue by TowhidKashem** [thebergamo/react-native-fbsdk-next#508]
Hi,

Apple will require select third party SDKs including the Facebook sdk to have a privacy manifest:

https://developer.apple.com/support/third-party-SDK-requirements/

in order to be allowed on the App Store pretty soon. I saw in the Facebook dashboard that my app which uses this package is not compatible at the moment. Is there any plans to update the lib to support this requirement or is the project abandoned at this point?

**Comment by 15matias15** [comment]
hey @TowhidKashem  check #507

**Comment by TowhidKashem** [comment]
@15matias15 Thanks I was late by a day and didn't see that one, I'll close my issue in favor of the other then!
