### ISSUE TITLE
Can't change to another account on login

### ISSUE THREAD

**Issue by razamsalem** [thebergamo/react-native-fbsdk-next#509]
When I'm trying to log in to facebook Its jsut suggest the old user and dosent let the option of change account/add another account

## 🐛 Bug Report
When user try to log in to another account its remember the last user and dosent let to connect to another user

## To Reproduce
When user log in to facebook

## Expected Behavior
Expected Behavior so user can change between accounts of facebooks

**Comment by tozlukozmos** [comment]
I think it is not related to the package. Just use your browser to log out from your old account. Then you can enter new credentials after click on the Facebook login button.

**Comment by mikehardy** [comment]
Hi there!
https://stackoverflow.com/help/minimal-reproducible-example
https://stackoverflow.com/help/minimal-reproducible-example

No information on versions in use or a minimal app.js that has code which would show the problem, so no help is really possible thus I'll close

may just be that you are not logging the user out correctly, but who can say with the information provided...

**Comment by razamsalem** [comment]
> I think it is not related to the package. Just use your browser to log out from your old account. Then you can enter new credentials after click on the Facebook login button.

So, how can I improve the user experience and disconnect him from the previous user from the broswer?
