### ISSUE TITLE
app[ios] crashed when installed react-native-fbsdk-next lib 

### ISSUE THREAD

**Issue by rvideep** [thebergamo/react-native-fbsdk-next#51]
Hi, I am a newbie,
To integrate facebook I installed the react-native-fbsdk-next library, after which app crashed and then I uninstalled the library but still getting the errors as below:

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-Glog' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'react-native-splash-screen' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'TOCropViewController' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'AppAuth' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleSignIn' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'RNImageCropPicker' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'RNStompWS' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-PeerTalk' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'boost-for-react-native' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flipper-DoubleConversion' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'RNShare' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'YogaKit' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'RNImageCropPicker-QBImagePicker' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'react-native-video' from project 'Pods')

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/deepak/Library/Developer/Xcode/DerivedData/churchee-eatfblnccklrpzgmakkkkslerztt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsiexecutor.build/Objects-normal/x86_64/JSIExecutor.o /Users/deepak/Desktop/church/churchee_mobile_app_recent/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/deepak/Library/Developer/Xcode/DerivedData/churchee-eatfblnccklrpzgmakkkkslerztt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsiexecutor.build/Objects-normal/x86_64/JSINativeModules.o /Users/deepak/Desktop/church/churchee_mobile_app_recent/node_mo

**Comment by mikehardy** [comment]
Hi there!

If you can reproduce the failure with the example app, we may investigate, but the build failures you post do not have any relationship to this module and no fix related to them will cause a change in this module, so it is not an issue with the module
