### ISSUE TITLE
iOS limited login

### ISSUE THREAD

**Issue by yosukapro** [thebergamo/react-native-fbsdk-next#514]
I'm using `react-native-fbsdk-sdk` for facebook login in my application. I just received email from Meta about upgrade FBSDKs to latest version (v17.0.0) to incorporate "Privacy Manifest" for Apple Store submission. So here is my update:
 - react-native-fbsdk-sdk :  ^12.1.3  →    ^13.0.0

## 🐛 Bug Report

 After upgrade to new version. I get two bugs:
 1. iOS limited login
 - I've followed the document to apply in my code
 ```
try {
      await LoginManager.logInWithPermissions(
        ['public_profile', 'email'],
        'limited',
        'my_nonce'
      );

      if (Platform.OS === 'ios') {
        const result = await AuthenticationToken.getAuthenticationTokenIOS();
        if (result?.authenticationToken)
          loginSocial(result.authenticationToken, LoginProvider.FACEBOOK);
      } else {
        const result = await AccessToken.getCurrentAccessToken();
        if (result) loginSocial(result.accessToken, LoginProvider.FACEBOOK);
      }
```
But in the facebook login screen, a warning appears with the following content. How can I hide them for my users?
![Simulator Screenshot - iPhone 15 - 2024-04-12 at 10 30 03](https://github.com/thebergamo/react-native-fbsdk-next/assets/49111851/df297d95-28ed-4fdc-949a-fe884760b1d8)

2. Can't fetch profile by authenticationToken
- I can't use token return from method `AuthenticationToken.getAuthenticationTokenIOS()` to fetch user profile. I have log and still receive the token

## To Reproduce
- Upgrade or install version 13.0.0

## Expected Behavior
  - Don't display warning content in facebook login view
  - Can fetch profile

## Code Example
  ...
```
 const pressFb = async () => {
    try {
      await LoginManager.logInWithPermissions(
        ['public_profile', 'email'],
        'limited',
        'my_nonce'
      );
      if (Platform.OS === 'ios') {
        const result = await AuthenticationToken.getAuthenticationTokenIOS();
        if (result?.authenticationToken)
          loginSocial(result.authenticationToken, LoginProvider.FACEBOOK);
      } else {
        const result = await AccessToken.getCurrentAccessToken();
        if (result) loginSocial(result.accessToken, LoginProvider.FACEBOOK);
      }
    } catch (error) {
      onClose();
      console.log('error', error);
    }
  };
```

...
        
`<Button.Primary
          label={translate('auth.continueWithFacebook')}
          outline
          leftIcon={'IC_FB'}
          style={BTN_LOGIN}
          labelStyle={TXT_BTN}
          onPress={pressFb}
        />
`
...

## Environment
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 106.08 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/drake/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by NidheeshVgopal** [comment]
I have the same issue when I  updated my fbdsk-next from 12.1.4 to 13.0.0. But the 12.1.4 is working fine.

**Comment by NidheeshVgopal** [comment]
> a warning appears with the following content. How can I hide them for my users?

Is there any way to hide the "Limited Login" Warning from the Login interface?

**Comment by yosukapro** [comment]
> Is there any way to hide the "Limited Login" Warning from the Login interface?
I not found it yet.

By the way, Apple still requires a Privacy Manifest, which requires upgrading fbsdk to the latest version. And version 13.0.0 of this package is not working.

**Comment by mikehardy** [comment]
No. The manifest comes with the native sdk. We just wrap the sdk here. Fix forward if at all possible I think

**Comment by yosukapro** [comment]
Hello, I would really appreciate it if you could tell me the plan for when we can resolve this issue?

**Comment by mikehardy** [comment]
A pr would be a huge help, I'll take you up in that if you can, you're at the leading edge of how it's working right now so anything you propose will likely be perfect

**Comment by mikehardy** [comment]
> @mikehardy Happy to help. 🙂 Should I add this info to #513 or would you prefer a separate PR?

That would be great - apologies for asking but please tag me when ready, so I don't miss it

**Comment by fdelavra** [comment]
Late posting but still meeting the problem ... Does any patch is available? or any solution for helping us patching it? 
Thanks a lot

**Comment by kelmag** [comment]
> [@fdelavra](https://github.com/fdelavra) did you fix it?

downgrade to react-native-fbsdk-next to version 12.1.4 is a temp fix for now

**Comment by goffxnca** [comment]
Downgrade react-native-fbsdk-next to 12.1.4 works well for me.

**Comment by fbeef** [comment]
Still facing the same issue. Is downgrading the version a good idea?

**Comment by arunraj-qburst** [comment]
We are facing same issue with latest versions of RN (0.81+)  & iOS (17+)  & fbpacakge ( v13.4.1 & v12.1.4 )as well . Any update on this would be much appreciated !

**Comment by arunraj-qburst** [comment]
> Downgrade react-native-fbsdk-next to 12.1.4 works well for me.

Could you please share the versios you are using in your project  ? Also, is there any additional changes you made in the facebook console ?

We are still getting the error while trying the login. 
Version details - RN (0.81+) & iOS (17+) & fbpacakge ( v13.4.1 & v12.1.4 )

Thanks in advance

**Comment by fbeef** [comment]
> > [@fdelavra](https://github.com/fdelavra) did you fix it?
> 
> downgrade to react-native-fbsdk-next to version 12.1.4 is a temp fix for now

@kelmag, We tried downgrading the version, but the login is stilln't working. Is there still no fix to this? Any kind of help will be appreciated.

**Comment by andrenjdev** [comment]
Still facing the same issue. How did you managed it @fbeef @arunraj-qburst ?

Thank you
