### ISSUE TITLE
Facebook SDK not initialized error when using react-native-fbsdk-next with Expo

### ISSUE THREAD

**Issue by ZiadEmadZaki** [thebergamo/react-native-fbsdk-next#517]
Description:
When integrating react-native-fbsdk-next with an Expo project, I consistently encounter the error message stating "Facebook SDK not initialized". This issue seems to persist despite following standard installation procedures for Expo projects.
i Followed the steps required in the documentation

here is the code from my project 
![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/119590895/6fc421cc-77cf-4493-9596-cf998a28ef1a)

Additional Context:
we are not managing out native code in the project. but aftetr running 'npx expo run:android' and checking the generated files i can see that there are some lines missing from the `AndroidManifest.xml` file and the `strings.xml` files. when adding them the build is successful and the error is gone.

```xml
 <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
   <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
```

```xml
<string name="facebook_app_id">1234</string>
<string name="facebook_client_token">56789</string>
```

Steps to Reproduce:
- Create a new Expo project.
- Integrate react-native-fbsdk-next using the provided installation instructions.
- no need to use any functionality provided by the sdk the error shows immediaty after opening the production build or development build 
- Observe the "Facebook SDK not initialized" error.

Expected Behavior:
The integration of react-native-fbsdk-next with Expo should seamlessly initialize the Facebook SDK without requiring manual intervention.

Actual Behavior:
The Facebook SDK initialization fails, resulting in the "Facebook SDK not initialized" error message.

![2024-04-15_20-57](https://github.com/thebergamo/react-native-fbsdk-next/assets/119590895/7c584549-2518-47f1-973c-b7e0e3bc3d00)

Environment:

react-native-fbsdk-next version: ^12.1.4
Expo SDK version: 49
Platform: (iOS/Android): Android

Am i doing somethig wrong here ?

**Comment by Flano-123** [comment]
![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/54198516/40b8c4cd-afbd-41c9-9fac-292127237831)
this line maybe should be: fb+your fb app id

**Comment by ZiadEmadZaki** [comment]
@Flano-123 Yes you are correct. but the issue persists regardless of the value of the scheme. i just tested again to be sure

**Comment by uncledent** [comment]
Down grade to 12.2.0 fixed it for me

**Comment by ZiadEmadZaki** [comment]
@uncledent i was already using version 12.1.4. and i just tested again with 12.2.0 and the same issue happens. could share some more details about your setup? like expo version and if you are implementing it the same way as i do.

**Comment by uncledent** [comment]
"expo": "^50.0.15"
 
 Don't forget to put authToken into appjson config.
 
 [
        "react-native-fbsdk-next",
        {
          "appID": "",
          "clientToken": "",
          "displayName": "",
          "scheme": "",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": false,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "This identifier will be used to deliver personalized content to you."
        }
      ]
      
      Also remove native projects and do the prebuild again after downgrading.

**Comment by aamir104512** [comment]
Hello, i was wondering if you found the solution and solved this problem, if you did can you please tell me what steps did you follow? Thanks

**Comment by idudinov** [comment]
downgrading to `^12` and doing a full rebuild helped me

**Comment by Almaroo** [comment]
In case you struggle with this in expo 51, set 

`"react-native-fbsdk-next": "^12",` in package.json

then run `npx expo prebuild --clean`

worked for me

**Comment by mikehardy** [comment]
@Almaroo what I read was:

"In case you struggle with <whatever> just downgrade this package to an obsolete version and don't ever worry about updating it, like even if you really need the underlying SDK to update"

Who would recommend such a thing vs a real solution ?

**Comment by mikehardy** [comment]
@andrejpavlovic - you proposed a PR to the expo plugin so I could be wrong but I assume you are using it successfully with expo? is it working for you currently with current versions of react-native-fbsdk-next? I don't use expo so I'm not aware of any breakage but it was my understanding that it was working...

**Comment by andrejpavlovic** [comment]
@mikehardy Version `13.1.3` is working fine with Expo 51.

Plugin config looks like this if it helps anyone.
```typescript
[
  'react-native-fbsdk-next',
  {
    appID: process.env.FACEBOOK_APP_ID,
    displayName: process.env.FACEBOOK_DISPLAY_NAME,
    scheme: process.env.FACEBOOK_APP_ID ? `fb${process.env.FACEBOOK_APP_ID}` : undefined,
    clientToken: process.env.FACEBOOK_CLIENT_TOKEN,
  },
],
```

**Comment by ziademadmohammed** [comment]
hello everyone, thank you for helping. just wanted to add the issue i was facing since i closed the issue without adding it

it was an error on my part. it had to to with the clientToken. i had the wrong value in. and the android dev tools didn't show the network requests fired from he native side so i couldn't tell.

**Comment by ZiadEmadZaki** [comment]
hello everyone, thank you for helping. just wanted to add the issue i was facing since i closed the issue without adding it

it was an error on my part. it had to to with the clientToken. i had the wrong value in. and the android dev tools didn't show the network requests fired from he native side so i couldn't tell.

**Comment by mikehardy** [comment]
No worries @Almaroo I know we're all trying our best, and sometimes this stuff is so irritating it'll definitely get to a person

**Comment by Parth-Bhanushali** [comment]
I ran into the same issue, and scratched my head a lot until I find out what I was doing wrong!

**Error 1:** The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
**Error 2:** Cannot find module 'babel-plugin-react-native-fbsdk-next', .... (pretty big error)

❌ Don't add this to plugins in `babel.config.js`.
✅ Add this to plugins in `app.json` or `app.config.js`.

Both these files have plugins to configure, and it's easy to overlook when you're in rush.

**P.S.** Error 2 came after I re-run the metro bundler with `--clear` flag.
