### ISSUE TITLE
LoginManager.logInWithPermissions always return {isCancelled: true}

### ISSUE THREAD

**Issue by galihlprakoso** [thebergamo/react-native-fbsdk-next#52]
## 🐛 Bug Report

I already implement all the required steps for the Login with Facebook feature on the official documentation of this library. and already implemented some step required like updating AndroidManifest and res/values/strings.xml . But when I tried to excecute this code:
`const result = await LoginManager.logInWithPermissions(['public_profile']);`

it opens another activity for a second and then back to the app and said {isCancelled: true} . 

Do I need to verify my business in order to use facebook login?

## To Reproduce

1. Add react-native-fbsdk-next
2. Follow required steps on android native.
3. Run LoginManager.logInWithPermissions function
4. return {isCancelled: true}

## Expected Behavior

return {isCancelled: false}

## Code Example

```
const result = await LoginManager.logInWithPermissions(['public_profile']);

if (result.isCancelled) {
  throw 'User cancelled the login process';
}

const data = await AccessToken.getCurrentAccessToken();

if (!data) {
  throw 'Something went wrong obtaining access token';
}

const facebookCredential = auth.FacebookAuthProvider.credential(data.accessToken);

return auth().signInWithCredential(facebookCredential);
```
## Environment

System:
    OS: macOS 11.2.2
    CPU: (8) x64 Apple M1
    Memory: 99.65 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/Projects/ghackdev/networth/node_modules/.bin/yarn
    npm: 7.5.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
Everyone should re-try with v6 of this library to see if it affects things, it has the up to date native libraries.
I'm going to close this as I'm not sure there is anything this module specifically can do other than stay up to date with native lib versions, but please feel free to continue sharing information on how best to use the available APIs / configurations

**Comment by hugoh59** [comment]
I'm still having this issue with the latest 11.x version

**Comment by MajaMilanovic** [comment]
Same here, with "react-native-fbsdk-next": "^11.1.0" version
