### ISSUE TITLE
App switches automatically to limited login when updated to v13

### ISSUE THREAD

**Issue by beliven-davide-lorigliola** [thebergamo/react-native-fbsdk-next#520]
I'm using react-native-fbsdk-sdk for facebook login in my application. 
I've update react-native-fbsdk-sdk :  ^13.0.0

Now my Facebook SSO login opens by default to `limited.facebook.com` domain.

Here's my code:

```
import {LoginManager, AccessToken} from 'react-native-fbsdk-next';
import auth from '@react-native-firebase/auth';
import {showErrorIfAllowed} from './functions';

export async function onFacebookButtonPress(onError) {
  try {
    // Attempt login with permissions
    const result = await LoginManager.logInWithPermissions([
      'public_profile',
      'email',
    ]);

    if (result.isCancelled) {
      throw {
        code: '-5',
        name: 'Error',
        message: 'User cancelled the login process',
      };
    }

    // Once signed in, get the users AccesToken
    const data = await AccessToken.getCurrentAccessToken();

    if (!data) {
      throw {
        code: '0',
        name: 'Error',
        message: 'Something went wrong obtaining access token',
      };
    }

    // Create a Firebase credential with the AccessToken
    const facebookCredential = auth.FacebookAuthProvider.credential(
      data.accessToken,
    );

    // Sign-in the user with the credential
    return auth().signInWithCredential(facebookCredential);
  } catch (e) {
    showErrorIfAllowed(e, onError);
  }
}

```

**Comment by brainbicycle** [comment]
this is an upstream change with version 17 of the Facebook iOS SDK: https://github.com/facebook/facebook-ios-sdk/issues/2375 and it sounds like it is a deliberate behavior change by Facebook, if you do not have tracking permissions you automatically get opted into limited login. 
So you have a few options:
- downgrade (harder with privacy manifest requirements)
- get tracking permissions to use classic login
- support limited login
- ask for a change on the iOS sdk on the above 

either way I don't think there is anything that can be done on this library.

**Comment by Daniel3711997** [comment]
question: how do i get 'get tracking permissions to use classic login' this permission ?

**Comment by gustavos00** [comment]
> question: how do i get 'get tracking permissions to use classic login' this permission ?

I do have the same question. So, if anyone has any information about this, would be very good if you share it :D

**Comment by vomchik** [comment]
@gustavos00 @Daniel3711997 you can use https://github.com/zoontek/react-native-permissions

Check `PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY`

**Comment by therealyubraj** [comment]
This actually works. Thanks a lot.

**Comment by mikehardy** [comment]
👋 just a note that we *love* documentation PRs, they're easy to make and easy to merge. If there's anything that will help future developers avoid some problem you had, proposing a docs PR is the way to help / pay it forward. Cheers

**Comment by Exilz** [comment]
Handling tracking permissions when first starting my app fixed the issue for me using 13.x
Something as simple as :

```typescript
import { requestTrackingPermissionsAsync } from 'expo-tracking-transparency';

const { status } = await requestTrackingPermissionsAsync();
if (status === 'granted') {
      Settings.initializeSDK();
      await Settings.setAdvertiserTrackingEnabled(true);
      Settings.setAdvertiserIDCollectionEnabled(true);
      Settings.setAutoLogAppEventsEnabled(true);
}
```
