### ISSUE TITLE
Compiling for iOS 13.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.4

### ISSUE THREAD

**Issue by dev-at-salt-and-tonic** [thebergamo/react-native-fbsdk-next#531]
## :bug: Bug Report
Building an app with expo-modules-core version 1.11.12 and the latest release of this repo in XCode results in the following error 

![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/118936547/49f6a9b9-944c-4f6a-95e5-1519e7d46427)

This bug appears to be related to this issue [346](https://github.com/thebergamo/react-native-fbsdk-next/issues/346) and this PR [344](https://github.com/thebergamo/react-native-fbsdk-next/pull/344).

## To Reproduce
Build an iOS app with expo-modules-core version 1.11.12 and the latest release of react-native-fbsdk-next (13.0.0).

## Expected Behavior
For this package to work with ExpoModulesCore 1.11.12

## Environment

System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M2
  Memory: 910.16 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/***/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/***/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by jdoroy-808** [comment]
I experienced the same issue. I just closed and relaunched XCode and tried to archive again and the error was gone.

**Comment by jaaywags** [comment]
same issue for me

**Comment by AftabUfaq** [comment]
same issue
