### ISSUE TITLE
iOS limited login sdk 17

### ISSUE THREAD

**Issue by richardReitz** [thebergamo/react-native-fbsdk-next#536]
## Question
Is it possible to remove the "limited login" warning in the Facebook login modal?

## Description
When users log in with Facebook using `react-native-fbsdk-next`, a "limited login" warning appears in the login modal. Even after upgrading the library to version 13.0.0, the login process works correctly, but this warning still appears. I would like to know if there is any way to remove or customize this warning, as it might be confusing or unnecessary for some users.

![Captura de Tela 2024-06-26 às 15 20 58](https://github.com/thebergamo/react-native-fbsdk-next/assets/93951962/18a13577-320f-4b8d-97e6-59177892d740)

## Lib version
**react-native-fbsdk-sdk : 13.0.0**

**Comment by arslangsten** [comment]
@richardReitz  are you able to login. i am getting the error while login can you share any docs you followed i am getting error 

'error...', [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.] 


can you please help me in this regard i am facing this issue in expo ios app

**Comment by trickeyd** [comment]
We also have this issue being reported by our users. Some percentage of them are totally unable to get into the app. When I test it, I see the message above, but then login works fine so I can't even debug it.

react-native-fbsdk-next: 13.0.0
react-native-firebase: 19.0.1

**Comment by mkhalil-dev** [comment]
Any update? I am able to login with facebook, however, this warning needs to be addressed still.

**Comment by trickeyd** [comment]
Related thread here:

https://github.com/invertase/react-native-firebase/issues/7126

**Comment by goffxnca** [comment]
Downgrade react-native-fbsdk-next to 12.1.4 works well for me.
