### ISSUE TITLE
Error while login facebook login in expo app 

### ISSUE THREAD

**Issue by arslangsten** [thebergamo/react-native-fbsdk-next#537]
i am getting this error 

error... [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]

i tried many ways but still getting issues. how can any one help me what i am doing wrong 

i am using version 13.0.0
React native 0.71.14
Expo 48.0.21

**Comment by trickeyd** [comment]
We also have this issue being reported by our users. Some percentage of them are totally unable to get into the app. When I test it, I see the message above, but then login works fine so I can't even debug it.

react-native-fbsdk-next: 13.0.0
react-native-firebase: 19.0.1

**Comment by trickeyd** [comment]
If this is stale, it is only due to lack of response.

**Comment by ctriantaf** [comment]
I had the same issue but it was fixed but adding support for `iOS limited login` and calling `Settings.initializeSDK` as mentioned [here](https://github.com/thebergamo/react-native-fbsdk-next?tab=readme-ov-file#platform-neutral-sdk-initialization)

**Comment by trickeyd** [comment]
@ctriantaf Doing both of those since before this issue started unfortunately 😔
