### ISSUE TITLE
Not Found react-native-fbsdk-next in the Maven Repository 

### ISSUE THREAD

**Issue by BrunKsp** [thebergamo/react-native-fbsdk-next#540]
Hello, I am facing a problem when using your library in developing my application using react-native with expo version 50.0, this week I build a new apk for Android preview and I receive a 502 error that it did not find the lib repository in the Maven, what can I do to make it work?
![Screenshot_127](https://github.com/user-attachments/assets/8c768734-9d94-42f8-afb2-7609aea22d94)
https://oss.sonatype.org/content/repositories/snapshots/com/facebook/android/facebook-android-sdk/maven-metadata.xml

**Comment by dohainamhn** [comment]
same issue any one resolve this?

**Comment by mikehardy** [comment]
@dohainamhn you have a network issue, nothing to do with this project

**Comment by BrunKsp** [comment]
I resolve this problem, with compile my project in another day
