### ISSUE TITLE
fetchDeferredAppLink() returns undefined

### ISSUE THREAD

**Issue by vrutikinx** [thebergamo/react-native-fbsdk-next#541]
We are looking to fetch the UTM param resources from the Facebook app ads into react native app. Unfortunately i tried fetchDeferredAppLink()  method from react-native-fbsdk-next library but it's not returning. 
I executed each and every steps according to the document. 
Steps :-

 1. Created a Facebook post or ad with a deeplink to install the app.
 2. Added UTM parameters (e.g., utm_source) into the deep link for the app installation.
 3. On clicking the "Install Now" button, on the Facebook post or ad.
 4. On the installed/opened app, called the fetchDeferredAppLink() method.

Expected Behavior:-
  The fetchDeferredAppLink() method should return the UTM parameters for the link added to the ad manager.

Actual Behavior:-
The method returns undefined.

Environment:
"react": "18.2.0",
"react-native": "^0.72.6",
"react-native-fbsdk-next": "^13.0.0"

**Comment by osafahmad** [comment]
Hi,

We are facing the same issue and have searched online for solutions. We've applied them, but we still haven’t received the link from the App Store. It works perfectly on the Android side via the Play Store but not on iOS.

Here are the details of our setup:

React: 18.2.0
React Native: 0.71.8
react-native-fbsdk-next: ^13.3.0
FBSDK iOS Library Version: 17.0 (latest version)
We’ve set up the ATE (App Tracking Transparency) permission popup, and I’ve allowed tracking.
I also tested the deep link functionality by clicking Test Deep Link from the Facebook campaign. I received a notification via the link provided on the [Facebook App Ads Helper](https://developers.facebook.com/tools/app-ads-helper).

However, I’m stuck and unable to retrieve campaign data. Below is the code I’ve been using for testing:

useEffect(() => {
  const handleDeepLink = ({ url }: { url: string }) => {
    console.log("URL:==> ", url);
    if (url) {
      dispatch(onMetaDeepLink(url));
    }
  };

  const requestPermission = async () => {
    const status = await requestTrackingPermission();
    if (status === 'authorized') {
      console.log('User granted permission for tracking');
      await Settings.setAdvertiserTrackingEnabled(true);
      await Settings.initializeSDK();

      setTimeout(() => {
        handleInitialURL();
      }, 5000);
    } else if (status === 'denied') {
      console.log('User denied permission for tracking');
    } else if (status === 'not-determined') {
      console.log('User has not yet made a decision');
    }
  };

  const handleInitialURL = async () => {
    try {
      const isFirstLaunch = await AsyncStorage.getItem('isFirstLaunch');
      if (isFirstLaunch === null || isFirstLaunch === undefined) {
        await AsyncStorage.setItem('isFirstLaunch', 'false');
        const deferredUrl = await AppLink.fetchDeferredAppLink();
        Alert.alert(JSON.stringify(deferredUrl));
        if (deferredUrl) {
          handleDeepLink({ url: deferredUrl });
        }
      } else {
        console.log("Second Launch");
        const initialUrl = await Linking.getInitialURL();
        console.log("Initial URL: ", initialUrl);
        if (initialUrl) {
          handleDeepLink({ url: initialUrl });
        }
      }
    } catch (error) {
      console.error("Error fetching initial/deferred URL:", error);
    }
  };

  if (Platform.OS === 'ios') {
    const majorVersionIOS = DeviceInfo.getSystemVersion();
    console.log("iOS Version: ", majorVersionIOS);
    const majorVersion = parseFloat(majorVersionIOS.split('.')[0]);
    if (majorVersion >= 14) {
      console.log("Check Worked");
      requestPermission();
    } else {
      Settings.setAdvertiserTrackingEnabled(true);
      Settings.initializeSDK();
      handleInitialURL();
    }
  }

  const subscription = Linking.addEventListener('url', handleDeepLink);
  return () => {
    subscription.remove();
  };
}, [dispatch, onMetaDeepLink]);

I would appreciate any guidance or insights into resolving this issue.
