### ISSUE TITLE
App Events Not Logging

### ISSUE THREAD

**Issue by gesturetaj** [thebergamo/react-native-fbsdk-next#542]
## 🐛 Bug Report
App events are not being registered in the Facebook dashboard when using the `react-native-fbsdk-next` config plugin in with Expo 51 and React Native 0.74.3

## To Reproduce
- Install React Native `0.74.3`
- Install Expo `51`
- Install react-native-fbsdk-next `3.0.0`
- Setup react-native-fbsdk-next config plugin
- Log custom events and observe events not showing in the Facebook events manager

## Expected Behavior
- Events should show in the Facebook events manager from iOS and Android apps

## Code Example
FB SDK Config Plugin
```
      [
        "react-native-fbsdk-next",
        {
          "appID": "xxx",
          "clientToken": "xxx",
          "displayName": "xxx",
          "advertiserIDCollectionEnabled": false,
          "autoLogAppEventsEnabled": true,
          "isAutoInitEnabled": true,
          "iosUserTrackingPermission": "This identifier will be used to deliver personalized ads to you."
        }
      ],
```
Permissions Request
```
  requestiOSTrackingPermissionsAsync = async () => {
    try {
      const {status} = await requestTrackingPermissionsAsync();
      if (device.iOS) {
        if (status === 'granted') {
          Settings.setAdvertiserTrackingEnabled(true).then(() => {
            Settings.initializeSDK();
            Settings.setAutoLogAppEventsEnabled(true);
            Settings.setAdvertiserIDCollectionEnabled(true);
            
            AppEventsLogger.logEvent(`Testing Expo Plugins 1. App Version ${appVersion}`);
            AppEventsLogger.logPurchase(50, 'USD')
          }).catch(err => {
            Alert.alert(`Error from FB SDK ${err}`)
          });
          AppEventsLogger.logEvent(`Testing Expo Plugins 3. App Version ${appVersion}`);
        } else {
          console.log('permission denied');
        }
      } else {
        if (status === 'granted') {
          Settings.initializeSDK()
          Settings.setAutoLogAppEventsEnabled(true);

          AppEventsLogger.logEvent(`Testing Expo Plugins 1. App Version ${appVersion}`);
          AppEventsLogger.logPurchase(50, 'USD')
        } else {
          console.log('permission denied android');
        }
      }
    } catch (error) {
      console.log(error);
    }
  };
```

## Environment

System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M3
  Memory: 308.31 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.1
    path: ~/.nvm/versions/node/v20.15.1/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.1/bin/npm
  Watchman:
    version: 2024.07.01.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by pratikgehlott** [comment]
You can checkout this link - https://github.com/thebergamo/react-native-fbsdk-next/issues/66
