### ISSUE TITLE
accessToken returned on iOS is invalid

### ISSUE THREAD

**Issue by domenicoprestia** [thebergamo/react-native-fbsdk-next#546]
## 🐛 Bug Report
Right now i'm retrieving the accessToken from the logInWithPermissions() function, on Android ti works normally, but on iOS looks like the token that it returns is invalid

## To Reproduce
Try to login with iOS accessToken

## Expected Behavior
The token should be valid and should let me authenticate normally

## Environment
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M2
  Memory: 104.22 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.2
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.7.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.04.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google Play Experimental 16k Page Size ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by gauthampait** [comment]
Facing the same problem with 

```
    "@react-native-firebase/app": "^20.4.0",
    "@react-native-firebase/auth": "^20.4.0",
    "react-native-fbsdk-next": "^13.0.0",
```

Error message: 

`"[auth/invalid-credential] The supplied auth credential is malformed or has expired."`

**Comment by BaluNaik** [comment]
Similar issue.

**Comment by Domniea** [comment]
I also have this same issue and can’t seem to figure out why.

**Comment by Puneet58** [comment]
Similar Issue

**Comment by antoine-waag** [comment]
same issue since I have update the package to the latest version

```
"@react-native-firebase/app": "^20.4.0",
"@react-native-firebase/auth": "^20.4.0",
"react-native-fbsdk-next": "^13.0.0",
```
    
`[Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]`

**Comment by shlomiro** [comment]
same here

**Comment by i-ked-ii** [comment]
You can try my solution #551

**Comment by zaryan98** [comment]
same issue here, 

[Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]

**Comment by i-ked-ii** [comment]
> same issue here,
> 
> [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]

You can try my solution https://github.com/thebergamo/react-native-fbsdk-next/issues/551#issuecomment-2345570693

**Comment by zaryan98** [comment]
> > same issue here,
> > [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]
> 
> You can try my solution [#551 (comment)](https://github.com/thebergamo/react-native-fbsdk-next/issues/551#issuecomment-2345570693)

Tried the solution you mentioned , but it stills giving me error on iOS, but works fine on android.
The access token is invalid or malified.

**Comment by i-ked-ii** [comment]
> > > same issue here,
> > > [Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired.]
> > 
> > 
> > You can try my solution [#551 (comment)](https://github.com/thebergamo/react-native-fbsdk-next/issues/551#issuecomment-2345570693)
> 
> Tried the solution you mentioned , but it stills giving me error on iOS, but works fine on android. The access token is invalid or malified.

Can I see your code. I think you miss some function.

**Comment by hungvu193** [comment]
While searching for the solution of this issue, I saw this helpful comment: https://github.com/facebook/facebook-ios-sdk/issues/2365#issuecomment-2078743846

It will require updating BE but it makes it work. Hopefully, it can help everyone else here.
