### ISSUE TITLE
App Crash Issue in android : java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by Virajmakwana** [thebergamo/react-native-fbsdk-next#552]
The app crashes with a NullPointerException when attempting to get the length of a null array in the Facebook SDK module. This occurs in the FBProfileModule class.

        NativeExceptionHandler:errorString java.lang.NullPointerException: Attempt to get length of null array
        at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:168)
        at com.facebook.react.bridge.CxxCallbackImpl.invoke(CxxCallbackImpl.java:27)
        at com.facebook.reactnative.androidsdk.FBProfileModule$1.run(FBProfileModule.java:50)
        at java.util.TimerThread.mainLoop(Timer.java:563)
        at java.util.TimerThread.run(Timer.java:513)

## Environment
React-native Version
0.74.5

react-native-fbsdk-next Version
13.0.0

Platform
Android

Using New architecture of React-native

**Comment by mikehardy** [comment]
Hi @Virajmakwana - this was actually flagged as a lint error and I just fixed it without realizing there was an open issue for the same line of code.

So I think this may be fixed in current version, but I never personally reproduced this, I just fixed it as a "fix code lint" task

If you have a reproduction scenario, could you re-test with current release and report your findings? Thanks

commit with fix --> https://github.com/thebergamo/react-native-fbsdk-next/pull/557/commits/45c69a6f1661a34f738b8c5b0202ea983eee7dc1

**Comment by Virajmakwana** [comment]
Thanks for the replying @mikehardy 

For my this problem somehow I found the solution and applied this below given patch and it worked for me and app is not crashing now.

`diff --git a/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java b/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
index 71ceda5..1589ad2 100644
--- a/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
+++ b/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
@@ -37,32 +37,12 @@ public class FBProfileModule extends ReactContextBaseJavaModule {
      * @param callback Use callback to pass the current logged profile back to JS.
      */
     @ReactMethod
-    public void getCurrentProfile(final Callback callback) {
-      // Return the profile object as a ReactMap.
-      if (Profile.getCurrentProfile() == null) {
-        final Timer timer = new Timer();
-        synchronized (timer) {
-          timer.schedule(
-            new TimerTask() {
-              @Override
-              public void run() {
-                timer.cancel();
-                callback.invoke(null);
-              }
-            },
-            30000
-          );
-          mProfileTracker = new ProfileTracker() {
-            @Override
-            protected void onCurrentProfileChanged(Profile oldProfile, Profile currentProfile) {
-              timer.cancel();
-              mProfileTracker.stopTracking();
-              callback.invoke(Utility.profileToReactMap(currentProfile));
-            }
-          };
-        }
-      } else {
-        callback.invoke(Utility.profileToReactMap(Profile.getCurrentProfile()));
-      }
+    public void getCurrentProfile(Callback callback) {
+        //Return the profile object as a ReactMap.
+        callback.invoke(Profile.getCurrentProfile() == null
+                ? null
+                : Utility.profileToReactMap(Profile.getCurrentProfile()));
+    
+   
   }
 }
`

**Comment by mikehardy** [comment]
You might look at the git blame on that file. You've removed a fix for a previous issue
