### ISSUE TITLE
Expo build error: "node"  expected version ">=20". Got "18.18.0"

### ISSUE THREAD

**Issue by IgorsKolcins** [thebergamo/react-native-fbsdk-next#561]
## 🐛 Bug Report
Running a build in Expo throws an error about incompatible Node version.

It seems that the Node version is being specified in the package.json file recently.
Expo is building on their side and have strict server infrastructure. Expo server infrastructure is using Node 18. (see [docs](https://docs.expo.dev/build-reference/infrastructure/))

## To Reproduce
1. Create a clean Expo 51 project
2. Install "react-native-fbsdk-next" package
3. Run Expo build "eas build --profile development --platform android" 

## Expected Behavior
Build successful

## Actual Result
Error during Install Dependencies
error react-native-fbsdk-next@13.1.2: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.18.0"
![image](https://github.com/user-attachments/assets/d8002d50-d998-42cd-a69e-b50f4627bc37)

**Comment by mikehardy** [comment]
sorry about that - didn't realize it would have a downstream effect, I understand v18 is still in wide use
semantic release components are now v20+ only but those are dev deps and I don't believe we need to enforce that as our engine spec, I believe we can back it down to v18

**Comment by IgorsKolcins** [comment]
Hi @mikehardy ,
I found that for Expo it is possible to specify node version in [eas.json](https://docs.expo.dev/build/eas-json/) file.
I think you can leave node 20, but update readme part about Expo.
Thank you for reply!
