### ISSUE TITLE
facebook business app: the app must have at least one supported permissions

### ISSUE THREAD

**Issue by amlcodes** [thebergamo/react-native-fbsdk-next#563]
using facebook for business login, and the login button, or the login manager from this package always gets this fb auth error with the url limited.facebook.com: it looks like this app is not available, the app must have at least one supported permissions

**Comment by princepardeepk** [comment]
facing same , if we use facebook login for Business. this error is coming ? any solution

**Comment by apcexchange** [comment]
Having the same issue, Once you switched to live mode , If you are not added as a tester, it show the error for both android and ios, please help

**Comment by apcexchange** [comment]
seems no provision for config_id, that's why it's happening,

**Comment by mikehardy** [comment]
Please note I am the only active maintainer here and this is not a use case of mine - what that means specifically is that I'm happy to merge reasonable PRs that solve any issue, but I don't have time to invest in creating any PRs, so solutions will have to come from interested people that are affected

**Comment by Vipul3452** [comment]
It's working fine in case of Android both in live and development, but for IOS it gives the error (App not available)

**Comment by apcexchange** [comment]
Not working for both and ios for me

**Comment by Inn116mac** [comment]
any update?i faced same issue.

**Comment by rajangargsmartdata** [comment]
I am also having the same issue any information will be helpful.

**Comment by Inn116mac** [comment]
use   "react-native-fbsdk-next": "^12.1.4" this version to resolve issue.

**Comment by DiegoFawr** [comment]
> use "react-native-fbsdk-next": "^12.1.4" this version to resolve issue.

Didn't work for me

**Comment by sajad-12** [comment]
For me i am facing the same issue in both ios and android , any update ? 
"react-native-fbsdk-next": "^13.4.1",
