### ISSUE TITLE
Info.plist entries in the example app for FacebookAutoLogAppEventsEnabled and FacebookAdvertiserIDCollectionEnabled as Strings instead of Booleans

### ISSUE THREAD

**Issue by yaroslavnikiforov** [thebergamo/react-native-fbsdk-next#564]
## 🐛 Bug Report
I was reviewing the Info.plist file in the example app and noticed that the following keys are set with string values "FALSE" instead of boolean values:
```
<key>FacebookAutoLogAppEventsEnabled</key>
<string>FALSE</string>
<key>FacebookAdvertiserIDCollectionEnabled</key>
<string>FALSE</string>
```

According to Meta's documentation, these keys should be of boolean type:
[https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-advertiser-id](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-advertiser-id)

I'm wondering if this was intentional or if it might be a mistake. Should these values be changed to booleans?

Thank you for your time and assistance!

**Comment by mikehardy** [comment]
That looks like an error to me - nothing like upstream documentation as a solid basis for argument at least
If you proposed a PR to the example and/or to any related documentation that would be a huge help 🙌 
well spotted
