### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by richardReitz** [thebergamo/react-native-fbsdk-next#566]
## 🐛 Bug Report
Description: I encountered an issue with React-callinvoker while using react-native-fbsdk-next in my project. The error message states that the pod requires a higher minimum deployment target, conflicting with my current deployment target set to iOS 12.4. Despite various attempts to resolve the issue, it persists.

```
/Users/user/Documents/app_name/node_modules/react-native-fbsdk-next/react-native-fbsdk-next.podspec:4: warning: previous definition of FBSDKVersion was here
[!] CocoaPods could not find compatible versions for pod "React-callinvoker":
  In Podfile:
    React-callinvoker (from `../node_modules/react-native/ReactCommon/callinvoker`)

Specs satisfying the `React-callinvoker (from `../node_modules/react-native/ReactCommon/callinvoker`)` dependency were found, but they required a higher minimum deployment target.
```

## To Reproduce

1. Add react-native-fbsdk-next to a React Native project.
2. Set the iOS deployment target to 12.4 in the Podfile.
3. Run pod install.

## Environment
react-native-fbsdk-next: 11.2.1
react-native: 0.75.4

**Comment by mikehardy** [comment]
You are conflating a warning related to this module with an error from another module

This is not the module with an error

You need to set the deployment target in the Xcode info section for the app, not the podfile
