### ISSUE TITLE
App Rejected Due to Usage of ASIdentifierManager and IDFA for Kids Category (Guideline 1.3)

### ISSUE THREAD

**Issue by quoctruongkt** [thebergamo/react-native-fbsdk-next#572]
My app has been rejected by Apple under Guideline 1.3 - Safety - Kids Category. The rejection states that the app includes third-party analytics or advertising with the ability to collect, transmit, or share identifiable information, including access to the ASIdentifierManager API and IDFA (Identifier for Advertisers).
Apple specifically highlighted that my app references the ASIdentifierManager API, which provides access to the user's IDFA, in the following locations within the app's binary:

/System/Library/Frameworks/AdSupport.framework/AdSupport
Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit
The app is intended for the Kids Category, and as per Apple's guidelines, apps targeting children should not collect, transmit, or share identifiable information, including access to the IDFA.

Please let me know what I need to do to get rid of this problem

Thanks

**Comment by mikehardy** [comment]
Please investigate this in the facebook-ios-sdk repository
We wrap their SDK and contain whatever symbols their SDK contains
Whatever they advise is what you need to do, and if that means that there needs to be a change here to separate things or use a different Pod or something then we can do that, but you may need to propose a PR to the podspec to make that happen in response to some variable being set in your Podfile
