### ISSUE TITLE
Facebook SDK is not updated to the latest version 

### ISSUE THREAD

**Issue by VarmeegoKateChiu** [thebergamo/react-native-fbsdk-next#574]
## 🐛 Bug Report
Facebook SDK is not updated to the latest version 

## To Reproduce
Facebook App Console returns SDK update required.
No Step to reproduce

## Expected Behavior
SDK is updated to latest version.

## Code Example
No Example required

## Environment
React-Native V0.74.3
react-native-fbsdk-next 13.1.3

**Comment by mikehardy** [comment]
> SDK is updated to latest version automatically

Nothing automatic in this world is there?

I look forward to your PR updating it - they are as easy to make as it is to write this issue - check out the podspec

**Comment by mikehardy** [comment]
@LukeGu-web has benevolently created the PR required for the iOS SDK bump and it's releasing now - thanks Luke!
