### ISSUE TITLE
Graph API v15.0

### ISSUE THREAD

**Issue by dmedina-vopero** [thebergamo/react-native-fbsdk-next#578]
Dear All,

I have recently received recurring emails from Facebook stating that I need to update my applications that currently access the API v15.0.

Our project currently uses:
"react-native-fbsdk-next": "^11.1.0"
"react-native": "0.73.9"

Is this solved by updating the SDK version?

Thanks!

**Comment by mikehardy** [comment]
So you are getting emails saying you need to update
Updates are available here
I'm not sure what the question is? (that is, it seems obvious?)

Update.
