### ISSUE TITLE
Exception App id not found <IOS>

### ISSUE THREAD

**Issue by AmirDoreh** [thebergamo/react-native-fbsdk-next#58]
## 🐛 Bug Report
Exception App id not found ,
the same codes working fine with fbsdk but when i migrate to fbsdk next i got this error on ios
## To Reproduce
add react native fbsdk next to your project and try to use it

## Expected Behavior
it should prompt the login page

## Environment
Xcode: 12.5
React-Native : 64.2
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 67.70 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
    
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      
      
      
      
      

   
![photo_2021-06-18_12-42-27](https://user-images.githubusercontent.com/45465967/122543141-1ee2f800-d034-11eb-9205-b13927fa4bc2.jpg)

**Comment by hks** [comment]
Do not forget this step:
  [FBSDKApplicationDelegate initializeSDK:launchOptions]; // Facebook SDK Initialization

It is happening to the ones who upgraded from "react-native-fbsdk" due to facebook's decision to discontinue it.

**Comment by mikehardy** [comment]
Duplicate #56 please search issues lists prior to posting, this was active literally yesterday
