### ISSUE TITLE
Facebook SDK Integration Warning Issue in React Native App for iOS 14+

### ISSUE THREAD

**Issue by Ivanov8973** [thebergamo/react-native-fbsdk-next#585]
**Issue:** 

I'm experiencing an issue with Facebook SDK integration in my React Native app. I just added a test event with the .**logEvent** function, but it shows a "Warning" indicator in the Facebook Event Manager :

<img width="1105" alt="fb" src="https://github.com/user-attachments/assets/3381d713-0fc6-476c-9e49-5fac7b73e73f">

**The Facebook documentation says:**

```
The Facebook Events Manager is telling you that you need to update your apps to the latest Facebook SDK in order to deliver ads to people using iOS 14.5 or later devices. This is because Apple has made changes to its privacy settings that require apps to get explicit permission from users before tracking their activity.

The latest version of the Facebook SDK includes the necessary changes to comply with Apple's new privacy rules. If you are using an older version of the SDK, your ads may not be delivered to users with iOS 14.5 or later.

To update your apps, you can follow the instructions in the Facebook Events Manager or consult the documentation for the Facebook SDK.
```
**Version**: 

` "react-native-fbsdk-next" : 13.3.0`
 
 
**## Environment**

System:
  OS: macOS 15.1.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 100.17 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.8.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.npm-global/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/todorivanov/.gem/ruby/2.6.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
-->

I tried even to hit "pod update" inside the .**podfile** (how the docs mentioned):

<img width="727" alt="Screenshot 2024-12-09 at 14 58 04" src="https://github.com/user-attachments/assets/cb8086ea-1360-449e-b343-69535a99530b">

but still has a lot of issues during pod install.

How to fix this Warning, what needs to be updated ? Do you plan to fix it with another release version ?

**Comment by mikehardy** [comment]
https://github.com/thebergamo/react-native-fbsdk-next/blob/d4813d8698028f7dd2408d6f4058c96875f322d5/react-native-fbsdk-next.podspec#L4

https://github.com/facebook/facebook-ios-sdk/releases

v17.4.0 is the most current version

v17.4.0 is what we specify to install as the native dependency in our podspec

I don't believe there is any action to take in this repository

Can reopen if so, but I don't see how we can update farther than the current installed version?

**Comment by pauloscardoso** [comment]
I'm also having this problem. Did anyone manage to solve it?

**Comment by pauloscardoso** [comment]
I am using the latest version. If I downgrade solve?

**Comment by iamrestrepo** [comment]
Hey @pauloscardoso, I am having the same issue where Facebook suggest I upgrade to the latest version for iOS. Checking the `react-native-fbsdk-next.podspec` I see `FBSDKVersion = "18.0"` which indicates is higher than the one suggested by Facebook. Did you find a work around for this?

**Comment by VictorAny** [comment]
It becomes our problem since they block advertising functionality because of this...
