### ISSUE TITLE
Difference between example and Meta guide of fb_login_protocol_scheme

### ISSUE THREAD

**Issue by fehergeri13** [thebergamo/react-native-fbsdk-next#586]
In the Meta guide, it says that the fb_login_protocol_scheme should have the `fb` prefix.

```xml
<string name="facebook_app_id">1234</string>
<string name="fb_login_protocol_scheme">fb1234</string>
<string name="facebook_client_token">56789</string>
```

https://developers.facebook.com/docs/facebook-login/android/

But in the example the fb_login_protocol_scheme does not have the prefix

https://github.com/thebergamo/react-native-fbsdk-next/blob/v13.3.0/RNFBSDKExample/android/app/src/main/res/values/strings.xml#L6

which one is the correct?

**Comment by mikehardy** [comment]
Indeed, searching facebook-android-sdk shows the `fb` prefix as well:

https://github.com/search?q=repo%3Afacebook%2Ffacebook-android-sdk%20fb_login_protocol_scheme&type=code

nice catch!
