### ISSUE TITLE
iOS 18 gets freeze on browser appear

### ISSUE THREAD

**Issue by german970814** [thebergamo/react-native-fbsdk-next#590]
## 🐛 Bug Report
It seems that at least in simulator it's freezing the app with no message errors in console for iOS 18 on:

```js
await LoginManager.logInWithPermissions(
        ['public_profile', 'email'],
        'limited',
      );
```

This is my whole code before that line:

```js
Settings.setAppID('...');
Settings.initializeSDK();

export default class FacebookLoginStrategy implements FacebookStrategy {
  id = 'facebook';
  delegate?: FacebookStrategyDelegate;

  static current: FacebookStrategy = new FacebookLoginStrategy();

  async authenticate(email?: string): Promise<void> {
    const result = await request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);

    if (result !== 'granted') {
      return;
    }

    try {
      await LoginManager.logInWithPermissions(
        ['public_profile', 'email'],
        'limited',
      );

      let accessToken: string | undefined;

      if (Platform.OS === 'ios') {
        accessToken = (await AuthenticationToken.getAuthenticationTokenIOS())
          ?.authenticationToken;
      } else {
        accessToken = (await AccessToken.getCurrentAccessToken())?.accessToken;
      }

      const token = accessToken?.toString();
      const response = someCallToMyAPI(token)

      if (response.status === 206) {
        this.delegate?.onEmailIncomplete();
      } else {
        this.delegate?.onSuccess(token!);
      }
    } catch (error: any) {
      try {
        this.delegate?.onError?.(error);
      } catch {}
      console.log(`Error authenticating with ${this.id} strategy: ${error}`);
    }
  }
}
```

<img width="397" alt="image" src="https://github.com/user-attachments/assets/a75a8a9e-44fe-4364-9d19-4582c4ea5693" />

## To Reproduce

I'm using version `13.3.0` of `react-native-fbsdk-next`, I tried iOS 17 and this same code is working there

## Expected Behavior

To be working well in iOS 18 as well

## Environment

System:
  OS: macOS 15.1.1
  CPU: (14) arm64 Apple M4 Pro
  Memory: 180.23 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.2.0
    path: ~/.nvm/versions/node/v23.2.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v23.2.0/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v23.2.0/bin/npm
  Watchman:
    version: 2024.11.11.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by mikehardy** [comment]
Can't reproduce with the example app, works fine. Can re-open if you determine a reproduction but you're likely missing some sort of config or perhaps you need to "erase content and data" or whatever they call it on the Simulator.

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/531b9448-ffa7-4701-be9b-68716b636d65" />

Example app is built automatically from this script so you can inspect and see if you maybe missed a step https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

Also appears you're on outdated versions of react-native and Xcode, not sure why you'd neglect updating those to current to make sure bugs haven't already been fixed vs logging an issue for triage prior
