### ISSUE TITLE
'FBSDKCoreKit/FBSDKSettings.h' file not found

### ISSUE THREAD

**Issue by DARPANMANEK** [thebergamo/react-native-fbsdk-next#591]
## 🐛 Bug Report
I am using the libraries:
```
"react-native-fbads": "^7.1.1"
"react-native-fbsdk-next": "^13.3.0"

```
When running the project in Xcode (Version 16.0 (16A242d)), I encounter an error in EXAdSettingsManager:
'FBSDKCoreKit/FBSDKSettings.h' file not found. 

## To Reproduce
To reproduce this error, create a new project using the latest version of React Native. Configure both libraries in the newly created project, install the pods, and run the project in Xcode.

## Code Example
this is my AppDelegate.mm file content
`#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>

#import "ReactNativeConfig.h"
#import "RNBootSplash.h" // <- add the header import
#import "GoogleMaps/GoogleMaps.h"
#import <CodePush/CodePush.h>
// #import <AuthenticationServices/AuthenticationServices.h>
// #import <SafariServices/SafariServices.h>
// #import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
#import <React/RCTLinkingManager.h>
#import <Firebase.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKCoreKit/FBSDKSettings.h>
// For iOS - headlessTask
#import "RNFBMessagingModule.h"

// For notifications
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  // Firebase setup
  if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
  }

  // Set up custom props and launch options
  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];

  // Read environment variables
  NSString *nativeModuleName = [ReactNativeConfig envFor:@"NATIVE_MODULE_NAME"];
  NSString *googleApiKey = [ReactNativeConfig envFor:@"GOOGLE_MAP_API_KEY"];
  self.moduleName = nativeModuleName;
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
  // Provide Google Maps API key
  [GMSServices provideAPIKey:googleApiKey];

  // Initialize Facebook SDK
  [[FBSDKApplicationDelegate sharedInstance] application:application
                             didFinishLaunchingWithOptions:launchOptions];

  // Set up notifications
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self bundleURL];
}
- (NSURL *)bundleURL
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [CodePush bundleURL];
#endif
}

// Handle openURL for deep linking and Facebook SDK
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

// Handle user activity continuation for deep linking
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

// Required for the register event
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Required for the notification event
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

// Required for registration error event
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}

// Handle local notification responses
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  completionHandler();
}

// Handle notification in foreground
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);
}

// Reset app badge and notifications on app activation
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents.shared activateApp];
  [UIApplication sharedApplication].applicationIconBadgeNumber = 0;
  [[UNUserNotificationCenter currentNotificationCenter] removeAllDeliveredNotifications];
}

// Reset app badge when the app enters the background
- (void)applicationDidEnterBackground:(UIApplication *)application {
  [UIApplication sharedApplication].applicationIconBadgeNumber = 0;
}

- (void)customizeRootView:(RCTRootView *)rootView {
  [super customizeRootView:rootView];
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // ⬅️ initialize the splash screen
}

@end
`
and this is my Podfile
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'demoFBSdk' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'demoFBSdkTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

## Environment
System:
  OS: macOS 15.0.1
  CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Memory: 1.74 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/levaral/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/local/opt/openjdk@17/bin/javac
  Ruby:
    version: 3.1.3
    path: /Users/levaral/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**Comment by mikehardy** [comment]
And yet our example works?

Have you tried cloning this repo and running the example? I just did a couple days ago, built and ran fine

This is the script that builds it so you can see necessary setup steps

https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

run it like so https://github.com/thebergamo/react-native-fbsdk-next/blob/master/RNFBSDKExample/README.md

**Comment by DARPANMANEK** [comment]
Thank you, @mikehardy! I found the solution in the example you provided in the library, and it worked perfectly for me.

**Comment by mikehardy** [comment]
Good to hear - good luck with your project
