### ISSUE TITLE
I think typescript is useful for this project

### ISSUE THREAD

**Issue by jihokim2** [thebergamo/react-native-fbsdk-next#6]
Hello, Do you have plan to make index.d.ts?

**Comment by thebergamo** [comment]
Hi @jihokim2 yes, it's part of the migration improvement. 
If you have some experience with Typescript, feel free to open a PR with this .d.ts while migration is still in progress :)

**Comment by thebergamo** [comment]
work is getting done here #10

**Comment by thebergamo** [comment]
TS definititons are released with version 4.1.0
https://github.com/thebergamo/react-native-fbsdk-next/releases/tag/v4.1.0
