### ISSUE TITLE
LoginError when Facebook app is installed (Android)

### ISSUE THREAD

**Issue by KrisLau** [thebergamo/react-native-fbsdk-next#60]
## 🐛 Bug Report
The login works great when the Facebook app is not installed but whenever I install the app and click login, this error pops up:
![image](https://user-images.githubusercontent.com/46275463/123337080-565a1480-d50c-11eb-8ce6-a5f6a6c60fd1.png)

## To Reproduce
1. Run any app that has this repo integrated. 
2. Implement login any way you want (I tested using both `LoginManager` & `LoginButton` which both seemed to give the same error)
3. Download Facebook on AVD.
4. Click login button.
5. Notice the LoginError message.

## Expected Behavior
The app automatically logs in if the FB app is logged in then prompts for permissions if this is the first time.

## Code Example
Not possible to repo on snack because it would require being able to download Facebook onto the emulator.

## Environment
Library version: `^4.3.0`

```
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 1.71 GB / 15.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.64.0 => 0.64.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Workaround
For anyone who might be looking into this issue and needs an immediate fix, the workaround I've been using for now is setting the login behaviour to web only before calling `logInWithPermissions` like this: 
`LoginManager.setLoginBehavior('web_only');`

**Comment by mikehardy** [comment]
This is one of only two active issues in the repo right now, and the one immediately prior - duplicate #59 ?

**Comment by mikehardy** [comment]
Oh wait! That one is iOS, this is Android. Oh no so this happens on both? It works for me on my phone though :thinking:

**Comment by hm-harshit** [comment]
> ## 🐛 Bug Report
> The login works great when the Facebook app is not installed but whenever I install the app and click login, this error pops up:
> ![image](https://user-images.githubusercontent.com/46275463/123337080-565a1480-d50c-11eb-8ce6-a5f6a6c60fd1.png)
> 
> ## To Reproduce
> 1. Run any app that has this repo integrated.
> 2. Implement login any way you want (I tested using both `LoginManager` & `LoginButton` which both seemed to give the same error)
> 3. Download Facebook on AVD.
> 4. Click login button.
> 5. Notice the LoginError message.
> 
> ## Expected Behavior
> The app automatically logs in if the FB app is logged in then prompts for permissions if this is the first time.
> 
> ## Code Example
> Not possible to repo on snack because it would require being able to download Facebook onto the emulator.
> 
> ## Environment
> ```
> System:
>     OS: Windows 10 10.0.19043
>     CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
>     Memory: 1.71 GB / 15.89 GB
>   Binaries:
>     Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
>     npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
>     Watchman: Not Found
>   SDKs:
>     Android SDK: Not Found
>     Windows SDK: Not Found
>   IDEs:
>     Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
>     Visual Studio: Not Found
>   Languages:
>     Java: 11.0.10
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: ^17.0.2 => 17.0.2
>     react-native: ^0.64.0 => 0.64.2
>     react-native-windows: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```

did you checked on your real device ?

**Comment by KrisLau** [comment]
@mikehardy Yup I looked into that issue before opening this one but I figured I should open a new one because that one was specific to iOS. Hmm it's strange that it would work on yours and not not on mine hahah. Maybe its an issue with later versions? I'm on the latest version currently (v4.3.0). Is there a way for me to default it to use the web browser always as a temporary fix?

@hm-harshit Nope not yet as I don't usually have my USB wire with me at work haha. I will update this by Monday once I test that out as well!

**Comment by KrisLau** [comment]
For anyone who might be looking into this issue and needs an immediate fix, the workaround I've been using for now is setting the login behaviour to web only. 
`LoginManager.setLoginBehavior('web_only');`

**Comment by hm-harshit** [comment]
@Ken-Lim you can make an unsigned apk on your machine you can found this on - https://stackoverflow.com/questions/35283959/build-and-install-unsigned-apk-on-device-without-the-development-server
and send this APK to your android device

**Comment by hakihome1412** [comment]
I tested on real Android devices , i see this issue appear when you logged in a account on your app Facebook

**Comment by mikehardy** [comment]
Not sure what to say. I just tested this, this moment, on my personal real android device, and it worked for me.
Does the example app work? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by hm-harshit** [comment]
@mikehardy @hakihome1412 which android version have you tested ?

**Comment by mikehardy** [comment]
My personal device is Android 10 (specifically OxygenOS version 10.3.11 running on Oneplus A6013 aka "OnePlus 6T")
All apps are fully up to date, Facebook is version 324.0.0.48.120

**Comment by KrisLau** [comment]
@hm-harshit Sorry for the late update! I tested on my actual phone and I still get an error. Testing phone is a OnePlus 7T on Oxygen OS 11.0.1.1 and Facebook app version 325.0.0.36.170. 

@mikehardy Something else I just realized I probably should have mentioned in the original post is that the app is not live yet on Facebook (still in development mode). So I'm using test accounts that I created on the Facebook Developer portal. Not sure of this affects it at all haha

**Comment by mikehardy** [comment]
I have 4 firebase backends for my app representing dev/qa/staging/prod. Only prod is in production mode with facebook, rest are developer. All 4 apps work on my real device with facebook app installed

**Comment by KrisLau** [comment]
I also just tried to run the example app but I'm getting an Invariant Violation error similar to #21. Seems like the example is outdated as there was also a reference to `react-native-fbsdk`. 

@mikehardy Really sorry for all the trouble I really am not sure what else would help to diagnose the issue 😓 I even recreated my entire repo just in case I messed up something else and it fixed some other issues I was having with other libraries. It doesn't seem to have helped with this particular issue unfortunately

**Comment by Vinayak-techahead** [comment]
@KrisLau are you able to resolve this issue by any means or find any temporary fixes ?

**Comment by KrisLau** [comment]
> ## Workaround
> For anyone who might be looking into this issue and needs an immediate fix, the workaround I've been using for now is setting the login behaviour to web only before calling `logInWithPermissions` like this:
> `LoginManager.setLoginBehavior('web_only');`
@Vinayak-techahead

**Comment by eat46** [comment]
I use 'web_only' now, but facebook sdk will deprecates the android webview in October. What should I do...

**Comment by thebergamo** [comment]
Original issue seems resolved.
@eat46 lets keep this discussion here: https://github.com/thebergamo/react-native-fbsdk-next/issues/94

**Comment by KrisLau** [comment]
@thebergamo I still get an `[Error: Login attempt failed.]` when I set the login behavior to `native_only`. If the web view gets deprected, I'm not really sure how I would go about implementing the Facebook login.

**Comment by thebergamo** [comment]
To be honest, I'm not really sure, but it seems to be reasonable.
But we must check how fb sdk(native one) will handle it

**Comment by mikehardy** [comment]
This is a closed issue with no reproduction, sorry.
The example app works, my app works both on devices without facebook installed (emulator) and my real device (with facebook installed)
Try the example app, put your app id in there or create a new app id on facebook and try that

**Comment by dinamoCoder** [comment]
I have the same error related to facebook that it give issue in login if i have no privacy url then i not test the facebook login functionality work on my app or not

**Comment by jquery-draggablestorm** [comment]
@hakihome1412 https://stackdev.space/questions/checking-for-logged-in-users-on-android-using-facebook-sdk-40
