### ISSUE TITLE
Unclear if I should add SkAdNetwork ID in Info.plist file

### ISSUE THREAD

**Issue by natasha08n** [thebergamo/react-native-fbsdk-next#62]
## 🐛 Bug Report
Should I add SkAdNetwork ID to Info.plist according to Apple's documentation https://developer.apple.com/documentation/storekit/skadnetwork/configuring_a_source_app?fbclid=IwAR0dw0ik0R_rytuvr3xfy3tqYpVsxjkj3ii6lwz9IxydqU_Li2zyGwkMCPs in order to track source of installation?

It is a but unclear from README file

**Comment by mikehardy** [comment]
On iOS we are just wrapping the underlying https://github.com/facebook/facebook-ios-sdk/ so in all things they will be the authoritative source

A quick scan of the results here https://duckduckgo.com/?q=facebook+sdk+skadnetwork+id indicates yes, you need to add it

If the docs are unclear, then after you verify it works we'd love a PR that updates any unclear bits! Just need to hit the edit button at top left of the file here in the GitHub UI and you get a nice web-based flow to make a suggestion in a couple clicks
