### ISSUE TITLE
Android App Crashing in Production

### ISSUE THREAD

**Issue by mohity777** [thebergamo/react-native-fbsdk-next#64]
![Screenshot 2021-06-29 at 11 37 55 AM](https://user-images.githubusercontent.com/56041802/123746342-237a9c80-d8cf-11eb-96ab-5debca7fe556.png)

**Comment by mikehardy** [comment]
Hi there! There is no information to go on here that would lead us to resolve this error.
No versions, no code, there is not even anything in the stack trace that has this package in it.
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mohity777** [comment]
I am using react-native-fbsdk-next. I searched for this error and i found out that there is an open issue on  facebook-android-sdk. 
 https://github.com/facebook/facebook-android-sdk/issues/758.

**Comment by mikehardy** [comment]
This looks related to the general issue of re-hydrating view hierarchies in react-native on Android, and a similar crash-fix to this would likely also stop your app from crashing

https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-557939158

Note that this implies your android app's fragment view state will not survive an android app pause/resume lifecycle, but that's a difficult problem to solve and out of scope for a general react-native module, https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-763996402

**Comment by mohity777** [comment]
Thanx for your help.
