### ISSUE TITLE
RN InputMask/RN InputMask.modulemap not found

### ISSUE THREAD

**Issue by rodrigogaraujo** [thebergamo/react-native-fbsdk-next#65]
Somebody knows a way to skip this?

**Comment by rodrigogaraujo** [comment]
<unknown>:0: error: module map file '/Users/rodrigogomesaraujo/Library/Developer/Xcode/DerivedData/appOrtopedia-emuedvzaifgqczgscfopetuacrsf/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found

**Comment by mikehardy** [comment]
@rodrigogaraujo that actually looks the result of using buildcache on an iOS project, I've seen that before. Effectively it's a corrupt iOS build cache.

`npx react-native-clean-cache` --> re-try

**Comment by mikehardy** [comment]
(this is not going to result in any change to the module though, it is not an issue in this module --> closing)

**Comment by carlosen14** [comment]
`npx react-native-clean-cache` does not exists anymore, do you know a similar?

**Comment by mikehardy** [comment]
Sorry it is react-native-clean-project
