### ISSUE TITLE
[Example] add full explanation on how to use events with latest ios changes

### ISSUE THREAD

**Issue by IljaDaderko** [thebergamo/react-native-fbsdk-next#67]
It took me a while to set this up so I think others might benefit from this proposal. In your example app, it probably makes sense to provide code samples for all modules of the app, in particular events and stuff related around app tracking transparency in ios that I think is hardest bit to set up at the moment.

It would be super helpfull if readme explained that additional modules / libs are needed to request / get user permissions for this as well.

**Comment by mikehardy** [comment]
Hey @IljaDaderko :wave:  - I agree - I think if you proposed a PR to do the same would be accepted just about instantly but it appears (to me at least) that current maintainers have their use cases covered so this would have to come from someone actually using the other modules to do it right.

**Comment by tereshchenkoartyom94-da** [comment]
Hey, @IljaDaderko I am working on ioS events setup right now and can not track any event, checked the tutorial twice, and there is still no result. I have no experience with native iOS, maybe you can suggest where should I look in order to solve this?

**Comment by garydevenay** [comment]
@mikehardy If this is an upstream issue and iOS event tracking is not supported by this package, I suggest we add a prominent alert in the ReadMe stating that it doesn't support iOS App Event tracking.

I'm happy to make that PR if we can confirm my understanding is correct.

**Comment by mikehardy** [comment]
I cannot personally confirm it one way or the other, sorry

**Comment by mikehardy** [comment]
I'm going to close this with a general statement of "PRs happily accepted".
Our release pipeline is clear, and it is automated, and we are on current versions now with a current example that is automatically kept up to date even.
