### ISSUE TITLE
[Android] Profile.getCurrentProfile() always returns null in the first time 

### ISSUE THREAD

**Issue by tungnguyenit0201** [thebergamo/react-native-fbsdk-next#73]
Can you tracking profile and return data instead of return null ?
This is my solution: change some lines in android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java 

replace
```java   
 @ReactMethod
    public void getCurrentProfile(Callback callback) {
        //Return the profile object as a ReactMap.
        callback.invoke(Profile.getCurrentProfile() == null
                ? null
                : Utility.profileToReactMap(Profile.getCurrentProfile()));
  }
```
with something like this:
```java
   import com.facebook.ProfileTracker;
   ...
   private ProfileTracker mProfileTracker;
   
   @ReactMethod
   public void getCurrentProfile(final Callback callback) {
        //Return the profile object as a ReactMap.
         if(Profile.getCurrentProfile() == null) {
                mProfileTracker = new ProfileTracker() {
                    @Override
                    protected void onCurrentProfileChanged(Profile oldProfile, Profile currentProfile) {
                        callback.invoke(Utility.profileToReactMap(currentProfile));
                        mProfileTracker.stopTracking();
                    }
                };
            }
             else {
                 callback.invoke(Utility.profileToReactMap(Profile.getCurrentProfile()));
                }

  }
```

**Comment by Ks0daR** [comment]
Hi, this solution worked for me. Thanks. When can you expect this in the library?

**Comment by mikehardy** [comment]
@Ks0daR without a PR, it won't advance - but I'd be happy to collaborate. Could you make a PR? Please pay special attention to the documentation for it, to make sure people understand it is a Promise (asynchronous resolution) and could be a bit delayed.

I would also want to make sure that it timed out in some way - is there a chance this could hang and never resolve? That would not be acceptable - it would violate the caller's expectation of the API, so if there is not a timeout in the underlying call we would need to make it interruptible and set a timeout ourselves

**Comment by mikehardy** [comment]
PRs happily accepted, otherwise not actionable, sorry

**Comment by ApolloRisky** [comment]
Hi there, thanks for giving the solution. Anyone thinking about a PR for this one?

**Comment by mikehardy** [comment]
I think there would be a comment to that effect if they were? Or a linked PR - as mentioned multiple times above, the library is alive, and you can see we release, but maintainer use cases !== community use cases, and as maintainer this just isn't an interesting case for me so I'm not coding it up. Happy to merge+release though.

For future folks though: please just post a PR or hold the comments. They generate notifications which is kind of a time theft for maintainers who are already chronically short on time. It's open source, just do the work in other words

**Comment by putuoka** [comment]
what is the PR? isn't this a critical issue?

**Comment by mikehardy** [comment]
@putuoka It's not critical to me so I'm not coding up the change and making a pull request. That's how open source works. It's not "hey free stuff", it's "hey, if something's important to you *you can fix it*". Feel free to do so: https://search.brave.com/search?q=github+how+to+make+a+pull+request - https://github.com/thebergamo/react-native-fbsdk-next/blob/master/CONTRIBUTING.md

**Comment by RONAKDHOLARIYA** [comment]
I use this method to fetch email
```
  const infoRequest = new GraphRequest(
                      '/me?fields=email',
                      null,
                      (err, res) => {
                        console.log({err, res}, 'this is');
                        doSocialLogin({
                          registerBy: 2,
                          token: currentProfile.userID,
                          user: {
                            firstName: currentProfile.firstName,
                            email: res.email,
                            lastName: currentProfile.lastName,
                          },
                        });
                      },
                    );
                    new GraphRequestManager().addRequest(infoRequest).start();
```

**Comment by Bratt-ec** [comment]
> I use this method to fetch email
> 
> ```
>   const infoRequest = new GraphRequest(
>                       '/me?fields=email',
>                       null,
>                       (err, res) => {
>                         console.log({err, res}, 'this is');
>                         doSocialLogin({
>                           registerBy: 2,
>                           token: currentProfile.userID,
>                           user: {
>                             firstName: currentProfile.firstName,
>                             email: res.email,
>                             lastName: currentProfile.lastName,
>                           },
>                         });
>                       },
>                     );
>                     new GraphRequestManager().addRequest(infoRequest).start();
> ```

Thanks!!! you saved my life
