### ISSUE TITLE
ReferenceError: facebookLogout is not defined

### ISSUE THREAD

**Issue by Lastvegac** [thebergamo/react-native-fbsdk-next#74]
"react-native-fbsdk-next": "^3.0.1",
 "react-native": "0.62.2",
==========================
facebookLogout = async (accessToken) => {
                console.log('accessToken', accessToken);
                let logout = new GraphRequest('me/permissions/', {
                    accessToken: accessToken,
                    httpMethod: 'DELETE',
                },
                   (error, result) => {
                        if (error) {
                            console.log('Error fetching data: ', error);
                        } else {
                            console.log('result', result);
                           LoginManager.logOut();
                        }
                    });
                new GraphRequestManager().addRequest(logout).start();
            };

**Comment by mikehardy** [comment]
Attempting to troubleshoot on outdated versions is a very inefficient use of time
- update to current stable versions to see if you can reproduce
- if you can still reproduce in your project, try the example project here (or from this PR #69)
- if you can still reproduce post your https://stackoverflow.com/help/minimal-reproducible-example
