### ISSUE TITLE
[Android] Invariant Violation: requireNativeComponent: "RCTFBLoginButton" was not found in the UIManager.

### ISSUE THREAD

**Issue by cage81** [thebergamo/react-native-fbsdk-next#77]
## 🐛 Bug Report
When I try to show a LoginButton, it appears the following error: `Invariant Violation: requireNativeComponent: "RCTFBLoginButton" was not found in the UIManager.`

## To Reproduce
I have a simple html button inside a WebView (react-native-webview package), on click I would like to show another view with the Facebook login button. (Note: navigations between views are handled with react-navigation/native package)

## Expected Behavior
On button click I expected a new view with the Facebook login button

## Code Example
```
import React from "react";
import {
  Text,
  View,
} from "react-native";
import { AccessToken, LoginButton } from "react-native-fbsdk-next";

const FacebookSdkLogin = () => {
  var token = null;
  return (
    <View>
      <LoginButton
        onLoginFinished={(error, result) => {
          if (error) {
            console.log("login has error: " + result.error);
          } else if (result.isCancelled) {
            console.log("login is cancelled.");
          } else {
            AccessToken.getCurrentAccessToken().then((data) => {
              console.log(data.accessToken.toString());
            });
          }
        }}
        onLogoutFinished={() => {
          console.log("logout.");
        }}
      />
      {token ? (
        <Text style={{ textAlign: "center" }}>{`Token: ${token}`}</Text>
      ) : null}
    </View>
  );
};

export default FacebookSdkLogin;

```

## Environment
```
![IMG_20210726_182122](https://user-images.githubusercontent.com/69848167/127024106-722d120f-fb01-4532-b5d8-2cb6cbe55aeb.jpg)
```

**Comment by cage81** [comment]
I think it's related to Expo tool because in a React-Native "pure app" this error doesn't appear.

**Comment by ShajiaAnnoor** [comment]
I am also having this same issue, please help.

**Comment by cage81** [comment]
> I am also having this same issue, please help.

Are you using Expo?

**Comment by Raheelbutt786** [comment]
I am facing the same issue. I am using expo

**Comment by Raheelbutt786** [comment]
Anyone have the resolution for this ? 
@mikehardy  @cage81 @ShajiaAnnoor

**Comment by mikehardy** [comment]
I saw something similar in device info just now, it appears something expo has done has broken things. Not sure what, I do not use Expo. 

https://github.com/react-native-device-info/react-native-device-info/issues/1381

No idea what would cause this. If you can reproduce it from a clean app (`npx react-native init ....`) then we have a bug, if it's just something Expo-specific, pursue on expo support site I think

**Comment by Raheelbutt786** [comment]
Thank you for your time @mikehardy. Really appreciated. 

It is happening only when I use the <LoginButton> tag.

I started by installing "react-native-fbsdk-next" .

and then followed along this documentation.
https://www.npmjs.com/package/react-native-fbsdk-next

after adding the below code as follows: 

`<LoginButton`
          `onLoginFinished={`
            `(error, result) => {`
              `if (error) {`
                `console.log("login has error: " + result.error);`
              `} else if (result.isCancelled) {`
                `console.log("login is cancelled.");`
              `} else {`
                `AccessToken.getCurrentAccessToken().then(`
                  `(data) => {`
                    `console.log(data.accessToken.toString())`
                  `}`
                `)`
              `}`
            `}`
          `}`
          `onLogoutFinished={() => console.log("logout.")}/>`
          
          and after running the code I receive the error "Render Error: requireNativeComponent: "RCTFBLoginButton" was not found in the UIManager" 
          
  
and the error is occurring for only <LoginButton> tag not for any others tags.

**Comment by mikehardy** [comment]
This was the most important part of my comment, it still stands:

> No idea what would cause this. If you can reproduce it from a clean app (npx react-native init ....) then we have a bug, if it's just something Expo-specific, pursue on expo support site I think

**Comment by moltedopablo** [comment]
Hi guys, this error was happening to me with a barebone expo app (expo app after expo prebuild). The problem was using `expo start` instead of `expo run`. When you execute `expo run` the app builds natively using the android dir and the lib is loaded properly. Hope it helps!
