### ISSUE TITLE
Email key is null even after adding it in the scope while using Profile.getCurrentProfile method 

### ISSUE THREAD

**Issue by Vinayak-techahead** [thebergamo/react-native-fbsdk-next#78]
## 🐛 Bug Report
Email field is null in iOS even after adding the scope of email in Login Manager after using the Profile.getCurrentProfile method .

//Object Received

[
  "The current logged user is: ",
  {
    "firstName": null,
    "lastName": null,
    "middleName": null,
    "linkURL": null,
    "imageURL": XXX,
    "userID": XXX,
    "email": null,
    "name": "Loreum Ipsum"
  }
]
## To Reproduce
Use Profile.getCurrentProfile method to retrieve user profile details from Facebook.

## Expected Behavior
Receive Email in profile object after adding email scope inside the Login Manager.

## Code Example

// Login Manager Function

    const facebookSignIn = () => {
        LoginManager.logInWithPermissions(["public_profile", "email"]).then(
            function (result) {
                if (result.isCancelled) {
                    console.log("Login cancelled");
                } else {
                    console.log(
                        "Login success with permissions: ",
                        result
                    );
                    FacebookProfile()
                }
            },
            function (error) {
                console.log("Login fail with error: " + error);
            }
        );
    }

// Function used for getting profile 

    const FacebookProfile = () =>{
        const currentProfile = Profile.getCurrentProfile().then(
            function(currentProfile) {
              if (currentProfile) {
                console.log("The current logged user is: " , currentProfile);
              }
            }
          );
        if (Platform.OS === 'ios') {
            AuthenticationToken.getAuthenticationTokenIOS().then((data) => {
              console.log(data);
            });
          } else {
            AccessToken.getCurrentAccessToken().then((data) => {
              console.log(data?.accessToken.toString());
            });
        }
    }

## Environment
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 98.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
<img width="804" alt="Screenshot 2021-07-27 at 1 49 36 PM" src="https://user-images.githubusercontent.com/83088930/127121133-c7dec9d7-7141-4e55-a6f7-3fc8c6c7a616.png">
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found

**Comment by mikehardy** [comment]
Isn't it suspicious that every data element is unpopulated :thinking: ?

**Comment by Vinayak-techahead** [comment]
It is @mikehardy , is there something missing from my end or do I have to provide any additional scope for the same.

**Comment by Vinayak-techahead** [comment]
const facebookSignIn = () => {
        if (Platform.OS === "android") {
        LoginManager.setLoginBehavior("web_only")
        
        }
        LoginManager.logInWithPermissions(['public_profile', 'email']).then(
        result => {
        if (result.isCancelled) {
        } else {
        
        AccessToken.getCurrentAccessToken().then(data => {
        const { accessToken } = data;
        let token = accessToken.toString();
        return fetch(
        'https://graph.facebook.com/v2.5/me?fields=email,name,first_name,last_name,picture.type(large),friends&access_token=' +
        token,
        {
        method: 'GET',
        headers: {
        'Content-Type': 'application/json',
        },
        },
        )
        .then(response =>
        response.json().then(facebookData => {
        const fbData = JSON.stringify(facebookData);
        console.log("My fbData", fbData)
        }),
        )
        .catch(err => {
        console.log('FBERROR', err.message);
        });
        });
        }i
        },
        function (error) {
        console.log('Login fail with error: ' + error);
        },
        );
        };

Ok I did got my desired fb data by using GraphQL api inside after getting the access token which provides me desired output for both the Platform.

**Comment by NguyenLuongVinh** [comment]
i also face the same error only on android

**Comment by Vinayak-techahead** [comment]
@NguyenLuongVinh  you can use the code above this will work for both the platforms
.

**Comment by NguyenLuongVinh** [comment]
> @NguyenLuongVinh you can use the code above this will work for both the platforms
> .

I hope somehow, the data returned when calling Profile.getCurrentProfile() will contain email because it still works fine on ios :((((((

**Comment by Vinayak-techahead** [comment]
> > @NguyenLuongVinh you can use the code above this will work for both the platforms
> > .
> 
> I hope somehow, the data returned when calling Profile.getCurrentProfile() will contain email because it still works fine on ios :((((((

@NguyenLuongLinh It is present in the documentation that email field doesn't get retrieved on Android.
<img width="803" alt="Screenshot 2021-07-28 at 2 33 56 PM" src="https://user-images.githubusercontent.com/83088930/127295456-5d5b24cf-533b-4670-b182-71399d0078e6.png">

**Comment by NguyenLuongVinh** [comment]
> > > @NguyenLuongVinh you can use the code above this will work for both the platforms
> > > .
> > 
> > 
> > I hope somehow, the data returned when calling Profile.getCurrentProfile() will contain email because it still works fine on ios :((((((
> 
> @NguyenLuongLinh It is present in the documentation that email field doesn't get retrieved on Android.
> <img alt="Screenshot 2021-07-28 at 2 33 56 PM" width="803" src="https://user-images.githubusercontent.com/83088930/127295456-5d5b24cf-533b-4670-b182-71399d0078e6.png">

Tks so much, I want to cry :(
