### ISSUE TITLE
Feature Unavailable: Facebook Login is currently unavailable for this app

### ISSUE THREAD

**Issue by shani293** [thebergamo/react-native-fbsdk-next#79]
When I try to login with an account other than Facebook developer account, it always giving me error. 
"Feature Unavailable: Facebook Login is currently unavailable for this app, since we are updating details for this app. Please try again later"
Can anyone address please?
Thanks

**Comment by Vinayak-techahead** [comment]
For this issue to be resolved you have to perform the following steps :

1. Get your Facebook account verified by performing Verification inside the Settings >> Basic
2.  Fill your data checkup form details just below it.
3.  After verification is completed comply with the Data Checkup Norms.

You can also visit this link for more details [https://stackoverflow.com/questions/25872434/facebook-login-is-currently-unavailable](url)

**Comment by shani293** [comment]
> For this issue to be resolved you have to perform the following steps :
> 
> 1. Get your Facebook account verified by performing Verification inside the Settings >> Basic
> 2. Fill your data checkup form details just below it.
> 3. After verification is completed comply with the Data Checkup Norms.
> 
> You can also visit this link for more details [https://stackoverflow.com/questions/25872434/facebook-login-is-currently-unavailable](url)

Thanks @Vinayak-techahead for your response.
I have resolved issue. Issue was that I have forgot to request permissions in App Review.
