### ISSUE TITLE
Idea: Add types to DefinitelyTyped

### ISSUE THREAD

**Issue by kunalbhatt** [thebergamo/react-native-fbsdk-next#8]
`react-native-fbsdk` had types supported but this package does not. Typically the author of the library has to add types. I'd be happy to assist in making this enhancement.

**Comment by mikehardy** [comment]
I think the idea is/was to actually convert to typescript so they're in-repo #6 - 

> Hi @jihokim2 yes, it's part of the migration improvement.
If you have some experience with Typescript, feel free to open a PR with this .d.ts while migration is still in progress :)

**Comment by thebergamo** [comment]
This is getting done in the #10 PR.

**Comment by thebergamo** [comment]
Closing this in favor of #6
