### ISSUE TITLE
FBSDKURLSession.h/FBSDKSafeCast.h file not found

### ISSUE THREAD

**Issue by passerbyloo** [thebergamo/react-native-fbsdk-next#81]
## 🐛 Bug Report

When upgrade ios `GoogleMobileAdsMediationFacebook` to `6.5.1.0`, `react-native-fbsdk-next`: `4.3.0` version, xcode build error.

![image](https://user-images.githubusercontent.com/11030696/127430681-01589915-97e9-41c4-89d1-c463ba1243f6.png)

Found some related reasons, 

in react-native-fbsdk-next.podspec file:
https://github.com/thebergamo/react-native-fbsdk-next/blob/master/react-native-fbsdk-next.podspec#L16
Core/Login/Share is point to 9.3 version instead of 11.0 version

related pr: https://github.com/thebergamo/react-native-fbsdk-next/pull/75

## To Reproduce
Upgrade to latest sdk version

## Expected Behavior
Can build successfully.

## Environment

react-native-fbsdk-next: 4.3.0 version
react native version: 0.63.4

**Comment by mikehardy** [comment]
We are not compatible with the facebook v11 sdk yet #55 - we would love it if someone had time to implement the required changes so we were.

Until then you must use only SDK versions that align with the v9 facebook iOS SDKs

I do not think there is anything actionable here other than to resolve this pending resolution of #55 - we may reopen if there is something independent worth doing here though.

In the meantime, if there is anywhere in the docs you think would help other developers that may help
