### ISSUE TITLE
Do not get installation tracking app event

### ISSUE THREAD

**Issue by GabrielLiade** [thebergamo/react-native-fbsdk-next#83]
Hi everyone, I have set up the Facebook SDK in order to tracks app event inside my app, and everything work fine I can track some event such as 'ActiveApp' , 'CompletedRegistration' event some custom event. But my Installation tracking is still not activated : 

<img width="948" alt="Capture d’écran 2021-08-02 à 15 31 21" src="https://user-images.githubusercontent.com/66065611/127869814-0b7c4166-8fa2-460c-8f5d-c9e6b5686d65.png">
 
I saw in some GitHub issues that some peoples use this fonction : 
`Settings.FacebookAutoLogAppEventsEnabled(true);`
But in my case this function does not exist and it return `undefined `

SO How can I enabled the installation app event  ? 

Thanks

**Comment by garydevenay** [comment]
I am also experiencing this issue on iOS (14.7.1) only.
I have added the `SKAdNetworkIdentifiers` to my `Info.plist`
I have tried test events with the Facebook app logged in to the correct account, and also tried without test events.

Added the following to the `AppDelegate.m`
`[[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];`

And am using the following in my React Native app

```
...
const enableTracking = status === 'authorized' || status === 'unavailable';
console.log(enableTracking)
if (enableTracking) {
    await Settings.setAdvertiserTrackingEnabled(true)
    Settings.initializeSDK();
}
...
```

I receive no events in `Test Events` and no events in `Overview` even after 12+ hours.

I have also tried completely uninstalling and re-installing with the provided instructions but no iOS events show at all

**Comment by Isuru-Nanayakkara** [comment]
Hello everyone 👋🏼 Any update on this issue? Has anyone found the cause and/or a solution to this?

**Comment by mikehardy** [comment]
Everyone should re-try with v6 of this library to see if it affects things, it has the up to date native libraries.
I'm going to close this as I'm not sure there is anything this module specifically can do other than stay up to date with native lib versions, but please feel free to continue sharing information on how best to use the available APIs / configurations

**Comment by fullStackOasis** [comment]
I realize this bug is closed and I just want to add my feedback in case anyone reads this. I'm not opening a new bug because I can see there's nothing to add.

After installing my app from Google Play Store, I do **not** see the "App installs" event in Facebook Events Manager.

Once I open the app, I **do** see the "Activate app" event being triggered.

I'm using react-native-fbsdk-next 8.0.5.

Screenshot of Facebook's Event Manager:

![image](https://user-images.githubusercontent.com/59945095/173445718-a9b92a1a-1b06-4c7f-8eca-b35697c2149a.png)

Would love to hear from anyone who has been able to fix this, since we're specifically trying to track installs and not just opens.

**Comment by martinsotirov** [comment]
I was just looking through the source because we have this problem too, and I don't see the `EVENT_NAME_ACTIVATED_APP` event used anywhere in the code of this plugin. 👀 Neither in the iOS part, nor the Android code.

**Comment by julian-gargicevich** [comment]
> I was just looking through the source because we have this problem too, and I don't see the `EVENT_NAME_ACTIVATED_APP` event used anywhere in the code of this plugin. 👀 Neither in the iOS part, nor the Android code.

Could you figure it out?

I'm having this issue as well, tracking every other event just fine except for app installs

**Comment by martinsotirov** [comment]
> Could you figure it out?
> 
> I'm having this issue as well, tracking every other event just fine except for app installs

No, unfortunately I couldn't figure it out.

**Comment by julian-gargicevich** [comment]
> > Could you figure it out?
> > I'm having this issue as well, tracking every other event just fine except for app installs
> 
> No, unfortunately I couldn't figure it out.

Did you try downgrading to 11.3.0? I'm trying that right now and apparently it solves the issue

**Comment by adrian-koczen** [comment]
Hi. I also have this problem on iOS.

react-native-fbsdk-next: 13.0.0
react-native: 0.74.5
expo: 51.0.31

 Facebook dashboard shows 'application activations' event, but not 'app installs' event.

**Comment by ethanneff** [comment]
was anyone able to figure this issue out?

**Comment by kailashAppDev** [comment]
I believe you have to set AutoLogAppEvents and isAutoInitEnabled to true or else the install events wont be send by the sdk.

**Comment by sanjaypathak1717** [comment]
> I believe you have to set AutoLogAppEvents and isAutoInitEnabled to true or else the install events wont be send by the sdk.

I am using Revenuecat + meta integration for subscribe events using conversion api and making autoLogAppEvents to true can lead to duplicate subscribe event. But making it to false, leads to no app install event fired by meta sdk. Has anyone found any solution?
