### ISSUE TITLE
Duplicate Symbols for architecture x86_64

### ISSUE THREAD

**Issue by AmirDoreh** [thebergamo/react-native-fbsdk-next#84]
I am using fbsdk-next version 4.3 , with Admost 
for using admost i should install the required pod which one of them is 
`  pod 'AMRAdapterFacebook', '~> 6.5'`
after installing , i got the following buildtime error.

![photo_2021-08-04_16-12-16](https://user-images.githubusercontent.com/45465967/128186813-fb55941f-edef-4aa1-af14-f21ea84a5bb4.jpg)
 which is addressing to /FBSDKCoreKit_Basics/libFBSDKCoreKit_Basics.a(FBSDKUserDataStore.o)

**Comment by mikehardy** [comment]
Please search, then post: https://github.com/thebergamo/react-native-fbsdk-next/issues?q=duplicate+symbols+x86_64
