### ISSUE TITLE
Get User credentials after successful login

### ISSUE THREAD

**Issue by PrincewillIroka** [thebergamo/react-native-fbsdk-next#9]
After successfully login with the Facebook login dialog, the result doesn't return the actual use credentials.
Instead it returns: {"declinedPermissions": [], "grantedPermissions": ["public_profile", "email"], "is
Cancelled": false}

```
LoginManager.logInWithPermissions(["public_profile"]).then(
  function(result) {
    console.log(result)
    //I get this in the console: {"declinedPermissions": [], "grantedPermissions": ["public_profile", "email"], "is
Cancelled": false}
    }
  },
);
```

**Comment by mikehardy** [comment]
Maybe related, react-native-firebase auth is having difficulty consuming the output from this module at the moment, that issue could use more triage before saying it is definitely related: https://github.com/invertase/react-native-firebase/issues/5106

**Comment by thebergamo** [comment]
@PrincewillIroka thanks for reporting this bug. 
Does it happen all the time?
Would you mind to clone this repo and implement some test for it in order to reproduce?

That would help me a lot in order to debug it and specially having your constraints (environment and platform) set to reproduce :)

**Comment by zRelux** [comment]
Be sure to check that you have enabled the facebook auth in the firebase console. I had the same issue, and enabling it fixed the problem

**Comment by mikehardy** [comment]
Interesting! That might explain why I have not been able to reproduce it in my project or help (I maintain react-native-firebase and wanted to solve this one...) thanks @zRelux - curious to here from @PrincewillIroka if that was the problem

**Comment by PrincewillIroka** [comment]
I've sorted the issue. @zRelux Thanks for your suggestion and @mikehardy thanks for your efforts too.
I also found out that I was making a mistake by trying to access the user credentials from here directly:
```
const result = await LoginManager.logInWithPermissions([
      'public_profile',
      'email',
    ]);
console.log(result)
```

I had to get the user AccessToken, pass it unto auth (from  '@react-native-firebase/auth) before gaining access to the user credentials.

```
import auth from '@react-native-firebase/auth';

    if (result.isCancelled) {
      throw 'User cancelled the login process';
    }

    // Once signed in, get the users AccessToken
    const data = await AccessToken.getCurrentAccessToken();

    if (!data) {
      throw 'Something went wrong obtaining access token';
    }

    // Create a Firebase credential with the AccessToken
    const facebookCredential = auth.FacebookAuthProvider.credential(
      data.accessToken,
    );

    // Sign-in the user with the credential
    auth().signInWithCredential(facebookCredential);
    auth().onAuthStateChanged((user)=>console.log(user));
```

**Comment by thebergamo** [comment]
Glad to see that everything went fine in this issue :)
