### ISSUE TITLE
‘AccessToken’ refers to a value, but is being used as a type here.  Did you mean ‘typeof AccessToken?’

### ISSUE THREAD

**Issue by rpatel-zynga** [thebergamo/react-native-fbsdk-next#92]
## 🐛 Bug Report
We're in the process of migrating from the [deprecated FBSDK wrapper](https://github.com/facebookarchive/react-native-fbsdk) to this one and are running into a few issues.

1. When trying to import and store `AccessToken` in a typed variable, see the following error: `‘AccessToken’ refers to a value, but is being used as a type here.  Did you mean ‘typeof AccessToken?’`
2. If we try to import `FBAccessToken` directly, see the following runtime error: `error: Error: Unable to resolve module react-native-fbsdk-next/types/FBAccessToken from /Users/rpatel/Projects/wwf/wf-react/src/domains/login/LoginStore.ts: react-native-fbsdk-next/types/FBAccessToken could not be found within the project or in these directories:
  node_modules`

What is the proper way to import/reference types like?

* AccessToken
* SharePhotoContent
* LoginResult
* ShareContent

## To Reproduce
1. Import `AccessToken` using `import { AccessToken } from 'react-native-fbsdk-next';` and try using `AccessToken` in something like `setFacebookUser(facebookToken?: FBAccessToken): void;` and you see the `typeof AccessToken` error.
2. Import `FBAccessToken` using `import { FBAccessToken } from 'react-native-fbsdk-next/types/FBAccessToken';` and then run the application, you see the `error: Error: Unable to resolve module react-native-fbsdk-next/types/FBAccessToken` in Metro.

## Expected Behavior
Be able to import and reference the specific types that I listed in the description.

#### AccessToken
```
import { AccessToken } from 'react-native-fbsdk-next';
...
setFacebookUser(facebookToken?: AccessToken): void;
```

#### FBAccessToken
```
import { FBAccessToken } from 'react-native-fbsdk-next/types/FBAccessToken';
...
setFacebookUser(facebookToken?: FBAccessToken): void;
```

## Environment
```
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 63.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/rpatel/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 10, 15, 16, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 8
      Build Tools: 19.1.0, 21.1.1, 21.1.2, 22.0.1, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.2, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-22 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
Strange.

```typescript
import {
  LoginManager,
  AccessToken,
  GraphRequest,
  GraphRequestManager,
} from 'react-native-fbsdk-next';
```

...works for me but then I notice I have a `@types/react-native-fbsdk-next/index.d.ts` with `declare module 'react-native-fbsdk-next';` in it, so of course anything works.

@g-dimitry did the work on the type definitions here, perhaps he may provide some insight or an example?

**Comment by g-dimitry** [comment]
Sorry for the late reply I'll check it out now

**Comment by g-dimitry** [comment]
I did some investigation let me explain the issue at hand.

In our FBAccessToken File we define a class named FBAccessToken:
https://github.com/thebergamo/react-native-fbsdk-next/blob/f9ab576285bc1e225ff0d93b448e39b17c1a0ad1/src/FBAccessToken.js#L47

We export the class:
https://github.com/thebergamo/react-native-fbsdk-next/blob/f9ab576285bc1e225ff0d93b448e39b17c1a0ad1/src/FBAccessToken.js#L227

In our root index.js file we export an object containing a getter named "AccessToken" that returns the class "FBAccessToken"
https://github.com/thebergamo/react-native-fbsdk-next/blob/f9ab576285bc1e225ff0d93b448e39b17c1a0ad1/src/index.js#L39-L41

What that means is the real type will always be FBAccessToken and not AccessToken. AccessToken is nothing but a reference to the class object which is the real type. That's why this error appears as the real type here should be FBAccessToken and not AccessToken.

For a fast and easy solution, you can use one of the below solutions: (If you are intending to pass an instance of the FBAccessToken class)
```
import { AccessToken } from 'react-native-fbsdk-next';
...
setFacebookUser(facebookToken?: InstanceType<typeof AccessToken>): void;
```
OR
```
import { AccessToken } from 'react-native-fbsdk-next';
import { FBAccessToken } from 'react-native-fbsdk-next/types/FBAccessToken';
...
setFacebookUser(facebookToken?: FBAccessToken): void;
```
If you're intending to pass the class itself:
```
import { AccessToken } from 'react-native-fbsdk-next';
...
setFacebookUser(facebookToken?: typeof AccessToken): void;
```

For future improvement:

1. Instead of exporting references to the classes, let's export the classes with the same name.
2. We need to revisit the Typescript migration. I wasn't available before but now I can do it, this will help heavily couple the real code with the types instead of handling both separately.

**Comment by mikehardy** [comment]
@g-dimitry fantastic analysis ! thanks for taking the time to fully explain it

**Comment by smacgregorZ** [comment]
Thank you @g-dimitry

**Comment by g-dimitry** [comment]
@smacgregorZ any time 😄 

@mikehardy it's always a pleasure to contribute 😄 If we're still considering the move to typescript please tell me and I can do it.

**Comment by mikehardy** [comment]
Hey @g-dimitry I just checked and the only item in the PR queue was one from me that was java-only and well-tested on other modules, so I merged it and kicked off a release

That means that there are zero PRs outstanding that would potentially be perturbed by a codebase-wide change.

If there was ever a time, this seems like a good one. If you want to do a typescript conversion I think that would be fantastic

I would love it if the combo of package.json elements (main, index etc) and build/distribution method (e.g. https://github.com/callstack/react-native-builder-bob or whichever) worked together such that it was fully backwards compatible and could just be a minor version release - that's my ideal scenario. Do you think that's possible?

**Comment by rpatel-zynga** [comment]
Thank you @g-dimitry.  We used your first suggestion, `InstanceType<typeof AccessToken>`, and it's working.

**Comment by mi-chal** [comment]
@g-dimitry Actually `import { FBAccessToken } from 'react-native-fbsdk-next/types/FBAccessToken';` returns ESLInt error: 
`Unable to resolve path to module 'react-native-fbsdk-next/types/FBAccessToken'.eslintimport/no-unresolved` ( as @rpatel-zynga wrote). 
What helps is importing it as a type:
`import type { FBAccessToken } from 'react-native-fbsdk-next/types/FBAccessToken';`

**Comment by gustavopch** [comment]
@g-dimitry's suggestion works for `AccessToken` but apparently not for others like `LoginResult` and `SharePhotoContent`. Isn't it basically a matter of copying what was done in https://npm.im/@types/react-native-fbsdk?

**Comment by mikehardy** [comment]
@gustavopch the real idea is to finally finally finish + merge #95 and then move forward on a solid foundation I think - would love someone to pull that fork/branch and carry it to the finish line :pray: :pray:

**Comment by thebergamo** [comment]
Either way, anyone interested in this, new beta version is released. Feel free to test it from version 7.0.0-beta.1
