### ISSUE TITLE
[iOS] fetchDeferredAppLink  not work only in iphone

### ISSUE THREAD

**Issue by tree1891** [thebergamo/react-native-fbsdk-next#93]
Deferred deep link does work in iPad, but not in iPhone 12 with same iOS 14.7.
The url is always nil, no error.
I have checked on app-ads-helper.

"react-native": "0.64.0"
"react-native-fbsdk-next": "^4.3.0"

**Comment by mikehardy** [comment]
Hi there!
This is a sincere question: how can a module like this one, that just wraps (very thinly) the native SDK, be the thing that causes it to work on iPad but not iPhone :thinking: 

Doesn't this seem like it will be a problem with the native SDK? I would search for issues upstream

That said, we're still on an old version of the upstream SDK until someone takes on #55

**Comment by tree1891** [comment]
Sorry, it does not work in iPad 14.7 too.

**Comment by tranducduong1994** [comment]
@tree1891 My Ipad is 14.8. fetchDeferredAppLink doesn't work too, Did you have a solution to resolve this issue?

**Comment by tree1891** [comment]
same issue here.

**Comment by tranducduong1994** [comment]
@tree1891  does it work on an iPhone ( IOS )?

**Comment by tree1891** [comment]
@tranducduong1994 no, it does not

**Comment by sarafcredable** [comment]
Please check this https://github.com/thebergamo/react-native-fbsdk-next/issues/234
