### ISSUE TITLE
Android Webview deprecation

### ISSUE THREAD

**Issue by AmirDoreh** [thebergamo/react-native-fbsdk-next#94]
according to [this doc ](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews) Beginning October 5, 2021, Facebook Login will no longer support using Android embedded browsers (WebViews) for logging in users.

will this affect react-native-fbsdk-next also ?

**Comment by yungkittty** [comment]
@AmirDoreh this should affect `react-native-fbsdk-next` as it logs either with webview or natively (works only if the app is installed). This means if the user don't have the app installed, he/she won't be able to login anymore.

**Comment by mikehardy** [comment]
It very well might! If you analyze the code in the module vs the linked docs, are there changes needed? If there are, could think of what should go in a PR + would you be willing to make a PR ?

**Comment by MilanObradovic** [comment]
Any news here? I tested Facebook login on Android devices when there is no Facebook app installed - custom tabs gets opened (not webview). Is there need to change anything if this is the case?

**Comment by mikehardy** [comment]
@MilanObradovic sounds like you've done real testing. So you were able to log in, no problems? If so, then login is working and I think that's the point, meaning it works. That would be great news as it would be "no change needed" I think.

**Comment by AmirDoreh** [comment]
i will also take time and check it from inside , if any pr needed i will absolutely make! @mikehardy

**Comment by mikehardy** [comment]
For what it's worth, I know I use it on emulators without facebook installed all the time, and it works for me :-)

**Comment by MilanObradovic** [comment]
> @MilanObradovic sounds like you've done real testing. So you were able to log in, no problems? If so, then login is working and I think that's the point, meaning it works. That would be great news as it would be "no change needed" I think.

That's correct. Only time webview shows up is when I specify login behaviour and set it to 'WEB_VIEW_ONLY'.
This behaviour is not specified here
![Screenshot 2021-09-22 at 09 24 44](https://user-images.githubusercontent.com/52998593/134300471-d89c4850-0d7b-45d0-bf1f-a19f547c961a.png)
but it can be set to that value. 
I guess custom tabs have advantage if no app is installed.

**Comment by mikehardy** [comment]
Not actionable, does not appear there is any action to take :shrug:
